### ISSUE TITLE
munin-plugins-mysql needs libcache-cache-perl

### ISSUE THREAD

**Issue by cgzones** [munin-monitoring/munin#1021]
The `mysql_` plugin needs `Cache::Cache`; Can you add the package `libcache-cache-perl` as dependency for `munin-plugins-mysql` in the branch `debian-experimental`

**Comment by cgzones** [comment]
Also `munin-plugins-ldap` needs `libnet-ldap-perl` for the plugin `slapd_` (`Net::LDAP`)

**Comment by cgzones** [comment]
And `munin-plugins-extra` needs `libcache-memcached-perl` for the plugin `memcached_` (`Cache::Memcached`)

**Comment by sumpfralle** [comment]
Indeed!

I pushed your proposals to my branch: https://salsa.debian.org/debian/munin/merge_requests/2
