### ISSUE TITLE
munin-node service must not include PrivateDevices=true

### ISSUE THREAD

**Issue by cgzones** [munin-monitoring/munin#1026]
When the munin-node systemd service is started with `PrivateDevices=true`, device oriented plugins like `smart_` are failing. Please remove the line in the branch `debian-experimental` from `debian/munin-node.service`.

**Comment by sumpfralle** [comment]
Very good point!

I pushed your recommendation to my branch of proposed packaging updates: https://salsa.debian.org/debian/munin/merge_requests/2
(I guess, the branch `debian-experimental` in this munin repository will be relocated to https://salsa.debian.org/debian/munin. We will see ...)
