### ISSUE TITLE
postgres_users plugin fails because of system queries

### ISSUE THREAD

**Issue by MarcSchmitzer** [munin-monitoring/munin#1032]
The postgres_users plugin produces errors when it encounters entries in `pg_stat_activity` that have `usename` `NULL`. This appears to be the case for some system queries on postgres 10+.

On a host running postgres 10.4 on Debian Stretch.  Munin-Node is 2.0.37-1~bpo9+1 from the Debian Stretch backports repo.
```
$ /usr/sbin/munin-run postgres_users
postgres.value 2
Use of uninitialized value $name in substitution (s///) at /usr/share/perl5/Munin/Plugin.pm line 170.
Use of uninitialized value $name in substitution (s///) at /usr/share/perl5/Munin/Plugin.pm line 172.
Use of uninitialized value $name in string eq at /usr/share/perl5/Munin/Plugin.pm line 175.
Use of uninitialized value $l in concatenation (.) or string at /usr/share/perl5/Munin/Plugin/Pgsql.pm line 362.
.value 4
```
It seems this is related to system quries without a username:
```
postgres=# select pid, backend_type, usename from pg_stat_activity where usename is null;
  pid  |    backend_type     | usename 
-------+---------------------+---------
 70836 | autovacuum launcher | 
 70373 | background writer   | 
 70372 | checkpointer        | 
 70835 | walwriter           | 
(4 rows)
```

This can be fixed by extending the WHERE clause of the plugin's queries with `AND usename IS NOT NULL`. This should be fine for postgres versions that do not have this problem, too.

Here's a patch for that: [postgres_users.patch.txt](https://github.com/munin-monitoring/munin/files/2294164/postgres_users.patch.txt)

**Comment by sumpfralle** [comment]
Thank you for exploring the details of that issue!

I pushed your proposal in 47e57e4e.

**Comment by MarcSchmitzer** [comment]
Thanks!
