### ISSUE TITLE
munin-update: perl warnings

### ISSUE THREAD

**Issue by cgzones** [munin-monitoring/munin#1040]
After https://github.com/munin-monitoring/munin/commit/5071b5f6ee6378bc8f7b41c88ec89c0e66937b65 munin-update logs several of the following warnings:
```
Use of uninitialized value $service_attr{"graph_order"} in split at /usr/share/perl5/Munin/Master/UpdateWorker.pm line 661, <GEN0> line 1888.
```

**Comment by sumpfralle** [comment]
Probably fixed in 97f83ac36d213af9069996e30cff24c32bc44481.
