### ISSUE TITLE
munin-limits not passing plugin information to contact.nagios.command when status OK

### ISSUE THREAD

**Issue by madhatter0** [munin-monitoring/munin#1052]
**Describe the bug**
I'm running (hand-built) munin 2.0.39 on CentOS 7.  `munin-limits --force` doesn't pass the fourth (free text) field to nagios when a service is in a non-error state.  This causes NAGIOS to misinterpret the notification and the service goes STALE as a result (if freshness checking is enabled).

**To Reproduce**
1. Monitor a plugin which isn't outside its warning or critical bounds
2. Run `munin-limits --force  --debug` (problem occurs also without --debug)
with

```
contact.nagios.command /usr/sbin/send_nsca localhost -c /etc/nagios/send_nsca.cfg
contact.nagios.max_messages 1
```

**Expected behavior**
Service is updated in NAGIOS with current OK state

**Screenshots & Logs**
debug output shows:
```
2018/08/24 11:02:36 [DEBUG] Opened pipe for nagios as pid 21048
2018/08/24 11:02:36 [DEBUG] sending message to nagios: "severn.exe      HDD temperature 0       "
2018/08/24 11:02:36 [DEBUG] Closing pipe for contact nagios
```
Note absence of fourth field sent to NAGIOS.  NAGIOS then logs
`[1535104956] EXTERNAL COMMAND: PROCESS_HOST_CHECK_RESULT;severn.exe;0;0`
because three field reports are HOST check results, not SERVICE check results.  Compare the following munin debug and consequent NAGIOS outputs from a service on the same host which isn't OK:

```
2018/08/24 11:02:35 [DEBUG] Opened pipe for nagios as pid 21044
2018/08/24 11:02:35 [DEBUG] sending message to nagios: "severn.exe      Disk usage in percent   2       CRITICALs: /mnt/homes is 99.96 (outside range [:98])."

[1535104956] EXTERNAL COMMAND: PROCESS_SERVICE_CHECK_RESULT;severn.exe;Disk usage in percent;2;CRITICALs: /mnt/homes is 99.96 (outside range [:98]).
```

**Desktop (please complete the following information):**
CentOS 7.5.1804
Munin 2.0.39, built from source

**Comment by sumpfralle** [comment]
Thank you for this detailed bug report!

I prepared a changeset in #1055 which fixes the output for `munin-limits --force`.
Could you please test, whether it also woks for you during regular status changes?

**Comment by madhatter0** [comment]
You're very welcome, I'm glad I could be sufficiently complete - and thanks for addressing the issue so promptly.

It works with the handbuilt 2.0.39 on the server which prompted this bug report.  For completeness' sake, I'm also testing on an older system that is using the EPEL packages, which I had forcibly held back to 2.0.25(-2); I've allowed the update to 2.0.33(-1), verified the bug is present, applied the patch, and verified the bug is gone.
