### ISSUE TITLE
munin update takes long time to run

### ISSUE THREAD

**Issue by Tamaradmin** [munin-monitoring/munin#1069]
Hello,

I'm using munin-async. In one of the monitored servers, when I run the munin plugins manually using the command munin-run it takes less than the automatic update.

Below are the statistics :
#time munin-run <all_plugins_name>
real    2m49.532s
user    3m59.382s
sys     0m34.730s

When i check the process munin-asyncd, it is still running almost 5 minutes. It becomes idle shortly before the 5 minutes of the munin update are over  : 
[root@server01 plugins]# ps -ef|grep munin-async
root      39722      1  0 09:19 pts/2    00:00:02 munin-asyncd [server01] [idle]

This prevent the graphs from being updated (munin-update log from the master):
2018/09/11 03:15:09 [INFO] starting work in 4728 for server01.dmz/ssh://server01:4949.
2018/09/11 03:15:09 [INFO] node server01.dmz advertised itself as server01 instead.
2018/09/11 03:15:09 [FATAL] Socket read from server01.dmz failed.  Terminating process. at /usr/share/perl5/vendor_perl/Munin/Master/UpdateWorker.pm line 379
2018/09/11 03:15:09 [ERROR] Error in node communication with server01.dmz/ssh://server01:4949: [FATAL] Socket read from server01.dmz failed.  Terminating process. at /usr/s                              hare/perl5/vendor_perl/Munin/Master/UpdateWorker.pm line 379
2018/09/11 03:15:09 [ERROR] Munin::Master::UpdateWorker<dmz;server01.dmz> failed to connect to node
2018/09/11 03:15:10 [INFO] Reaping Munin::Master::UpdateWorker<dmz;server01.dmz>.  Exit value/signal: 20/0
2018/09/11 03:15:30 [INFO] Remaining workers: dmz;server01.dmz
2018/09/11 03:15:30 [INFO] No old data available for failed worker dmz;server01.dmz.  This node will disappear from the html web page hierarchy

*******************
OS+Distribution Version: CentOS release 6.9 
Munin Version 2.0.33 (munin-node and munin-async)
*******************

Any one has an idea why the update takes long time in the server and if there is a way to accelerate it?

thanks.

**Comment by doublehp** [comment]
What is your bug ?

"Any one has an idea why the update takes long time in the server and if there is a way to accelerate it?" this fits a forum, not a BTS. What makes a node long to answer is either heavy load, lack of physical ressources, or a system crash. You need to disable all your plugins, run them manually one by one, and readd them individually to determine which one is causing you trouble; google for dichotomy for details.

Close this bug, and open a new one when you have identified a real problem.

**Comment by Tamaradmin** [comment]
THe issue was in the spool directory it was too big for munin-async to fetch for the file with the correct timestamp. I removed the olf spool files and now it works correctly

**Comment by sumpfralle** [comment]
Thank you for reporting the solution for this problem!
