### ISSUE TITLE
Mail subject for entering alert state is indistinguishable from recovery

### ISSUE THREAD

**Issue by mlissner** [munin-monitoring/munin#1085]
I might be wrong about this, but I think these facts are true: 

1. Munin will send an alert (if configured) when something goes from an OK to a Warning or Critical state.
2. Munin will send *another* alert (if configured) when something returns to an OK state.

I'm not sure about number two, but I think it's the reason that I've been getting mysterious "alerts" that seem to indicate that everything is OK. 

This isn't documented anywhere that I could find and it's kind of strange behavior as implemented. Two changes that might clarify this are:

1. Add an explanation of this to the documentation, at the top. 
1. In the "Everything is OK again" email, mark it that way. Say that, "This variable has returned to an OK state." or something like that. That way, it's clear why the email is being sent.

One of my disks has an intermittent issue of some kind, so one minute I get an error, and the next I get an email that says: 

> OKs: Power_On_Hours is 100.00, Unused_Rsvd_Blk_Cnt_Tot is 0.00, Current_Pending_Sector is 100.00, Raw_Read_Error_Rate is 100.00, Reallocated_Event_Count is 100.00, Runtime_Bad_Block is 100.00, End_to_End_Error is 100.00, Reallocated_Sector_Ct is 100.00, Unknown_Attribute is 100.00, Temperature_Celsius is 65.00, smartctl_exit_status is 0.00, Power_Cycle_Count is 100.00, Unknown_SSD_Attribute is 100.00, Reported_Uncorrect is 100.00, UDMA_CRC_Error_Count is 100.00, Offline_Uncorrectable is 100.00.

It's really hard to understand that an email that just says that is actually an indication that a problem in a previous email is now fixed.

------

Or maybe I'm totally misunderstanding things, in which case, sorry for the confusion!

**Comment by matt-matt2** [comment]
This is a normal behaviour for monitoring apps in my experience.

**Comment by mlissner** [comment]
I'm fine with the emails existing, but they're incredibly unclear. They'd be much better if they had a subject line that started with "RECOVERED: XYZ is now OK" or if they just said something like that at the top of the message. As it is, they look like alerts about something bad, not about a recovery.

**Comment by matt-matt2** [comment]
You're right, the subject line of all the emails is identical whether it's a problem or a recovery. It makes no effort to construct a subject line at all.
At the end of the day this is a feature I've used very little given that it's not really suited to it.

**Comment by mlissner** [comment]
>  it's not really suited to it.

Seems like it works well to me. For us it's a perfect tool to make sure none of our servers are falling over. Love to hear what other processes you might have though (other than Nagios, which seems to cost a fortune).

**Comment by matt-matt2** [comment]
Eh? Nagios is free (Nagios XI is not), but that's not the point.
Munin's greatest strength imho is speed of deployment for new or custom checks, and the addition of async data collection makes it perfect for intermittently connected hosts too, which is a very different set of use cases from a monitoring tool. For some very simple setups it works fine, yes. For me, I didn't like having the thresholds themselves encoded in the plugin on each remote box, I'd rather configure them from my central monitoring server.

**Comment by matt-matt2** [comment]
I would go further and suggest the email subject lines should be customised to reflect the type and severity of failure/recovery. You shouldn't need to read the email itself unless you want to read the raw values.

**Comment by sumpfralle** [comment]
The mail subject is configurable. Sadly the suggestion in the sample configuration file and in the documentation contained only a very simple mail subject.

The following notiifcation setting offers a more helpful mail subject:
```
contact.email.command mail -s "Munin ${var:worst}: ${var:group}::${var:host}::${var:plugin}" your@email.address.here
```
The above template could lead to such a mail subject:
```
Munin WARNING: foo::bar::sensors_power
```

See 064c0cb224178db34664b20734f6bee3530c1508 and 55efdca2bb779a385a9fd77937453d97b4a4f070.

**Comment by mlissner** [comment]
Woo! Thank you!
