### ISSUE TITLE
Munin doesn't reject bad configuration lines

### ISSUE THREAD

**Issue by mlissner** [munin-monitoring/munin#1087]
**Describe the bug**
Over the past couple days I've had an intermittent error with one of my drives, which causes smartctl to alternate between an exit code of zero and four. The error seems to be fine, so I tried using the following variable to make it not throw alerts:

    env.ignoreexit 4

That didn't work, and I'm new to Munin so I've been tinkering with it, trying to make it work. Nothing seemed to work, so I eventually found the patch that implemented the `ignoreexit` command. Sure enough it's from ~before~ *after* my version of Munin. Bummer.

That's my problem, but this bug is that munin doesn't throw any kind of error when an unknown setting is discovered. Or at least, I haven't seen any.

**To Reproduce**

1. Set up a bad parameter for a plugin.
2. Look for errors in the logs, by using `munin-run`, etc.
3. Restart munin-node and look for errors there.

**Expected behavior**
When there's an erroneous configuration, Munin should throw an error in the logs and when restarted.

**Desktop (please complete the following information):**
 - OS+Distribution Version: Ubuntu 16.04
 - Munin Version: 

```
↪ sudo dpkg -l munin
[sudo] password for mlissner: 
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version         Architecture    Description
+++-====================-===============-===============-=============================================
ii  munin                2.0.19-3ubuntu0 all             network-wide graphing framework (grapher/gath
```

**Comment by steveschnepp** [comment]
This is by design.

The `env` construction enable to set environment variables, that *might* be picked up by a plugin. 

The node has actually no knowledge of the various env that change the behavior of a plugin. And it would be extremely difficult to implement it, as env var can br anything.

**Comment by mlissner** [comment]
Is it possible to implement this incrementally? For example, could plugins have a list at the top of them of the various env's they support? In theory, this would allow an error to be logged (assuming plugins can log things), and over time, if there's some kind of plugin best practice or template, this could move things in a direction where the kinds of really frustrating problems I had could be fixed. 

Not knowing if a configuration is entirely invalid is a difficult thing to diagnose.

**Comment by niclan** [comment]
It's not worth doing.

The plugin would have to declare to munin-node which environment variables it obeys and munin-node would have to check that.  But some plugins obeys environment variables based on device name and other dynamic things. And then the plugin would have to output the names of all allowable environment variables at runtime.  ... but wait, we wanted plugins to be simple....

What is worth doing is writing complete documentaiton for plugins, which also explains what environment variables are used.
