### ISSUE TITLE
Problema el zoom de graficas de Munin al hacer update Centos 7

### ISSUE THREAD

**Issue by elm1976** [munin-monitoring/munin#1103]
Hola, actualice mi Centos 7 con "yum update" y me dejó de andar el zoom en Munin, podrían ayudarme?

Mi Centos 7:
[root@bkpagu conf.d]# uname -or
3.10.0-514.21.2.el7.x86_64 GNU/Linux

Mi apache:
[root@bkpagu conf.d]# httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built: Jun 27 2018 13:48:59

Mi Munin:
[root@bkpagu conf.d]# munin-node-configure --version
Version:
This is munin-node-configure (munin-node) v2.0.40.

Gracias!!!!

**Comment by sumpfralle** [comment]
You should have added a note to [your other identical posting](https://github.com/munin-monitoring/munin/issues/1071#issuecomment-428988296) in #1071. This prevents duplicate efforts of people responding to you.

My [comment from the other thread](https://github.com/munin-monitoring/munin/issues/1071#issuecomment-429079523) applies here, too.
Or what do you think?

**Comment by elm1976** [comment]
Si de acuerdo, cierro este caso si te parece bien.
