### ISSUE TITLE
No email when state changes from CRITICAL to WARNING.

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1105]
I get an email when state changes from OK -> WARNING or WARNING -> OK. I also get email every 5min while in CRITICAL state (I have "contact.admin.always_send critical" enabled).

There is no email sent when state changes from CRITICAL to WARNING. Last email I get is state being CRITICAL. I would expect an email to be sent with state being WARNING.

Munin 2.0.42.

**Comment by sumpfralle** [comment]
I tried to reproduce this issue, but I failed.

I used the following plugin and swtiched (manually) between values for *CRITICAL* and *WARNING* - messages were always visible in the logs and send as mails:
```shell
#!/bin/sh

case "${1:-}" in
    config)
        echo "graph_title title-foo"
        echo "foo.label label-foo"
        echo "foo.warning -10:10"
        echo "foo.critical -20:20"
        echo "foo.unknown_limit 2"
        ;;
    *)
        echo "foo.value 15"
        ;;
esac
```

Can you still reproduce the issue?

**Comment by kimheino** [comment]
This seems to work fine on 2.0.50. You can close this bug, I'll reopen if it happens again.
