### ISSUE TITLE
long established Munin no longer updating. 

### ISSUE THREAD

**Issue by gzcwnk** [munin-monitoring/munin#1118]
**Describe the bug**

Munin stopped updating on the 8th November.

**To Reproduce**

**Expected behavior**

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS+Distribution Version: [e.g. Ubuntu 16.04, FreeBSD 10]
 - Browser (if relevant) [e.g. chrome, safari]
 - Munin Version [e.g. 2.0.35]

**Additional context**

Version,

[root@vuwunicomrtg002 munin]# rpm -q munin
munin-2.0.33-1.el7.noarch
[root@vuwunicomrtg002 munin]# rpm -q munin-node
munin-node-2.0.33-1.el7.noarch
[root@vuwunicomrtg002 munin]# 

Plenty of disk space,

[root@vuwunicomrtg002 munin]# df -h
Filesystem                              Size  Used Avail Use% Mounted on
/dev/mapper/VolGroupboot-LogVolroot      20G  4.0G   15G  22% /
/dev/sda1                               1.9G  230M  1.6G  13% /boot
/dev/mapper/VolGroupboot-LogVolhome      38G  4.5G   34G  12% /home
/dev/mapper/VolGroupboot-LogVoltmp      7.9G   33M  7.8G   1% /tmp
/dev/mapper/VolGroupboot-LogVolopt      2.0G   33M  2.0G   2% /opt
/dev/mapper/VolGroupboot-LogVolvar      9.8G  1.8G  8.1G  19% /var
/dev/mapper/VolGroupdata1-LogVolvarwww  130G  895M  130G   1% /var/www
/dev/mapper/VolGroupboot-LogVolvarlog   9.8G  421M  9.4G   5% /var/log
/dev/mapper/VolGroupdata2-LogVolvarlib   32G  2.8G   30G   9% /var/lib
/dev/mapper/VolGroupboot-LogVolaudit    7.9G   71M  7.8G   1% /var/log/audit
/dev/mapper/VolGroupboot-LogVolvarlib    20G   33M   20G   1% /var/tmp
[root@vuwunicomrtg002 munin]# 

Log files are all 0 length for 9th v of considerable size before this.

I dont know what happened here.  I suspected a patching update as the cause but appears not.  Not aware of any other changes it "simply" no longer works.  I have rebooted and even patched, no difference.

**Comment by sumpfralle** [comment]
Interesting!

I would suggest to check the following details in order to understand, where something goes wrong:
* do you see relevant hints in /var/log/munin?
* is the munin-node (providing the data) is running? (`echo list | nc localhost munin`)
* is crond running?
* are the rrd (data) files up-to-date? (`find /var/lib/munin -type f -name "*.rrd" -mtime -1`)

**Comment by gzcwnk** [comment]
Another admin broke it, he's fixed it.  :(

**Comment by sumpfralle** [comment]
Thank you for sharing!
