### ISSUE TITLE
diskstats plugin reports near 100% usage for NVME drives

### ISSUE THREAD

**Issue by nyetwurk** [munin-monitoring/munin#1119]
For some reason, the kernel always reports NVME drives (but not partitions) with near 100% utilization. iostat reports the same thing.

$ cat /proc/diskstats | awk '{print $3, $7, $11, $7+$11, $13, $14}' | grep nvme
nvme0n1 22988 457568 480556 2440737408 2441207708
nvme0n1p1 22988 339624 362612 528884 978496

Note that the $7+$11 column for n1p1 isn't that far off of $13

See also
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1790181

Patch that demonstrates the difference:
```diff
--- diskstats-dist      2018-11-11 04:48:17.000000000 -0800
+++ diskstats   2018-11-12 10:46:36.086041994 -0800
@@ -234,6 +234,9 @@
     # a given second, the device is nearly 100% saturated.
     my $utilization = $tot_ticks / $interval;

+    # NVME drives tend to show nearly 100% util, so lets use r+w as an alternate
+    my $rw_util = ($rd_ticks + $wr_ticks) / $interval;
+
     # Average time an I/O takes on the block device
     my $servicetime_in_sec =
       $total_ios_per_sec ? $utilization / $total_ios_per_sec / 1000 : 0;
@@ -253,9 +256,11 @@
       : 0;

     my $util_print = $utilization / 10;
+    my $rw_util_print = $rw_util / 10;

     return {
         utilization              => $util_print,
+        rw_util                  => $rw_util_print,
         servicetime              => $servicetime_in_sec,
         average_wait             => $average_wait_in_sec,
         average_rd_wait          => $average_rd_wait_in_sec,
@@ -298,6 +303,8 @@

         print "${graph_id}_util.value "
           . $result->{$device}->{'utilization'} . "\n";
+        print "${graph_id}_rw_util.value "
+          . $result->{$device}->{'rw_util'} . "\n";
     }

     print "\nmultigraph ${plugin_name}_throughput\n";
@@ -342,6 +349,7 @@

 multigraph ${plugin_name}_utilization.$graph_id
 util.value $result->{'utilization'}
+rw_util.value $result->{'rw_util'}
 EOF

     }
@@ -784,6 +792,11 @@
 ${graph_id}_util.info Utilization of the device
 ${graph_id}_util.min 0
 ${graph_id}_util.draw LINE1
+${graph_id}_rw_util.label $cur_diskstats{$device}->{'pretty_device_name'} (r+w)
+${graph_id}_rw_util.type GAUGE
+${graph_id}_rw_util.info Read/write utilization of the device
+${graph_id}_rw_util.min 0
+${graph_id}_rw_util.draw LINE1
 EOF
     }

@@ -911,6 +924,11 @@
 util.info Utilization of the device in percent. If the time spent for I/O is close to 1000msec for a given second, the device is nearly 100% saturated.
 util.min 0
 util.draw LINE1
+rw_util.label Read/write utilization
+rw_util.type GAUGE
+rw_util.info Read/write utilization of the device in percent. If the time spent for I/O is close to 1000msec for a given second, the device is nearly 100% saturated.
+rw_util.min 0
+rw_util.draw LINE1

 EOF
```

**Comment by nyetwurk** [comment]
Could also just use a stack for this I suppose but for other disks, tot_ticks is actually often less than rd_ticks+wr_ticks for some reason.

**Comment by steveschnepp** [comment]
Seems computing the usage of a device is complex on modern SSD (& NVME) : https://brooker.co.za/blog/2014/07/04/iostat-pct.html

But this bug might be due to the more precise units (nanoseconds)

**Comment by nyetwurk** [comment]
From my investigation, I don't think it is a units problem. It is more likely it is what is mentioned in the article you linked above.

It is interesting, though, that summing read/write has different effects on conventional drives; in my case, my non-ssd reports a higher r+w %util than %util

**Comment by nyetwurk** [comment]
I'm starting to think maybe summing rd_ticks and wr_ticks might be the right solution
https://forums.fedoraforum.org/showthread.php?318580-iostat-svctm-and-busy-numbers-are-wrong-for-NVME-drives

svctm might just not be useful in the future.

**Comment by sumpfralle** [comment]
@nyetwurk: I would really appreciate a change request that is applicable both to the non-NVME and NVME disks. Thus the plugin probably *needs* to stick to the definition of the fields provided by the kernel documentation. If the fields are deprecated (or of unknown usefulness), then we should remove them from the plugin.

What would you suggest?

**Comment by nyetwurk** [comment]
Interestingly netdata seems to give useful utilization for both nvme and non nvme drives.. I'm out of town but will investigate when I get home

**Comment by nyetwurk** [comment]
Having rebooted recently i'm starting to think it might be a 32bit signed integer overflow problem. Looking through my logs, it seems the problem popped up once the ticks got > 0x80000000

**Comment by nyetwurk** [comment]
No it isn't a wraparound, I think it's a problem in the munin script when it parses an integer greater than 0x80000000 from /proc

I'm guessing though, I have to make some sort of test program to simulate a proc file for munin to read to test it

**Comment by sumpfralle** [comment]
I am confused.
Could you please summarize the issue in a few sentences for me? Up to now I thought, that the numbers provided by `/proc/diskstats` are not accurate.

**Comment by sumpfralle** [comment]
@nyetwurk: ping?

**Comment by sumpfralle** [comment]
The two models of NVME disks, that I use in different servers do not show a high utilization in the `diskstats` plugin (only around 5%).

Thus I assume, that the above description applies to models that either lack proper support or they simply report invalid values.

**Comment by niclan** [comment]
Should note that the % busy stat is calculated based on the kernels I/O busy stats. If the kernel reports that the device was busy almost 1000ms for each second the device is indeed busy.
