### ISSUE TITLE
postgres_connections_ total count wrong with PostgreSQL 10 when using ALL config

### ISSUE THREAD

**Issue by shuehner** [munin-monitoring/munin#1129]
Since PostgreSQL 10 pg_stat_activity view which is used as datasource for this plugin contains information about not just information about connections but other internal postgres processes.

As the plugin does not filter those new rows out it miscounts the connections by typically +5 (or more depending on postgres config (i.e. if streaming replication is used)

Documentation:
https://www.postgresql.org/docs/10/monitoring-stats.html
Table 28.3. pg_stat_activity View
backend_type column

**Type of current backend. Possible types are autovacuum launcher, autovacuum worker, background worker, background writer, client backend, checkpointer, startup, walreceiver, walsender and walwriter.**

To get accurate connection information the output needs to be filtered with: backend_type = 'client backend'.

Note:
* This only applies to the _ALL config of the plugin. If it is configured to only graph a single database this issue is indirectly avoided (as the new lines do not have database name in their output they are filtered out by the database name filter.
* As the new backend_type column was only added in PostgreSQL 10 that requires another version dependent SQL to be added  to the plugin.

**To Reproduce**
1. Configure plugin to run against a PostgreSQL 10 (or higher) database with _ALL config
2. Do not have any active connection open to any database for this PostgreSQL 10 cluster
2. munin-run postgres_connections_ALL 

**Expected behavior**
Expected output is to have 0 connections of any type

**Current, wrong behavior**
Output is:
active.value 0
idle.value 0
idletransaction.value 0
unknown.value 0
waiting.value 5

**NOTE: This issue is about the total count being 5 instead of 0. That all idle connections are reported as waiting for lock is reported as #1131

**Comment by sumpfralle** [comment]
Your proposal #1137 was merged, but I noticed now, that the [documentation you referred to](https://www.postgresql.org/docs/10/monitoring-stats.html) mentions `client backend` while your commit uses  `client connection` as a filter for `backend_type`.

I am tempted to change the condition in order to match the string used in the documentation.
Or what do you think?

**Comment by sumpfralle** [comment]
Ping?
(the release of 2.0.45 is approaching - I would like to finish this before)

**Comment by sumpfralle** [comment]
I changed the filter to `client backend`. I guess, everything is fine now.
