### ISSUE TITLE
warning-HRULES use wrong colour if individual colour for that field

### ISSUE THREAD

**Issue by harvey637** [munin-monitoring/munin#1135]
Hi,
if a field has as special colour defined in the configuration, like in 
<label_name>. colour aabbcc
and has a warnung, than the resulting colour of the HRULE line
ignores this and uses the predefined line_colour from predefined 
colour-array with the field_index.

Problems are in GraphOld.pm lines 1181, 1191, 1259, 1269

Or even as a featurerequest, enable the possibility to configure to
suppress the HRULE for a warning completly.

In my example I have different temperatures in my RZ/Racks with different warnings.
with 8 temperatures and 4 different warnings the graph is a bit overloaded with
all these HRULES for the warnings (and wrong colours also). I I want a HRULE
I can add it manually in the configuration.

cu
Harvey

**Comment by sumpfralle** [comment]
Hello Harvey,

regarding more control over HRULEs: I think, we would rather want to keep the complexity low here ...

Regarding the HRULE colour: please try #1138 and report back!

**Comment by sumpfralle** [comment]
It works for me - thus I merged the branch.
