### ISSUE TITLE
Memory Graph Colors Shifted

### ISSUE THREAD

**Issue by ananomaly** [munin-monitoring/munin#1145]
It appears that the field shmem was added to the memory graph and this caused the colors to shift.
Swap is now grey whereas it used to be red.

OS: CentOS 6.10
Munin versions used
munin-2.0.43-1.el6.noarch
munin-common-2.0.43-1.el6.noarch
munin-node-2.0.43-1.el6.noarch

![capture](https://user-images.githubusercontent.com/16945877/50666434-bba79d00-0f82-11e9-8740-564e4dd67ee9.PNG)

**Comment by sumpfralle** [comment]
Indeed - red is much better :)

The issue was recently fixed in #1126 and released in munin 2.0.44.

Thank you for your report!
