### ISSUE TITLE
munin-node-configure fails on umask set to 0000

### ISSUE THREAD

**Issue by juh** [munin-monitoring/munin#1154]
If the current umask is set to 0000 _munin-node-configure_ fails to run any plugin with "Unable to set umask:". All plugins will fail with a return code of 255.

Reason is line 247 in Node/OS.pm:
`sub set_umask { umask(0002) or croak "Unable to set umask: $!\n"; }`
As umask() returns the old umask value (in my case 0) the test outcome is negative even though the new umask is set successfully. Actually, umask() can never fail, see "man 2 umask":
>        This system call always succeeds and the previous value of the mask
>        is returned.

**How to reproduce**
`#~ umask 000`
`#~ munin-node-configure --suggest`

See how all plugin calls return 255 and no usable suggestions are produced.

**Comment by sumpfralle** [comment]
Thank you for your detailed description!

I fixed the issue now in 878995f7.
