### ISSUE TITLE
disktstats plugin needs to be updated to work with Linux kernel 4.18+

### ISSUE THREAD

**Issue by casasfernando** [munin-monitoring/munin#1159]
Due to changes in the /sys/block/device/stats file introduced in kernel 4.18 and newer the diskstats plugin needs to be updated.
The file reports now 15 fields instead of 11, adding 4 fields for "discard" information.
Since now more than 11 fields are reported the plugin exits with an error. ie:

'/sys/block/dm-0/stat' doesn't contain exactly 11 values. Aborting at /etc/munin/plugins/diskstats line 430.
	main::read_sysfs() called at /etc/munin/plugins/diskstats line 456
	main::parse_diskstats() called at /etc/munin/plugins/diskstats line 528
	main::fetch_device_counters() called at /etc/munin/plugins/diskstats line 35

More information from the kernel documentation:

- Block layer statistics in /sys/block/<dev>/stat: https://www.kernel.org/doc/Documentation/block/stat.txt
```
Name            units         description
----            -----         -----------
read I/Os       requests      number of read I/Os processed
read merges     requests      number of read I/Os merged with in-queue I/O
read sectors    sectors       number of sectors read
read ticks      milliseconds  total wait time for read requests
write I/Os      requests      number of write I/Os processed
write merges    requests      number of write I/Os merged with in-queue I/O
write sectors   sectors       number of sectors written
write ticks     milliseconds  total wait time for write requests
in_flight       requests      number of I/Os currently in flight
io_ticks        milliseconds  total time this block device has been active
time_in_queue   milliseconds  total wait time for all requests
discard I/Os    requests      number of discard I/Os processed
discard merges  requests      number of discard I/Os merged with in-queue I/O
discard sectors sectors       number of sectors discarded
discard ticks   milliseconds  total wait time for discard requests
```

- I/O statistics fields: https://www.kernel.org/doc/Documentation/iostats.txt

```
Here are examples of these different formats::

   2.4:
      3     0   39082680 hda 446216 784926 9550688 4382310 424847 312726 5922052 19310380 0 3376340 23705160
      3     1    9221278 hda1 35486 0 35496 38030 0 0 0 0 0 38030 38030

   2.6+ sysfs:
      446216 784926 9550688 4382310 424847 312726 5922052 19310380 0 3376340 23705160
      35486    38030    38030    38030

   2.6+ diskstats:
      3    0   hda 446216 784926 9550688 4382310 424847 312726 5922052 19310380 0 3376340 23705160
      3    1   hda1 35486 38030 38030 38030

   4.18+ diskstats:
      3    0   hda 446216 784926 9550688 4382310 424847 312726 5922052 19310380 0 3376340 23705160 0 0 0 0
```

**Comment by casasfernando** [comment]
I temporally worked around this issue by removing the "discard" values from the array which is not ideal of course but it will do in my case until the plugin is updated:

```
diff --git a/diskstats.original b/diskstats
index 51e76c4..08d6f24 100755
--- a/diskstats.original
+++ b/diskstats
@@ -426,6 +426,7 @@ sub read_sysfs {
         chomp $line;
 
         my @elems = split /\s+/, $line;
+       splice @elems, 11, 4;
 
         croak "'$stats_file' doesn't contain exactly 11 values. Aborting"
           if ( @elems != 11 );
```

**Comment by sumpfralle** [comment]
Thank you for your report and your detailed description!

Indeed this issue is already fixed in 2.0.43 and 2.999.10 (see a913c523976bb13b2a34968ee5fe3b55d2b0918f).

Please report back, if you still have issues with this change set applied.

**Comment by casasfernando** [comment]
Thanks for looking into this and sorry for the duplicate. Indeed with the change set applied it's working.

**Comment by sumpfralle** [comment]
Great - thank you for testing it!
