### ISSUE TITLE
postgres_connections_ fails for individual databases

### ISSUE THREAD

**Issue by Talkless** [munin-monitoring/munin#1168]
**Describe the bug**
Commit 07794c560f1a40b57109ca73a91ae811bc560708 has stray comment `/* */` that produces query error for the individual database check.

This works OK:
```
# munin-run postgres_connections_ALL
active.value 0
idle.value 20
idletransaction.value 0
unknown.value 0
waiting.value 0
```
This does not:
```
# munin-run postgres_connections_jiradb
Query failed!
```

**Comment by sumpfralle** [comment]
Fixed in #1169, thanks!
