### ISSUE TITLE
memory leak in munin-cgi-html ?

### ISSUE THREAD

**Issue by sevrob** [munin-monitoring/munin#1180]
**Describe the bug**
munin-cgi-html seems to have a memory leak.
It seems to slowly use all available memory, before kernel finally kills the process. This happens once a day.

Running on centos 7, 4GB ram. (2GB before, didn't help to upgrade to 4GB).

Centos7 latest updates, and munin 2.0.45-1.el7 from epel.
Monitoring around 60 hosts, where at least 5 or 10 of them are down.

Logs:
Apr 24 04:17:15 munin-dev1 kernel: Out of memory: Kill process 22812 (munin-cgi-html) score 821 or sacrifice child

Apr 24 04:17:15 munin-dev1 kernel: Killed process 22812 (munin-cgi-html) total-vm:5060760kB, anon-rss:3018580kB, file-rss:4kB, shmem-rss:0kB"

screenshots from munin monitoring itself:
![load-week](https://user-images.githubusercontent.com/48047858/56646448-df046e00-667f-11e9-84e8-19c402eecea3.png)
![memory-week](https://user-images.githubusercontent.com/48047858/56646457-e3c92200-667f-11e9-90df-a60f9eea358f.png)

**Comment by sumpfralle** [comment]
Thank you for the good description of the issue and the graphs!

I took a quick look at the code of `munin-cgi-html`, but I could not see an obvious source of growing memory usage.

@steveschnepp: do you have a recommendation, how I could investigate this problem? When looking for the *perl way* of identifying memory leaks, `Devel::Leak::Object` was quite often mentioned (e.g. https://markandruth.co.uk/2015/12/17/debugging-perl-memory-leaks). Do you have an idea, how we could apply this to the execution model of `munin-cgi-html`? I was thinking of letting the process dump its memory usage to a file whenever a process signal arrives. But my perl wisdom is too narrow to estimate, whether this is a suitable approach.

**Comment by sevrob** [comment]
I forgot to mention a possibly important thing: 
I'm running nginx, so munin-cgi-html and munin-cgi-graph is started as a service - not spawned by CGI.
systemd-scripts for this is provided by munin-cgi package from epel. Also on "latest".

**Comment by steveschnepp** [comment]
A very common workaround is to limit the number of requests a CGI script can handle before being recycled.

**Comment by steveschnepp** [comment]
To be honest, I won't really invest too much time into that one, since there are working workarounds. Therefore closing the issue.

That said, if that leak is still happening in the 2.999.x, it's get fixed then.
