### ISSUE TITLE
Feature request: Node saves values until fetched by master

### ISSUE THREAD

**Issue by merspieler** [munin-monitoring/munin#1181]
**Is your feature request related to a problem? Please describe.**
I'm monitoring a network that contains some laptops which are not always connected to the WLAN or VPN.  
Ofc. I can't get any data from them, when they are not connected but I'd like to view it after they are connected again.

**Describe the solution you'd like**
I'd like the node to collect the data, if not requested by a master and after a reconnect the master asks for an update of the time since the last time it recived an update.

**Describe alternatives you've considered**
Running a master on each laptop... Works fine but I'd like to have it centralized.

**Additional context**

**Comment by sumpfralle** [comment]
I am quite confident, that "munin-async" is exactly, what you are looking for.

Maybe you want to take a closer look: http://guide.munin-monitoring.org/en/latest/node/async.html#the-proxy-node-in-detail-munin-async

Please re-open this issue, if "munin-async" does not solve your task.

**Comment by merspieler** [comment]
Worx for me.. thanks
