### ISSUE TITLE
Overlapping charts

### ISSUE THREAD

**Issue by merspieler** [munin-monitoring/munin#1183]
**Describe the bug**
I've got four hosts in a group. If I view the group by day, the page is wider than my screen.  
Most charts are shown side by side but a few of the fourth host are overlapping charts of the third

**To Reproduce**
I'm not sure, my guess would be that the chart description si to wide...

**Expected behavior**
Show the charts side by side without overlapping

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.
[![munin.png](https://i.postimg.cc/T1VvYyFH/munin.png)](https://postimg.cc/9wQnLfWG)

**Desktop (please complete the following information):**
 - OS+Distribution Version: Raspbian stretch 
 - Browser (if relevant) tested with qutebrowser and firefox
 - Munin Version 2.0.33

**Additional context**

**Comment by sumpfralle** [comment]
Indeed: the visualization uses a static grid in munin 2.0.

Munin 3.0 is getting close to its release - thus we are not putting any more effort into the munin 2.0 visualization. With munin 3.0 the graph layout seems to be more flexible: https://demo.munin-monitoring.org/server/comparison-day.html (not suffering from the bug you described).

Thus I am closing this issue for now. Thanks for your report!
