### ISSUE TITLE
munin-update is very slow (resource consuming)

### ISSUE THREAD

**Issue by bra-fsn** [munin-monitoring/munin#1193]
**Describe the bug**
I have some multigraph nodes which publish a lot of data (a complete conversation between the node and the master is around 900 kiB).
munin-update runs on one of this nodes (when all other nodes are disabled, so this is the only thing which the machine has to run) for about 200 seconds.
If all hosts are configured, munin-update workers just times out or they just take so long it's just too slow (around 10 minutes!).
 
Running munin-update with NYTProf shows where the problem is:

Calls | P | F | ExclusiveTime | InclusiveTime | Subroutine
-- | -- | -- | -- | -- | --
2233 | 1 | 1 | 122s | 122s | Munin::Master::Host::get_canned_ds_config
190 | 1 | 1 | 13.8s | 13.8s | Munin::Master::Node::CORE:sysread (opcode)
30006 | 1 | 1 | 3.94s | 3.94s | Munin::Master::Node::CORE:readline (opcode)
30027 | 3 | 2 | 1.35s | 146s | Munin::Common::Timeout::do_with_timeout (recurses: max depth 1, inclusive time 5.75s)
9 | 1 | 1 | 1.28s | 2.06s | Munin::Master::Node::parse_service_config
30006 | 5 | 1 | 521ms | 6.27s | Munin::Master::Node::_node_read_single
34814 | 3 | 1 | 448ms | 534ms | Munin::Master::Node::_sanitise_fieldname
30006 | 1 | 1 | 372ms | 4.32s | Munin::Master::Node::__ANON__[Munin/Master/Node.pm:657]
204356 | 12 | 1 | 342ms | 342ms | Munin::Master::Node::CORE:match (opcode)
9 | 1 | 1 | 288ms | 6.45s | Munin::Master::Node::_node_read
9 | 1 | 1 | 277ms | 572ms | Munin::Master::Node::parse_service_data
11374 | 30 | 4 | 169ms | 189ms | Log::Log4perl::__ANON__[Log/Log4perl.pm:140]
2232 | 1 | 1 | 142ms | 252ms | Munin::Master::UpdateWorker::_ds_config_eq
9 | 1 | 1 | 142ms | 123s | Munin::Master::UpdateWorker::_compare_and_act_on_config_changes
4496 | 3 | 1 | 110ms | 110ms | Munin::Master::UpdateWorker::_get_rrd_data_source_with_defaults

Each iteration of get_canned_ds_config takes around 50 ms and there's 2233 of them here (due to the high number of graphs/data).
There's even a 
`    # XXX: Could this be done in some sane way?
`
in that code, so even the author(s) felt that this is not the right way to do this. :)
Could you please fix this somehow? We're otherwise fine, but this kills us.

**To Reproduce**
1. have a node with a lot of data points
2. get a 100% pegged CPU for a long time in munin-update and get missing data plots due to timeouts

**Expected behavior**
This resource wasting loop should be fixed.

**munin master:**
 - OS+Distribution Version: FreeBSD 12
 - Munin Version 2.0.49

**Comment by sumpfralle** [comment]
Thank you for benchmarking this issue in detail!

I took a look at `get_canned_ds_config` and its callers, but I did not see an obvious approach for reducing the number of calls.

Maybe you could try whether the following patch improves the performance for you?
```patch
--- a/master/lib/Munin/Master/Host.pm
+++ b/master/lib/Munin/Master/Host.pm
@@ -66,11 +66,11 @@ sub get_canned_ds_config {
 
     my %ds_config;
     my $svc_ds_prefix = "$service.$data_source.";
+    my $svc_ds_prefix_length = length($svc_ds_prefix);
 
     for my $svc_ds_prop (keys %$self) {
-        if (index($svc_ds_prop, $svc_ds_prefix) == 0) {
-            my $prop = substr($svc_ds_prop, length($svc_ds_prefix));
-            $ds_config{$prop} = $self->{$svc_ds_prop};
+        if (rindex($svc_ds_prop, $svc_ds_prefix, 0) == 0) {
+            $ds_config{substr($svc_ds_prop, $svc_ds_prefix_length)} = $self->{$svc_ds_prop};
         }
     }
 
```

I could imagine, that the usage of `rindex` instead of `index` and the removal of the temporary variable could save a good amount of time. But I am not sure, whether these are the steps that are crucial for performance.
I am looking forward to your evaluation!

**Comment by bra-fsn** [comment]
Thanks for the quick response, but I couldn't see any significant differences. :(

**Comment by steveschnepp** [comment]
The upcoming 3.0 is specially designed to provide real performance improvements.

I'd suggest you try the 2.999.x branch, and give us feedback

**Comment by bra-fsn** [comment]
@steveschnepp : according to this: https://github.com/munin-monitoring/munin/blob/2.999.11/lib/Munin/Master/Host.pm
it has the same code, so I'm not sure what should I expect from it...

**Comment by sumpfralle** [comment]
>  it has the same code in get_canned_ds_config, so I'm not sure what should I expect from it...

Yes, indeed this function stayed unchanged. But `get_canned_ds_config` is not called anymore.
I am not sure, whether this is a problem (i.e. the configuration statements are not applied anymore) or whether its functionality was replaced meanwhile.

**Comment by bra-fsn** [comment]
Oh, I'm trying it then.
First attempt to run `munin-update`:
```
Insecure dependency in sysopen while running with -T switch at /usr/local/lib/perl5/site_perl/Munin/Master/Utils.pm line 103.
```
Trying to run munin-httpd gives similar:
```
2019/06/02-21:32:22 Insecure $ENV{PATH} while running with -T switch at /usr/local/lib/perl5/site_perl/Net/Server/Proto.pm line 180, <DATA> line 16.
```

Also, running munin-update gives a lot of:
```
Use of uninitialized value $rrd_file in concatenation (.) or string at /usr/local/lib/perl5/site_perl/Munin/Master/UpdateWorker.pm line 1049, <GEN0> line 2747.
Use of uninitialized value $ds_id in concatenation (.) or string at /usr/local/lib/perl5/site_perl/Munin/Master/UpdateWorker.pm line 495, <GEN0> line 2747.
```
Is this expected, or should I change something?

Otherwise it really seems to be somewhat faster, but the graphs were empty, so I'll double check later what happened.

**Comment by steveschnepp** [comment]
What commit/tag did you try ?

**Comment by bra-fsn** [comment]
This one:
`commit 20abb86186335e9b2dda04b9163687c1df2d4328 (HEAD, tag: 2.999.11)`

**Comment by bra-fsn** [comment]
Apart from all above, I could switch to 2.999.11 by copying all RRDs. I can confirm that munin-update is much faster and eats less CPU.
Roundtrip time to collect all data is around 2 minutes which is totally fine.

**Comment by steveschnepp** [comment]
Could you test https://github.com/munin-monitoring/munin/commits/2.999.12 ?

**Comment by bra-fsn** [comment]
Yes, it solves the issue with taint mode! Thanks!

**Comment by steveschnepp** [comment]
so, could you test your performance issues with that one, and close the issue if it is handled

**Comment by bra-fsn** [comment]
Sure!
BTW, I have other problems, for example two hours ago all graphs just stopped (rrd files are updated, at least according to their mtime, I haven't yet looked into them).
But I will open a new issue for that.
