### ISSUE TITLE
Double-timestamping with back-dated plugins and munin-async

### ISSUE THREAD

**Issue by shtrom** [munin-monitoring/munin#1225]
**Describe the bug**
When a plugin issues back-dated values, as described in http://guide.munin-monitoring.org/en/latest/develop/plugins/plugin-concise.html#fetch, and this plugin is queried using munin-async, the data returned on spoolfetch is incorrect, and contains two timestamps:

    <TIMESTAMP_async>:<TIMESTAMP_plugin>:VALUE

This in turns confuses `munin-update`:

    2019/09/09 23:00:32 [ERROR] In RRD: Error updating /var/lib/munin/host-internode_usage-current-hourly_rate-d.rrd: /var/lib/munin/host-internode_usage-current-hourly_rate-d.rrd: found extra data on update argument: 188192950706

where the `extra data` is actually the value.

Example plugin: https://github.com/munin-monitoring/contrib/blob/7fff067ffad6bbb7f87bd8709f351f7bbe5d561b/plugins/isp/internode_usage#L184

**To Reproduce**
1. Create a dummy plugin that returns, say, `dummy.value $(date -d -1day +%s):${RANDOM}`
2. Use that plugin on a machine running `munin-asyncd`
3. Use `munin-async --spoolfetch`
4. See the data returned as `dummy.value <NOW>:<YESTERDAY>:<RANDOM_VALUE>`

**Expected behavior**

The timestamp of when `munin-asyncd` collected the data should not be prepended

    dummy.value <YESTERDAY>:<RANDOM_VALUE>

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS+Distribution Version: Debian Bullseye
 - Munin Version 2.0.49

**Comment by sumpfralle** [comment]
Thank you for reporting this issue!

I think, the issue was introduced in 700d08a2975127c9f5f5b98e817a61c06c9db717.
Would you please verify, that #1227 fixes this issue for you?

**Comment by shtrom** [comment]
Yep, that fixed it :+1: 

Side question: when should I use `N` versus just no timestamp in my plugins?

**Comment by sumpfralle** [comment]
> Yep, that fixed it

Great - thanks for testing!

> Side question: when should I use N versus just no timestamp in my plugins?

The same question bugs me, too :(
Since rrdtool seems to accept the magic value `N` as a placeholder for "now", I can imagine, that the original author intended to let this backend detail slip into the munin protocol.
And least it is not documented - thus maybe we can rid of it somewhen in the future ...
