### ISSUE TITLE
TLS connection failed

### ISSUE THREAD

**Issue by hajes** [munin-monitoring/munin#1229]
**Describe the bug**
I have followed official Munin TLS Guide

I have created certificates using easy-rsa according to this guide >>> https://sven.stormbind.net/blog/posts/misc_munin_tls/

## Munin Master
./easyrsa init-pki
./easyrsa build-ca
./easrsa gen-req master
./easyrsa sign-req client master
./easyrsa set-rsa-pass master nopass

## munin-node
I have copied CA cert from munin-master
./easyrsa gen-req node1
./easyrsa sign-req server node1
./easyrsa set-rsa-pass node1 nopass

after restarting services, following errors appeared in munin-update.log

* master.key & master.cer "permission denied" - in your guide is suggested "chmod 700"

SOLUTION is chmod 755, which is most likely dangerous kludge

* after permission problems came `[ERROR] Could not enable TLS:  19222: 1 - error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`

* with "tls_verify_certificate no" comes `[PERL WARNING] Use of uninitialized value $read in string eq at /usr/share/perl5/Munin/Common/TLS.pm line 379, <GEN1> line 2.
2019/09/21 10:10:01 [FATAL] Socket read from 19-01.hajes.org failed.  Terminating process. at /usr/share/perl5/Munin/Master/UpdateWorker.pm line 90.
2019/09/21 10:10:01 [ERROR] Error in node communication with 19-01.hajes.org/136.243.67.68:4949: [FATAL] Socket read from 19-01.hajes.org failed.  Terminating process. at /usr/share/perl5/Munin/Master/UpdateWorker.pm line 90.
2019/09/21 10:10:01 [ERROR] Munin::Master::UpdateWorker<hajes.org;19-01.hajes.org> failed to connect to node`

munin-master runs on KVM Debian and munin-node is on Debian root dedicated server. There is no guide that explains all in detail and I have no idea whether it is certificates error or some bug.

Non-paranoid mode also failed

Both servers are registered in DNS as FQDN and config file refers to FQDN as well as certificates have been made with same FQDN.

Perhaps address in munin-node should also use FQDN instead of IP

**Comment by ssm** [comment]
Hello.

Regarding the key permissions, they should be readable only for the user running the process. The certificate is usually publicly readable from the server network interface.  The permissions depend on the user and group owning the files. "root:munin 0440" (u=r,g=r) or "munin:munin 0400" (u=r) are good values.  

Regarding the "certificate verify failed" message: If certificate verification is enabled, the client (and server) may verify the name in the certificate against the name of the other end of the connection.  The host name should match the name in the certificate, and the CA certificate should be added to the trust store used.

- If the munin master connects to an IP address, and the certificate does not contain that IP address, name verification will fail.

If the munin master connects to an IP address, and munin is not configured to trust the CA certificate, certificate verification will fail based on that..

The "uninitialized value" looks like a bug in the munin TLS code.  Which version are you running?

**Comment by hajes** [comment]
Hi thanks for reply.

Munin-master is Debian stable "munin (2.0.49-1)"

Munin-node is same. I will try backports.

I have changed "address" in config to FGDN used in certificates. Error remains same.

**Comment by hajes** [comment]
I have generated certificates again after long search. A guide you suggest on your web page is useless.

I can confirm that TLS connection works.

Shall I make a guide for future users?

**Comment by sumpfralle** [comment]
> Shall I make a guide for future users?

This would be great and allow others to avoid the hassle you suffered ...
