### ISSUE TITLE
more detail in example for snmp

### ISSUE THREAD

**Issue by syswombat** [munin-monitoring/munin#1235]
Hello
on this Example
https://github.com/munin-monitoring/munin/blob/master/doc/tutorial/snmp.rst
it is not cleare how to have a more complex naming!

As example

[muninMaster.vm.domain.com]

Monitoring other VM
[github-01.vm.domain.com]

it show me nice listetd

if i wish to add a devie with SNMP

[swt-01.switch.domain.com] this naming is not working

[swt-01] is working but out of the hirarchy

so what i do wrong?

in the example with dumbledore munin and munin-node is not clear, or not to me.

have a nice day
vinc

**Comment by sumpfralle** [comment]
> [swt-01.switch.domain.com] this naming is not working

Are you sure? Did you notice an error message?

I am quite confident, that this name works.

> [swt-01] is working but out of the hirarchy

If you want to group your nodes in the munin listing, then you should use the ";" (semicolon):
```
[bar;foo]
....
```
This specifies the host `foo` within the group `bar`.

Does that solve your issue?

In this case I will improve the documentation, that you referred to.

**Comment by syswombat** [comment]
[switch.domain.com;swt-01]
i will try to add it like this!

i did not check the Log file, it's just not there in the Gui

**Comment by sumpfralle** [comment]
> i did not check the Log file, it's just not there in the Gui

This would certainly be an unknown bug or a local configuration issue. Feel free to explore it (via the log file), if you feel like ...

**Comment by syswombat** [comment]
if i do it like this it show corect in the GUI
[switch.domain.com;swt-01]
BUT, it stop to collect information
going back i have a hole in the missing time but the Graph are back
---
the Log files
multitail munin-html.log munin-graph.log munin-node.log munin-update.log
show's no error about the SNMP-Plugin!
----
giving a try again, with your solution, the page looks orderd like it should, but no graph also the update information not changing.
i think like this
[switch.domain.com;swt-01] it is only taged
[swt-01.switch.domain.com] like this the plugin know to pick up the snmp community password

**Comment by sumpfralle** [comment]
OK - sorry, I forgot about your usage of SNMP.
Indeed - this may need some special treatment. But I cannot really comment it, since I do not use SNMP based plugins.

Maybe someone else can provide some input?

**Comment by yunal** [comment]
@syswombat : The community string is not in the munin-master configuration, but rather on the node where the snmp plugins run.

So, firstly get the plugin working: This you can check by running "munin-run -d <plugin name>" on the server/node you want to run the plugin on. Please provide the output as a file attachemnt or paste it verbatim.

**Comment by syswombat** [comment]
Hello, my Munin-Master, is also a Munin-Node too!
i do pick the Information bei SNMP because i can't install a Munin-Node on a CiscoSwitch!
to get the Information works fine, the SNMP-Plugin works fine.

just 
to keep and show it in a structure is not working

[swt-01.infra.domain.com]
In the Group the it would show Infra.domain.com and there inside i would see all device belonging there.
same system i have with VM.domain.com and all my VM are listed there, but the difference all of them have a Munin-Node installed and do not work with SNMP

**Comment by yunal** [comment]
I know all this I wrote some snmp support for Munin. Now please show me what "munin-run -d <snmp_plugin>" outputs and we'll take it from there.

**Comment by syswombat** [comment]
i will do it tonight - but the Plugin itself work i just can't add it to a Group.
have a nice day
vinc

**Comment by syswombat** [comment]
and the last line is correct 108 Days up an running (switch)
```
**# munin-run -d snmp_swt-02_uptime**
# Processing plugin configuration from /etc/munin/plugin-conf.d/README
# Processing plugin configuration from /etc/munin/plugin-conf.d/deb_packages
# Processing plugin configuration from /etc/munin/plugin-conf.d/dhcpd3
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/snmp_communities
# Processing plugin configuration from /etc/munin/plugin-conf.d/spamstats
# Setting /rgid/ruid/ to /113/65534/
# Setting /egid/euid/ to /113 113/65534/
# Setting up environment
# Environment community = dpJIvOa
# About to run '/etc/munin/plugins/snmp_swt-02_uptime'
uptime.value 108.816945023148
```

**Comment by yunal** [comment]
So, the plugins "host" part of the plugin name reads "swt-01" and "swt-02". The plugin reports it's own host name to munin as "swt-01" and "swt-02".

Munin master must look for the nodes as the same name, as configured in the master configuration. Please have a look at this http://munin-monitoring.org/wiki/FAQ_no_graphs#Inconsistentnamesforthenodeonthemasterandonthenode (the third section).

**Comment by syswombat** [comment]
Thanks for your feedback, i will try tonight, but first i have to activate Telnet on the switch too.
and will report back. i did add the device also in the host file 
101.10.10.15   swt-01    swt-01
i did so the SNMP Plugin write the name and not the IP
have a nice day
vinc

**Comment by niclan** [comment]
If the switch host names are listed in your hosts file you can list them like this:
1. In /etc/hosts: `101.10.10.15 swt-01.infra.kozo.ch swt-01` The first name is "canonical"
1. Rename the plugin to snmp_swt-01.infra.kozo.ch_uptime
1. Restart munin-node

You will loose the graph history unless you also "mv" the rrd files from the old location to the new location.

**Comment by syswombat** [comment]
whats the meaning of canonical? sorry about that.

@niclan i change like you did and yes in the structure it works like this. only to rename the file did not work, i will have to find out if and where it is key sensitiv.
have a nice day and thanks for your patience

**Comment by syswombat** [comment]
@niclan so i deleted and set it up with new naming like you sugest.
snmp_uptime works on Both
snmp_if_multi did work before but now it is not showing the 10 Ports on both switch not working any more

also to test it with 
# munin-run -d snmp_swt-02.Infra.kozo.ch_uptime   | works fine

# munin-run -d snmp_swt-02.Infra.kozo.ch_if_multi
# Unknown service 'snmp_swt-02.Infra.kozo.ch_if_multi'

**Comment by niclan** [comment]
The `unknown service` means that there is no such plugin or that is there is a symlink in /etc/munin/plugins it points to nothing.

**Comment by syswombat** [comment]
Hello @niclan 
yes, it works like i wished!
the problem - i think - there have ben a space at the end.
i deleted all, and recreated and - it works - thanks a lot for your help!
have a nice day
vinc

**Comment by yunal** [comment]
Good. Munin is like a database and the host names are keys.  Everything has to match up. You have to arrange it so.

**Comment by sumpfralle** [comment]
@syswombat: I am glad, that you solved the issue!

Do you have any hints, how we can improve the documentation for your use-case?

**Comment by syswombat** [comment]
Hello Lars
maybe you should show how it is possible to group with this name. and also the Difference between the Munin-Node  and the SNMP-Plugin. Because it is working different. And also to point it have to bee the same in the SNMP-Plugin-Name but also in the munin.conf - sometimes is the documentation not easy to understand.
I think if coder write the documentation - some steps are clear to them but for a no-Coder it is not easy to follow.

**Comment by sumpfralle** [comment]
I understand. Thank you for your comments.

But I have no experience with SNMP plugins, thus I am poor at writing documentation for it.
Maybe you gained some specific insights during this adventure, which you could write down here, so I can copy it into the documentation?
