### ISSUE TITLE
cat: No such file when munin gets metrics

### ISSUE THREAD

**Issue by philippemilink** [munin-monitoring/munin#1236]
Hi,

I use the following plugin to measure the speed of my network connection:
```sh
#!/bin/bash

case $1 in
        config)
        echo "graph_category network"
        echo "graph_title Speedtest"
        echo "graph_args --base 1000 -l 0"
        echo "graph_vlabel DL / UL"
        echo "graph_scale no"
        echo "down.label DL"
        echo "down.type GAUGE"
        echo "down.draw LINE1"
        echo "up.label UL"
        echo "up.type GAUGE"
        echo "up.draw LINE1"
        echo "graph_info Graph of Internet Connection Speed"
        exit 0;;
esac

OUTPUT=`cat /tmp/speedtest.out`
DOWNLOAD=`echo "$OUTPUT" | grep Download | sed 's/[a-zA-Z:]* \([0-9]*\.[0-9]*\) [a-zA-Z/]*/\1/'`
UPLOAD=`echo "$OUTPUT" | grep Upload | sed 's/[a-zA-Z:]* \([0-9]*\.[0-9]*\) [a-zA-Z/]*/\1/'`

echo "down.value $DOWNLOAD"
echo "up.value $UPLOAD"
```

The file /tmp/speedtest.out contains the following data:

> Ping: 26.634 ms
> Download: 88.34 Mbit/s
> Upload: 92.60 Mbit/s

The plugin is configured as follow:
```conf
[speedtest]
user root
```

This plugin is configured on a RaspberryPi with Raspbian 10 with munin-node 2.0.49-1. The munin server runs on a VPN with Debian 8 and munin 2.0.25-1+deb8u3. 

Evertything works as expected, except this speedtest plugin. In the Raspeberry Pi logs, there is the following error:

> 2019/10/13-18:10:09 [3118] Error output from speedtest:
> 2019/10/13-18:10:09 [3118]      cat: /tmp/speedtest.out: No such file or directory

I cannot understand what is the cause of this bug. I played with rights of the file speedtest.out, but even with rights 666 it isn't working.

The more surprising is that it worked before ! Before what, that is the question...

Any idea about how to solve the problem ?

**Comment by sumpfralle** [comment]
This is probably caused by the hardening features for `munin-node` being enabled.

Take a look at the systemd service file shipped for munin-node. It contains the following line:
```
PrivateTmp=true
```

You may want to create an override configuration file for this service (via `systemctl edit munin-node`).

**Comment by philippemilink** [comment]
Yeah ! Indeed, I overrided the service definition and now it works ! Thanks a lot !

Is it mentionned somewhere in the documentation (to know if I missed it !) ?

**Comment by sumpfralle** [comment]
> Is it mentionned somewhere in the documentation (to know if I missed it !) ?

Indeed, the Debian package lacks a hint for this at the moment. Since issues like this were reported from multiple people, we will definitely mention in the README.Debian with the next package update.

**Comment by niclan** [comment]
@philippemilink - there is good reason to avoid putting files with fixed names into /tmp because they have a very long history of being used for security breaches. This is also the reason for the PrivateTmp setting (which I did not know about). It is far better to put this intermediate file into something like /var/lib/speedtest where only the speed test script has writing permissions. This also allows you to not weaken your systems' security.
