### ISSUE TITLE
Spent over 10 hours and cannot install Munin

### ISSUE THREAD

**Issue by adrianTNT** [munin-monitoring/munin#1237]
I have centos 7, I installed munin, munin-node and munin-apache with yum (from epel repo).

I am lost and frustrated as hell. 

Can someone tell me what alias I need to create in `/etc/httpd/conf.d/munin.conf`  ?
Now I have this:

```
<VirtualHost *:80>
    ServerName munin.MY-SITE.net
    ServerAlias munin

    DocumentRoot /var/www/html

    Alias /munin/ /etc/munin/
    <Directory /etc/munin>
        Require all granted
        DirectoryIndex index.html
    </Directory>

    Alias /munin/static/ /etc/munin/static/
    <Directory /etc/munin/static>
        Require all granted
        DirectoryIndex index.html
    </Directory>

    ScriptAlias /munin-cgi/munin-cgi-graph /usr/lib/munin/cgi/munin-cgi-graph
    ScriptAlias /munin /usr/lib/munin/cgi/munin-cgi-html
    <Directory /usr/lib/munin/cgi>
        Require all granted
        <IfModule mod_fcgid.c>
            SetHandler fcgid-script
        </IfModule>
        <IfModule !mod_fcgid.c>
            SetHandler cgi-script
        </IfModule>
    </Directory>

</VirtualHost>
``` 

I see this path in the munin.conf file but I don't have it on server:  `/usr/lib/munin/cgi/munin-cgi-graph`

When I access `/munin` or `/munin/static` , the apache log says:

```
Cannot serve directory /etc/munin/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
```

**Comment by sumpfralle** [comment]
How did you solve this issue? Is this maybe a problem with the munin packaging in the epel repository?

**Comment by adrianTNT** [comment]
I closed the issue because I attempted by other means and I didn’t want others to spend time answering here.

I “fixed” it by setting the Munin config to generate the stats by “chron” instead of “cgi” so no apache config is involved, works ok.

**Comment by sumpfralle** [comment]
Regarding your above configuration: I guess you need to replace `Alias /munin/ /etc/munin/` with one of the following:
* CGI: `ScriptAlias /munin /usr/lib/munin/cgi/munin-cgi-html`
* cron: `Alias /munin /var/cache/munin/www`

**Comment by kimheino** [comment]
"rpm -qi munin" includes:

```
You must also install munin-nginx or munin-apache package. See
/usr/share/doc/munin-*/*.conf for example config files and installation
instructions.
```

I'll include more pointers to example config files.

**Comment by adrianTNT** [comment]
I do see the sample config in `/usr/share/doc/munin-*/*.conf` , this helps a lot, because sometimes configuration is different with different Apache and Munin versions, so having sample files in the installed version is a plus. 
I didn't come across these sample files when looking trough the online Munin documentation :(
