### ISSUE TITLE
munin-limits in 2.0.50 is broken

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1239]
Copy from irc channel:

Commit 290650ee2c2f breaks munin 2.0.50 in rhel7. I'm now receiving this warning every 5min by email:

Undefined subroutine &Munin::Master::LimitsOld::looks_like_number called at /usr/share/perl5/vendor_perl/Munin/Master/LimitsOld.pm line 410.

...and munin-limits dies on that.

Simply removing that function call isn't enough, as "0.00" and "0.000340436183048969" triggers logging.The idea in that commit is great and it helps to debug problems, so please fix it.

**Comment by kimheino** [comment]
Yes, that works.

**Comment by sumpfralle** [comment]
Fixed in 369d6a92bf6b226ae8cf28a924832df20f9f74e4.
