### ISSUE TITLE
Linux proc plugin doesn't recognize negative nice level

### ISSUE THREAD

**Issue by rclasen** [munin-monitoring/munin#1241]
**Describe the bug**
processes with negative niceness show zero data

**To Reproduce**
1. in plugin-conf.d:
[proc]                                                                           
user root                                                                        
env.procname sleep

2. enable plugin
ln -s  /usr/share/munin/plugins/proc /etc/munin/plugins

3. start non-nice processes *as root*
nice -n -10 sleep 3600

munin-run proc
[...]
multigraph proc_processes    
sleep.value 0
[...]

**Expected behavior**
proc_processes/sleep.value should be >= 1

**Desktop (please complete the following information):**
 - debian buster... but I've checked the version in master has the same issue

**Additional context**
regexp for Column 19 in /proc/*/stat needs to allow a leading '-' - similar to column 18:

https://github.com/munin-monitoring/munin/blob/c803db5be11f1a97e8897ee59af91dda722ef562/plugins/node.d.linux/proc#L365

**Comment by sumpfralle** [comment]
Thank you for your precise description of the problem.

I fixed the issue in 1b0fefcaf5b9a2872c28b57ef5901fde00e29763.
