### ISSUE TITLE
RPM packages for CentOS 8?

### ISSUE THREAD

**Issue by gralex54** [munin-monitoring/munin#1242]
Hello,

I clear understand it is up to to Epel repository maintainers to release RPM packages for CentOS 8, and still could you give any idea whether you can force the release?

Regards,
Alex.

**Comment by sumpfralle** [comment]
> [..] and still could you give any idea whether you can force the release?

I guess, you have two options: "encourage" or "do it" :)

Additionally you can find "bcg" in he IRC channel #munin (irc.oftc.net). He packages munin for EPEL.

Closing, since I hope, that I answered your question.
