### ISSUE TITLE
ntp_states plugin doesn't work in debian package v.2.0.49-1

### ISSUE THREAD

**Issue by Jo-Jo0** [munin-monitoring/munin#1244]
**Describe the bug**
In commit 87e1e94 the lines stating the graph title etc. got removed from the ntp_states plugin, what breaks the funktionality of the plugin. Reinserting the lines, fixes the problem.

**To Reproduce**
Install v.2.0.49-1 of the munin-plugins Debian Package and try using the ntp_states plugin. Munin won't render the ntp_states graph.

**Expected behavior**
Render the ntp_states graph.

**Desktop (please complete the following information):**
 - OS+Distribution Version: Server: Debian 9 Stretch
                                            Client: Debian 10 Buster
 - Munin Version 2.0.49

**Comment by sumpfralle** [comment]
I fixed the issue in 738b47356e7582ba96bf73a9e00b20f095611e.

Thank you!
