### ISSUE TITLE
Cannot update munin on linux CentOS

### ISSUE THREAD

**Issue by claitonpena** [munin-monitoring/munin#1252]
**Describe the bug**
From munin@ip- .us-west-2.compute.internal  Sun Dec  1 08:30:02 2019
Return-Path: <munin@ip- .us-west-2.compute.internal>
Received: from ip- .us-west-2.compute.internal (localhost [127.0.0.1])
    by ip- .us-west-2.compute.internal (8.14.7/8.14.7) with ESMTP id xB1CU248013125
    for <root@ip- .us-west-2.compute.internal>; Sun, 1 Dec 2019 08:30:02 -0400
Received: (from munin@localhost)
    by ip- .us-west-2.compute.internal (8.14.7/8.14.7/Submit) id xB1CU2JF013124;
    Sun, 1 Dec 2019 08:30:02 -0400
Date: Sun, 1 Dec 2019 08:30:02 -0400
Message-Id: <201912011230.xB1CU2JF013124@ip- .us-west-2.compute.internal>
From: "(Cron Daemon)" <munin@ip- .us-west-2.compute.internal>
To: root@ip-.us-west-2.compute.internal
Subject: Cron <munin@ip- >  /usr/bin/munin-cron
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=165506>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/993>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <MAILTO=root>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/var/lib/munin>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=munin>
X-Cron-Env: <USER=munin>

Creating lock /var/run/munin/munin-update.lock failed: Permission denied
 at /usr/share/perl5/vendor_perl/Munin/Master/Update.pm line 129.

**To Reproduce**
1. Go to 'Yum update'

**Expected behavior**
Update Munin

Creating lock /var/run/munin/munin-update.lock failed: Permission denied
 at /usr/share/perl5/vendor_perl/Munin/Master/Update.pm line 129.

**Desktop (please complete the following information):**
 - Linux version 3.10.0-1062.4.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP 
 - Munin Version 

**Additional context**
line 129 from Update.pm  >>

my $lock = "$config->{rundir}/munin-update.lock";
    munin_runlock($lock);

**Comment by sumpfralle** [comment]
Updating a packaged version of munin is usually distribution-specific.

@kimheino: do you have an idea?

**Comment by kimheino** [comment]
What was previous Munin version, what is the new one?

What are attributes of /var/run/munin/ directory (owner, mode) and it's selinux content?

**Comment by sumpfralle** [comment]
@claitonpena: ping?

**Comment by sumpfralle** [comment]
Assuming that this is either a local or a packing problem, I am closing the issue.
