### ISSUE TITLE
munin-plugin ignoring group

### ISSUE THREAD

**Issue by lifeofguenter** [munin-monitoring/munin#1259]
**Describe the bug**

When setting `user` and `group` in `plugin-conf.d`, `group` is ignored. This is verified by using `munin-run` with a simple shell script to output `id -un` and `id -gn`.

**Comment by sumpfralle** [comment]
Could this be similar to #633?

**Comment by lifeofguenter** [comment]
@sumpfralle I did check that issue and also tried out by adding `set -p` but it seems to be a different issue. The script is not running as root but as `$user:munin`. I expect it to run as `$user:$group`.

**Comment by lifeofguenter** [comment]
Mystery solved, while the initial bug is still true (and most probably solved with #633) the underlying issue I had was due to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921985#36 :)
