### ISSUE TITLE
Enhancement of plugin hddtemp_smartctl

### ISSUE THREAD

**Issue by vpieper** [munin-monitoring/munin#1262]
Certain Intel SSDs have a temperature attribute flag of the smart ID# 194 named "Temperature_Internal", that is not in this plugin yet.

I use Debian Jessie with Munin version 2.0.25-1+deb8u3

I tried to directly insert the latest plugin from Github to my Munin plugin dir however upon reviewing it, it is clear that the flag is not present in the plugin.

HDDTemp understands the flag of this type of disk (Intel DC3500 SSD):

```
hddtemp /dev/sda
/dev/sda: INTEL SSDSC2BB120G4: 27°C

```
Smart output:

Command used: `/usr/sbin/smartctl -A -d sat /dev/sda`

```
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
194 Temperature_Internal    0x0022   100   100   000    Old_age   Always       -       27
```

There is another temp flag in this particular Intel disk named Temperature_Case, which is the airflow flag:

```
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
190 Temperature_Case        0x0022   080   075   000    Old_age   Always       -       20 (Min/Max 20/25)
```

Can this or these flag(s) be added to the plugin?

An identical issue was fixed under #798 (Samsung SSDs)

**Comment by sumpfralle** [comment]
Thanks for your report!

I think, the issue (with `Temperature_Internal`) was fixed in c81804ec123258349798cfb316ca1cd0cc731142.
The name was part of a regex pattern - maybe you overlooked it.
(the same goes for `*_Case`)

Please re-open, if it does not work for you.
