### ISSUE TITLE
sensors_: dealing with warnings produced for RTC batery voltage

### ISSUE THREAD

**Issue by Talkless** [munin-monitoring/munin#1264]
**Is your feature request related to a problem? Please describe.**

Munin page hints about "problem", it says: `Warning (1)`, if `sensors` output has field `RTC Battery Voltage`, as it is on `ASUS PRIME Z370-A` motherboard with `nct6796` chip.

Current battery voltage indicator is `3.20`,  while Munin's `Warn` range is `2.28:3.13`. So, since battery is not too old, it's voltage is (obviously) still rather high. Well, that's how batteries work, they lose their voltage in time... Though initial higher voltage in fact that's a good indicator, not an issue.

`sensors_` does have `env.volt_warn_percent` option, I could decrease it by a lot (instead of default 20%), but it might not be preferred for other "normal", non-battery voltage inputs.

**Describe the solution you'd like**

Maybe ability to specify (override) `volt_warn_percent` for a specific input (like `volt_warn_percent_<n>`), or disable warning for specified inputs might do the trick?

Any other ideas?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sumpfralle** [comment]
Just for my understanding: the battery (or the board / controller) reports a specific minimum and maximum value for the battery (resulting in `2.28:3.13` for your case). But the battery exceeds the maximum. As you said, this could be an indicator for a good quality - which can only be evaluated by the user.

It would surely be possible to add another environment variable to work around such a misbehavior of the battery (or improper specification delivered by the board / chip).

Personally I have to admit, that I am not enthusiastic to implement this. Especially given the fact, that `sensors_` was replaced in `master` (for munin 3.0) with the `hwmon` plugin (see 28db208a2da6f807c5322f5422fcfeba9850b5d8).

Maybe it is possible to solve this issue by configuring `lm-sensors` instead? The [arch wiki](https://wiki.archlinux.org/index.php/Lm_sensors#Adjusting_values) describes how to override values via the `sensors3.conf` file. I guess, this would be the simplest approach for mis-reported values.
Of course, code contributions are welcome nevertheless.

**Comment by Talkless** [comment]
> But the battery exceeds the maximum

No. Maximum is 3.41v:
```
RTC Battery Voltage:   +3.20 V  (min =  +2.00 V, max =  +3.41 V)
```
That range that you pasted is `[min+20%;max-20%]`. If I understand `sensors_` implementation correctly, that is.

> Maybe it is possible to solve this issue by configuring lm-sensors instead? 

Yeah, I could bump `max` so that new battery voltage would not enter "warning" from the high-voltage side.

**Comment by Talkless** [comment]
> Especially given the fact, that sensors_ was replaced in master (for munin 3.0) with the hwmon plugin

Oh, I didn't new that, I should check it, thanks!
