### ISSUE TITLE
Timeout doesn't work in munin-update

### ISSUE THREAD

**Issue by bra-fsn** [munin-monitoring/munin#1265]
**Describe the bug**
munin-update doesn't time out, not matter what value is specified to it with `--timeout=xxx`.
If the remote machine hangs, the munin-update process will hang forever too, blocking all updates.

**To Reproduce**
1. Issue a `kill -STOP $munin-node-pid` on the remote machine
2. Start a `munin-update --verbose --screen --timeout=10`
3. Wait forever, until munin-update exits with a timeout (it doesn't)

**Expected behavior**
I expect munin-update to exit with a failure after the timeout has expired (10 seconds in the above example).

**Desktop (please complete the following information):**
 - OS: FreeBSD 12
 - Munin master from git

**Comment by sumpfralle** [comment]
Fixed in 90421a9ca71a17d00ca52f41008291c63878a38b.

Thanks for your report!

**Comment by sumpfralle** [comment]
Please note, that the fix will reach `master` only after the next release of the `stable-2.0` branch.
