### ISSUE TITLE
2.0.53 breaks munin-run on rhel7 (and on debian 9?)

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1266]
```
# munin-run df
systemd-run: unrecognized option '--collect'
```

RHEL7 has old systemd 219 with lot of patches, so it doesn't support --collect.

If I remove "--collect" from munin-run:

```
# munin-run df
systemd-run: unrecognized option '--pipe'
```

If I remove that:

```
# munin-run df
systemd-run: unrecognized option '--wait'
```

If I remove that:

```
# munin-run df
Unknown assignment EnvironmentFile=/tmp/GO4hy1ysuI.
Failed to create bus message: No such device or address
```

I gave up. This works:

```
# munin-run --ignore-systemd-properties df
_dev_shm.value 0.000340436293426905
...
```

Can you add systemd version check to munin-run? Should I add a patch to rhel7 package that disables systemd support? Both options are fine for me, but other distributions might have similar problems. For example debian 9 has systemd 232, which also lacks --collect.

**Comment by sumpfralle** [comment]
Thank you for your report!

Please take a look at fd1ffdff20dbec1f587b2742ea8f0951a90ac23c - this should fix the problem for older versions of systemd (before 236).

**Comment by kimheino** [comment]
```
    my @version_output = `systemd --version 2>/dev/null`;
```

There is no binary called "systemd" in RHEL or Fedora. So this patch disables systemd support in Fedora, even it has systemd v243.

How about running "systemd-run --version" instead, as that's the binary you'll be calling later anyway?

```
Fedora:
# systemd-run --version
systemd 243 (v243.5-1.fc31)

RHEL7:
# systemd-run --version
systemd 219

Debian:
# systemd-run --version
systemd 241 (241)
```
