### ISSUE TITLE
2.0.53 adds multiple "dashes" labels to graphs is rhel7

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1267]
See https://heino.kim/df-day.png. Those multiple "dashes" labels are included in graphs that have warning levels set.

Reverting commit 66d1eff271fa52f5d94ca64929e41e551d418135 and restarting munin-cgi-graph fixes this.

RHEL7 has:

rrdtool-perl-1.4.8-9.el7.x86_64
rrdtool-1.4.8-9.el7.x86_64

RHEL6 has even older version, 1.3.8.

**Comment by kimheino** [comment]
![df-day](https://user-images.githubusercontent.com/688356/72670160-f0c64680-3a42-11ea-9b13-3b3ac873b24c.png)

**Comment by sumpfralle** [comment]
closed via e8fab57
