### ISSUE TITLE
Systemd version detection in  #1266 is fragile

### ISSUE THREAD

**Issue by steveschnepp** [munin-monitoring/munin#1268]
As @kimheino said in #1266  :

    my @version_output = `systemd --version 2>/dev/null`;
There is no binary called "systemd" in RHEL or Fedora. So this patch disables systemd support in Fedora, even it has systemd v243.

How about running `systemd-run --version` instead, as that's the binary you'll be calling later anyway?

Fedora:
    # systemd-run --version
    systemd 243 (v243.5-1.fc31)

RHEL7:
    # systemd-run --version
    systemd 219

Debian:
    # systemd-run --version
    systemd 241 (241)

**Comment by sumpfralle** [comment]
closed via 7844b50
