### ISSUE TITLE
"munin-run --debug df" is broken in 2.0.54

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1273]
Copied from IRC:

13:53     @be0rn | # munin-run --debug df
13:53     @be0rn | Running 'munin-run' via 'systemd-run' with systemd properties based on 'munin-node.service'.
13:53     @be0rn | When did this start?
13:54        bcg | 2.0.53 ?
13:54     @be0rn | Hm.
13:54     @be0rn | I sure don't get any plugin debug, only systemd debug.
14:00        bcg | try with --ignore-systemd-properties ?
14:01     @be0rn | Perfect <3
14:01        bcg | and open a github issue saying that "--debug" is not passed to systemd-run?
14:01        bcg | sumpfralle3: see above

14:03        bcg | there's also a small bug, as that "Running..." line should be "# Running..."
14:04        bcg | And same for "Skipping systemd properties..."

**Comment by kimheino** [comment]
There's something wrong in 2.0.54:

version: munin-node-2.0.54-1.fc31.noarch

<pre>
(15:00) root@cobra:~$ munin-run --ignore-systemd-properties load
load.value 0.28
(15:00) root@cobra:~> munin-run load
(15:00) root@cobra:~> munin-run load --ignore-systemd-properties --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/00-default
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /969/974/
# Setting /egid/euid/ to /969 969/974/
# Setting up environment
# Environment load_warning = 100
# About to run '/etc/munin/plugins/load'
load.value 0.30
(15:00) root@cobra:~> munin-run load --debug
Running 'munin-run' via 'systemd-run' with systemd properties based on 'munin-node.service'.
Command invocation: systemd-run --collect --pipe --quiet --wait --property EnvironmentFile=/tmp/g5X85EV1MI --property UMask=0022 --property LimitCPU=infinity --property LimitFSIZE=infinity --property LimitDATA=infinity --property LimitSTACK=infinity --property LimitCORE=infinity --property LimitRSS=infinity --property LimitNOFILE=524288 --property LimitAS=infinity --property LimitNPROC=62981 --property LimitMEMLOCK=65536 --property LimitLOCKS=infinity --property LimitSIGPENDING=62981 --property LimitMSGQUEUE=819200 --property LimitNICE=0 --property LimitRTPRIO=0 --property LimitRTTIME=infinity --property SecureBits=0 --property 'CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend cap_audit_read' --property AmbientCapabilities= --property DynamicUser=no --property MountFlags= --property PrivateTmp=yes --property PrivateDevices=no --property ProtectKernelTunables=no --property ProtectKernelModules=no --property ProtectControlGroups=no --property PrivateNetwork=no --property PrivateUsers=no --property PrivateMounts=no --property ProtectHome=read-only --property ProtectSystem=full --property NoNewPrivileges=no --property LockPersonality=no --property MemoryDenyWriteExecute=no --property RestrictRealtime=no --property RestrictSUIDSGID=no --property RestrictNamespaces=no --property ProtectHostname=no -- /usr/sbin/munin-run --ignore-systemd-properties load --debug
(15:00) root@cobra:~> 
</pre>

So ignore above, --debug is really passed, but output is empty.

You should still include "# " prefix to those systemd debug lines.

**Comment by kimheino** [comment]
Ignore above, my problem was selinux related. Works on permissive mode.

This is still valid:

You should still include "# " prefix to those systemd debug lines.

**Comment by sumpfralle** [comment]
> Ignore above, my problem was selinux related. Works on permissive mode.

I am not used to selinux. Do you think, that this should be solved upstream (in munin) or in the packaging?

**Comment by kimheino** [comment]
Selinux problems should be solved in Fedora's selinux-policy package, not in Munin (upstream or packaging). I'll gather more data and open Fedora bugs later.
