### ISSUE TITLE
please update master/doc/installation/install.rst

### ISSUE THREAD

**Issue by oz42** [munin-monitoring/munin#1274]
As of 2020, munin is no longer available at the EPEL repos.
Please correct the web page.

**Comment by sumpfralle** [comment]
As far as I know, the munin's package in EPEL is well and timely maintained (by @kimheino). Indeed it seems to be unavailable in the EPEL 8 repository at the moment, but I am confident, that it will be there, soon.

**Comment by kimheino** [comment]
Munin for EPEL 8 has been on testing for 11 days and will be moved to stable in 3 days.

https://bugzilla.redhat.com/show_bug.cgi?id=1757027
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-f9f8233b27

**Comment by sumpfralle** [comment]
Good to hear, thanks!
