### ISSUE TITLE
Useless logging from munin-asyncd in 2.0.57

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1294]
Commit b45a9130dff8 includes logger() calls in sd_notify support. Starting munin-asyncd logs following four lines to syslog:

```
Mar 10 20:49:48 risa munin-asyncd: 2020/03/10-20:49:48 [12455] sd_notify: looking for NOTIFY_SOCKET environment variable
Mar 10 20:49:48 risa munin-asyncd: 2020/03/10-20:49:48 [12455] sd_notify: preparing connection to '/run/systemd/notify'
Mar 10 20:49:48 risa munin-asyncd: 2020/03/10-20:49:48 [12455] sd_notify: connected to socket '/run/systemd/notify'
Mar 10 20:49:48 risa munin-asyncd: 2020/03/10-20:49:48 [12455] sd_notify: sending READY signal to '/run/systemd/notify'
```

I assume it should not. Munin-node is fine, it doesn't.

**Comment by kimheino** [comment]
It doesn't log anything else than those four lines.

**Comment by sumpfralle** [comment]
Fixed in 1ae431f6f306925c1dfc418d56194a497b9e8b9f. Thanks!

**Comment by bleve** [comment]
This bugfix is not acceptable. It causes dependency on perl module which causes installation of 58 new packages on system. Correct fix is to remove those loggings.

**Comment by sumpfralle** [comment]
Thank you for report.

Indeed the `Log::log4perl` dependency was new for `munin-node` and `munin-asyncd` (but already used in munin master). I did not intend this and plan to fix it (#1307).

> It causes dependency on perl module which causes installation of 58 new packages on system.

According to the Debian package `liblog-log4perl-perl` it only depends on perl itself. Instead it *recommends* other modules. Thus you can work around this easily by avoiding the installation of recommended packages.

@bleve: as a personal side note: I would appreciate a more nuanced tone when raising your valid concerns.

**Comment by bleve** [comment]
Please check https://bleve.fi/munin.txt - We are working on rhel7 based systems and there is no soft dependencies. So this bug affects rhel7 and centos7 etc...

**Comment by sumpfralle** [comment]
> We are working on rhel7 based systems and there is no soft dependencies.

Interesting!

In this case I would recommend to wait for 2.0.60. It will be released in the next days.

**Comment by bleve** [comment]
Exellent. Thank you.
