### ISSUE TITLE
Shouldn't there be graphs for Apache?

### ISSUE THREAD

**Issue by BETLOG** [munin-monitoring/munin#1299]
Question: Shouldn't there be graphs for
Apache accesses
Apache processes
Apache volume
On the munin server.
My pizero runs both munin and munin-node, and I just realised that there was no graphs  for those data sets. I was surprised to find no apache plugins active, but even after manually symlinking the apache* plugins and restarting apache/munin/munin-node I only get an empty graph.
Suggestions?
```
pi@pizero:~ $ sudo service apache2 status
● apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-03-16 14:35:01 AEST; 29min ago
     Docs: https://httpd.apache.org/docs/2.4/
  Process: 459 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
 Main PID: 488 (apache2)
   Memory: 7.8M
   CGroup: /system.slice/apache2.service
           ├─488 /usr/sbin/apache2 -k start
           ├─489 /usr/sbin/apache2 -k start
           ├─492 /usr/sbin/apache2 -k start
           └─493 /usr/sbin/apache2 -k start

Mar 16 14:34:59 pizero systemd[1]: Starting The Apache HTTP Server...
Mar 16 14:35:01 pizero apachectl[459]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Mar 16 14:35:01 pizero systemd[1]: Started The Apache HTTP Server.

```

![2020-03-16--15-01-44_betlognuc_MuninmuninGoogleChrome](https://user-images.githubusercontent.com/12265451/76724592-39765380-6797-11ea-8378-e35e1e6f7831.png)

**Comment by sumpfralle** [comment]
You need to take a look at the output of `munindoc apache_processes`: it describes, that this plugin requires an additional apache configuration directive.

In general it is a good idea to run `munin-run apache_processes` (or for other plugins) in order to check, whether reasonable values are retrieved. In your case the plugin probably emits values of `U` - this means *unknown*.

Does this fix your problem?

**Comment by BETLOG** [comment]
The main reason I am querying this before spending any serious amounts of time investigating is that this is the second time I have installed munin on this pi zero, the first time I did not need to do any extra configuration. Apache graphs were simply there and populated by default. 
Given that I document the commands and urls used to install almost everything on my computers, and revise copies of them each time I need to repeat the process... it seems very odd that one install would have, and another install a month later would not have these graphs.
....So I thought I should ask first.

>munindoc apache_processes

Strangely, this is the first time I have ever used the munindoc command to read a config man.
As I have mentioned in other issues; there seems to be a disconnect between google search results and core munin documentation.

```
This configuration section shows the defaults of the plugin:

      [apache_*]
         env.url   http://127.0.0.1:%d/server-status?auto
         env.ports 80
         env.showfree 1
```

Presumably that goes into:

>/etc/munin/plugin-conf.d/munin-node

But if those are the defaults it seems odd that a) I need to enter them b) they aren't already present.
I have to assume I'm doing something wrong or have accidentally deleted a section.

```
pi@pizero:~ $ sudo munin-run apache_processes
LWP::UserAgent not found at /etc/munin/plugins/apache_processes line 107.
```
Now google does reveal some results for this, none on the various munin-proper domains, but stackexchange is always useful.
https://serverfault.com/questions/748987/apache-graphs-and-data-not-updating-in-munin-on-ubuntu-14-04

```
sudo aptitude install libwww-perl
```
and https://pw999.wordpress.com/2013/05/19/munin-apache-plugin-lwpuseragent-not-found/ seems to confirm where the configuration string goes:

and hey presto:

```
sudo munin-run apache_processes
busy80.value 1
idle80.value 49
free80.value 100
```

So I know this is too much information and not really a query, feature request, or issue, but you got me feeling like I was contributing somehow in one of my other issues, so I guess I'm brainfarting toward that goal again here.
Presumably I have previously accidentally installed libwww-perl as a side effect of originally following the various blog-style installation instructions that used ngnix or lighttpd. Or somehow despite the very copy and paste style of my reinstalls have omitted that component in this install. Or broken in in the process of figuring out why something else (like the 403 when attempting view from another machine...or... fritzconnection requests lxml pip perl confusion)
In any case, I did not expect it to just suddenly vanish from the graphs.

And now that I have wasted your time writing all this, munin has had time to populate something other than NaN, and it works.

![2020-03-17--07-43-06_betlogbeast_MUNINnoteslinuxmunintxtKate](https://user-images.githubusercontent.com/12265451/76802325-30cb5f00-6823-11ea-95a2-59acd45eab92.png)

**Comment by sumpfralle** [comment]
> Strangely, this is the first time I have ever used the munindoc command to read a config man.
> As I have mentioned in other issues; there seems to be a disconnect between google search results and core munin documentation.

Another good hint - thanks!

> But if those are the defaults it seems odd that a) I need to enter them b) they aren't already present.

Indeed these are the defaults. Thus they do not need to be specified explicitly. That's why you did not find them in `/etc/munin/plugin-conf.d/munin-node`.

Thanks for correcting my assumption about the missing apache configuration. The relevant apache module seems to be enabled by default.

**Comment by BETLOG** [comment]
> That's why you did not find them in `/etc/munin/plugin-conf.d/munin-node`.

So then it looks like the entirety of the 'fix' in this instance is  to simply install libwww-perl
I'll strip those redundant apache defaults.
