### ISSUE TITLE
_list_services fails on hosts with underscores in the name

### ISSUE THREAD

**Issue by lorimbrius** [munin-monitoring/munin#1303]
The regex used in Server.pm line 182 "/^list\s*([0-9a-zA-Z\.\-]+)?/i" fails to match underscores and thus truncates hostnames, causing the check in _list_services at line 348 (exists $nodes{$node}) to fail. I rectified this by adding \_ to the end of the regex: "/^list\s*([0-9a-zA-Z\.\-\_]+)?/i" and now it's working for my host with an underscore.

**Comment by lorimbrius** [comment]
I'd like to push this fix and create a PR but I can't push to a new branch on this repo. Thanks.

**Comment by lorimbrius** [comment]
Never mind: underscores are invalid in hostnames.

**Comment by sumpfralle** [comment]
> Never mind: underscores are invalid in hostnames.

Thanks for your report and your goodwill for fixing it, anyway!
