### ISSUE TITLE
Node name missing on some diskstats graphs

### ISSUE THREAD

**Issue by misiek08** [munin-monitoring/munin#1305]
Basically live issue since 2015 (or even longer): http://munin-monitoring.org/ticket/1758

**Describe the bug**
On the disk-day.html (and disk-week etc.) pages, above about half of the graphs the nodename is missing, making it hard to figure out to which host the graphs correspond to. 

**To Reproduce**
1. Configure single node to monitor, make sure diskstats plugin is enabled.

**Expected behavior**
Node name should be visible before double-colon `::` like over other graphs.

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.

**Desktop (please complete the following information):**
- Ubuntu 18
- Munin 2.0.37-1ubuntu0.1

If it's known and widely spotted issue I can look into it and fix - just let me know if I'm not the only one.

**Comment by sumpfralle** [comment]
Thank you for your bug report. Indeed, this issue was reported before as #787. Thus I am closing this as a duplicate.

In fact your report pushed me into digging into the issue and fixing it for the next release.
