### ISSUE TITLE
munin-asyncd is broken in 2.0.58

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#1306]
Commit b29b36801 broke munin-asyncd:

Mar 24 10:29:17 risa munin-asyncd: Bareword "min_update_rate_threshold" not allowed while "strict subs" in use at /usr/sbin/munin-asyncd line 174.
Mar 24 10:29:17 risa munin-asyncd: Execution of /usr/sbin/munin-asyncd aborted due to compilation errors.

Fix is trivial, add missing $ before min_update_rate_threshold in line 174.

**Comment by sumpfralle** [comment]
Fixed in 74425aae4ddb64df2b59f0c2f97032e9f7ca9f8f.

Thanks for your report.
