### ISSUE TITLE
munin-async is missing a selinux policy on Fedora 31

### ISSUE THREAD

**Issue by zorun** [munin-monitoring/munin#1309]
**Describe the bug**
On Fedora 31, `munin-asyncd` fails to connect to the local `munin-node` socket because of a missing (or broken) selinux policy.

I'm not sure this is the right place to report the issue but I saw that another selinux issue was discussed by @kimheino in #1273

**To Reproduce**
1. Install Fedora 31, selinux will run in enforced mode
2. Try to start munin-asyncd
3. munin-asyncd will fail to start after 20 seconds with `Error connecting to munin node (localhost:4949): Permission denied`

**Expected behavior**
munin-asyncd should start without error.

**Screenshots & Logs**

The main error on `munin-asyncd` side is this:
```
Error connecting to munin node (localhost:4949): Permission denied at /usr/sbin/munin-asyncd line 85.
```

Here is the full log with selinux audit logs:
```
09:51:20 systemd[1]: Started Munin Node - Asynchronous Proxy.
09:51:20 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=munin-asyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
09:51:20 audit[441849]: AVC avc:  denied  { nnp_transition } for  pid=441849 comm="(n-asyncd)" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:munin_t:s0 tclass=process2 permissive=0
09:51:20 audit: SELINUX_ERR op=security_bounded_transition seresult=denied oldcontext=system_u:system_r:init_t:s0 newcontext=system_u:system_r:munin_t:s0
09:51:20 audit[441849]: AVC avc:  denied  { ioctl } for  pid=441849 comm="munin-asyncd" path="/usr/sbin/munin-asyncd" dev="dm-0" ino=155437 ioctlcmd=0x5401 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:munin_exec_t:s0 tclass=file permissive=0
09:51:20 audit[441849]: AVC avc:  denied  { name_connect } for  pid=441849 comm="munin-asyncd" dest=4949 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:munin_port_t:s0 tclass=tcp_socket permissive=0
09:51:40 audit[441849]: AVC avc:  denied  { name_connect } for  pid=441849 comm="munin-asyncd" dest=4949 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:munin_port_t:s0 tclass=tcp_socket permissive=0
09:51:40 munin-asyncd[441849]: Error connecting to munin node (localhost:4949): Permission denied at /usr/sbin/munin-asyncd line 85.
09:51:40 systemd[1]: munin-asyncd.service: Main process exited, code=exited, status=13/n/a
09:51:40 systemd[1]: munin-asyncd.service: Failed with result 'exit-code'.
```

**Desktop (please complete the following information):**
 - OS+Distribution Version: Fedora 31
 - Munin Version 2.0.54

**Additional context**

**Comment by zorun** [comment]
I gave it a try with the help of this doc:
https://wiki.centos.org/HowTos/SELinux#Gathering_Audit_Logs_In_Permissive_Mode
https://wiki.centos.org/HowTos/SELinux#Creating_Custom_SELinux_Policy_Modules_with_audit2allow

Here is the policy I obtained and it seems to be working:

```
module muninasync 1.0;

require {
	type init_t;
	type munin_exec_t;
	type munin_var_lib_t;
	type munin_port_t;
	type munin_t;
	class process2 nnp_transition;
	class file { execute ioctl read };
	class tcp_socket name_connect;
}

#============= init_t ==============
allow init_t munin_exec_t:file ioctl;
allow init_t munin_port_t:tcp_socket name_connect;
allow init_t munin_t:process2 nnp_transition;
allow init_t munin_var_lib_t:file read;
```

`munin_port_t:tcp_socket name_connect` and `munin_var_lib_t:file read` are kind of expected, but I don't understand what the other two are doing. I never touched selinux before.

Quick help to compile and load this policy (see the doc above for details), with absolutely no guarantee:

```
yum install policycoreutils-python-utils
# Start by saving policy to muninasync.te
checkmodule -M -m -o muninasync2.mod muninasync2.te
semodule_package -o muninasync2.pp -m muninasync2.mod
semodule -i muninasync.pp
```

**Comment by zorun** [comment]
Sorry, I got confused, this is Fedora 31, not Fedora 29

**Comment by zorun** [comment]
The strange thing is that `munin-asyncd` is running fine on Fedora 29 and Fedora 30, even though they also run in "Enforcing" selinux mode.

I thought it could be caused by the new `ProtectSystem` & all in the systemd unit file, but no, these options are already here in Fedora 30 and it works fine with selinux.

I still suspect that it could be a bad interaction between systemd and selinux, leading selinux to believe that systemd is doing the syscalls instead of munin-asyncd...

@kimheino do you have more ideas about this issue?

**Comment by sumpfralle** [comment]
Indeed this is more of a packaging issue for Fedora and thus not really applicable for munin itself.

But let us wait for @kimheino to chime in and let him decide, where the discussion should happen.

(sorry, I have no clue about selinux and thus cannot really participate in this discussion)

**Comment by kimheino** [comment]
You should open bug in redhat's bugzilla against selinux-policy component (not munin!). See for example:

https://bugzilla.redhat.com/show_bug.cgi?id=1823088

Unfortunately it might take a long time to get fixed. I'm also using similar custom policy myself:

```
allow init_t munin_exec_t:file ioctl;
allow init_t munin_port_t:tcp_socket name_connect;
allow init_t munin_t:process2 nnp_transition;
```

That "file read" rule should not be needed and your audit.log didn't show it either.Try `restorecon -RFv /var/lib/munin`, maybe you have some bad label?

Anyway, please continue in redhat's bugzilla and this bug here can be closed.
