### ISSUE TITLE
Supersampling errors

### ISSUE THREAD

**Issue by rwky** [munin-monitoring/munin#1315]
**Describe the bug**

I'm not sure if this is a problem with the plugin or munin.

I'm trying the [multicpu1sec](https://github.com/munin-monitoring/contrib/blob/master/plugins/cpu/multicpu1sec) plugin which uses supersampling and munin-update logs an error (see below) and the graphs just show nan.

I'm assuming the plugin output (see below) is correct however I'm not entirely sure what the separator between the epoch and value should be.

**To Reproduce**
Install the multicpu1sec plugin and wait for it to update then check the munin-update log

**Expected behavior**
No errors.

**Screenshots & Logs**

munin-update error:

```
2020/04/17 22:20:06 [ERROR] In RRD: Error updating /var/lib/munin/domain.com/example.domain.com-multicpu1sec-cpu4-g.rrd: /var/lib/munin/domain.com/example.domain.com-multicpu1sec-cpu4-g.rrd: found extra data on update argument: 6.25
```
The plugin is sending on fetch:
```
cpu0.value 1587162549:6.25
cpu1.value 1587162549:6.25
cpu2.value 1587162549:6.25
cpu3.value 1587162549:6.25
cpu4.value 1587162549:6.25
cpu5.value 1587162549:6.25
cpu6.value 1587162549:6.25
cpu7.value 1587162549:6.25
cpu8.value 1587162549:6.25
cpu9.value 1587162549:6.25
cpu10.value 1587162549:6.25
cpu11.value 1587162549:6.25
cpu12.value 1587162549:6.25
cpu13.value 1587162549:6.25
cpu14.value 1587162549:6.25
cpu15.value 1587162549:6.25
```
**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Munin Version 2.0.37

**Comment by sumpfralle** [comment]
I tried to reproduce the problem with Munin 2.0.66, but I could find such error messages in the log.

Indeed the output of the plugin looks reasonable and should be interpreted properly by Munin.

I am not aware of any recent changes (besides fixes for munin-async), which would be related to the timestamp handling. But maybe you could try to upgrade your Munin package and check, whether the problem still occurs?
