### ISSUE TITLE
plugin http_loadtime error

### ISSUE THREAD

**Issue by Phil353556** [munin-monitoring/munin#1322]
fresh install on raspberry pi 4  with Raspbian GNU/Linux 9 (stretch), latest update , upgrade of course.

In  /var/log/munin/munin-update.log
...
2020/05/03 11:55:06 [ERROR] In RRD: Error updating /var/lib/munin/raspberry2/raspberry2-http_loadtime-http___localhost_-g.rrd: /var/lib/munin/raspberry2/raspberry2-http_loadtime-http___localhost_-g.rrd: found extra data on update argument: 
...
run munin-run http_loadtime --debug
last line is:
http___localhost_.value /etc/munin/plugins/http_loadtime: line 105: -f: command not found

the variable: time_bin=`which time`  in line 50 is empty because which time command doesn't return anything
# time_bin=`which time`
# echo $time_bin
#
and line 105 :  
   loadtime=`$time_bin -f "%e" wget $wget_opt --header='Accept-Encoding: gzip,deflate' $uri 2>&1`

wget package is installed and runs fine.

Thank you for your help

**Comment by sumpfralle** [comment]
This issue is fixed in 2.0.35 (36144573c7bcdee6df12789b24afc5b76e74a528).
