### ISSUE TITLE
ping_ plugin outputs undesired error

### ISSUE THREAD

**Issue by solsticedhiver** [munin-monitoring/munin#1325]
with munin 2.0.61:

    munin-run ping_1.1.1.1
    which: no ping4 in (/usr/sbin:/usr/bin:/sbin:/bin)
    packetloss.value 0
    ping.value 0.016334

the test used in the shell code of the plugin is wrong:
line 63:

    if which ping6 >/dev/null; then

shoud be 

    if which ping6 &>/dev/null; then

line 72, it's the same

    if which ping4 >/dev/null; then

should be

    if which ping4 &>/dev/null; then

Or may be use the more general ?? 2> redirection ??

**Comment by sumpfralle** [comment]
Fixed in 6745001.
