### ISSUE TITLE
apt_all env.release option not used

### ISSUE THREAD

**Issue by KsmoinO** [munin-monitoring/munin#1331]
Also the option env.releases is set, apt_all reports all release states

**To Reproduce**
1) configure various releases on apt sources.list files
2) runs the plugins

**Expected behavior**
The automatic detection should not run, and the plugin should only report releases configured

 - Raspbian 10
 - Munin Version v2.0.49

**Comment by KsmoinO** [comment]
Forget this issue, a recent version of the plugin works as expected, sorry for the inconvenience

**Comment by sumpfralle** [comment]
No problem - thanks for verifying it!
