### ISSUE TITLE
apt_all random report only one release

### ISSUE THREAD

**Issue by KsmoinO** [munin-monitoring/munin#1332]
**Describe the bug**
running munin-run apt_all only report one release

**To Reproduce**
run munin-run apt_all

**Expected behavior**
apt_all plugin should report all releases

**Desktop (please complete the following information):**
 - OS+Distribution Version: Raspbian 10
 - Munin Version v2.0.49

**Additional context**
removing `last;` on https://github.com/munin-monitoring/munin/blob/9d92c6e8dff912014d77a9dc5177ddd6b039d5e9/plugins/node.d.linux/apt_all seems to solve the issue

**Comment by sumpfralle** [comment]
I guess, this issue was fixed in 9a792a331b9d652e7e48355bfdf5c2817f0c7845.

Please take a look, whether you still see issues with the [current version](https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/apt_all).

**Comment by KsmoinO** [comment]
Yes you're right, i missed read the la code version.
Sorry for the inconvenience
