### ISSUE TITLE
high cpu usage from munin/plugins/node.d.linux/fw_conntrack 

### ISSUE THREAD

**Issue by NoxInmortus** [munin-monitoring/munin#1334]
**Describe the bug**
high cpu usage from munin/plugins/node.d.linux/fw_conntrack 

**To Reproduce**
Install munin on a server with high number of tracked connections

**Expected behavior**
the plugin should not be using a lot of cpu to gather these metrics

**Desktop (please complete the following information):**
 - Debian Jessie, Stretch & Buster 64 bits
 - Munin Version : 2.0.33 and 2.0.49

**Additional context**
The issue seems related to :
```
    foreach (@conntrack_max_files) {
        if ( -r $_) {
            chomp($max = `cat $_`);
            last;
        }
    }
```
`cat /proc/net/nf_conntrack` is not very efficient

**Comment by ssm** [comment]
Out of curiosity, is the command "ss --summary" equally slow on that server?

**Comment by NoxInmortus** [comment]
Hello @ssm 

This is not my busiest machine but the case occurs regularly on this one :

```
time ss --summary
Total: 8185 (kernel 8309)
TCP:   7668 (estab 7311, closed 319, orphaned 0, synrecv 0, timewait 168/0), ports 0

Transport Total     IP        IPv6
*         8309      -         -        
RAW       0         0         0        
UDP       34        17        17       
TCP       7349      7328      21       
INET      7383      7345      38       
FRAG      0         0         0        


real    0m0.023s
user    0m0.004s
sys     0m0.008s
```

as you can see, not slow

**Comment by sumpfralle** [comment]
What is the output of `time munin-run fw_conntrack` on your busy server?

Which approach for connection retrieval is used by your machine? The following command should show this:
```shell
ls -l /usr/sbin/conntrack /proc/net/nf_conntrack /proc/net/ip_conntrack
```

**Comment by NoxInmortus** [comment]
Hello
```
# ls -l /usr/sbin/conntrack /proc/net/nf_conntrack /proc/net/ip_conntrack
ls: cannot access /usr/sbin/conntrack: No such file or directory
ls: cannot access /proc/net/ip_conntrack: No such file or directory
-r--r----- 1 root root 0 Jul 17 09:08 /proc/net/nf_conntrack

 # time munin-run fw_conntrack
established.value 516
fin_wait.value 0
time_wait.value 2332
syn_sent.value 1
udp.value 109
assured.value 2865
nated.value 30
total.value 2988

real    0m0.176s
user    0m0.096s
sys     0m0.036s

**Comment by sumpfralle** [comment]
> -r--r----- 1 root root 0 Jul 17 09:08 /proc/net/nf_conntrack

Indeed this file is just read via `cat`.

Thus it would be nice, if you could run the following commands for comparison:
```shell
time ss --summary >/dev/null
time cat /proc/net/nf_conntrack >/dev/null
```

**Comment by NoxInmortus** [comment]
Hello @sumpfralle, after looking from time to time, I did not see any real difference between these two. ss is a bit quicker by a few ms but nothing more.

I upgraded some vm from Jessie to Stretch and did some cleanup. I have far less high cpu usage peaks without having less connections, so im not so sure anymore about what to think.

**Comment by sumpfralle** [comment]
Thanks for following up on the topic.

> I have far less high cpu usage peaks without having less connections, so im not so sure anymore about what to think.

In this case I would use this state of inconclusiveness as an excuse for closing this issue, until further details come up :)
