### ISSUE TITLE
Update doc on {fieldname}.line

### ISSUE THREAD

**Issue by shtrom** [munin-monitoring/munin#1336]
On this note:
https://github.com/munin-monitoring/munin/blob/81b3e064dc71aac97fafde8bac26801db8ede756/doc/reference/plugin.rst#L359

I managed to get it to work with munin_2.0.63-1 and  rrdtool_1.7.2-3+b4 on Debian. It's a bit tricky to get right.

The full syntax is this
```
field.line 0:666666:label
```
where `0` is the value, `666666` is a hex-colour code (without #, and which doesn't support munin colours), and `label` is the label for the legend.

* Without the `:label` part, the line is drawn, but no legend is added
* Without the `666666` part, the line is drawn using the series' colour (`{fieldname}.colour`)

Another important note is that there can only be one line per field. If there are multiple, the last one is the one that is honoured.

It might be worth updating the documentation with those or similar examples.

**Comment by sumpfralle** [comment]
Thank you!
