### ISSUE TITLE
TLS connection issues (AGAIN)

### ISSUE THREAD

**Issue by hajes** [munin-monitoring/munin#1339]
Follow up of [resolved issue](https://github.com/munin-monitoring/munin/issues/1229).

Certificates expired and I simply generated all new certificates with same parameters as before.

Of course Debian 10 has been many time updated. Latest stable Munin (Debian) version 2.0.49-1

TLS Paranoid setup.

server error
`[TLS] Warning in read:  23013: 1 - error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca`

client error
`[ERROR] Could not enable TLS:  26565: 1 - error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed`

Perhaps it is something with TLS v1 what has been recently disable in OpenSSL?

**Comment by sumpfralle** [comment]
`alert unknown ca` sounds like the client does not know the relevant CA certificate. Could this be the case in your setup?

**Comment by hajes** [comment]
What I have found so far is that this error is related to failure in checking whole certificate chain.

What I do no understand why it work before and suddenly it doesn't work anymore.

CA > master > node certificates seems to be ok. I cannot see what may be wrong.

I couldn't figure it out after a day so I reversed to normal two certificates chain, which works but with some security issues.

**Comment by sumpfralle** [comment]
Did you try `openssl s_client`? This is usually a good tool for checking the validity of SSL-based services.

**Comment by hajes** [comment]
> Did you try `openssl s_client`? This is usually a good tool for checking the validity of SSL-based services.

yes, I have tried but it didn't connect and didn't show anything useful.

Unfortunately, I don't know how to properly debug it.

**Comment by sumpfralle** [comment]
I am afraid, that it is hard to determine, what caused the problem. Please re-open, if you encounter additional details.
