### ISSUE TITLE
--exitnoterror not considered in munin-node-configure

### ISSUE THREAD

**Issue by kboenke** [munin-monitoring/munin#1341]
When running `munin-node-configure`, help and the [user-guide](http://guide.munin-monitoring.org/en/latest/reference/munin-node-configure.html#cmdoption-remove-also) suggest that passing option `--exitnoterror` restricts output to plugins that produce valid output:
>**--remove-also**
> 
> When “–shell” is enabled, also provide commands to remove plugins that are no longer applicable from the service directory.

However, that option does not seem to be evaluated. Looking at  [munin-node-configure:91](https://github.com/munin-monitoring/munin/blob/master/script/munin-node-configure#L93) it does not seem to be considered as a valid option since [_Merge tag '2.0.40'_](https://github.com/munin-monitoring/munin/commit/5c6cb75ee7c443917112a1bf3e119b89e55bae1b#diff-bf885eb2145ab775ca8874cefd653fa8). Not sure if this was intentional by @sumpfralle - but either documentation needs to be updated or the option put back in.

**To Reproduce**
1. Run `munin-node-configure --suggest --shell`.
2. Confirm that the script runs and proper output is generated as expected.
3. Run `munin-node-configure --suggest --exitnoterror --shell`.
4. An error is returned: _Unknown option: exitnoterror_

**Expected behavior**
As per example, a list of shell-commands that configure the local munin-node as per suggestions from all Plugins that support Auto-Configuration.

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem:

> me@hostname:/etc/munin# `/usr/sbin/munin-node-configure --suggest --exitnoterror --shell`
> **Unknown option: exitnoterror**
> Usage:
>       munin-node-configure [options]
> [...]
>     --exitnoterror
>         Do not consider plugins that exit non-zero exit-value as error.
> [...]

**System**
 - Debian GNU/Linux 10 (buster)
 - munin-node-configure (munin-node) v2.0.49

**Comment by sumpfralle** [comment]
Good catch!

Indeed this option should have been removed from the manpage with commit 37e72a5adac0b9c6. I fixed this now. Thanks!
