### ISSUE TITLE
Munin plugin "df" does not show all drives installed

### ISSUE THREAD

**Issue by waywit** [munin-monitoring/munin#1344]
Hi, 

I am not sure if this is a bug, but I did not find any hint on the solution how to fix it. Let me describe it... I have 12 HDD in my server which is monitored with Munin. I am using df to monitor the "Disk Usage" on the server. I have the same issue with "df_inode" and "df_with_nfs" from Munin_contrib, so you can exchange the described behaviour for every mentioned plugin.

I am using Ubuntu Server 20.04 with the included Munin version 2.0.56

If I call the command line "df" on the command line it works and shows all HDDs installed with all parameters. 

If I use the linked Munin "df" plugin directly as a script, it also shows all HDDs (sda - sdl), the output is sorted for reading it better:

```
user@system/etc/munin/plugins$ ./df | sort
_dev_nvme0n1p1.value 1.51744488273247
_dev_nvme0n1p2.value 15.9602369905943
_dev_sda1.value 76.2409033654476
_dev_sdb1.value 76.2322696686468
_dev_sdc1.value 81.0728819239608
_dev_sdd1.value 78.8965371271784
_dev_sde1.value 41.177121112536
_dev_sdf1.value 81.1746592407957
_dev_sdg1.value 81.953489477738
_dev_sdh1.value 83.4748061641998
_dev_sdi1.value 73.6665786642128
_dev_sdj1.value 97.1155269915375
_dev_sdk1.value 69.368972558235
_dev_sdl1.value 38.0103126081217
_dev_shm.value 9.76349400301789e-05
_run_lock.value 0.078125
_run_user_1000.value 0.000488175176780436
_run.value 0.245307427567185
_sys_fs_cgroup.value 0
_tmp.value 0.794219970703125
```

But if I use "munin-run" to execute the same "df" plugin, it does not show all the installed HDDs anymore, sdc, sdf, sdg, sdh are missing:

```
user@system/etc/munin$ sudo munin-run df | sort
_dev_nvme0n1p1.value 1.51744488273247
_dev_nvme0n1p2.value 15.9608711943443
_dev_sda1.value 76.2409033654476
_dev_sdb1.value 76.2322696686468
_dev_sdd1.value 78.8965371271784
_dev_sde1.value 41.177121112536
_dev_sdi1.value 73.6665786642128
_dev_sdj1.value 97.1155269915375
_dev_sdk1.value 69.368972558235
_dev_sdl1.value 39.284152241544
```

I have also find some tipps and tricks fr debugging which does not helpmeet at all:

```
user@system/etc/munin/plugins$ sudo munin-run --ignore-systemd-properties --debug df
# Processing plugin configuration from /etc/munin/plugin-conf.d/README
# Processing plugin configuration from /etc/munin/plugin-conf.d/dhcpd3
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/spamstats
# Setting /rgid/ruid/ to /119/65534/
# Setting /egid/euid/ to /119 119/65534/
# Setting up environment
# Environment warning = 98
# Environment exclude = none unknown rootfs iso9660 squashfs udf romfs ramfs debugfs cgroup_root devtmpfs tmpfs
# Environment critical = 99
# About to run '/etc/munin/plugins/df'
_dev_nvme0n1p2.value 15.9910913108967
_dev_nvme0n1p1.value 1.51744488273247
_dev_sda1.value 76.2471410263374
_dev_sdb1.value 76.2545547016138
_dev_sde1.value 41.5779818066745
_dev_sdi1.value 73.6665786642128
_dev_sdd1.value 78.9273321646327
_dev_sdk1.value 69.368972558235
_dev_sdg1.value 65.4589691974237
```

Does anybody has an idea where to check or perhaps an idea why the HDDs are missing and cannot be monitored?

Just for your information, all HDDs are "ext4" types:

```
/dev/sda1      ext4
/dev/sdb1      ext4
/dev/sdc1      ext4
/dev/sdd1      ext4
/dev/sde1      ext4
/dev/sdf1      ext4
/dev/sdg1      ext4
/dev/sdh1      ext4
/dev/sdi1      ext4
/dev/sdj1      ext4
/dev/sdk1      ext4
/dev/sdl1      ext4
```
Any idea what I can do?

**Comment by niclan** [comment]
As you see munin-run drops from root to user #99, probably "munin".

# Setting /rgid/ruid/ to /119/65534/
# Setting /egid/euid/ to /119 119/65534/

If indedd uid 99 is munin then try running "su - munin --shell=/bin/bash" and then running the plugin again directly. Does it see or not see the the drives?

**Comment by waywit** [comment]
Thanks for your fast help... This looks like the issue... I just tried it out:

```
munin@system:/etc/munin/plugins$ ./df | sort
_dev_nvme0n1p1.value 1.51744488273247
_dev_nvme0n1p2.value 15.9898818377258
_dev_sda1.value 76.2471410263374
_dev_sdb1.value 76.2545547016138
_dev_sdd1.value 26.0800073803982
_dev_sde1.value 41.5174051946963
_dev_sdg1.value 65.7761222252525
_dev_sdi1.value 73.6665786642128
_dev_sdj1.value 0.00083877919478312
_dev_sdk1.value 69.368972558235
_dev_shm.value 9.76348923672946e-05
_run_lock.value 0.078125
_run_user_1000.value 0.000488175176780436
_run.value 0.203568551831873
_sys_fs_cgroup.value 0
_tmp.value 0.008392333984375
```

There are missing different sd* but this is because I am working on the hardware ;-) Thanks, what can I do to prevent that the user is changed?

**Comment by niclan** [comment]
You probably have some underlying problem that causes this that might also cause problems in the future.  Does "df" deviate similarly?

The quick and possebly wrong way to fix it is this: You can take a chance and give the plugin root privs, on my servers `/etc/munin/plugin-conf.d/` I would drop a file that might be named `df` (but can have any name) with this content:
```
[df]
  user root
```

**Comment by waywit** [comment]
Thanks a lot... this was the hint I needed... I have checked the access rights for the mount point vs. the missing HDDs.
And I have found the solution...
All missing mount points have:

`drwxr-x---`

The working mount points have:

`drwxr-xr-x`

So I have changed the "everybody rights" back to "r-x" and now it is working. 

Thanks a lot and I will close this issue :-)
