### ISSUE TITLE
Plain text only from webserver

### ISSUE THREAD

**Issue by eisengrau** [munin-monitoring/munin#1352]
Hello,

I have followed the installation and configuration procedure for munin on Debian Buster. I have installed the munin packages from backports, the rest from the standard debian repos.

I have installed these additional packages (were not mentioned in the official docs, also does not pull all of them as dependencies): libcgi-fast-perl libapache2-mod-fcgid libwww-perl

Enabled apache2 modules: fcgid cgid cgi rewrite

Current config of apache24.conf (ln -s to ./sites-enabled):

```
root@mumo:/etc/munin# cat apache24.conf
# Munin configuration for apache2
#
# Apache can serve munin's files that are either statically generated
# (in a cron job) or generated on demand (via cgi).
# The relevant munin settings are "html_strategy" and "graph_strategy".
# The related apache settings can be adjusted at the end of this file.
#
# See /usr/share/doc/munin/README.Debian for details.


# ***** COMMON SETTINGS FOR ALL STRATEGIES *****

ScriptAlias /munin-cgi/munin-cgi-graph /usr/lib/munin/cgi/munin-cgi-graph
Alias /munin/static/ /var/cache/munin/www/static/

<Directory /var/cache/munin/www>
    AddHandler cgi-script .cgi .pl
    Options FollowSymLinks +ExecCG
    Require all granted
    Options FollowSymLinks SymLinksIfOwnerMatch
</Directory>

<Directory /usr/lib/munin/cgi>
        Require all granted
        Options FollowSymLinks SymLinksIfOwnerMatch
    <IfModule mod_fcgid.c>
        SetHandler fcgid-script
    </IfModule>
    <IfModule !mod_fcgid.c>
        SetHandler cgi-script
    </IfModule>
</Directory>


# ***** SETTINGS FOR CGI/CRON STRATEGIES *****

# pick _one_ of the following lines depending on your "html_strategy"
# html_strategy: cron (default)
#Alias /munin /var/cache/munin/www
# html_strategy: cgi (requires the apache module "cgid" or "fcgid")
ScriptAlias /munin /usr/lib/munin/cgi/munin-cgi-html
root@mumo:/etc/munin#
```

Perl v5.28.1 , installed as default on Debian 10.

The problem is, munin is loaded as plain text in the browser:

![image](https://user-images.githubusercontent.com/42865787/94901813-830a5f80-0497-11eb-98be-d18c17e5e204.png)

What am I missing, what configuration step could be wrong?

Thank You,

**Comment by sumpfralle** [comment]
> I have installed these additional packages (were not mentioned in the official docs, also does not pull all of them as dependencies): libcgi-fast-perl libapache2-mod-fcgid libwww-perl

I think, you do not need these packages. (but I appreciate, that you experimented a bit to work around your issue)

> Enabled apache2 modules: fcgid cgid cgi rewrite

Good!
Are you sure, that you restarted apache2 afterwards?

**Comment by eisengrau** [comment]
Regarding those packages, I had my inspiration from various tutorials floating around the net, like howtoforge, etc.

As it should have been trivial, I mostly did just reload apache, now I have restarted it and behold :) :

![image](https://user-images.githubusercontent.com/42865787/95168280-5d3fcc00-07b1-11eb-91f2-70c2585afee4.png)

I should configure some other nodes. Does the default node, on the master, is enabled to collect data?

Thank You,

**Comment by sumpfralle** [comment]
> As it should have been trivial, I mostly did just reload apache, now I have restarted it and behold :) :

great!

Regarding the screenshot: the CSS seems to be missing. You probably just need to append a slash to the URL (`.../munin/`).

Regarding the necessary steps for configuration: the Debian package should do everything for you, if apache2 was already installed before. At least the automated packaging tests verify just that: install package and issue HTTP request ...

Probably the lack of an installed apache2 server caused a chain of confusion and digging around. Sorry for that!

**Comment by eisengrau** [comment]
Ah, yes, the / slash did the trick. Also, it was indeed the case of installing apache2 AFTER the munin packages.

Now, I just need to dig around how to get actuall metrics data there :)

Thank you!

**Comment by sumpfralle** [comment]
> Ah, yes, the / slash did the trick. Also, it was indeed the case of installing apache2 AFTER the munin packages.

Good. I will need to find a way to make this more obivous during the installation of the Debian package.

> Now, I just need to dig around how to get actuall metrics data there :)

This is easy: install `munin-node` on the relevant hosts, allow access from your master host and add an entry for each new host to the master configuration.

Have fun!
