### ISSUE TITLE
Flacky apt_all

### ISSUE THREAD

**Issue by JulienPalard** [munin-monitoring/munin#1358]
**Describe the bug**
Spotted holes in my apt-all graphs, and there's often `nan` in them, so I digged.

**To Reproduce**
Tried using netcat, on localhost, and got:
```
fetch apt_all
pending_buster_updates.value 0
hold_buster_updates.value 0
.
fetch apt_all
pending_buster_backports.value 78
pending_buster_backports.extinfo bind9 bind9-host bind9utils dirmngr dnsutils e2fslibs e2fsprogs e2fsprogs-l10n exim4-base exim4-config exim4-daemon-light geoip-database gnupg gnupg-agent gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm gpgv hdparm iproute2 iptables less libcom-err2 libcomerr2 libcryptsetup12 libext2fs2 libgeoip1 libiptc0 libldap-2.4-2 libldap-common libnftnl11 libnss-systemd libpam-systemd libseccomp2 libss2 libsystemd0 libudev1 libunbound8 libxtables12 libzstd1 linux-image-amd64 linux-libc-dev manpages manpages-dev munin-common munin-node munin-plugins-core munin-plugins-extra netbase nftables python3-debianbts python3-idna rsync systemd systemd-sysv udev +bind9-dnsutils +bind9-libs +bind9-utils +jo +jq +libip4tc2 +libip6tc2 +libjq1 +libmaxminddb0 +libnftables1 +libonig5 +libuv1 +libxxhash0 +linux-image-5.8.0-0.bpo.2-amd64 +logsave +perl-doc +systemd-timesyncd
hold_buster_backports.value 0
.
fetch apt_all
pending_buster.value 0
hold_buster.value 0
```

**Expected behavior**
I bet it should give consistent values.

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS+Distribution Version: Debian 10
 - Munin Version v2.0.49

**Additional context**

Tried to strace it (I don't read perl), I see both process read their state file, both getting the exact same result from it, but returning different values.

The one that gave no packages goes like:
```
read(3, "pending_buster_updates.value 0\nhold_buster_updates.value 0\npending_buster_backports.value 78\npending_buster_backports.extinfo bind9 "...
read(3, "", 8192)
close(3)
[a few rt_sigaction and getpid, redacted for readability]
write(1, "pending_buster.value 0\nhold_buster.value 0\n", 43) = 43
```

The one that give packages goes like:
```
read(3, "pending_buster_updates.value 0\nhold_buster_updates.value 0\npending_buster_backports.value 78\npending_buster_backports.extinfo bind9 "...
read(3, "", 8192)                 = 0
close(3)                          = 0
[a few rt_sigaction and getpid, redacted for readability]
1079  write(1, "pending_buster_backports.value 78\npend"...
```

**Comment by JulienPalard** [comment]
Spotted another variation:
```
# /etc/munin/plugins/apt_all
pending_buster.value 0
hold_buster.value 0

# /etc/munin/plugins/apt_all
pending_buster_updates.value 0
hold_buster_updates.value 0
```

I'm not sure this is normal?

**Comment by sumpfralle** [comment]
Yes, this is indeed not normal.

I took a look at the history of `apt_all` plugin. There were quite a few significant changes since 2.0.48, thus please check, whether the problem still exists today (2.0.66). Thanks!

**Comment by ruliane** [comment]
I got the same issue on a fresh Debian Buster installation (Munin v2.0.49).
Everything now works after upgrading to the newest (2.0.67) `apt_all` plugin. I guess commit https://github.com/munin-monitoring/munin/commit/4a51d76a76d91c2aa901e652d759ca2b1344c60e solved the issue.

**Comment by sumpfralle** [comment]
> Everything now works after upgrading to the newest (2.0.67) apt_all plugin.

Just for clarification: probably this was not 2.0.67, but 2.999.x (`master` branch) - at least I understand #1393 like that.

I still assume, that the current version of munin (2.0.67 or something similar) should solve the issue reported above.
I would welcome a confirmation (or dismissal) of this assumption.

**Comment by ruliane** [comment]
As you pointed out in #1393, I was confused with versions `2.x` and `3.x`.

Anyway, I am now using the plugin `apt_all` from v2.0.67, and it's running well.
Unless @JulienPalard still has issue with v2.0.67, this issue can be closed.

**Comment by JulienPalard** [comment]
I'll be able to test soon™ and I'll be happy to do so.

**Comment by JulienPalard** [comment]
Currently testing it, and it works like a charm. Thanks all!
