### ISSUE TITLE
munin-node - Lock already exists Update.pm line 127.

### ISSUE THREAD

**Issue by itdaemon** [munin-monitoring/munin#1362]
I have a RedHat 7 (7.8) server that updated munin-node this morning and am now getting errors that the munin-update.lock file exists.  This is the munin-node release info:

Name        : munin-node
Arch        : noarch
Version     : 2.0.65
Release     : 1.el7
Size        : 1.4 M
Repo        : installed
From repo   : epel

In the munin-update.log file I see this same error every 5 minutes:

2020/12/03 15:00:00 [INFO]: Starting munin-update
2020/12/03 15:00:00 [INFO] starting work in 6061 for gogllxecv05/127.0.0.1:4949.
2020/12/03 15:00:02 [FATAL ERROR] Lock already exists: /var/run/munin/munin-update.lock. Dying.
2020/12/03 15:00:02  at /usr/share/perl5/vendor_perl/Munin/Master/Update.pm line 127.
2020/12/03 15:00:05 [INFO]: Munin-update finished for node gogllxecv05;gogllxecv05 (4.67 sec)
2020/12/03 15:00:05 [INFO] Reaping Munin::Master::UpdateWorker<gogllxecv05;gogllxecv05>.  Exit value/signal: 0/0
2020/12/03 15:00:05 [INFO]: Munin-update finished (4.78 sec)

The updates and graphs all seem to be working I'm just emailed the error every 5 minutes now.  Looking at the /var/run/munin directory, I only see the lock files when munin-node runs.  I've checked for other instances or cron entries and am not finding any.

The system has been running fine until the update this morning to 2.0.65.

**Comment by sumpfralle** [comment]
The `munin-update.lock` file is created by the cron job executing `munin-update`.

It seems that there are two instances of this cron job running at the same time.

Can you think of a reason why two cron jobs exist? Maybe there is a systemd-based timer and a cron job both being active?

**Comment by itdaemon** [comment]
Yes, that was the issue.  It must have changed with the new release and started using the munin.timer instead of the cron job.  I see the timer file in /usr/lib/systemd/system/munin.timer and when I run systemctl list-timers --all I see it running.

Thanks for pointing me in the right direction.  I removed the munin cron file from /etc/cron.d and all is well now.

Thanks again.
