### ISSUE TITLE
make worker and munin-update configurable

### ISSUE THREAD

**Issue by Sephtex** [munin-monitoring/munin#1369]
It would be nice if timeout and worker_timeout would be configurable through munin.conf:
https://github.com/munin-monitoring/munin/blob/stable-2.0/master/lib/Munin/Master/ProcessManager.pm#L39

Currently we have a timeout that is configurable, but it doesn't seem to reflect the timeouts from above, but more the timeout from a single execution? I'm not sure where the timeout that is configurable is actually picked up.

The munin_stats has the timeout of 240 statically set to have a line for the max execution and should be updated accordingly.

Changing the timeout for the munin-update would be ok when working with munin-async. While it wouldn't be ok in most cases when connecting to the munin-node directly. With munin-async we don't care if we exceed the timeout, the master graphs wouldn't be updated for the last moments, but will get it's data feeded a bit later.

Eg: when you have a big backlog, you don't need to rely on small sample sized of munin-asyncd spool data, nor a low limit of the amount of samples to be able to send: https://github.com/munin-monitoring/munin/blob/stable-2.0/node/lib/Munin/Node/SpoolReader.pm#L107 (`$max_samples_per_service`)

**Comment by sumpfralle** [comment]
> Currently we have a timeout that is configurable, but it doesn't seem to reflect the timeouts from above, but more the timeout from a single execution?

Do you mean this one? http://guide.munin-monitoring.org/en/latest/reference/munin.conf.html#cmdoption-munin-conf-arg-timeout

In case it is not properly used, then we should indeed fix this.

> The munin_stats has the timeout of 240 statically set to have a line for the max execution and should be updated accordingly.

If I remember correctly, the `munin_stats` plugin uses a rather fragile log file parsing. But I will take a look at that (when the timeout is cleared) and at least add a note.

> Changing the timeout for the munin-update would be ok when working with munin-async. While it wouldn't be ok in most cases when connecting to the munin-node directly. With munin-async we don't care if we exceed the timeout, the master graphs wouldn't be updated for the last moments, but will get it's data feeded a bit later.

Currently both kind of nodes are use in the same way, I think. Thus it would be problematic to use different timeouts, I guess?

**Comment by Sephtex** [comment]
> Currently both kind of nodes are use in the same way, I think. Thus it would be problematic to use different timeouts, I guess?

I think a higher timeout when using the munin protocol would lead to gaps in the graphs. Therefor I think it's not a good idea to increase it when using the munin protocol. But in case you'll need higher values, then there would be something wrong, and then I would suggest to investigate the plugins that are causing the long updates, or move to munin-async to decrease munin-update time.

**Comment by sumpfralle** [comment]
Yes, I agree.

But maybe my comment was misleading: I think, the `do_work` function currently treats *spooling* nodes and regular nodes the same. Thus it looks complicated to me, to apply different timeouts to both. Additionally there is a global lock for `munin-update`, which would disallow the next `munin-update` run, while the previous one is still running due to longer *spooling* transfers.

Or did I misunderstand you?

**Comment by Sephtex** [comment]
There shouldn't be different timeouts in function of the protocol, since munin-update is at a higher level and can mix all protocols. I would just make both of the mentioned timeouts configurable, with maybe a warning on the config.

That would gives the user the flexibility to increase the timeouts if needed in case munin-async is used. But I would put a NOTE on the config line to mention to not change the value in case the default munin protocol is used or it could lead to gaps in the graphs if 300s would exceed.

**Comment by sumpfralle** [comment]
In theory, I agree. But I have no clear concept, of how do it.
If you find the time (and enthusiasm), I would welcome a code proposal :)

**Comment by Sephtex** [comment]
Sure, I think I have an idea on how to do it :)

**Comment by sumpfralle** [comment]
Fixed in #1371, thanks!
