### ISSUE TITLE
Plugin ok with munin-run but errors in log and no graphs created

### ISSUE THREAD

**Issue by msgrt** [munin-monitoring/munin#1370]
I am currently trying to transfer all munin monitoring tasks from a Raspberry Pi 3 to a Raspberry Pi 4.
Meanwhile all plugins work on RPi4, exept 1 php script.
Scripts on both, RPi3 and RPi4 are exactly the same: https://pastebin.com/6tbcQciT
No issues or errors with this on RPi3.

On RPi4 the munin-run output is as expected, something like this:
AussenTemperature.value 7.8

Nevertheless, no graphs are created. The following errors can be found in munin-node.log:
>2020/12/16-15:55:20 [10098] Error output from netatmo_Temperature_outdoor:
2020/12/16-15:55:20 [10098]     PHP Warning:  file_get_contents(/tmp/netatmo_cache_n): failed to open stream: No such file or directory in /usr/share/munin/plugins/netatmo_Temperature_outdoor.php on line 30
2020/12/16-15:55:20 [10098]     PHP Warning:  Invalid argument supplied for foreach() in /usr/share/munin/plugins/netatmo_Temperature_outdoor.php on line 41

Means, munin-run is able to locate and access the cache file in /tmp, munin-node isn't ?!
I know that the versions of munin, python and php are different on RPi3 and RPi4, but I am confused that munin-run is working perfectly fine with the script but munin-node isn't.
Any help is highly appreciated.

**What I already checked**
Cache file is identical on both RPi's, access rights (read) are ok
>pi@raspi1:~ $ ls -l /tmp/net*
-rw-r--r-- 1 pi pi 918 Dez 16 16:02 /tmp/netatmo_cache_n

>pi@raspi3:~ $ ls -l /tmp/net*
-rw-r--r-- 1 pi pi 918 Dez 16 16:02 /tmp/netatmo_cache_n

allow_url_fopen is "on"
>pi@raspi1:~ $ sudo grep -Rin "allow_url_fopen" /etc/php
/etc/php/7.0/cli/php.ini:820:allow_url_fopen = On
/etc/php/7.0/cgi/php.ini:820:allow_url_fopen = On

>pi@raspi3:~ $ sudo grep -Rin "allow_url_fopen" /etc/php
/etc/php/7.3/apache2/php.ini:852:allow_url_fopen = On
/etc/php/7.3/cgi/php.ini:852:allow_url_fopen = On
/etc/php/7.3/cli/php.ini:853:allow_url_fopen = On
/etc/php/7.3/fpm/php.ini:852:allow_url_fopen = On

Test in CLI ok:
>pi@raspi3:~ $ php -a
Interactive mode enabled
php > $last_measures = unserialize(file_get_contents('/tmp/netatmo_cache_n'));
php > print_r($last_measures);
Array
(
    [0] => Array
        (
            [station_name] => Zu Hause (Indoor)
            [modules] => Array
                (
                    [0] => Array
                        (
                            [module_name] => Indoor
                            [time] => 1608131536
                            [Temperature] => 21.7
                            [CO2] => 1752
                            [Humidity] => 61
                            [Pressure] => 1021.4
                            [Noise] => 38
                        )
                    [1] => Array
                        (
                            [module_name] => Aussen
                            [time] => 1608131496
                            [Temperature] => 7.2
                            [Humidity] => 86
                        )
                )
        )
)
php >

**The old one: Raspberry Pi 3**
>Linux raspi1 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
Munin 2.0.33-1
Python 2.7.13
Python 3.5.3
PHP 7.0.33-0+deb9u10 (cli) (built: Oct  6 2020 17:08:28) ( NTS ) Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies with Zend OPcache v7.0.33-0+deb9u10, Copyright (c) 1999-2017, by Zend Technologies

**The new one: Raspberry Pi 4**
>Linux raspi3 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
Munin 2.0.49
Python 2.7.16
Python 3.7.3
PHP 7.3.19-1+deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS ) Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.3.19-1+deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by sumpfralle** [comment]
> Means, munin-run is able to locate and access the cache file in /tmp, munin-node isn't ?!

If `munin-node` is started, via systemd, then your distribution probably applies hardening flags, one of these is `PrivateTmp=true`.
Your plugin should use the directory name defined in the environment variable `MUNIN_PLUGSTATE` instead.

I guess, this would solve everything?

**Comment by msgrt** [comment]
> Your plugin should use the directory name defined in the environment variable `MUNIN_PLUGSTATE` instead.
Cache file is now located there and now it works like a charm.

Thank you very much ! ;)
