### ISSUE TITLE
"df" does not show drives anymore. 

### ISSUE THREAD

**Issue by henti** [munin-monitoring/munin#1375]
**Describe the bug**
Noticed my disk monitoring is no longer working, investigated and found:

munin-run df config shows only `/run` `/run/lock` `/run/shm` and `/sys/fs/cgroup` labels while `/etc/munin/plugins/df config` shows all partitions as expected. 

Running `/etc/munin/plugins/df config` as munin user also shows all partitions as expected. 

**To Reproduce**
1. run `munin-run df config`
2. run `/etc/munin/plugins/df config` 

**Expected behavior**
I expected the output of both commands to be the same. 

**Screenshots & Logs**
```
root@farin:~# munin-run df config --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /113/65534/
# Setting /egid/euid/ to /113 113/65534/
# Setting up environment
# Environment exclude_re = ^/run/user ^/dev
# Environment critical = 98
# Environment warning = 92
# About to run '/etc/munin/plugins/df config'
graph_title Disk usage in percent
graph_args --upper-limit 100 -l 0
graph_vlabel %
graph_scale no
graph_category disk
_run.label /run
_run.warning 92
_run.critical 98
_run_lock.label /run/lock
_run_lock.warning 92
_run_lock.critical 98
_run_shm.label /run/shm
_run_shm.warning 92
_run_shm.critical 98
cgroup.label /sys/fs/cgroup
cgroup.warning 92
cgroup.critical 98
```
UID 113 is `munin`
```
munin@farin:/$ /etc/munin/plugins/df config
graph_title Disk usage in percent
graph_args --upper-limit 100 -l 0
graph_vlabel %
graph_scale no
graph_category disk
_run.label /run
_run.warning 92
_run.critical 98
_dev_mapper_main_root.label /
_dev_mapper_main_root.warning 92
_dev_mapper_main_root.critical 98
_run_lock.label /run/lock
_run_lock.warning 92
_run_lock.critical 98
_run_shm.label /run/shm
_run_shm.warning 92
_run_shm.critical 98
_dev_mapper_main_home.label /home
_dev_mapper_main_home.warning 92
_dev_mapper_main_home.critical 98
_dev_mapper_main_tmp.label /tmp
_dev_mapper_main_tmp.warning 92
_dev_mapper_main_tmp.critical 98
_dev_mapper_main_var.label /var
_dev_mapper_main_var.warning 92
_dev_mapper_main_var.critical 98
_dev_mapper_main_varlog.label /var/log
_dev_mapper_main_varlog.warning 92
_dev_mapper_main_varlog.critical 98
_dev_mapper_main_vartmp.label /var/tmp
_dev_mapper_main_vartmp.warning 92
_dev_mapper_main_vartmp.critical 98
_dev_mapper_main_apt_archive.label /srv/apt-archive
_dev_mapper_main_apt_archive.warning 92
_dev_mapper_main_apt_archive.critical 98
_dev_mapper_main_dist.label /srv/dist
_dev_mapper_main_dist.warning 92
_dev_mapper_main_dist.critical 98
_dev_mapper_main_acng.label /var/cache/apt-cacher-ng
_dev_mapper_main_acng.warning 92
_dev_mapper_main_acng.critical 98
cgroup.label /sys/fs/cgroup
cgroup.warning 92
cgroup.critical 98
_run_user_0.label /run/user/0
_run_user_0.warning 92
_run_user_0.critical 98
_run_user_10027.label /run/user/10027
_run_user_10027.warning 92
_run_user_10027.critical 98
```

**Desktop (please complete the following information):**
 - Debian GNU/Linux 9 (stretch)
 - This is munin-node v2.0.33-1

**Additional context**
All the drives that are missing are Logical volumes. This was working before.

**Comment by henti** [comment]
This impacts the `df` and `df_inode` but not `diskstats`

**Comment by sumpfralle** [comment]
Maybe this is caused by hardening flags configured for the munin-node service (via systemd, see [d#939339](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939339)).

You can verify this easily by executing `munin-run --ignore-systemd-properties df` and `munin-run df` (comparing the output of both).

In this case you can disable the hardening locally by executing `systemctl edit munin-node` and entering the following:
```
[Service]
ProtectHome=read-only
```

**Comment by henti** [comment]
> Maybe this is caused by hardening flags configured for the munin-node service (via systemd, see [d#939339](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939339)).
> 
> You can verify this easily by executing `munin-run --ignore-systemd-properties df` and `munin-run df` (comparing the output of both).
> 
> In this case you can disable the hardening locally by executing `systemctl edit munin-node` and entering the following:

The systems are not setup with systemd, and `munin-run` does not have the `munin-run --ignore-systemd-properties df` option.

**Comment by sumpfralle** [comment]
> The systems are not setup with systemd, and munin-run does not have the munin-run --ignore-systemd-properties df option.

Indeed, you are using an older version of munin, thus the option for munin-run is not available. Thus the problem is somewhere else. Interesting!

I can imagine two approaches for investigating the source of the problem:
* A) try a newer version of munin (if this is easily doable in your setup)
* B) generate `strace` logs for the two differing plugin executions (e.g. `strace -o SOME_FILE -f munin-run df`) and share these two log files with us

What do you think?

**Comment by henti** [comment]
This is truly getting bizarre interesting. 

I upgraded to stretch-backport version, which fixed the issue. So I tested and rolled back to original version, and it kept working. 

I then tested by doing a reinstall, which didn't work, but a purge and then install does work. 

# Reinstall 
```
root@xi:~# apt-get install munin-node --reinstall
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 9 not upgraded.
Need to get 133 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://mirror.ox.ac.uk/debian stretch/main amd64 munin-node all 2.0.33-1 [133 kB]
Fetched 133 kB in 0s (0 B/s)
(Reading database ... 216107 files and directories currently installed.)
Preparing to unpack .../munin-node_2.0.33-1_all.deb ...
Stopping Munin-Node: done.
Unpacking munin-node (2.0.33-1) over (2.0.33-1) ...
Setting up munin-node (2.0.33-1) ...
Initializing new plugins..done.
Restarting munin-node..Stopping Munin-Node: stopped beforehand.
Starting Munin-Node: done.
Starting Munin-Node: started beforehand.
Processing triggers for systemd (232-25+deb9u12) ...
Scanning processes...                                                                                                                                                                                                                                                                     Scanning candidates...                                                                                                                                                                                                                                                                    Scanning linux images...                                                                                                                                                                                                                                                                  Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
```

#purge && install 
```
root@xi:~# apt-get purge munin-node
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libio-multiplex-perl libnet-cidr-perl libnet-server-perl libnet-snmp-perl munin-common munin-plugins-core munin-plugins-extra
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  munin-node*
0 upgraded, 0 newly installed, 1 to remove and 9 not upgraded.
After this operation, 297 kB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 216107 files and directories currently installed.)
Removing munin-node (2.0.33-1) ...
Stopping Munin-Node: done.
(Reading database ... 216075 files and directories currently installed.)
Purging configuration files for munin-node (2.0.33-1) ...
Processing triggers for systemd (232-25+deb9u12) ...
 
 root@xi:~# apt-get install munin-node
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  acpi | lm-sensors ethtool hdparm libcrypt-ssleay-perl libdbd-pg-perl liblwp-useragent-determined-perl libnet-irc-perl libtext-csv-xs-perl libxml-simple-perl logtail munin munin-plugins-java default-mysql-client net-tools smartmontools
The following NEW packages will be installed:
  munin-node
0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
Need to get 0 B/133 kB of archives.
After this operation, 297 kB of additional disk space will be used.
Selecting previously unselected package munin-node.
(Reading database ... 216068 files and directories currently installed.)
Preparing to unpack .../munin-node_2.0.33-1_all.deb ...
Unpacking munin-node (2.0.33-1) ...
Setting up munin-node (2.0.33-1) ...
Initializing plugins..done.
Restarting munin-node..Created symlink /etc/systemd/system/multi-user.target.wants/munin-node.service → /lib/systemd/system/munin-node.service.
Starting Munin-Node: done.
Processing triggers for systemd (232-25+deb9u12) ...
Scanning processes...
Scanning candidates...                                                                                                                                                                                                                                                                    Scanning linux images...
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
```
Running as root : `munin-run df`
[notworking.txt](https://github.com/munin-monitoring/munin/files/5880305/notworking.txt)
```
_run.value 0.0796638497945922
_run_lock.value 0
_run_shm.value 0.000585765888899736
cgroup.value 0
```
Running as root : `/etc/munin/plugins/df config`
[working.txt](https://github.com/munin-monitoring/munin/files/5880306/working.txt)
```
graph_title Disk usage in percent
graph_args --upper-limit 100 -l 0
graph_vlabel %
graph_scale no
graph_category disk
_run.label /run
_run.warning 92
_run.critical 98
_dev_mapper_main_root.label /
_dev_mapper_main_root.warning 92
_dev_mapper_main_root.critical 98
_run_lock.label /run/lock
_run_lock.warning 92
_run_lock.critical 98
_run_shm.label /run/shm
_run_shm.warning 92
_run_shm.critical 98
_dev_mapper_main_home.label /home
_dev_mapper_main_home.warning 92
_dev_mapper_main_home.critical 98
_dev_mapper_main_tmp.label /tmp
_dev_mapper_main_tmp.warning 92
_dev_mapper_main_tmp.critical 98
_dev_mapper_main_var.label /var
_dev_mapper_main_var.warning 92
_dev_mapper_main_var.critical 98
_dev_mapper_main_varlog.label /var/log
_dev_mapper_main_varlog.warning 92
_dev_mapper_main_varlog.critical 98
_dev_mapper_main_vartmp.label /var/tmp
_dev_mapper_main_vartmp.warning 92
_dev_mapper_main_vartmp.critical 98
cgroup.label /sys/fs/cgroup
cgroup.warning 92
cgroup.critical 98
_run_user_10003.label /run/user/10003
_run_user_10003.warning 92
_run_user_10003.critical 98
_run_user_10027.label /run/user/10027
_run_user_10027.warning 92
_run_user_10027.critical 98
_run_user_111.label /run/user/111
_run_user_111.warning 92
_run_user_111.critical 98
```

For additional troubleshooting: running on machine where I uninstalled and re-installed:

Running as root : `munin-run df`
[xi_working.txt](https://github.com/munin-monitoring/munin/files/5880355/xi_working.txt)
```
_run.value 0.0519377059935332
_dev_mapper_main_root.value 72.3233950059912
_run_lock.value 0
_run_shm.value 0.000390510592599824
_dev_mapper_main_home.value 23.5974574490859
_dev_mapper_main_tmp.value 1.07479931781451
_dev_mapper_main_var.value 21.0535381121801
_dev_mapper_main_varlog.value 1.6148809405024
_dev_mapper_main_vartmp.value 0.427936848459416
nas_02_srv_internal_company_com__mnt_tank_jenkins_slave_persist_data.value 49.4872436523438
cgroup.value 0
```

**Comment by sumpfralle** [comment]
> I upgraded to stretch-backport version, which fixed the issue. So I tested and rolled back to original version, and it kept working.

Yes, that is really a strange mystery :(

The `df` plugin is one of the simplest munin plugins (without any kind of state), thus it is hard to understand how it could fail. 

Thinking about your original report again: the difference between `/etc/munin/plugins/df config` and `munin-run df config` is:
* A) no user context switching without `munin-run`
* B) no parsing of plugin configurations (`/etc/munin/plugin-conf.d/`) without `munin-run`

The plugin configuration for the `df` plugin is quite trivial (in Debian):
```
[df*]
env.warning 92
env.critical 98
env.exclude_re ^/run/user
```

Thus the absence of the configuration parsing does not explain the difference, that you experienced.

The diff between both strace outputs is confusing, since the relevant line for `/home/` is identical:
```
statfs("/home", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=87467988, f_bfree=78900422, f_bavail=74460253, f_files=22282240, f_ffree=21709111, f_fsid={val=[2355020254, 4231744725]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_NODEV|ST_RELATIME}) = 0
```

Thus both kind of executions should allow `df` to gather the same information.

The environment settings for both calls are different (e.g. `LANG=C` and `LANG=en_GB`), but this should not matter.

Regarding systemd: it looks like it is indeed installed on the system (according the your `--reinstall` log), but the `munin-node.service` in 2.0.33-1 did not contain any hardening flags, thus it is not relevant.

I am running out of ideas for debugging, what causes this difference.

**Comment by nborisenkov** [comment]
Maybe I don't understand something, but the first log says:
`# Environment exclude_re = ^/run/user ^/dev`
When you call the plugin directly (/etc munin/plugins/df) this environment variable (exclude_re) is not applied.

**Comment by henti** [comment]
> Maybe I don't understand something, but the first log says:
> `# Environment exclude_re = ^/run/user ^/dev`
> When you call the plugin directly (/etc/munin/plugins/df) this environment variable (exclude_re) is not applied.

It appears to be, because `/run/user` and `/dev` is not listed, only `/run/lock`, `/run/shm` and `/sys/fs/cgroup`

**Comment by sumpfralle** [comment]
The `exclude_re` environment variable only applies to the mountpoint (not the mounted device). Thus it should not interfere with `/dev/mapper/main_home` being mounted at `/home`.
Or do I misunderstand something?

**Comment by henti** [comment]
> The `exclude_re` environment variable only applies to the mountpoint (not the mounted device). Thus it should not interfere with `/dev/mapper/main_home` being mounted at `/home`.
> Or do I misunderstand something?

It seems this was the issue. 

Changing 
```
env.exclude_re ^/run/user ^/dev
```
 to 
```
env.exclude_re ^/run/user
```

resolved my issue.

**Comment by sumpfralle** [comment]
OK, I just looked up the description of `exclude_re` in the plugin:

> Devices can be explicitly included or excluded based on their mountpoint or device name using the include_re and exclude_re environment variables.

Thus it works as documented (even though I was surprised, since I did not read the documentation of the plugin).

I guess, the line `env.exclude_re ^/run/user ^/dev` was manually configured on your system?
(at least the Debian packaging only uses `env.exclude_re ^/run/user`)

**Comment by henti** [comment]
> I guess, the line `env.exclude_re ^/run/user ^/dev` was manually configured on your system?
> (at least the Debian packaging only uses `env.exclude_re ^/run/user`)

Indeed it was, tho sadly I cannot find any notes to why it was added and I cannot recall right now :(

**Comment by sumpfralle** [comment]
At least the mystery is solved - thanks for your feedback!
