### ISSUE TITLE
error on line 340 at column 9: Opening and ending tag mismatch: li line 0 and ul

### ISSUE THREAD

**Issue by eohrnberger** [munin-monitoring/munin#1376]
**Describe the bug**
Accessing the munin index.html page, receive the following error in the browser:

This page contains the following errors:
error on line 340 at column 9: Opening and ending tag mismatch: li line 0 and ul
Below is a rendering of the page up to the first error.

**To Reproduce**
1. Go to munin index web page, rendered in the browser.

**Expected behavior**
Error shouldn't be there, and the navigation should be there.

**Desktop (please complete the following information):**
 - Gentoo default/linux/amd64/17.1/desktop (stable)
 - Chrome and Opera browsers, likely others also
 - Munin Version [e.g. 2.0.66]

**Additional context**
Tried uninstalling and re-installed to the same results.
Also, added more nodes to monitor in /etc/munin/munin.conf, not being rendered in the web pages.

**Comment by sumpfralle** [comment]
The main template was recently changed (in 2.0.66, see 48e1e0af6237ebb0863674163cf3835d9ee5a18e). Maybe this causes this issue for you?

Maybe you want to take a look at the following versions of the template: [munin-overview-template-versions.zip](https://github.com/munin-monitoring/munin/files/5875559/munin-overview-template-versions.zip)

Inside that archive you find:
* the older version (v2.0.64)
* the current version (since v2.0.65)
* an adjusted template with improved indentation and a missing `</li>` tag added
    * I would commit this to the repository, if it fixes the issue for your

Anyway: I am very surprised, that an error is thrown on your system. I have never heard a similar report.

**Comment by eohrnberger** [comment]
> The main template was recently changed (in 2.0.66, see [48e1e0a](https://github.com/munin-monitoring/munin/commit/48e1e0af6237ebb0863674163cf3835d9ee5a18e)). Maybe this causes this issue for you?

This turned out to be the issue.   Replacing the template file cleared up the error message.  Thank you!

> Maybe you want to take a look at the following versions of the template: [munin-overview-template-versions.zip](https://github.com/munin-monitoring/munin/files/5875559/munin-overview-template-versions.zip)
> 
> Inside that archive you find:
> 
> * the older version (v2.0.64)
> * the current version (since v2.0.65)
> * an adjusted template with improved indentation and a missing `</li>` tag added
>   
>   * I would commit this to the repository, if it fixes the issue for your
> 
> Anyway: I am very surprised, that an error is thrown on your system. I have never heard a similar report.

**Comment by sumpfralle** [comment]
> This turned out to be the issue. Replacing the template file cleared up the error message.

Did you try all three versions in that archive? Which ones worked?
(I am hoping for the latest one)

**Comment by eohrnberger** [comment]
> > This turned out to be the issue. Replacing the template file cleared up the error message.
> 
> Did you try all three versions in that archive? Which ones worked?
> (I am hoping for the latest one)

I copied munin-overview.tmpl-new to munin-overview.tmpl, allowed an update to run, and the error was removed from the index.html page.

**Comment by sumpfralle** [comment]
> I copied munin-overview.tmpl-new to munin-overview.tmpl, allowed an update to run, and the error was removed from the index.html page.

That's what I was hoping for. Thank you for testing!
