### ISSUE TITLE
Diskstats plugin broken on Raspberry Pi kernel 5.10.x

### ISSUE THREAD

**Issue by bondskin** [munin-monitoring/munin#1382]
**Describe the bug**
Since upgrade from kernel 5.4.83-v7l+ to 5.10.14-v7l+ the disk stats plugin is not working any longer

**To Reproduce**
munin-node.log
2021/02/12-13:55:07 [22251] Error output from diskstats:
2021/02/12-13:55:07 [22251]     '/sys/block/loop0/stat' contains the wrong amount of values. Aborting at /etc/munin/plugins/diskstats line 432.
2021/02/12-13:55:07 [22251]             main::read_sysfs() called at /etc/munin/plugins/diskstats line 458
2021/02/12-13:55:07 [22251]             main::parse_diskstats() called at /etc/munin/plugins/diskstats line 530
2021/02/12-13:55:07 [22251]             main::fetch_device_counters() called at /etc/munin/plugins/diskstats line 35
2021/02/12-13:55:07 [22251] Service 'diskstats' exited with status 25/0.

**Expected behavior**
Plugin runs without errors

**Screenshots & Logs**
2021/02/12-13:55:07 [22251] Error output from diskstats:
2021/02/12-13:55:07 [22251]     '/sys/block/loop0/stat' contains the wrong amount of values. Aborting at /etc/munin/plugins/diskstats line 432.
2021/02/12-13:55:07 [22251]             main::read_sysfs() called at /etc/munin/plugins/diskstats line 458
2021/02/12-13:55:07 [22251]             main::parse_diskstats() called at /etc/munin/plugins/diskstats line 530
2021/02/12-13:55:07 [22251]             main::fetch_device_counters() called at /etc/munin/plugins/diskstats line 35
2021/02/12-13:55:07 [22251] Service 'diskstats' exited with status 25/0.

**Desktop (please complete the following information):**

**Additional context**

**Comment by sumpfralle** [comment]
I assume, this was fixed in c3e46710fd7b08385ff81995208e65ba423dd2d5 (Munin 2.0.56).

Please re-open the issue, if you are using a newer version of Munin.

**Comment by bondskin** [comment]
Indeed, I am using a newer version

This is munin-node v2.0.66

**Comment by sumpfralle** [comment]
In this case your `diskstats` plugin seems to be outdated (maybe a locally modified copy instead of the released one?).

Please take a closer look at c3e46710fd7b08385ff81995208e65ba423dd2d5.
This commit replaces the string
> contains the wrong amount of values

with

> contains less than 11 values

Your log output contains the former string, thus the plugin seems to be out of date.

**Comment by bondskin** [comment]
Hi @sumpfralle, thanks for the hint. I manually installed the updated plugin from git and now it works.
I updated the munin-node some time ago but it seems that the plugins are not updated as part of this process.
Is there a simplistic approach to update all plugins to the latest release?

**Comment by sumpfralle** [comment]
>  Is there a simplistic approach to update all plugins to the latest release?

Personally I am using the Debian packages (`munin-node`, `munin-plugins-core`, ...). These packages contain the munin plugins and should be updated via your package manager.
The same approach is probably used packages for most other distributions.

I could only imagine, that you *copied* this specific plugin to `/etc/munin/plugins/diskstats`. In this case you would have overwritten the existing symlink (created by your package manager) and thus the content of `/etc/munin/plugins/diskstats` would no longer get updated by newer packages.
Instead this file (`/etc/munin/plugins/diskstats`) should probably be a symlink to the *packaged* plugin (on Debian: `/usr/share/munin/plugins/diskstats`).

**Comment by bondskin** [comment]
I did not copy the packages but used back port releases to update on Buster. So I guess in those packages the plugins where not included.
But I understand the logic and I am glad it works again. thank you!

**Comment by sumpfralle** [comment]
> So I guess in those packages the plugins where not included.

The diskstats plugin is [part of the package](https://packages.debian.org/buster-backports/all/munin-plugins-core/filelist). Thus I can only imagine, that there was some local interference around your system.

Anyway: I am glad, it works for you now!
