### ISSUE TITLE
diskstat is producing disk (write) IO

### ISSUE THREAD

**Issue by dotmpe** [munin-monitoring/munin#1383]
**Describe the bug**
with diskstats (or diskstat_iops_mmcblk0) there is a temporary? file (with random name) written to disk. 

**Steps to reproduce**
I am trying to eliminate all periodic disk writes on SD/MMC storage based single board computers. Mine is an Orange Pi One running Armbian Focal (Linux 5.10.12-sunxi armv7l) and munin-node with version: 2.0.56-1ubuntu1. I hunt for disk IO with:
```
sudo sysctl vm.block_dump=1
dmesg
```
And then move files into /tmp or setup more zram mount points.
But when I turn on the munin-plugin to monitor the progress, a new periodic change message appears:
```
[  820.370382] diskstat_iops_m(3537): dirtied inode 127891 (6vYr29v7rI) on mmcblk0p1
[  820.371569] diskstat_iops_m(3537): WRITE block 4460728 on mmcblk0p1 (8 sectors)
[  820.371817] diskstat_iops_m(3537): dirtied inode 127892 (?) on mmcblk0p1
```

**Expected behavior**
I would expect temporary files to be in /tmp or maybe configurable. I cannot find the path location of the file or where the file is generated. I added ``chdir('/tmp')`` to the plugin script but to no effect.

**Comment by niclan** [comment]
It's not a bug, it's a feature: It's not a temporary file, It's saving state. 

https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/diskstats#L170

If you build your munin from source:
http://munin-monitoring.org/wiki/MuninInstallProcedure - during build set @@PLUGSTATE@@ or maybe fiddle with symlinks at some later time.

At runtime set the MUNIN_PLUGSTATE environment variable for the plugin(s) through plugin configuraiton by dropping a file in the plugin config directory.  A few plugins will not handle the loss of state all that well but I'm not sure how diskstats will fare, I guess you'll find out.

**Comment by dotmpe** [comment]
Ah I see, that narrowed it down to ``/var/lib/munin-node/plugin-state``. Thanks for the quick reply!
