### ISSUE TITLE
Diskstats plugin broken  (Munin 2.0.66).

### ISSUE THREAD

**Issue by bondskin** [munin-monitoring/munin#1385]
I assume, this was fixed in c3e46710fd7b08385ff81995208e65ba423dd2d5 (Munin 2.0.56).

Please re-open the issue, if you are using a newer version of Munin.

_Originally posted by @sumpfralle in https://github.com/munin-monitoring/munin/issues/1382#issuecomment-780579551_

**Comment by bondskin** [comment]
Running munin 2.0.66, issue appears again

**Comment by sumpfralle** [comment]
Thanks for the hint. I just re-opened the original issue (#1382), in order to keep the discussion in once place.

(I thought, you could just re-open that older issue instead of opening a new one - but maybe this is limited in the web interface ...)
