### ISSUE TITLE
Keep the static generation ability

### ISSUE THREAD

**Issue by steveschnepp** [munin-monitoring/munin#1395]
In the upcoming version of Munin, I move away from the static site, as it is very wasteful if you have many nodes. And in 2013 when I started to think about it, we wanted to scale towards many nodes. 

But, in 2021, I agree that the security it procures might overtake the performance boost, specially since hardware is much better and our png generation is not using more resources than before.

**Comment by auduny** [comment]
Being able to just put it as static pages on the internett and know more or less read-only is a good thing. 

I vote to keep it (atleast as an option).
I would argue that [KISS](https://en.wikipedia.org/wiki/KISS_principle) (in addition to awesome maintainers like you 🏆 ) is one of success factors of Munin the last 19 years (If you count my first commits to LRRD back in 2002 :)

**Comment by GreenReaper** [comment]
It also encourages you to think about which graphs you actually use. If you just want warnings, you can set `.graph off` and save a bit of time, both generating and looking at them. This matters if you're near the limit of a shared-core VM, as it slows down execution proportionately - a run which took two minutes to generate might suddenly be three or four.
