### ISSUE TITLE
How do i stop munin from removing hostnames?

### ISSUE THREAD

**Issue by BETLOG** [munin-monitoring/munin#1398]
How do i stop munin from removing hostnames?

I have a raspberry pizeroW that has issues, and locks up occasionally, but the data munin-node records that might indicate why it's dropping out is often hidden, because the host no longer appears in munin's main page (running on another machine, obviously).

Can I specify that certain hosts always appear? Regardless of their responsiveness to munin queries?

**Comment by sumpfralle** [comment]
There was an issue in munin before v2.0.48 (see #579), which caused hosts to disappear after being unreachable.

Could this be the cause of your problem?

**Comment by BETLOG** [comment]
iirc I solved it by remembering to set:
`host_name pizerocam3`
in munin-node.conf
becasue my router was calling it 
pizerocam3.lan

Sorry for previously forgetting to close.
