### ISSUE TITLE
Munin cpu issue

### ISSUE THREAD

**Issue by MidhunVijayan** [munin-monitoring/munin#1400]
Hi, 

Munin is showing wrong cpu usage on the server, I have monitored the cpu usage from the server , and couldn't find any load spike in it. 

Please check the below screenshot for the same

https://prnt.sc/12in0nl

Also getting the following log from the server

```
2021/05/05-08:55:26 [2344258]   '/sys/block/md2/stat' contains the wrong amount of values. Aborting at /etc/munin/plugins/diskstats line 432.
2021/05/05-08:55:26 [2344258]           main::read_sysfs() called at /etc/munin/plugins/diskstats line 458
2021/05/05-08:55:26 [2344258]           main::parse_diskstats() called at /etc/munin/plugins/diskstats line 530
2021/05/05-08:55:26 [2344258]           main::fetch_device_counters() called at /etc/munin/plugins/diskstats line 35
2021/05/05-08:55:26 [2344258] Service 'diskstats' exited with status 25/0.
2021/05/05-08:55:29 [2344258] Error output from acpi:
2021/05/05-08:55:29 [2344258]   cat: '/sys/class/thermal/thermal_zone*/type': No such file or directory
2021/05/05-08:55:29 [2344258] Error output from acpi:
2021/05/05-08:55:29 [2344258]   cat: '/sys/class/thermal/thermal_zone*/temp': No such file or directory
2021/05/05-08:55:29 [2344258]   (standard_in) 1: syntax error

```

can yo please help me on this

**Comment by niclan** [comment]
Can you recapture the screen shot _with_ the legends?  Also note, that this graph does not show the calculated system load, it shows how busy the system was, which is not necessarily the same.

**Comment by MidhunVijayan** [comment]
hi,

please find the below screenshot for clarification.

https://prnt.sc/12iw93l

I am not sure why the graph is showing as irregular,  please let me know about your suggestion

thank you!

**Comment by niclan** [comment]
And the load graph please.

It is very easy to attach graphs to tickets in github. I copied the the graph into your previous comment.

**Comment by MidhunVijayan** [comment]
Hi,

Okay, I have only issue with the graph regarding the cpu usage, in the the previous screenshot you can see, there is an irregular pattern in every day. I don't know why its happening in a particular time and what that means in the graph. 

![cpu_irregular](https://user-images.githubusercontent.com/46282796/117248709-050f9c00-ae5e-11eb-8944-5896410ae394.PNG)

can you please explain?

**Comment by niclan** [comment]
Yes, I can see that and I'm not commenting until I see the load graph - it's different from the CPU graph.  These things are connected and that is why munin is showing you all these graphs so you can see how they are connected by eye.

I can tell you that the CPU graphs are quite certainly correct and that the problem is most likely understanding them.

**Comment by MidhunVijayan** [comment]
Hi,

thank you ! please find the load graph below 

![load_graph](https://user-images.githubusercontent.com/46282796/117251362-2ffbef00-ae62-11eb-84e1-0874cb3f74b3.PNG)

**Comment by niclan** [comment]
Thanks. I have looked more closely at the graphs now.

Is this a system with 3 CPUs? Is it a physical machine or is it in any way virtual?  What kind of CPU? Intel? Arm? Other?

There are a couple of interesting issues with your CPU graph:
- They numbers don't add up to 300% most of the time, there is a white margin at the top of the graph.  This happens some times if a kernel has bugs in it's CPU accouting or has introduced a new kind of CPU usage that the plugin does not handle. BUT:
- When the CPU usage seems to spike between about 04:30 and about 08:45 they go way over 300. This seems to be the same time period each night. The MAX column shows readings of 11000% and 30000% which is much more than the 300% that 3 CPUs can deliver.
- The CPU numbers does not seem to relate to the load graph at all, the highest load appears to be from 12:00 (noon) until 24:00.
- The numbers seem to fluctuate between very high (high towers) and 0 (whte stripes in the middle of the high towers). Which is insane too.

The graph simply reproduces what the kernel reports.  Therefore I think your kernel's CPU accounting is broken.  If you look back - click on the CPU graph to see the month and year graphs as well - was it always like this?  Does it change if you boot to a different (older or newer) kernel?

Do you run a specific kind of job during this time? A backup job? Something that uses a lot of disk I/O? Anything different from the rest of the day when the numbers seem more normal?

There might also be a issue in how the plugin parses the CPU accounting. If you were to run `sudo munin-run` during the time the numbers are off, does it produce any error messages?  Run it many times if you can. A clean run looks like this:

```
$ sudo munin-run cpu
user.value 65208616
nice.value 12385416
system.value 224289823
idle.value 2889388423
iowait.value 183736767
irq.value 0
softirq.value 27668061
steal.value 0
guest.value 0
```

The errors you show from the log in your initial message relates to the diskstats plugin and probably the sensors plugins.  They do not affect the CPU accounting.

**Comment by niclan** [comment]
I should add that as it is I don't think the CPU graph reflects a real problem with your system.  Just a counting/accounting problem in the kernel.

**Comment by MidhunVijayan** [comment]
hi,

This is a an lxd container inside the machine FYI . while I checking I could see that the load is same for the lxd container  as in the machie

```
root@machine:~# w
 06:52:55 up 156 days, 20:36,  1 user,  load average: 13.56, 12.66, 11.61
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     pts/142  149.202.89.4     06:52    7.00s  0.03s  0.02s w
root@machine:~# lxc exec mumble-vm bash
dircolors: no SHELL environment variable, and no shell type option given
root@mumple-vm:~# w
 06:53:00 up 65 days, 18 min,  0 users,  load average: 13.44, 12.65, 11.61
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT

```

**Comment by MidhunVijayan** [comment]
Hi ,

I have also executed the command and getting the below result from the lxd container.

```
# sudo munin-run cpu
user.value 9074921
nice.value 0
system.value 162144
idle.value 3780439829
iowait.value 0
irq.value 0
softirq.value 0
steal.value 0
guest.value 0
 ```

**Comment by MidhunVijayan** [comment]
Hi,

As it is a LXD container, it is using the same kernel  on the Host. And munin graph is good for the host machine.
kernel version is :

5.9.0-3-amd64 #1 SMP Debian 5.9.9-1 (2020-11-19) x86_64 GNU/Linux

 Munin graph for host machine below,

![host_cpu](https://user-images.githubusercontent.com/46282796/117257792-e7483400-ae69-11eb-9f17-0dac973c4dc2.PNG)
![host_load](https://user-images.githubusercontent.com/46282796/117257806-ea432480-ae69-11eb-8fcf-e562862f4928.PNG)

So I don't know why this issue only in lxd container only?

**Comment by yunal** [comment]
In that case I conclude that CPU accounting is broken in LXD/kernel name spaces.  If you want to take this further I suggest you take it to the LXD project.
