### ISSUE TITLE
postgres_*_ plugins only consider 10 "random" databases in munin-node-configure --suggest

### ISSUE THREAD

**Issue by ap-wtioit** [munin-monitoring/munin#1407]
Currently when auto configuring the plugins for postgres with `munin-node-configure --suggest --shell` when having more than 10 databases on your postgres instance the plugin only configures 10 "random" databases to be monitored. This is caused by suggestquery being something like `... ORDER BY 1 LIMIT 10`

On our server i modified the suggestquery to have a higher limit, but as the number picked by me is specific to our server i wanted to discuss the issue here before providing a patch. Can we remove the limit or pick another arbitrarily higher limit?

See
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_cache_#L87
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_locks_#L122
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_scans_#L81
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_transactions_#L89
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_tuples_#L102
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_size_#L89
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_querylength_#L104
* https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_connections_#L149

Our server info (but the issue is still present in master):
```
username@host /etc/munin/plugins # munin-node --version
Version:
    This is munin-node v2.0.37-1ubuntu0.1

    $Id$

Copyright:
    Copyright (C) 2002-2006 Audun Ytterdal, Jimmy Olsen, and Tore Anderson /
    Linpro AS.

    This is free software; see the source for copying conditions. There is
    NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
    PURPOSE.

    This program is released under the GNU General Public License
```

**Comment by sumpfralle** [comment]
Interesting!

I took a quick look at the git history (`git log -p -S "ORDER BY 1 LIMIT 10"`): the three commits related to this string do not discuss the purpose of this limit. Thus it seems to be just an arbitrary number.

Thanks for opening this discussion!

I guess we have the following options:
* A) pick an (arbitrary) higher number (e.g. 100)
* B) make this value configurable via an environment setting (e.g. `env.postgres_suggest_database_limit 100`)
* C) do not limit the number of databases to be used

I guess, that people running a hundred databases also have the capacity to handle a few hundred more munin plugins.
Thus I am tempted to lean towards (C).

Opinions?

**Comment by ap-wtioit** [comment]
thanks for picking this up. i also would tend to C. my thinking is that anyone not wanting more database plugins to be activated could just grep -v them when they are suggested.
