### ISSUE TITLE
Help With Munin

### ISSUE THREAD

**Issue by tncitaly** [munin-monitoring/munin#1408]
Good evening everyone.
I ask for your help.
I need not to connect to a linux machine to monitor a windows server 2019 machine outside my network.
I have installed Munin on ubuntu, but I don't know how to configure the node on windows.
The pc is external from Ubuntu

**Comment by sumpfralle** [comment]
Maybe you want to try [munin-node-win32](https://github.com/munin-monitoring/munin-node-win32) or [munin-node-windows](https://github.com/munin-monitoring/munin-node-windows)?

Happy monitoring!
