### ISSUE TITLE
Configuring a webserver apache/nginx/lighttpd on freebsd is painfull.

### ISSUE THREAD

**Issue by devosalain** [munin-monitoring/munin#1410]
I was unable to correctly configure a webserver apache/nginx or lighhttp on freebsd.
So i removed the package from the system and hope next release is easier to configure correctly.

**Comment by sumpfralle** [comment]
You can find the documentation in the munin guide: http://guide.munin-monitoring.org/en/latest/installation/webserver.html

Feel free to join the IRC channel (`#munin` at OFTC) if you have any questions.
