### ISSUE TITLE
mysql_ plugin sometimes fails with "Unknown section: Main thread process..."

### ISSUE THREAD

**Issue by mnalis** [munin-monitoring/munin#1412]
**Describe the bug**
	munin plugin mysql_, invoked as for example mysql_qcache (or any other, sometimes (but not always) fails with errors like:

	Unknown section: Main thread process no. 21673, id 139511430366976, state: sleeping at /etc/munin/plugins/mysql_qcache line 1382

	thus resulting in VERY unusable mysql munin stats (about 20% visible, 80% broken in my case)

**To Reproduce**
1. run `munin-run mysql_qcache` (or any other `mysql_`)
2. have a busy mysql/percona server running queries with views involved
3. sometimes (but not always) error is shown (and graph is not updated)

**Expected behavior**
I would expect that the output is parsed normally and munin graph for mysql plugins updated, instead of graph being full of holes due to `mysql_` plugin dying majority of the time.

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS+Distribution Version: Debian Stretch/Buster/Buster-Backports/Bullseye
 - Munin Version: `2.0.67-1~bpo10+1` (also `2.0.49-1~bpo9+1` and before)

**Additional context**
I've reported the bug at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=991622 too.

**Comment by mnalis** [comment]
After some debugging, I found out the problem is output of "show engine innodb status"
which sometimes (when mysql views are used in some way?) returns this output on which 
mysql_ barfs:

```
  --------------
  ROW OPERATIONS
  --------------
  0 queries inside InnoDB, 0 queries in queue
  2 read views open inside InnoDB
  1 RW transactions active inside InnoDB
  0 RO transactions active inside InnoDB
  1 out of 1000 descriptors used
  ---OLDEST VIEW---
  Normal read view
  Read view low limit trx n:o 14142166371
  Read view up limit trx id 14142166371
  Read view low limit trx id 14142166371
  Read view individually stored trx ids:
  -----------------
  Main thread process no. 21673, id 139511430366976, state: sleeping
  Number of rows inserted 9568126016, updated 1596177407, deleted 515944374, read 15378019524560
  0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 16020000.00 reads/s
  ----------------------------
  END OF INNODB MONITOR OUTPUT
  ============================
```

instead of this output which is parsed OK:

```
  --------------
  ROW OPERATIONS
  --------------
  0 queries inside InnoDB, 0 queries in queue
  0 read views open inside InnoDB
  0 RW transactions active inside InnoDB
  0 RO transactions active inside InnoDB
  0 out of 1000 descriptors used
  Main thread process no. 21673, id 139511430366976, state: sleeping
  Number of rows inserted 9568124954, updated 1596176891, deleted 515943708, read 15377906700512
  0.17 inserts/s, 1.67 updates/s, 0.00 deletes/s, 880245.13 reads/s
  ----------------------------
  END OF INNODB MONITOR OUTPUT
  ============================
```

**Comment by mnalis** [comment]
This patch quickly removes the offending (non-standardly formatted) and unused `---OLDEST VIEW---` section, thus fixing the issue.

```
--- /usr/share/munin/plugins/mysql_.orig        2021-03-08 11:57:43.000000000 +0100
+++ /usr/share/munin/plugins/mysql_     2021-07-28 21:33:05.984676113 +0200
@@ -1348,6 +1348,9 @@
 sub parse_innodb_status {
     local $_ = shift;

+    # remove non-stanard (and useless) "---OLDEST VIEW---" section, as it breaks the plugin
+    s{^---OLDEST VIEW---\v.*?^-----------------\v}{}ms;
+
     # Add a dummy section to the end in case the innodb status output
     # has been truncated (Happens for status > 64K characters)
     $_ .= "\n----------\nDUMMY\n";
```

It would be nice if this or similar fix could find its way in next version.

**Comment by mnalis** [comment]
it does not seems to be happening in latest master https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/mysql_

**Comment by steveschnepp** [comment]
I still applied your patch in the stable branch as 5827cb71f1570f1ef38e36d2d20d5e42db01a093.

Thanks!
