### ISSUE TITLE
X axis of graphs by week mislabelled

### ISSUE THREAD

**Issue by xxxmicrobexxx** [munin-monitoring/munin#1433]
**Describe the bug**
On graphs in WHM Munin plugin, the X axis labels show the dates and values from the last few days rather than the last few weeks.  The graphs themselves appear to show the correct time period (weeks)

**To Reproduce**
1. Go to your Munin page in WHM plugins
2. View graphs

**Expected behavior**
It should show weekly data rather than daily data.  This seems to be a recent issue though I don't know when it started.  

**Screenshots & Logs**
If applicable, please add screenshots and/or logs to help explain your problem.
![munin](https://user-images.githubusercontent.com/1052491/138787027-f64029aa-4555-4db2-b9ae-260da79b486b.png)

**Desktop (please complete the following information):**
 - CentOS Linux release 7.9.2009 (Core) running cPanel
 - Munin Version 2.0.30

**Comment by sumpfralle** [comment]
Currently the graphs (URLs and filenames) use the suffixes `day`, `week`, `month` and `year`.
I am confident, that we want to stick to these suffixes (they are accurate and widely used).
Thus I can only image, that we could change the title in the graph.
*But* I think, we want to avoid a situation where the word "day" appears in the graph called "week".
Maybe you have a good idea which specific wording could solve this?

**Comment by xxxmicrobexxx** [comment]
Instead of "by week" etc. it would be more accurate to say "last week" because that is what data are showing.  The last week's data by each day.

![image](https://user-images.githubusercontent.com/1052491/139509790-fece8dad-d9c1-4940-b27c-dfe625b13d1a.png)

**Comment by xxxmicrobexxx** [comment]
Is there no interest in accuracy of the labelling of graphs?

**Comment by steveschnepp** [comment]
Actually, there's 11eb157fdef4d5cf7c6bd4a1bb5466607592fce5 in master about this topic.
