### ISSUE TITLE
fail2ban plugin: please integrate thresholds

### ISSUE THREAD

**Issue by mehturt** [munin-monitoring/munin#1448]
The fail2ban plugin currently does not support thresholds.  I got it working locally sourcing plugin.sh and adding print_thresholds to the config() function.  Could someone please do this the way it should be done? I can attach my local diff, if that helps. Thanks

**Comment by yunal** [comment]
Adding print_thresholds to the config() function is good.  The threshold settings should be in the munin managed plugin configuration though, this is often in files in the `/etc/munin/plugin-conf.d/` directory (but this could have other names).

**Comment by sumpfralle** [comment]
Thank you for you suggestion. 
I implemented this now in commit a79ef7488f39a407f94a8d16414ef41dc0447d81.
