### ISSUE TITLE
Gauge graphic shows values like floats

### ISSUE THREAD

**Issue by ndTEC** [munin-monitoring/munin#1451]
All the gauge graphs shows the values like floats even though the plugin always returns integer

For example the number of connections in this nginx plugin should be an integer, 10 30 or 15 , but the graphic shows 7.35
This is happening for all gauge graphics.

munin-2.0.66-1

![munin](https://user-images.githubusercontent.com/79922948/149907368-17a2f37c-e4b6-45aa-8cbc-df04ab2c7373.png)

**Comment by steveschnepp** [comment]
It is normal. A good explanation is at http://rrdtool.vandenbogaerdt.nl/process.php
