### ISSUE TITLE
GitHub branch `master` contains older code than `stable-2.0`

### ISSUE THREAD

**Issue by mikkorantalainen** [munin-monitoring/munin#1453]
**Issue**
GitHub branch `master` contains a lot older code than `stable-2.0`. Anybody doing `git clone https://github.com/munin-monitoring/munin.git` will end up with old code that doesn't contain the latest bugfixes nor the latest features.

**Solution I'd recommend**
The `master` branch should either be the latest development branch or the latest stable branch.

I'd recommend using `master` as the official development branch (that is, it should contain all the bugfixes and latest features but it would have seen less testing than the stable branch). You already have `stable-2.0` branch that should contain the supported features and bugfixes for munin project at version 2.x.

Another alternative is to get rid of branch `master` and set the default branch for new clones (see GitHub settings for this repo, "default branch") to `stable-2.0`.

Third option is to replace contents of `master` branch with file`README.rst` only, explaining how the users are expected to use the branches. That way anybody doing a blind clone would end up with just a README file explaining what to do next.

**Comment by mikkorantalainen** [comment]
Sorry, I read the GitHub interface incorrectly and this issue should be probably closed.

It seems that you're using `master` as the development branch and it's just missing some bugfixes already applied to stable-2.0 branch.

For example, file https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/postgres_querylength_ is missing two bugfixes already in the stable-2.0 branch.

**Comment by steveschnepp** [comment]
Lets aim for getting 3.0 out.
