### ISSUE TITLE
Docs seem to suggest can put plugin in /etc/munin/plugins, but not detected unless in /usr/share/plugins

### ISSUE THREAD

**Issue by hayden-t** [munin-monitoring/munin#1460]
Debian stretch, munin-node v2.0.67

My plugins are only showing up in munin-node-configure if located in /usr/share/plugins and linked to /etc/munin/plugins
(i know this is normal practice, but didnt think this was reflected by the documentation, unless its not intended, or its versios/os specific)

http://guide.munin-monitoring.org/en/latest/plugin/writing.html

>Place the plugin in the /etc/munin/plugins/ directory, and make it executable. Note that most distributions place plugins in a different directory, and ‘activate’ them by symlinking htem to /etc/munin/plugins. New module development should use a similar approach so that in-process development doesn’t get run by mistake.
>
>Any time a new plugin is placed or symlinked into /etc/munin/plugins, munin-node should be restarted.

**Comment by steveschnepp** [comment]
There is no check if it is a symlink, only if it is readable & executable. 

So, the practice of putting a real executable script in `/etc/munin/plugins` should work. 
Are you sure you are doing the restart ?

Note that some plugins are "wildcards" ones, and they need to have their name changed. This is usually done via symlinks, but can also be done via simple copy.

**Comment by hayden-t** [comment]
I just double tested to check, and moved my own enabled and working plugin script from /usr/share/munin/plugins to /etc/munin/plugins (after removing the symlink) issued 'systemctl restart munin-node.service' then 'munin-node-configure' and then the plugin gone, not visible or enabled.
also to double check set it to 777 and chmod a+x but no difference

**Comment by niclan** [comment]
The munin-node-configure command is only needed to link plugins automatically into the /etc/munin/plugins directory.

If you have placed the plugin into that directory yourself you can test it by running `munin-run <plugin>`.

**Comment by hayden-t** [comment]
Ah ! ok thanks i got myself all confused with that. My plugin is working fine now in /etc/munin/plugins
