### ISSUE TITLE
haproxy_ does not use clean_fieldname(), munin simply ignore some field

### ISSUE THREAD

**Issue by fraff** [munin-monitoring/munin#1467]
Munin simply ignore some field/value because it contains invalid chars.

Patch attached
[clean_fieldname.txt](https://github.com/munin-monitoring/munin/files/8530944/clean_fieldname.txt)

**Comment by sumpfralle** [comment]
I applied your patch (slightly modified): 54cdde35c9242311fa5bb05c074bc073bd3c1c62

Thank you!
