### ISSUE TITLE
The netstat Linux plugin plots values of different units of measure against the same axis

### ISSUE THREAD

**Issue by wferi** [munin-monitoring/munin#1473]
**Describe the bug**
The `established` datasource is of type GAUGE, means a count and is thus unitless, while the other datasources (`active`, `passive`, `failed` and `resets`) are of type DERIVE, mean a rate and their unit is Hz (1/second). Consequently it doesn't make much sense to plot them against the same axis, as the axis can't be labelled with a single unit of measure (like it isn't currently, making the interpretation of the graph impossible without further research). Besides being incomparable, the usual value ranges of these datasources also differ by orders of magnitude, making the combined graph less useful. I suspect this is why the vertical axis was switched to logarithmic (many years ago), but that's wrong because zero is a perfectly valid value for each of the datasources and the logarithm of zero is not defined.

The "Info" column on the dedicated plugin page shows helpful descriptions of the fields, though it still lacks the unit of measure for the `resets` datasource.

**To Reproduce**
Use the plugin on a system with a not too high failed/reset rate. For example, the problem is readily observable on the screenshot in the [netstat entry](https://gallery.munin-monitoring.org/plugins/munin-2.0/netstat/) of the plugin gallery.
 
**Expected behavior**
The `established` field should be plotted on a separate graph.
The `failed`/`resets` lines should be nice and smooth, most of the time even zero.

**Screenshots & Logs**
On the current (logarithmic) graph of the plugin the `failed`/`resets` (orange/yellow) lines jump around wildly, because they're often (close to) zero, and the logarithm maps such values to large negative (or undefined) values:
![elm-netstat-day_logarithmic](https://user-images.githubusercontent.com/5689797/171361678-15d3abfc-baf1-4f8c-b162-ff531bae380f.png)

Linear graph showing the rates only (that is, with the `establised` GAUGE field omitted):
![elm-netstat-day_linear](https://user-images.githubusercontent.com/5689797/171361672-7bf68485-0795-462a-988f-540fadbbcc96.png)

**Desktop**
 - OS+Distribution Version: Debian 11
 - Browser: Firefox (irrelevant)
 - Munin Version: 2.0.49

**Comment by lucrus73** [comment]
I find that hard to read too. Moreover:

> The "Info" column on the dedicated plugin page shows helpful descriptions of the fields

I could not find said "Info" column.

**Comment by kenyon** [comment]
Example: https://beta.kenyonralph.com/munin/kenyonralph.com/hydrogen.kenyonralph.com/netstat.html

![image](https://github.com/munin-monitoring/munin/assets/68514/1e5e26f3-382d-4036-8c3f-9502d46a2ef7)

@lucrus73 the info column is in the lower right of my screenshot.

**Comment by steveschnepp** [comment]
Actually, the `netstat` plugin in master already does that. I just removed it fully from the graph.

Can you test the PR ?
