### ISSUE TITLE
Cannot run plugin in sandbox environment with systemd-run

### ISSUE THREAD

**Issue by penguinpee** [munin-monitoring/munin#1474]
**Describe the bug**
`./dev_scripts/plugin run` fails with:
```
Insecure $ENV{PATH} while running with -T switch at ./devel/munin-monitoring/munin/sandbox/bin/munin-run line 155
```

**To Reproduce**
1. `./dev_scripts/install node`
2. `./dev_scripts/disable_taint`
3. `./dev_scripts/plugin run plugin_name`
4. Above error

**Expected behavior**
Plugin should be executed in sandbox environment.

**Additional context**
I tracked the error down to `dev_scripts/run`. In there `munin-run` is called with `perl -T`. `dev_scripts/disable_taint` only searches `${SANDBOX}/bin`. After changing `dev_scripts/run` I was able to execute my plugin in the sandbox.

**Comment by steveschnepp** [comment]
fixed by your PR #1475
