### ISSUE TITLE
Feature: Exclude localhost from overview

### ISSUE THREAD

**Issue by kroese** [munin-monitoring/munin#1478]
It seems the Munin server always includes localhost as a node, besides the configured external nodes.

I really would like to be able to exclude "localhost" from the list of nodes in the overview, since it is useless in my case.

**Comment by niclan** [comment]
Munin only includes what is explicitly configured.  Look at your configuration and you will find "localhost" configured, just comment it out.

**Comment by steveschnepp** [comment]
@kroese using a 3rd-party prebuild docker for a system that connects itself to everything you want to monitor sounds dangerous. 

That said, it might mean that we should offer the option 🤔

**Comment by steveschnepp** [comment]
There are some [Dockerfile](Dockerfile) in this project. 

And `make docker`will happily build a docker image for you, but it is currently more aimed as a developement aid than a productive usage.
