### ISSUE TITLE
Graph color(colour) differentiate(separate)

### ISSUE THREAD

**Issue by robozb** [munin-monitoring/munin#1488]
Dear All, 

I'm sure this is not a bug, but I would like to ask you how can I differentiate easily the colors on a graph? It is almost impossible when there are too many elements is included :(

Thank you so much for your help!

Bela

![graph](https://user-images.githubusercontent.com/8656998/186090413-416d30f5-0072-4c60-a78f-a5cd22144764.JPG)

**Comment by steveschnepp** [comment]
You have multiple options.
 
Basically, the most effective way is unfortunately to **reduce the number of fields**. 
If you really want to keep all of those, you can stack them as it would show them separately.

Usually, the purpose of having a crowded bunch of fields in a single graph is to be able to **single out a rogue field**. 
Once you easily saw that there's a rogue one, **the information underneath** becomes your way to know which one.

**Comment by robozb** [comment]
Dear Steve,

Thank you so much! I'll try your advices!

Regards: Bela

**Comment by smokris** [comment]
> reduce the number of fields

Also, if you want to continue to collect all the data, but only see a subset of it, you could create a [virtual node with a graph consisting of only a few fields](https://guide.munin-monitoring.org/en/latest/reference/munin.conf.html#virtual-node).

(Related: #911, #1206)

**Comment by steveschnepp** [comment]
Actually, you can [hide some fields ](https://guide.munin-monitoring.org/en/latest/reference/plugin.html) with 

    my_field.label my_label
    my_field.type GAUGE
    my_field.graph no

**Comment by robozb** [comment]
Thanks the advices!

**Comment by robozb** [comment]
I figured out a workaround when I'm curious only for the peaks I narrow the diagram and I can find the top value in the bottom list  easily! 
![1](https://user-images.githubusercontent.com/8656998/191962926-4f9134bc-c2a5-4dae-9fa1-472bc9ca121a.JPG)
![2](https://user-images.githubusercontent.com/8656998/191962943-39e8fd4e-a466-4201-8010-8c01941edbd7.JPG)
