### ISSUE TITLE
Uneven legend in 2.999.16

### ISSUE THREAD

**Issue by yunal** [munin-monitoring/munin#1519]
**Describe the bug**

The legend text has un-even width in 2.999.16 (with rrd 1.4.8 on CentOS 7).

**To Reproduce**

Any graph with field.negative setting seems to go this way.

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/1274709/223116969-d7989501-57a1-44f7-8889-409a5af7485a.png)

**Comment by yunal** [comment]
(The title here is large as the server is running 2.999.16 +  https://github.com/munin-monitoring/munin/pull/1518)

**Comment by yunal** [comment]
https://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/if_eth0.html has the same issue.

![image](https://user-images.githubusercontent.com/1274709/223132319-254e6555-f650-4c8e-8c07-2ce55cfe0b1c.png)

**Comment by niclan** [comment]
I've fixed this
