### ISSUE TITLE
Cpanel-cloudlinux swap doesn't work

### ISSUE THREAD

**Issue by kozmaakos** [munin-monitoring/munin#1524]
**Describe the bug**
We have several cpanel servers with and without cloudlinux. On the servers where we have cloudlinux the swap munin plugin doesn't work. If I run the swap script manually it gives me real datas but the munin-update.log says :
"Service swap on localhost/127.0.0.1:4949 returned no data for label swap_in
Service swap on localhost/127.0.0.1:4949 returned no data for label swap_out"

**To Reproduce**
1. su -s /bin/bash munin
2. If you run this command:
```
/usr/local/cpanel/3rdparty/share/munin/plugins/swap

It gives back this kind of values:

swap_in.value 495695974
swap_out.value 624367918
```
3. /usr/local/cpanel/3rdparty/share/munin/munin-update --debug --host localhost --service swap
`"[WARNING] Service swap on localhost/127.0.0.1:4949 returned no data for label swap_out"
"[WARNING] Service swap on localhost/127.0.0.1:4949 returned no data for label swap_in"`

**Screenshots & Logs**
![munin-swap](https://user-images.githubusercontent.com/95054157/224311580-695b17ff-765e-4ad0-93ca-d39e70337958.png)

**Desktop (please complete the following information):**
 - CloudLinux 7.9
 - munin-node v2.0.30

**Comment by yunal** [comment]
This will be a problem specific to your environment. Most often the cause of such mysteries is selinux, permissions, etc. You can experiment with running the plugin as "root" but this will most likely not help.

Googleing cloudlinux: "Essentially a set of kernel modifications to the Linux distribution, CloudLinux implements features to enable system administrators to take fine-grained control of their server's resource usage.".

Such a OS might have security features isolating some kinds of processes from system resources and their metrics.  I suggest you seek advice in the Cloudlinux community or with your vendor. This will be impossible to debug without a cloudlinux instance.
