### ISSUE TITLE
Can a munin node store history?

### ISSUE THREAD

**Issue by kroese** [munin-monitoring/munin#1531]
I have one munin server, and several nodes. 

If the server cannot connect to one of the nodes for a few hours/days (for example because of an IP change, misconfigured firewall, etc.) it will create gaps in the graphs.

Is there a way to let nodes store the data locally when there is no server. And send this backlog to the server as soon as it re-connects?

And if not, could this feature be added? I understand that nodes cannot build up a very large cache, but if only it was just 48 hours worth of data it would prevent almost every gap.

**Comment by steveschnepp** [comment]
That's actually exactly the gap that [munin-async ](https://guide.munin-monitoring.org/en/latest/node/async.html) is filling. 

It is not included in the node as I prefer to have small independent parts.
