### ISSUE TITLE
Munin server generates excessive I/O

### ISSUE THREAD

**Issue by mtillberg** [munin-monitoring/munin#1546]
**Describe the bug**

Munin server, specifically the SQLite database, generates excessive I/O, to the point of slowing down polling.  

**To Reproduce**

During my testing of munin, I pulled munin-sandbox-var out of /run/user and put it on disk.  This caused major slowdowns in monitoring, even with 6 threads rather than the default 16.  The performance is even worse with 12 threads.  Granted my server is a VM with snapshots, so I/O is not that fast, the amount of I/O is unnecessarily large for a 2.5MB database.  For reference, I have approx. 17 nodes, 800 services, 3500 datasources defined in the database.

One suggestion is to switch from journal_mode=DELETE to journal_mode=WAL.  You can read more about WAL mode [here](https://www.sqlite.org/wal.html).  Basically, the current journal mode creates a copy of the database for every transaction with a change.  Since all config info is deleted/reinserted with each munin_update, this is causing a lot of database copies to be written.  WAL mode changes that to use a write ahead log to write pages which are then applied to the database file later.  There are tradeoffs with WAL, so this change shouldn't be taken lightly.  In my testing, WAL mode removes about 60% of I/O.  This still leaves a noticeable slowdown in sampling relative to munin 2.0.

The other suggestion is already mentioned in the comments, updates should be reduced by storing changes rather than delete/insert all config info each munin_update run.

**Comment by steveschnepp** [comment]
To be fair, if you really need performance, you can leverage a postgresql database as it's _really_ much better. 
SQLite is nice, but really currently only suited for very small setups.

`journal_mode=WAL` was actually used in the past, but it isn't compatible with every setup whereas `journal_mode=DELETE` is. And the SQLite usage is really focused on "ease of use and portability". 

Now, I agree that there's some performance improvements possible by doing diffs, which IMHO should be done before tweaking the database itself.

**Comment by mtillberg** [comment]
Is there any documentation on setting up postgresql as the data store?  I set it up to test my stats fix PR, but I didn't find anything in the docs or even in google on how to configure the db* params.  

For the journal_mode, maybe this can be a configurable?  Looking at the code, there are currently two transactions per service, one to update config, one to store fetched values in state.  So only updating config changes is only going to yield a 50% decrease in data written with journal_mode=delete.  Journal mode wal safely reduces 60% of writes, memory or off unsafely removes 70% of writes, and combined with reducing config writes would mean sqlite should be quite usable as a default database.

The database seems to be effectively a short term cache, it's just about recreated with each munin_update run (I don't know how async mode works with this however).  So using unsafe journal_mode=MEMORY or even journal_mode=OFF and adding a pragma quick_check at the start of db_init to detect a corrupt DB may be a workable setup.

**Comment by steveschnepp** [comment]
How does no journal cope with concurrent accessing from update and httpd at the same time? 🤔

**Comment by mtillberg** [comment]
For all the various journal modes except WAL, writes go directly to the database, and the journal is a backup.  So there'd be no change.  For WAL, writes go to the WAL first, so there'd be a bit of a penalty reading in httpd since queries would search the sqlite file and the WAL file. 

OFF is not a good idea, it removes rollback capability, and some errors can corrupt the DB.  I was looking at performance only.  But using MEMORY would mean accepting that the DB might need to be tossed and rebuilt. The UI could be broken until a munin_update run recreates the DB.

**Comment by steveschnepp** [comment]
> The UI could be broken until a `munin_update` run recreates the DB.

That's perfectly acceptable to me. But during the updates, we shall continue to serve UI pages.

**Comment by steveschnepp** [comment]
I created 0ca6e5bced0f7554cf862d8aa6256206dc2ebc01, could you check if it solves the issue ? 
No specific configuration should be required.

**Comment by mtillberg** [comment]
The truncate/off combo gives really good performance.  I was seeing some issues with WAL testing between update and httpd, that was fixed by setting pragma's only if the dbh is not read only.  Also, I think AutoCommit should stay off, it's definitely faster in my testing, and I doubt there's much difference in risk.

However, what I've done is basically implement the differential save.  It's not fully tested yet, but you can look [here](https://github.com/mtillberg/munin/tree/differential_save).  With this, WAL/normal sync becomes usable with speed and I/O, although I'm no longer sure if it's any real benefit over WAL/off.  The differential save has surprisingly small benefit in rollback journal mode through, saving maybe 50% I/O in normal sync mode.

There's also a handful of bug fixes, I'll look at pushing those over as separate pulls so they can be looked at separately.

**Comment by steveschnepp** [comment]
I'm really undecided on differential save. As on one hand, it feels much better, but the current brutal mode is almost foolproof and rock solid.
