### ISSUE TITLE
Can't connect to TCP port 4949 on :: [Invalid argument]

### ISSUE THREAD

**Issue by BETLOG** [munin-monitoring/munin#1579]
**Describe the bug**
munin-node stopped logging, service will not restart

** Steps to reproduce the behavior: **
- notice munin is not logging one machine
- check munin-node service on machine in question, service cannot be restarted
- internet search, see issue relating to error message i get, proceed to post question in wrong issue tracker. (see below)
 
**expected behaviour **

 - Kubuntu 23.04
 
```
$munin-cron -v
munin version 2.0.57.

$ munin-node -v
Version:
    This is munin-node v2.0.71
```
**detail/other info **

Someone discovered an issue with (what I understand to be) a changed sysctl default in recent *buntu that disabled ipv6 and thereby prevents munin from initialising.
Given that the fix seems fairly trivial I don't understand why one of my machines cant start munin-node.

Original question copied from [here](https://github.com/iiab/iiab/issues/3434#issuecomment-1736462983)
If I understand correctly; this should work..right?

```
$ sudo sysctl -p
net.ipv4.ping_group_range = 1000 1000
net.ipv6.conf.all.disable_ipv6 = 0

$ sudo systemctl stop munin-node

$ sudo systemctl disable munin-node
Synchronizing state of munin-node.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable munin-node
Removed "/etc/systemd/system/multi-user.target.wants/munin-node.service".

$ sudo systemctl enable munin-node
Synchronizing state of munin-node.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable munin-node
Created symlink /etc/systemd/system/multi-user.target.wants/munin-node.service → /lib/systemd/system/munin-node.service.

$ sudo systemctl start munin-node
Job for munin-node.service failed because the control process exited with error code.
See "systemctl status munin-node.service" and "journalctl -xeu munin-node.service" for details.
```

I'm seeing multiple LU and KUbuntu machines are logging normally, and yet munin-node on at least one has been down since 2023-09-05 despite multiple reboots since then.

```
$ cat /var/log/munin/munin-node.log
023/09/27-09:14:05 Munin::Node::Server (type Net::Server::Fork) starting! pid(41724)
Resolved [*]:4949 to [::]:4949, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 4949 on host :: with IPv6
2023/09/27-09:14:05 Can't connect to TCP port 4949 on :: [Invalid argument]
  at line 66 in file /usr/share/perl5/Net/Server/Proto/TCP.pm
2023/09/27-09:14:05 Server closing!
shutdown() on unopened socket GEN0 at /usr/lib/x86_64-linux-gnu/perl-base/IO/Socket.pm line 325.
```

**Comment by BETLOG** [comment]
Facepalm.
After all this time I now realise that the error is because I put a comment on the end of the host line:
`host 0.0.0.0 # limits bind to any IP4`

Config files without endofline comment checking......InCoNCeIvAbLe!

**Comment by steveschnepp** [comment]
Huge kudos for your bug report. It is nicely detailed.
The fact that you find out the fix yourself is just the cherry on that nice cake.

**Comment by h01ger** [comment]
On Wed, Nov 15, 2023 at 11:45:10PM -0800, BETLOG wrote:
> Facepalm.
> After all this time I now realise that the error is because I put a comment on the end of the host line:
> `host 0.0.0.0 # limits bind to any IP4`
> Config files without endofline comment checking......InCoNCeIvAbLe!

fwiw, exactly this happened to me some days ago, where I had this
line in munin-node.conf:
host $IP 
instead of
host $IP
Can you spot the difference? That also broke munin-node :(

(added space at the end...!)


-- 
cheers,
	Holger

 ⢀⣴⠾⠻⢶⣦⠀
 ⣾⠁⢠⠒⠀⣿⡁  holger@(debian|reproducible-builds|layer-acht).org
 ⢿⡄⠘⠷⠚⠋⠀  OpenPGP: B8BF54137B09D35CF026FE9D 091AB856069AAA1C
 ⠈⠳⣄

In Europe there are people prosecuted by courts because they saved other people
from drowning in the  Mediterranean Sea.  That is almost as absurd  as if there
were people being prosecuted because they save humans from drowning in the sea.

**Comment by BETLOG** [comment]
I actually noticed a space in an error log entry and looked into it a week ago.
"<...cannot bind.. or something> 0.0.0.0 "
It took me a week to realise why it broke though.

Config files need basic sanity checking. 
sed 's|^ *||; s| *$||; s|#.*$||' FTW

**Comment by codustyle** [comment]
> On Wed, Nov 15, 2023 at 11:45:10PM -0800, BETLOG wrote: Facepalm. After all this time I now realise that the error is because I put a comment on the end of the host line: `host 0.0.0.0 # limits bind to any IP4` Config files without endofline comment checking......InCoNCeIvAbLe!
> fwiw, exactly this happened to me some days ago, where I had this line in munin-node.conf: host $IP instead of host $IP Can you spot the difference? That also broke munin-node :( (added space at the end...!)




stupid space. thank you.
