### ISSUE TITLE
env.ignore_ not ignoring

### ISSUE THREAD

**Issue by BETLOG** [munin-monitoring/munin#1594]
env.ignore_ is not ignoring anything:
- crit/warn messages still get triggered
- graphs still graph

What am I missing here? Has it been removed or something? [Searching the docs](https://guide.munin-monitoring.org/en/latest/search.html?q=env&check_keywords=yes&area=default) has very little in general, and nothing at all on the syntax i am seeing in online search results.

```
root@betlognuc:/# for s in sensors_temp sensors_volt sensors_fan;do sudo munin-run $s config|grep 'graph no';done
temp1.graph no
temp5.graph no
temp6.graph no
temp7.graph no
temp8.graph no
temp9.graph no
volt6.graph no
fan1.graph no
fan3.graph no
```

![2023-11-18--20-17-07_betlogbeast_1920x1080+0+1080](https://github.com/munin-monitoring/munin/assets/12265451/15b6d87a-7727-43ba-9aaa-f80052050c36)

**Comment by BETLOG** [comment]
Note to self: although finding the ?obvious? answer myself 5 minutes after opening an issue is still a solve, and probably not bad documentation for future seekers to find, it's may also be generating Contributor help-fatigue.

Solution: (I think) : Name the file properly.
If plugin-actual is:
/usr/share/munin/plugins/**sensors_**
Then we need a plugin modification file called:
/etc/munin/plugin-conf.d/**sensors_**
not
/etc/munin/plugin-conf.d/sensors_**.conf**

...I assumed that plugin-to-modificationFile matching happened by the [sensors_*] header inside the file, but it seems that is not correct.

![sensors_temp-day](https://github.com/munin-monitoring/munin/assets/12265451/61f941cb-c42a-48b7-9dd1-518c121e53c3)

**Comment by steveschnepp** [comment]
You might want to propose some extra info in the doc. As if you didn't find it, someone else won't either.

**Comment by BETLOG** [comment]
Will do (in future). Also:
Generally when i get stuck i notice there isn't a sufficient range of examples, from trivial to niche, that demonstrate the syntax. 
Sometimes there are things casually mentioned that really should be expressed as actual command syntax  instead of a 'do the thing', or should link to the article named, but don't.
Often in examples it's difficult to know what is arbitrary user-decided names and what is strict command syntax, in this respect [this sort of stuff](https://github.com/munin-monitoring/munin/blob/master/doc/example/graph/aggregation-combined.rst) is pretty clear, but the [Munin Guide](https://guide.munin-monitoring.org) can sometimes sacrifice clarity for brevity/layout cleanliness.

Off the top of my head heres stuff i remember recently having touble with:
- The README says use zzz-foo, but that doesnt work for me, afaik i have to use the same name as the plugin. I still dont know if the readme is outdated or i just dont understand it.
- If the filename has to be identical to the plugin, then why is the [sensors_*] heading required? what are the use-cases where you might use separate files for sensors_temp sensors_fan and sensors_volt? Is the [sensors_*] heading even required? How does zzz-sensors_ even relate to all that? (also see below)
- Where else can i use env.ignore_? in munin.conf? in munin-node.conf?
- Where is a full list of all the possible env combinations? env.ignore_ isnt even in the one i found. There almost no mention of env.ignore_ in the offfical doc search results. Surely something else uses it as part of it's documentation, is the search function working properly?

Then theres incidental stuff that just generates more and more tangental things to wonder about, like:
- `man munin-run' having both `config` and `--config <file>` syntax is potentially confusing. But has no examples.
- Given that `/etc/munin/plugin-conf.d/acpi` is being referenced in all three commands below, how can one fail? It made me wonder if the header was required at all with `--config` as opposed to `--sconfdir` or `sconffile`....which is just weird.
With this kind of thing I find myself blindly trying all of the various possible permutations to find out, and I'm pretty sure that starts causing memory-loss at some point :)

```
# munin-run acpi --sconfdir /etc/munin/plugin-conf.d
thermal_zone0.value 27.8
thermal_zone1.value 29.8
thermal_zone2.value 50

# munin-run acpi --config /etc/munin/plugin-conf.d/acpi
ERROR: Failed to parse config file '/etc/munin/plugin-conf.d/acpi': Line is not well formed ([acpi]) at /usr/sbin/munin-run line 134.

# munin-run acpi --sconffile /etc/munin/plugin-conf.d/acpi
thermal_zone0.value 27.8
thermal_zone1.value 29.8
thermal_zone2.value 47
```

**Comment by steveschnepp** [comment]
Writing documentation is an art in itself.

As most of the time, bad documentation is due to missing key information that seems obvious to the writer, but not to the reader.

So, I'm eager to add anything in the docs that can help if you pinpoint me to specific examples

**Comment by BETLOG** [comment]
> Writing documentation is an art in itself.

I Understand.

>  pinpoint me to specific examples

Well, I just did. :)
But to be even more specific on one I forgot to mention above:

https://guide.munin-monitoring.org/en/latest/tutorial/alert.html
- The title is odd. Something more like 'mail/scripted alerts' might be better and more translatable.
- Add information about:
`contact.<mailWarningLabel>.text <content>`
`contact.<mailWarningLabel>.always_send warning`
with an example that builds on the complexity of the existing example found in: 
`contact.<mailWarningLabel>.command`

This was the essential information I was seeking in an email alert, but had to spend time searching elsewhere for examples I could understand before returning to refer to the syntax information further down the page. 
ie: Before I realised `contact.<>.text` existed it was quite confusing.
```
contact.warn.command if [ "${var:worst}" != "OK" ]; then mail -s "${var:worst} ${var:host} ${var:plugin}" user@betlogbeast.lan; fi
contact.warn.text ${if:wfields (${var:numwfields})${var:worst} ${var:host} ${var:plugin} (${var:graph_title})\n${loop< >:wfields ${var:label}\t${var:value} [${var:wrange}]\t${if:extinfo : ${var:extinfo}}\n}\n}\nhttp://<serverRunningMunin>/munin/munin/${var:host}/${var:plugin}.html
contact.warn.always_send warning
#
contact.crit.command if [ "${var:worst}" != "OK" ]; then mail -s "${var:worst} ${var:host} ${var:plugin}" user@betlogbeast.lan; fi
contact.crit.text ${if:cfields (${var:numcfields})${var:worst} ${var:host} ${var:plugin} (${var:graph_title})\n${loop< >:cfields ${var:label}\t${var:value} [${var:crange}]\t${if:extinfo : ${var:extinfo}}\n}\n}\nhttp://<serverRunningMunin>/munin/munin/${var:host}/${var:plugin}.html
contact.crit.always_send critical
```
