### ISSUE TITLE
apache_accesses x-axis value

### ISSUE THREAD

**Issue by zenonp** [munin-monitoring/munin#1614]
Output from /server-status?auto like ".353 requests/sec - 7.5 kB/second - 21.4 kB/request - 5.68532 ms/request" (note the decimal in .353) results in a graph with the x-axis legend "accesses/second", values from 100 m to 800 m, and the graph average at approximately 350 m. I don't know why requests are abbreviated "m", nor why the real value is multiplied by 1000, but the graph is definitely misleading or confusing or both.

**Comment by niclan** [comment]
m for milli accesses/second. milli means 1/1000th.

It's only confusing if you forgot about scaling units such as kilo, Mega, Giga and milli.

**Comment by zenonp** [comment]
So you're saying that the graph multiplies the value by 1000 and then expects the user to mentally divide it by 1000, instead of simply plotting the real number without any of this completely unnecessary complication. The (printed) scale in this case could have been from 0.1 to 0.8 with the graph oscillating around 0.35. 

The only valid technical reason I can think of for not doing that, would be that the graphs can only handle integers. But that is not the case, as clearly illustrated below. 

![users-day](https://github.com/munin-monitoring/munin/assets/10004285/94a2740a-9a01-46c2-b39f-f4fad13b2809)

**Comment by zenonp** [comment]
For documentation, a "graph_scale no" solves it:

--- apache_status.orig  2024-03-26 00:17:41.519391219 +0000
+++ apache_status       2024-03-25 17:30:35.606742602 +0000
@@ -169,7 +169,8 @@
 
 multigraph apache_accesses
 graph_title Apache accesses
-graph_args --base 1000 -l 0
+graph_args --base 1000 --lower-limit 0
+graph_scale no
 graph_vlabel accesses / \${graph_period}
 graph_category webserver
 END

This is probably also a good candidate for --logarithmic.
