### ISSUE TITLE
cpuspeed plugin problems

### ISSUE THREAD

**Issue by baranyaib90** [munin-monitoring/munin#1617]
Dear munin developers and mainainers! I would like to share my observations and solutions with you about cpuspeed plugin.

**Describe the bug**

1. Graph shows nan value when frequency is under minimum. Example: minimum is 700Mhz, my value: 699964hz.
2. nan value is misleading! It is a number, just bellow minimum value.
3. The CPU intensity of munin update procedure raises the frequency over the normal value. So it fakes the measurement and graph is useless by default (see attached images).

**Expected behavior**

1. Allow values bellow minimum like in case of: https://github.com/munin-monitoring/munin/commit/76fe8bf5fc0a1830b967a5b1dc7e68e0060ac4f9
So adding `MINHZ=$(( $MINHZ - $MINHZ / 10 ))` [here](https://github.com/munin-monitoring/munin/blob/47517b38cb11e924ca238bfe2626113071718eb1/plugins/node.d.linux/cpuspeed#L157).
2. Simple dash character or "oor" (out of range) would be more helpful to debug.
3. I have added in case of Intel CPU `sleep 0.2` before measuring CPU frequencies in the script ([here](https://github.com/munin-monitoring/munin/blob/47517b38cb11e924ca238bfe2626113071718eb1/plugins/node.d.linux/cpuspeed#L167)). In my case this 200ms is enough for the Intel N100 CPU to slow down to normal frequency. For me that is an acceptable delay.

**To Reproduce**
Just have an idle system with Alder Lake or newer Intel CPU.

**Screenshots & Logs**
nan value when frequency is bellow minimum. I had to zoom in to provide proof:
![nan](https://github.com/munin-monitoring/munin/assets/5031516/77642915-5e7b-40d3-8cf2-c8d802ef8a04)
Graph by default:
![default_mess](https://github.com/munin-monitoring/munin/assets/5031516/7470483e-b53a-49ab-a2be-49f44a531430)
After adding 200ms sleep before measurement and fixing minhz:
![after_sleep](https://github.com/munin-monitoring/munin/assets/5031516/17b3278c-b25d-425d-a820-c6db383f2346)

**Environment**
 - OS+Distribution Version: Ubuntu 23.10
 - Kernel: 6.5.0-28-generic x86_64
 - Munin Version: 2.0.71-2ubuntu1

**Additional context**
I have an Intel N100 CPU which changes frequency quite often (plenty time within a second). My setup is idle in most of the time, so mostly the CPU is running in minimum frequency.

**Comment by steveschnepp** [comment]
This an inherent issue with the way the plugin was writen, as it measures while it runs. 

So with a 200ms delay, it give it time to slow down from the initial burst.

**Comment by baranyaib90** [comment]
Yes. I'm not interested about the CPU frequency while munin update is running. I want to graph it in normal circumstances.

**Comment by steveschnepp** [comment]
Then you have to emit the *average* of the interval between 2 runs. 

And that's rewriting the plugin to leverage state

**Comment by steveschnepp** [comment]
I would suggest to look at https://github.com/munin-monitoring/contrib/blob/master/plugins/cpu/multicpu1sec or its C version to craft a cpuspeed1sec

**Comment by niclan** [comment]
The maddening thing here is that some (many?) years ago there was a cpu governor related `/proc` (or `/sys`) file that counted time at each CPU speed level which would be the perfect data source for this, just let rrd track the change in the counter on each speed level.

And I wrote a plugin for it which I can't find.

But it might have been related to a specific version of speed governor and CPU.

**Comment by steveschnepp** [comment]
Having the kernel tracking it would be perfect indeed

**Comment by niclan** [comment]
I've looked over everything I could think of on my intel laptop and this seems a pipe dream.

Taking performance metrics while munin-node is running the plugins is going to be a headache forever.  And with the current information from /proc and /sys it seems we can only get the "instant" speed reading.  I see the frequency changes _very_ often.  ... If only the cpu governor had a way to keep stats.

**Comment by steveschnepp** [comment]
Can you check #1618 ?
