### ISSUE TITLE
Munin does not build graphs correctly.

### ISSUE THREAD

**Issue by bagasik** [munin-monitoring/munin#1621]
Hello.
After updating programs on the server, munin does not build graphs correctly.
There was no munin program update in the list.

My system FreeBSD 14.0-RELEASE-p6 amd64.

# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=en_US.UTF-8

# pkg version -v | egrep 'rrd|munin|py'
munin-common-2.0.75_1              =   up-to-date with index
munin-master-2.0.75_1              =   up-to-date with index
munin-node-2.0.75_2                =   up-to-date with index
p5-File-Copy-Recursive-0.45        =   up-to-date with index
py311-awscli-1.29.81               =   up-to-date with index
py311-botocore-1.34.120            =   up-to-date with index
py311-colorama-0.4.6               =   up-to-date with index
py311-docutils-0.19,1              =   up-to-date with index
py311-jmespath-1.0.1_1             =   up-to-date with index
py311-packaging-24.0               =   up-to-date with index
py311-pyasn1-0.6.0                 =   up-to-date with index
py311-pysocks-1.7.1_1              =   up-to-date with index
py311-python-dateutil-2.9.0        =   up-to-date with index
py311-rsa-4.9_1                    =   up-to-date with index
py311-s3transfer-0.10.1_1          =   up-to-date with index
py311-setuptools-63.1.0_1          =   up-to-date with index
py311-six-1.16.0                   =   up-to-date with index
py311-urllib3-1.26.18_1,1          =   up-to-date with index
py311-yaml-6.0.1                   =   up-to-date with index
python311-3.11.9                   =   up-to-date with index
rrdtool-1.8.0_4                    =   up-to-date with index

I attached a screenshot of the graphs to the topic.
Please help me solve the problem, I don’t understand what has changed in plotting.
![ttt](https://github.com/munin-monitoring/munin/assets/70150149/2974d76d-d84f-4631-a441-7d443863d3ba)

**Comment by steveschnepp** [comment]
it seems that the RRD library cannot find the TTF.

**Comment by bagasik** [comment]
I solved the problem, rebuilt rrdtool with DEJAVU support.
Now the graphics are formed correctly!
Thank you all for your assistance!
