### ISSUE TITLE
infinite recursion URLs with munin-cgi-html and diskstats plugin

### ISSUE THREAD

**Issue by kenyon** [munin-monitoring/munin#283]
I noticed googlebot crawling URLs that seemed to be getting longer and longer, and they always seemed to involve diskstats. I have disabled munin-cgi-html now because of this, but here is an example URL that was valid:

http://kenyonralph.com/munin-cgi/munin-cgi-html/kenyonralph.com/darwin.kenyonralph.com/kenyonralph.com/diskstats_latency/devildog.kenyonralph.com/diskstats_throughput/buddyinfo/diskstats_latency/turing.kenyonralph.com/diskstats_iops/apache_accesses.html

The relevant Apache configuration lines:

```
Redirect /munin/ /munin-cgi/munin-cgi-html/
Alias /munin-cgi/munin-cgi-html/static /var/cache/munin/www/static
ScriptAlias /munin-cgi/munin-cgi-html /usr/lib/munin/cgi/munin-cgi-html
<Location /munin-cgi/munin-cgi-html>
        <IfModule mod_fcgid.c>
            SetHandler fcgid-script
        </IfModule>
        <IfModule !mod_fcgid.c>
            SetHandler cgi-script
        </IfModule>
</Location>
<Location /munin-cgi/munin-cgi-html/static>
        Options -ExecCGI
      SetHandler None
</Location>
```

**Comment by chteuchteu** [comment]
Most links may be broken for now when using munin-cgi. This issue seems to be related to #398, #421 and #440.

Indeed, munin-cgi may produce wrong links, but still providing content for those, which may lead to an unpredictable behavior like the one you described.

Side question: why would you want Google to crawl your munin report pages?

**Comment by kenyon** [comment]
Because why not have Google index the munin pages? It's useful to search for other people's munin pages for comparison with yours, for example. Not that I "want" Google crawling, but I don't have a robots.txt preventing it, so it just happens. It shouldn't cause infinitely long links.

**Comment by chteuchteu** [comment]
It may be a security threat if your server is critical (attackers would know how much an attack is affecting your server), but if not, there's no special reason not to, indeed.
Actually, Google crawling is not the source of the problem, it helped you find it!

Do you think that you can track the path that Google followed to get this weird URL recursion?

**Comment by steveschnepp** [comment]
@kenyon does current devel still produce those with httpd ?

**Comment by sumpfralle** [comment]
I cannot find any unwanted links on the html page produced for the diskstats plugin here on Debian Stretch (munin v2.0.33).

Thus I would close this ticket, if no one objects.
