### ISSUE TITLE
Graph order vs. legend order

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#296]
Could you clarify why the topmost item in legend belongs to graph at the bottom?

Would it be easier to read if the topmost legend item would belong to the graph at the top?

**Comment by sumpfralle** [comment]
The option `--legend-direction` of [rrdgraph](https://oss.oetiker.ch/rrdtool/doc/rrdgraph.en.html) seems to control the behaviour (and allows the reverse direction).

Maybe someone wants to add support for this feature?

**Comment by sumpfralle** [comment]
Indeed the feature was always there. Just add  the following to a graph configuration:
```
graph_args --legend-direction bottomup
```
