### ISSUE TITLE
plugins/node.d/ipmi_sensor_.in needs cleanup

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#301]
- [ ] Usage of `os.env` instead of separate config file
- [ ] Removal of default sensors
- [ ] Addition of fans/rpm alternative
- [ ] Configuration example
- [x] fan tresholds (warning and critical) are inverse-checked: not greater than, but less than

~~I think munin cannot handle "lower then X" warnings.~~ [It can.](http://munin-monitoring.org/wiki/fieldname.warning)

Maybe I will be the one doing it.
#### Current (non-conform) config example

/etc/munin/ipmi
_Note:_ not in `plugin-conf.d`

``` ini
rpm = CPU FAN, SYSTEM FAN
volts = System 12V, System 5V, System 3.3V, CPU0 Vcore, System 1.25V, System 1.8V, System 1.2V
degrees_c = CPU0 Dmn 0 Temp
```

**Comment by leeclemens** [comment]
It seems both ipmi_ and ipmi_sensor use ipmitool (plugins written in bash and python, respectively). Should they be merged (regardless of language)?

**Comment by steveschnepp** [comment]
@leeclemens it sounds like a good idea, yes.

The less plugins, the more multigraph they are, the merrier.

**Comment by sumpfralle** [comment]
@leeclemens: are you still interested in merging them?

**Comment by recentralized** [comment]
This change broke my ipmi_sensor_u_rpm by reversing the critical min:max values.

I have a couple different SuperMicro boards and they report low RPM in the 300's and high in the 20,000 range.  I suspect that Viktor Szép has different hardware with a bug somewhere that reports the range incorrectly.

Here's the output of _ipmitool sensor get 'FAN 1'_:
```
Locating sensor record...
Sensor ID              : FAN 1 (0x41)
 Entity ID             : 29.1
 Sensor Type (Threshold)  : Fan
 Sensor Reading        : 4800 (+/- 0) RPM
 Status                : ok
 Lower Non-Recoverable : 300.000
 Lower Critical        : 450.000
 Lower Non-Critical    : 600.000
 Upper Non-Critical    : 18975.000
 Upper Critical        : 19050.000
 Upper Non-Recoverable : 19125.000
 Positive Hysteresis   : 75.000
 Negative Hysteresis   : 75.000
 Assertion Events      : 
 Assertions Enabled    : lcr- lnr- unc+ ucr+ unr+ 
 Deassertions Enabled  : lcr- lnr- unc+ ucr+ unr+ 
```

Here's the output of _munin-run ipmi_sensor_u_rpm config_ after the patch:
`fan_1.critical 19050.000:450.000`

**Comment by sumpfralle** [comment]
Indeed the change introduced by the above commit (68eaf22a0e368dbd509c5abad451090e03e6ee9b) seems to be suitable only for a specific (broken) device. For the other devices it erroneously reverses the lower and upper critical value.

See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914156.

@szepeviktor: maybe a firmware upgrade already fixed the issue for you? Or maybe `ipmitool` could work around the bad output of your device? I would like to avoid introducing device-specific workarounds into munin's plugins, but rather fix the data sources.
