### ISSUE TITLE
Fraction values on integer inputs

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#309]
![munin update log](http://i.snag.gy/cP0ol.jpg)
This is the output of [Update log](https://github.com/munin-monitoring/munin/issues/307).

I have:

- 1 FATAL
- 2 ERROR

What calculation's result is `Max:0.97`?
How to set it up to 1 be 1 and 2 be 2?

**Comment by ssm** [comment]
Yes, I need to add this to the documentation

**Comment by szepeviktor** [comment]
Thank you.
