### ISSUE TITLE
Sorted SMART attributes

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#310]
I think `smartctl` displays attributes in sensible order.

Would it be much better **unsorted**?
https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d/smart_.in#L208
https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d/smart_.in#L231

**Comment by dipohl** [comment]
I also vote for sort by #ID like smartctl does in its first column. See "smartctl -A <device>"
Adding "(#ID)" to field label would also be nice, as we have no reference to #ID at the time on plugins detail page.
But I don't think it has to be backwards compatible. I see no need for sort by name and vote for no extra plugin variable for this purpose.

**Comment by szepeviktor** [comment]
Thank you.
