### ISSUE TITLE
Forced installation step

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#317]
Is it OK to force the user to manually copy some configuration?
```
The user running this plugin needs read and write access to the
fail2ban communications socket. You will need to add this:
    [fail2ban]
    user root
```
https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d/fail2ban.in#L20-L24

Could it be in `/etc/munin/plugin-conf.d/fail2ban` by **default**?

**Comment by ssm** [comment]
Yes, I think it is OK to make the user add configuration to use plugins.
