### ISSUE TITLE
Fork workers more

### ISSUE THREAD

**Issue by PF4Public** [munin-monitoring/munin#323]
As far as I understand, munin forks separate worker for each host in config file. Wouldn't it be advantageous for a worker to first get list of plugins available on a node and fork some more workers in order to request config and results? For example if it happens to be the time when server experiences heavy I/O, requesting some I/O related information first would give great delay for next requests, however you can at this time request other information, like network related, which will return faster, without delay. This will definitely speed up the process since delays do not accumulate.

**Comment by steveschnepp** [comment]
Having a per-plugin workload compared to a per-host workload we currently have means some heavy modifications. 

That said, it is a very good idea, and it can be mostly done via `munin-asyncd --fork` even right now.

**Comment by ssm** [comment]
I'll close this, In the interest of keeping the open issues list to contain "bugs in munin".
