### ISSUE TITLE
Default Configuration Files

### ISSUE THREAD

**Issue by minnesotags** [munin-monitoring/munin#324]
Assuming the default munin file locations for Debian (using Apache2 2.4 and current version of Munin), the etc/apache2/sites-enabled/default-munin.conf (example name for the munin virtual host file), etc/munin/apache24.conf, and munin/munin.conf all work together. I'm assuming the Apache24.conf file is the replacement for apache.conf in the etc/munin/ directory.  This file gets symlinked into etc/apache2/conf-available and is enabled using a2enconf to be then symlinked into apache2/conf-enabled.
At least for Debian (and Ubuntu?), the "correct" way for Apache2 2.4 to be configured is to install application specific config files in /etc/apache2/conf-available, and then enable them as a symlink in /etc/apache2/conf-enabled in a similar fashion as sites-available/sites-enabled for virtual hosts. I assume this can be done via symlinks to the config file /etc/munin, or directly. I suppose having it installed this way would be an "enhancement" git request. It would also be a great thing to have "default" configuration files for each of these available on github to copy.

**Comment by ssm** [comment]
There are configuration examples in the munin guide. Please see if http://guide.munin-monitoring.org/en/latest/example/index.html is helpful

**Comment by minnesotags** [comment]
Hello ssm. Unfortunately, there are no apache.conf or apache24.conf examples in the munin guide.  There is a virtual host example only.
