### ISSUE TITLE
Silence "OK" alerts

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#347]
I propose to have `${var:okfields}` also to be able to silence "OK" alerts.
I mount and umount the backup disk and it generates an alert.

**Comment by ssm** [comment]
:+1:

**Comment by sumpfralle** [comment]
> I propose to have ${var:okfields} also to be able to silence "OK" alerts.

Could you please elaborate your wish a bit more?
(if it is still relevant)

**Comment by szepeviktor** [comment]
Hello!

Currently the alert from failing state to OK state is always sent. I'd like to avoid it.

**Comment by sumpfralle** [comment]
I would recommend to filter this in your setup.Something like the following should help:
```shell
contact.email.command if [ "${var:worst}" != "OK" ]; then mail -s "Munin-notification for ${var:group} :: ${var:host}" your@email.address.here; fi
```

I think, we should keep this kind of specific configuration outside of munin.

Other opinions?

**Comment by szepeviktor** [comment]
@ssm Could you weigh in?

**Comment by ssm** [comment]
I'd try the suggestion proposed by @sumpfralle first, if possible.

**Comment by h01ger** [comment]
On Sun, Oct 20, 2019 at 12:46:04PM -0700, Lars Kruse wrote:
> I think, we should keep this kind of specific configuration outside of munin.

I agree. IMO it's pretty uncommon not wanting to be alerted about
services gone good again.


-- 
cheers,
	Holger

-------------------------------------------------------------------------------
               holger@(debian|reproducible-builds|layer-acht).org
       PGP fingerprint: B8BF 5413 7B09 D35C F026 FE9D 091A B856 069A AA1C

**Comment by sumpfralle** [comment]
OK - so let us stick with configuration instead of code in this case.
