### ISSUE TITLE
Add configurable ssh options

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#397]
There is a need for configurable ssh options.

Add a default, and a configuration variable for this.  Also look at overriding this per configured node.

Use cases:
- Compression, for speed
- Control Master sockets, for speed
- Connecting through a proxy, for access

This will track the code changes discussed in #319

**Comment by maxbeth** [comment]
Is this issue obsolet throw #319 and ./doc/example/transport/ssh.rst ?

**Comment by sumpfralle** [comment]
Yes, I think #319 provides documentation for all of the above possibilities.
