### ISSUE TITLE
Sparklines shows legend (while they shouldn't)

### ISSUE THREAD

**Issue by chteuchteu** [munin-monitoring/munin#401]
In the [example provided by Steve S. months ago](https://twitter.com/steve_schnepp/status/184606469524697088), we can see that sparkline graphs doesn't display anything much than the graph. 
When trying to display those sparklines now (`?&only_graph=1&size_x=128&size_y=32`), I saw that they seems broken (since acting like a real graph): 
![traffic-day](https://cloud.githubusercontent.com/assets/1551971/6986680/f1bbdfea-da3f-11e4-9339-25d64198977f.png)

`only_graph` parameter seems broken, isn't it?

**Comment by steveschnepp** [comment]
oh. bug in 2.1 :(
