### ISSUE TITLE
munin-httpd should emit caching headers

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#418]
The Munin HTTPD should emit caching headers to help browsers and proxies.

http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/ looks like it has some useful information.

**Comment by chteuchteu** [comment]
We have to be careful about caching: we do want to cache resources (CSS, JS, logo), but not the graphs (there can be weird behaviors about caching)

**Comment by ssm** [comment]
For each graph we generate, we have data for how often it is updated, and how old the data is.
In that case, we _could_ add headers to the effect of "this yearly graph will not change for the next hour, keep it until then".

Alternatively, look at If-Modified-Since, and return 304 if a new graph is not needed.

…And we should have a switch to disable caching for development.

**Comment by steveschnepp** [comment]
`If-Modified-Since` not worth handling usualy.

I'd prefer to emit correct cache headers, as you suggested, and let another tool handle that (varnish ?)

**Comment by ssm** [comment]
good point.
