### ISSUE TITLE
Comparison and categories page aren't available with munin-httpd

### ISSUE THREAD

**Issue by chteuchteu** [munin-monitoring/munin#421]
When trying to reach following pages, one gets 404 error instead:

- `http://{host}:4948/{group}/comparison-hour.html`
- `http://{host}:4948/apache-day.html`

Also, are there comparison and categories pages for -hour time range yet? If not, we should add those, right?

**Comment by ssm** [comment]
the "apache-day.html" pages gets less and less useful as you add nodes, unless you can say "I want all the graphs in the apache service group, but only for these hosts or host groups"

**Comment by chteuchteu** [comment]
I agree with your point of view! We should remove the links from the left navigation menu then.

**Comment by chteuchteu** [comment]
Categories pages are now handled, we still have to implement comparison ones though.

**Comment by steveschnepp** [comment]
Oh. That's something for my next munin hackaton :-1:
