### ISSUE TITLE
ui: show the problematic graphs with some kind of *overlayed* color

### ISSUE THREAD

**Issue by steveschnepp** [munin-monitoring/munin#429]
Now only the oultine changes. It would be nice to have the *whole* graph glow red.

This would also be used to grey out removed plugins, as tracked by #311.

**Comment by chteuchteu** [comment]
Here it is: problematic graphs are now even more visible in one glance!

Criticals:
![icrit](https://cloud.githubusercontent.com/assets/1551971/7072240/14da1b72-deeb-11e4-8ca3-eb954d1b1826.png)

Warnings:
![iwarn](https://cloud.githubusercontent.com/assets/1551971/7072241/19bccf90-deeb-11e4-83e1-1acebf296673.png)

**Comment by steveschnepp** [comment]
yeah that's exactly what I had in mind :+1:
