### ISSUE TITLE
Update definitions.html design

### ISSUE THREAD

**Issue by chteuchteu** [munin-monitoring/munin#433]
Same as #432: there is a `definitions.html` file ([`munin/web/static/definitions.html`](https://github.com/munin-monitoring/munin/blob/devel/web/static/definitions.html)).

Is this still used? If so, it would also benefit to be redesigned to match the new interface!

**Comment by steveschnepp** [comment]
Seems so in https://github.com/munin-monitoring/munin/blob/devel/web/templates/munin-serviceview.tmpl#L134

**Comment by chteuchteu** [comment]
Fixed by 784f7a6 - removed definitions.html file, moved definitions to contextual tooltips.
