### ISSUE TITLE
RRD ERROR Could not save pngg to & Could not draw graph & [RRD ERROR] Unable to graph & [RRD ERROR] rrdtool 'graph'

### ISSUE THREAD

**Issue by Zwordi** [munin-monitoring/munin#434]
Hi Munin,

I have this error for only one of my nodes. The fact is that event the png are under /var/cache/www/ i got this error into the logs of cgi-graphs.

2015/04/09 16:26:46 [WARNING] Could not draw graph "/var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.be/apache_accesses-month.png": /var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.e/apache_accesses-month.png
2015/04/09 16:26:46 [WARNING] Could not draw graph "/var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.be/apache_accesses-week.png": /var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.be/apache_accesses-week.png
2015/04/09 16:26:46 [RRD ERROR] Unable to graph /var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.be/apache_accesses-year.png : Could not save png to '/var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.be/apache_accesses-year.png'
2015/04/09 16:26:46 [RRD ERROR] rrdtool 'graph' '/var/lib/munin/cgi-tmp/munin-cgi-graph/VOIP/sip.toto.be/apache_accesses-year.png' \
    '--title' \
    'Apache accesses - by year' \
    '--start' \
    '-400d' \
    '--base' \
    '1000' \
    '--vertical-label' \
    'accesses / second' \
    '--slope-mode' \
    '--height' \
    '175' \
    '--width' \
    '400' \
    '--imgformat' \
    'PNG' \
    '--font' \
    'DEFAULT:0:DejaVuSans,DejaVu Sans,DejaVu LGC Sans,Bitstream Vera Sans' \
    '--font' \
    'LEGEND:7:DejaVuSansMono,DejaVu Sans Mono,DejaVu LGC Sans Mono,Bitstream Vera Sans Mono,monospace' \
    '--color' \
    'BACK#F0F0F0' \
    '--color' \
    'FRAME#F0F0F0' \
    '--color' \
    'CANVAS#FFFFFF' \
    '--color' \
    'FONT#666666' \
    '--color' \
    'AXIS#CFD6F8' \
    '--color' \
    'ARROW#CFD6F8' \
    '--border' \
    '0' \
    '-W' \
    'Munin 2.0.6-4+deb7u2' \
    'DEF:aaccesses80=/var/lib/munin/VOIP/sip.toto.be-apache_accesses-accesses80-d.rrd:42:MAX' \
    'DEF:iaccesses80=/var/lib/munin/VOIP/sip.toto.be-apache_accesses-accesses80-d.rrd:42:MIN' \
    'DEF:gaccesses80=/var/lib/munin/VOIP/sip.toto.be-apache_accesses-accesses80-d.rrd:42:AVERAGE' \
    'CDEF:caccesses80=gaccesses80' \
    'COMMENT:       ' \
    'COMMENT: Cur:' \
    'COMMENT:Min:' \
    'COMMENT:Avg:' \
    'COMMENT:Max:  \j' \
    'LINE1:gaccesses80#00CC00:port 80 ' \
    'GPRINT:caccesses80:LAST:%6.2lf%s' \
    'GPRINT:iaccesses80:MIN:%6.2lf%s' \
    'GPRINT:gaccesses80:AVERAGE:%6.2lf%s' \
    'GPRINT:aaccesses80:MAX:%6.2lf%s\j' \
    'VRULE:1428589506#999999' \
    'COMMENT:Last update: Thu Apr  9 16:25:06 2015\r' \
    '--end' \
    '1428537600'

There is my munin packages.

i  munin                                2.0.6-4+deb7u2                all          network-wide graphing framework (grapher/gatherer)
ii  munin-async                          2.0.6-4+deb7u2                all          network-wide graphing framework (async master/client)
ii  munin-common                         2.0.6-4+deb7u2                all          network-wide graphing framework (common)
ii  munin-doc                            2.0.6-4+deb7u2                all          network-wide graphing framework (documentation)
ii  munin-node                           2.0.6-4+deb7u2                all          network-wide graphing framework (node)
ii  munin-plugins-core                   2.0.6-4+deb7u2                all          network-wide graphing framework (plugins for node)
ii  munin-plugins-extra                  2.0.6-4+deb7u2                all 

I'have been thourgh old issus on the old tracker but nothing with unable to save png.

Any help could be helpfull.

Thanks

**Comment by bikramjiit** [comment]
Its an old issue, just adding for someone's help in future! 
was having same problem because apache was running as user apache. Following fixed it :
# chmod g+w /var/lib/munin/
# usermod -a -G munin apache
# service httpd restart

**Comment by deva420patra** [comment]
Hi Bikramj

I am also facing the same in my Munin Version 2.0.33 on Linux Rhel 6.9 distro.
munin-cgi-graph.log shows
'CDEF:ngrdio=grdio,-1,*' \
 'LINE1:ngrdio#00CC00' \
 'CDEF:ngavgrdrqsz=gavgrdrqsz,-1,*' \
 'LINE1:ngavgrdrqsz#0066B3' \
 'LINE1:re_zero#000000' \
 'VRULE:1502964745#999999' \
 'COMMENT:Last update\: Thu Aug 17 11\:12\:25 2017\r' \
 '--end' \
 '1502964900'
2017/08/17 11:16:55 [WARNING] Could not draw graph "/var/lib/munin/cgi-tmp/munin-cgi-graph/emea.leaseplancorp.net/LPISVSCDB0001.emea.leaseplancorp.net/diskstats_iops/sdb-day.png": /var/lib/munin/cgi-tmp/munin-cgi-graph/emea.leaseplancorp.net/LPISVSCDB0001.emea.leaseplancorp.net/diskstats_iops/sdb-day.png

munin-update.log shows
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
2017/08/17 11:19:12 [WARN] RRDCached feature ignored: rrdcached socket not writable
.
please check my ownership of /var/lib/munin and sussgest is everything is correct
/var/lib
drwxr-xr-x   3 root    root    4.0K Feb 23  2015 munin-node
drwxr-xr-x  13 munin   munin   132K Aug 17 11:22 munin
 My graphs are are not updating in Munin fro Jul21. Please help
