### ISSUE TITLE
Dynazoom: low/high limits doesn't work

### ISSUE THREAD

**Issue by chteuchteu** [munin-monitoring/munin#435]
When using [dynazoom](http://demo.munin-monitoring.org/static/dynazoom.html?plugin_name=munin-monitoring.org%2Fdemo.munin-monitoring.org%2Fapache_accesses&start_iso8601=2015-04-08T16%3A20%3A27%2B0200&stop_iso8601=2015-04-09T22%3A20%3A27%2B0200&start_epoch=1428502827&stop_epoch=1428610827&lower_limit=1&upper_limit=2&size_x=800&size_y=400&step=&cgiurl_graph=%2Fmunin-cgi%2Fmunin-cgi-graph) feature, one can specify values up and down limits.

As you can see on demo.munin-monitoring.org, those limits doesn't seem to be taken in account. This issue can be reproduced on the last version of devel branch.
The values are well transmitted in the image URL, so it's not a Javascript issue.

**Comment by steveschnepp** [comment]
It should be handled by bd319cb55777d892ccab4f88783d632ac02ad562 which is in 2.1.11.

**Comment by chteuchteu** [comment]
I just checked, and this actually works. Thank you for the fix!
