### ISSUE TITLE
user in munin-node.conf useless

### ISSUE THREAD

**Issue by trepas15** [munin-monitoring/munin#438]
Hi,

In munin-node.conf, user specified is root , nevertheless munin-node use munin user to launch plugins .

<b>munin-node.conf :</b>
<table><tr><td>[...]
<i>background 1
setsid 1

user root
group root
[...]</i></td></tr><table>

<b>./munin-run --debug df:</b>
<table><tr><td><i>
\# Processing plugin configuration from /opt/munin/etc/plugin-conf.d/du_nfs.conf
\# Setting /rgid/ruid/ to /<b>30001</b>/99/
\# Setting /egid/euid/ to /30001 30001/99/</i>
</td></tr><table>

while debugging i found in munin-run and munin-node when user is transmit to service.pm:
 $services = Munin::Node::Service->new(
        servicedir => $servicedir,
      <b>  defuser    => $config->{defuser},
        defgroup   => $config->{defgroup},</b>
        pidebug    => $PIDEBUG,
    );

but these value is empty.

The object $config doesnt contain any defuser :
![muninobject](https://cloud.githubusercontent.com/assets/11886282/7089076/74842dc0-df99-11e4-8608-e093d10ce757.png)

By default it take munin user (Common.pm).

**Comment by steveschnepp** [comment]
The node itself is launched as `root`. That particular configuration is handled directly by `Net::Server`.

It then downgrades itself to some user when launching plugins according to the plugin configuration. Default user is `nobody:munin`. Which is insecure and will be changed in the next major version to something like `nobody:nogroup`.
