### ISSUE TITLE
html: the overview bar has wrong URL

### ISSUE THREAD

**Issue by steveschnepp** [munin-monitoring/munin#440]
The `href`starts with `//` instead of a single `/`

**Comment by chteuchteu** [comment]
I think this issue is related with #398. All the links works fine when served with Apache (pre-generated HTML files), but a lot fails when using munin-httpd. It seems that `<TMPL_VAR NAME="R_PATH">` returns incorrect value.

**Comment by chteuchteu** [comment]
I'f I'm right, R_PATH should contain the relative path to munin root. Examples:
- [/](http://demo.munin-monitoring.org/) -> `.`
- [/munin-monitoring.org/demo.munin-monitoring.org/index.html](http://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/index.html) -> `../..`

For now, R_PATH returns an empty string, which produces an empty href attribute on links.

There also seems to be some issues with other relative links (not just R_PATH). If you look at the navigation part of the header (links on the center). While they seems to be relative links on pre-generated HTML pages (served by Apache, such as `../index.html`, example [here](http://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/index.html)), it seems that they are absolute links (with one more `/` at the beginning of the URL, as you pointed out).
That's the same for dynazoom link: it looks like `//dynazoom.html?...`, while it should be `../../dynazoom.html` (it works fine [here](http://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/if1sec_eth0.html)).

**Comment by chteuchteu** [comment]
After removing all R_PATH vars, there's still an issue with some pages:

- All the header links printed by PATH loop contains two '//' (overview link, the first one, seems correct)
- Service view: dynazoom link: same as upper, it starts with two '//'

Everything else seems to be OK
