### ISSUE TITLE
Please move the plugins/node.d/mysql_ in devel to stable

### ISSUE THREAD

**Issue by annajonna** [munin-monitoring/munin#443]
The stable branch of plugins/node.d/mysql_ has multiple issues on both RH 6 and 7 and CentOS 6 and 7 with MySQL 5.1.x and Mariadb 10.1.x  . At least the devel version is maintained wheras the stable is not maintained and has multiple issues.

**Comment by sumpfralle** [comment]
`devel` was merged - thus it is probably fixed.
