### ISSUE TITLE
Virtual network interfaces not monitored

### ISSUE THREAD

**Issue by franciscopaniskaseker** [munin-monitoring/munin#449]
have one server that have eth0 with main IP and eth0:1 (ip alias, a virtual network interface).

I use only eth0:1 IP. Newrelic recognize my both real interfaces (eth0 and eth1) but do not show any graphic about bandwidth.

All of my servers that do not use ip alias (virtual network interface) I can see the bandwidth graphics normally.

I can see other graphics (disk, firewall etc) normally.
![screenshot-192 99 41 90 2015-04-22 14-47-56](https://cloud.githubusercontent.com/assets/8779476/7281247/b7670144-e8fe-11e4-8519-62b2e37db3e9.png)

**Comment by sumpfralle** [comment]
I am not sure, if statistics are collected for alias interfaces (at least I doubt this for linux).
Or can you find these values by other means? (e.g. `ifconfig`)
Otherwise, I doubt, that the plugin can do anything without a suitable source of information.

**Comment by sumpfralle** [comment]
I am quite confident, that statistics for alias network interface are not collected by the kernel an thus cannot be retrieved with the `if_` plugins. Probably one of the iptables-related plugins could be used for such a purpose (which requires custom firewall rules).
