### ISSUE TITLE
Overview: hide load sparkline when load plugin isn't installed

### ISSUE THREAD

**Issue by chteuchteu** [munin-monitoring/munin#453]
We should be able not to display the load sparkline on overview page when load plugin isn't available.
Would it be possible to send a boolean var to overview template (for each node) to tell if this plugin is installed?

**Comment by chteuchteu** [comment]
That could be done by adding a `SELECT COUNT(*) > 0 as has_load_plugin FROM service s WHERE s.node_id = n.id AND s.name='load'` somewhere, by I didn't know how to put it. `_get_params_groups` seems to be used in some other pages so it wouldn't be brilliant to add it here.

Looping over `$template_params{GROUPS}` in HTML.pm (~ l.167) would be better, but I didn't achieved to do it

**Comment by steveschnepp** [comment]
@chteuchteu I think it would be even better to have `HTMLpm` choosing a plugin to use as a sparkline. With an empty values meaning *no sparkline*.

**Comment by chteuchteu** [comment]
@steveschnepp Yes indeed! How would it chose it?
