### ISSUE TITLE
Documentation lacks information about node groups, implicit and nested

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#456]
Node groups is not documented well.  Need to add:

* Implicit group,  the domain is implicitly used as the group  ("foo.example.com" becomes "example.com;foo.example.com")

* Explicit group.  How to explicitly group nodes

* Nested groups.  The ability to nest groups, making node FQNs like "customer;production;webserver;web123.example.com"

**Comment by chteuchteu** [comment]
About implicit/explicit groups: something seems to be said in the [wiki](http://munin-monitoring.org/wiki/munin.conf):

    [example.com;bar.example.com] # Same as above, but with an explicit definition.
                                  # of the host's group.

**Comment by ssm** [comment]
yes, I'll take the information from the wiki, check that it is sane, move it to the guide, and replace the wiki page with a link to the guide.

**Comment by chteuchteu** [comment]
:+1:

**Comment by ssm** [comment]
I think 7e245fa7847357f54c4dd426d93d8148af40c8a9 handles this, it documents the group, node, service and data source FQN
