### ISSUE TITLE
Munin and Docker hassles

### ISSUE THREAD

**Issue by heikkis** [munin-monitoring/munin#459]
Munin 2.0.25
Centos 5.7 (master), Centos 6.6 (node)

Munin monitors instance with Docker containers. Once in a while (few times a day per container) founds erros:

domain.com :: server1.domain.com :: Disk latency per device :: Average latency for /dev/mapper/docker-253:0-394894-db3ae2af4ce14af3b0612c569a99b9381253ce2fb3d9f9dd563de47956669249
	WARNINGs: Read IO Wait time is 138547.32 (outside range [0:3]).
	OKs: Write IO Wait time is 0.00.

==>

domain.com :: server1.domain.com :: Disk latency per device :: Average latency for /dev/mapper/docker-253:0-394894-db3ae2af4ce14af3b0612c569a99b9381253ce2fb3d9f9dd563de47956669249
	OKs: Read IO Wait time is 0.00, Write IO Wait time is 0.00.

	
Is this problem with Docker or Munin? I dont know. Does someone know?

**Comment by ssm** [comment]
I will assume the reported numbers are correct.
