### ISSUE TITLE
Calculating memory consumption for MariaDB in Munin plugin

### ISSUE THREAD

**Issue by annajonna** [munin-monitoring/munin#463]
In accordance with the calculation method used at http://www.mysqlcalculator.com/ , I have raised an issue at mariadb-discuss as seen here: 
https://lists.launchpad.net/maria-discuss/msg02550.html 

I propose the following patch: 

```
--- munin/plugins/node.d/mysql_ 2015-04-10 14:15:38.840157778 +0000
+++ munin/plugins/ab/mysql_     2015-04-29 15:24:49.746988533 +0000
@@ -1929,22 +1929,22 @@
        $sth->finish();
     }

+    my $tmp_table_size = $data->{'tmp_table_size'};
+    my $max_heap_table_size = $data->{'max_heap_table_size'};
     $data->{'mysql_base_memory'} = $data->{'key_buffer_size'} 
                                          + $data->{'query_cache_size'}
                                          + $data->{'innodb_buffer_pool_size'}
                                          + ( $data->{'innodb_additional_mem_pool_size'} || 0 )
                                          + $data->{'innodb_log_buffer_size'}
+                                        + ( $tmp_table_size >= $max_heap_table_size ? $tmp_table_size : $max_heap_table_size )
                                          + ( $data->{'tokudb_cache_size'} || 0 );

-    my $tmp_table_size = $data->{'tmp_table_size'};
-    my $max_heap_table_size = $data->{'max_heap_table_size'};
     $data->{'mysql_connection_memory'} = $data->{'read_buffer_size'}
                                    + $data->{'read_rnd_buffer_size'}
                                    + $data->{'sort_buffer_size'}
                                    + $data->{'join_buffer_size'}
                                    + $data->{'binlog_cache_size'}
                                    + $data->{'thread_stack'}
-                                   + ( $tmp_table_size >= $max_heap_table_size ? $tmp_table_size : $max_heap_table_size )
                                    + ( $data->{'tokudb_read_buf_size'} || 0 );

    # wsrep_thread_count was separated from max_connections for mariadb-5.5.38 https://mariadb.atlassian.net/browse/MDEV-6206

```

**Comment by chteuchteu** [comment]
Thank you for your contribution! Don't hesitate to open a Pull Request for this modification. We'll then be able to test your changes, but also discuss about those on the PR once it is opened.

**Comment by steveschnepp** [comment]
@annajonna Seems that the [tmp_table_size documentation](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_tmp_table_size) clearly indicates that it isn't *used* memory. 

It only serves as a **threshold** on *when* to offload to disk for temporary tables.

**Comment by grooverdan** [comment]
@annajonna , really appreciate you trying to update the gross approximation that is memory used (that I added).

Justin's response to your your thread was "Thus multiplying each connection by the tmp_table_size is a bad approximation, but probably the best approximation possible.". Its really not a base memory value so you can't just move it there.

Here's another assumption using status variables:
( Created_tmp_files - Created_tmp_disk_tables ) / Connections = number of temp tables per connection to multiply by max_connections?

**Comment by grooverdan** [comment]
@steveschnepp , if it doesn't offload to disk it is used in memory up to this amount, but this only occurs when needed.

The main point of this graph to to avoid over-allocation by tampering of settings, I'm happy to accept some overestimation here. Consequences of OOM killer are worse than a few undersized buffers normally.

**Comment by sumpfralle** [comment]
Any thoughts or pull requests? Otherwise I would tend to close this issue ...
