### ISSUE TITLE
Quick question please>>will munin mongodb plugin monitor mongodb running on windows?

### ISSUE THREAD

**Issue by necroscope** [munin-monitoring/munin#464]
Hi,
Solutions like cacti ssh to monitor mongodb and will not work because we have mongodb on windows.
Munin looks great because it has a windows node...but will the mongodb plugin work to monitor
mongodb on windows?  Please advise...so very appreciative of the work you have done!

Thanks!!

**Comment by steveschnepp** [comment]
I'd guess that since https://github.com/munin-monitoring/contrib/tree/master/plugins/mongodb plugins are all using python, they should work also on windows.
