### ISSUE TITLE
Meaning of `<b>Maj</b> to move quicker`

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/munin#478]
Could you use a more common verb?
(I don't understand "Maj".)
https://github.com/munin-monitoring/munin/blob/devel/web/static/js/munin-nodeview-eventruler.js#L60

**Comment by szepeviktor** [comment]
I think it mean to keep `Shift` pressed.

**Comment by chteuchteu** [comment]
I've got to stop working so late... Maj is the French word for Shift
Thank you for noticing this!
