### ISSUE TITLE
munin-node-configure should read plugin configuration for autoconfiguration

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#481]
The "munin-node-configure" command should set environment from the plugin configuration before doing autoconfiguration.

This would be useful for SNMP  configuration, where usernames and passwords are required both in the configuration and on the command line.

**Comment by ssm** [comment]
Looks like it should be working, but may have a bug.  Needs investigating.

**Comment by sumpfralle** [comment]
@ssm: where do you suspect a problem?

**Comment by sumpfralle** [comment]
Assuming it is working. Please re-open if you still see an issue.
