### ISSUE TITLE
Document munin-httpd and nginx as well

### ISSUE THREAD

**Issue by doliver3** [munin-monitoring/munin#483]
I'm using Ubuntu 14.10, and I've installed the latest munin master and node via apt-get. 

Munin is running in that it can generate the static graph output. However, I would like to use nginx to serve the pages. The documentation says that nginx should be able to proxy to munin-httpd. 

However, there is no munin-httpd script or process as far as I can tell on my Ubuntu server. I have no idea how to start munin-httpd.  

In addition, this documentation describing munin-httpd is not in agreement with the other munin documentation that describes fast cgi. The documentation is not at all clear about how to get nginx to serve munin pages.

What is the correct, most modern way to configure nginx to proxy to munin and how do you get the munin process that serves the html and graphs running?

Thanks

**Comment by doliver3** [comment]
I've found I don't have the latest 2.1 installed on my server.

**Comment by ssm** [comment]
Check the example from the munin 2.0 docs at http://guide.munin-monitoring.org/en/stable-2.0/example/webserver/nginx.html
