### ISSUE TITLE
apt_all should work also for Debian and Ubuntu

### ISSUE THREAD

**Issue by dipohl** [munin-monitoring/munin#489]
I tried to use apt_all on a Ubuntu Server which fails.
Found a bug report which describes my problem: https://bugs.launchpad.net/ubuntu/+source/munin/+bug/1038044
and referred is a patch: https://launchpadlibrarian.net/113037357/apt_all.in.patch

In parallel my colleague found a plugin named "apt_ubuntu" here: https://github.com/GlenSearle/munin-apt_ubuntu/blob/master/apt_ubuntu

which is a complete rewrite from a plugin in old repo at munin-monitoring.org: http://munin-monitoring.org/browser/munin-contrib/plugins/ubuntu/apt_ubuntu

It seems that apt_ubuntu is not contained in the github repo.
I would like to see it on contrib at least.

Concerning the core collection I vote for a multi platform version as enhancement of apt_all

What's your opinion?

**Comment by kenyon** [comment]
Enhancing apt_all seems like a good idea to me. Can you test the latest patch? If it works, you can make a pull request.

**Comment by dipohl** [comment]
I tried with the latest patch and found that it is not working on Ubuntu 16.04.1 LTS. I got only empty results when try to fetch data with "munin-run apt_all". The statefile is empty also.

Found out that there is an critical error existent in the (not-patched) original version of apt_all.

If you try to use the "update" function you always only get the help message because ARGV[1] and ARGV[2] are not set when running e.g. "munin-run apt_all update 600 1"

```
  if ($ARGV[0] and $ARGV[0] eq "update") {
        my $maxinterval = $ARGV[1] ? $ARGV[1] : update_helpandexit;
        my $probability = $ARGV[2] ? $ARGV[2] : update_helpandexit;

```
fyi and cheers,

Gabriele

**Comment by sumpfralle** [comment]
> If you try to use the "update" function you always only get the help message [..]

This is related to [Debian #715141](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=715141). Currently `munin-run` does not use additional parameters when calling the plugin.

The simplest approach is probably to read the above values (`maxinterval` and `probability`) from the environment, if they are not given on the commandline.

**Comment by dipohl** [comment]
On Tue, 20 Feb 2018 16:43:21 -0800
sumpfralle wrote:

> > If you try to use the "update" function you always only get the help message [..]  
> 
> This is related to [Debian #715141](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=715141). Currently `munin-run` does not use additional parameters when calling the plugin.
> 
> The simplest approach is probably to read the above values (`maxinterval` and `probability`) from the environment, if they are not given on the commandline.
> 

thanks for your investigation and the info.

I am not using this plugin anymore as
the Debian servers I had to care for then, 
have been phased out in between.

fyi and cheers,

Gabriele
