### ISSUE TITLE
Looking for munin RPM for RHEL 6.5

### ISSUE THREAD

**Issue by August2008** [munin-monitoring/munin#494]
I'm looking for a RPM package for the munin to get it installed on one of my MongoDB servers for monitoring, which is running RHEL 6.5. I found sources on SourceForge, but there are no RPM packages. I would appreciate if someone can help me with:

1. Understanding how to convert munin tar.gz file to RPM package.
2. Finding the actual RPM ready to be installed.

I cannot install munin from the terminal as described by the MongoDB resource due to environment policy setting on our Linux machines, which prohibits package downloading.

**Comment by tyll** [comment]
munin is packaged in Fedora EPEL (Extra Packages for Enterprise Linux), which is an add-on repository for RHEL and clones. You can use the RPM from there:
http://koji.fedoraproject.org/koji/buildinfo?buildID=618817

More details about EPEL are here:
https://fedoraproject.org/wiki/EPEL

**Comment by August2008** [comment]
Thanks, Till, but RPM dependency chain seems huge. I don't mind resolving this on my free time, but would you know alternative for installing munin in a locked environment, which does not allow downloading via HTTP?

That's how far I've got, but there's more.

epel-release-6-8.noarch.rpm
munin-common-2.0.25-2.el6.noarch.rpm
pgdg-redhat94-9.4-1.noarch.rpm
postgresql94-libs-9.4.4-1PGDG.rhel6.x86_64.rpm
postgresql94-9.4.4-1PGDG.rhel6.x86_64.rpm
perl-DBD-Pg-2.17.1-1.el6.rfx.x86_64.rpm
perl-List-MoreUtils-0.25.2-1.el6.rft.x86_64.rpm
perl-Net-DNS-0.71-1.el6.rfx.x86_64.rpm
perl-Crypt-DES-2.05-3.2.el6.rf.x86_64.rpm
perl-Socket6-0.23-1.el6.rfx.x86_64.rpm
perl-Net-SNMP-5.2.0-1.2.el6.rf.noarch.rpm
perl-Time-HiRes-1.9724-1.el6.rfx.x86_64.rpm
perl-Net-Server-0.99-1.el6.rf.noarch.rpm
perl-Net-CIDR-0.13-1.el6.rf.noarch.rpm
munin-node-2.0.25-2.el6.noarch.rpm
perl-FCGI-0.68-1.el6.rf.x86_64.rpm
perl-CGI-3.49-2.el6.rfx.noarch.rpm
perl-Error-0.17019-1.el6.rfx.noarch.rpm
perl-Cache-Cache-1.06-1.el6.rf.noarch.rpm
perl-String-CRC32-1.4-1.el6.rfx.x86_64.rpm
perl-Cache-Memcached-1.29-1.el6.rfx.noarch.rpm
perl-Carp-Always-0.09-2.el6.noarch.rpm
perl-Test-Harness-3.23-1.el6.rfx.noarch.rpm
perl-Test-Simple-0.98-1.el6.rfx.noarch.rpm
perl-Params-Validate-0.95-1.el6.rfx.x86_64.rpm
perl-DateTime-Locale-0.45-1.el5.rf.noarch.rpm
perl-Class-Singleton-1.4-1.el6.rfx.noarch.rpm
perl-DateTime-TimeZone-1.08-1.el5.rf.noarch.rpm
perl-DateTime-0.5300-2.el6.rfx.x86_64.rpm
perl-File-Copy-Recursive-0.38-1.el6.rfx.noarch.rpm
perl-HTML-Template-2.9-1.el6.rf.noarch.rpm
perl-IO-Socket-INET6-2.57-2.el6.rfx.noarch.rpm
perl-Log-Log4perl-1.26-1.el6.rf.noarch.rpm
perl-Net-SSLeay-1.36-1.el6.rfx.x86_64.rpm

And mode..

error: Failed dependencies:
        cairo is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        libcairo.so.2()(64bit) is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        libdbi.so.0()(64bit) is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        libpango-1.0.so.0()(64bit) is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        libpangocairo-1.0.so.0()(64bit) is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        pango is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        perl(RRDp) is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        perl(RRDs) is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        ruby is needed by rrdtool-1.4.7-1.el6.rfx.x86_64
        xorg-x11-fonts-Type1 is needed by rrdtool-1.4.7-1.el6.rfx.x86_64

**Comment by ssm** [comment]
Please look to EPEL for finding RPMs of munin.
