### ISSUE TITLE
"Could not find FQN" error in munin-graph output

### ISSUE THREAD

**Issue by xtavras** [munin-monitoring/munin#495]
Hi,

I get this message 2-3 times per day with munin-graph cron
```
Could not find FQN root/ext.example.com/pg02ng.ext.example.com/df! at /usr/share/perl5/Munin/Master/Utils.pm line 586
	Munin::Master::Utils::munin_find_node_by_fqn('HASH(0x2c95f60)', 'root/ext.example.com/pg02ng.ext.example....') called at /usr/share/perl5/Munin/Master/GraphOld.pm line 785
	Munin::Master::GraphOld::process_work('babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', 'babel.bln.example.com', ...) called at /usr/share/perl5/Munin/Master/GraphOld.pm line 414
	Munin::Master::GraphOld::graph_main('ARRAY(0x2fce258)') called at /usr/share/munin/munin-graph line 298
	main::draw_graph('ext.example.com', 'pg02ng.ext.example.com', 'df', '--day', '/var/cache/munin/www/ext.example.com/pg02ng.ext.nat...') called at /usr/share/munin/munin-graph line 308
	main::draw_graph_or_complain('ext.example.com', 'pg02ng.ext.example.com', 'df', '--day', '/var/cache/munin/www/ext.example.com/pg02ng.ext.nat...') called at /usr/share/munin/munin-graph line 160
```

the graphs looks ok for me, munin-check doesn't found really problems either (only wrong permission supposedly in  "/var/lib/munin/cgi-tmp/munin-cgi-graph/" which are actually right.) 

I'm using munin 2.0.25 from wheezy-backports on Debian Wheezy 7.8 amd64.

Best,
Stan

**Comment by moses-moore-spafax** [comment]
I've started seeing this too, starting on 2015 July 15 after using munin for almost a year at this site without problems.  Using munin v2.0.19.

Could not find FQN root/XXXXXX.com/croesus.XXXXXX.com/threads! at /usr/share/perl5/Munin/Master/Utils.pm line 586, <GEN1> line 2005.
Munin::Master::Utils::munin_find_node_by_fqn('HASH(0x3241d20)', 'root/XXXXXX.com/croesus.XXXXXX.com/threads') called at /usr/share/perl5/Munin/Master/GraphOld.pm line 783  
Munin::Master::GraphOld::process_work('alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', 'alt-staging.XXXXXX.com', ...) called at /usr/share/perl5/Munin/Master/GraphOld.pm line 412  
Munin::Master::GraphOld::graph_main('ARRAY(0x2d86fa8)') called at /usr/share/munin/munin-graph line 298  
main::draw_graph('XXXXXX.com', 'croesus.XXXXXX.com', 'threads', '--month', '/var/cache/munin/www/XXXXXX.com/croesus.XXXXXX.com/threads-mo...') called at /usr/share/munin/munin-graph line 308  
main::draw_graph_or_complain('XXXXXX.com', 'croesus.XXXXXX.com', 'threads', '--month', '/var/cache/munin/www/XXXXXX.com/croesus.XXXXXX.com/threads-mo...') called at /usr/share/munin/munin-graph line 160  

How can I satisfy "todo: need more information" to help with this?

**Comment by jcharaoui** [comment]
I'm having the same problem on Debain Wheezy using the backported package (2.0.25). It just stopped working some time ago.

**Comment by jcharaoui** [comment]
I solved the problem over here: there were missing nodes in the master config file.

**Comment by doublehp** [comment]
Same for me: similar messages, graphs seem ok, 2 or 3 emails per day, don't understand what's wrong.

There must be an issue; and generating 3 emails per day without any reason is not nice ...
