### ISSUE TITLE
RFE: Allow to get alerts only if they are persistent for a certain amount of time

### ISSUE THREAD

**Issue by tyll** [munin-monitoring/munin#496]
On some of my machines, there are sometimes spontaneous alerts which only last less an than hour, e.g. an ntp offset. This produces unecessary alert mails. Therefore I would like to be able to configure certain alerts to be only created when the issue exists for a certain amount of time.

**Comment by ssm** [comment]
This is not in Munin today, nor is it planned.

Munin sends _everything_ to an external system, most often Nagios or Icinga.

I would be happy to merge a pull request containing this functionality, but for the moment, an external program containing this logic is the option I will reocmmend.
