### ISSUE TITLE
I want to know when the master fail to pull data from node

### ISSUE THREAD

**Issue by CoolJY** [munin-monitoring/munin#497]
I use Munin to monitor all our servers include WAS, DB, NAT, VPN...

But sometimes, it looks like fail to pull data from node.
If the master fails to pull data, it doesn't notice it but jump over the graph.

Can I receive alarm when it fails to pull data from node?

**Comment by ssm** [comment]
No, this is not a feature in munin.  You could have something tail the munin logs, and warn you when somthing happens.
