### ISSUE TITLE
Static html pages still link to dynazoom (which is expectedly broken) when using cron *_strategy for cgi-less nginx.

### ISSUE THREAD

**Issue by Kunou** [munin-monitoring/munin#498]
It's just as the subject says.  It seems to me there shouldn't even be any links to dynazoom when using a cron *_strategy, since you aren't using cgi to begin with.  Shouldn't dynazoom just be ripped out entirely for cron strategies?  Or better yet would be a static image that gets generated with the others during munin-cron runs (size configurable in munin.conf, separate from the others).  If you've ever used/tried monitorix that's basically the kind of thing I'm talking about.

**Comment by sumpfralle** [comment]
> It seems to me there shouldn't even be any links to dynazoom when using a cron *_strategy, since you aren't using cgi to begin with.

The `html_strategy` works as follows:
* `cron`: html pages are generated during every execution of `munin-cron`
* `cgi`: html pages are generated on demand

The zoom graphs can be used with both settings. Obviously the zoom feature requires a working CGI setup. But it is perfectly possible to combine static html output (`cron` strategy) and the CGI-based zoom feature.
