### ISSUE TITLE
 Change nodes arrangment in munin GUI

### ISSUE THREAD

**Issue by vikashdhiman** [munin-monitoring/munin#506]
Hello,

Is it possible that nodes are arrange as services not as automatically by hostname? Like I want to arrange all nodes on Munin server via monitoring plugins. 

Eg : I want that all nodes which have Nginx should arrange in single group and so on.

**Comment by niclan** [comment]
Normally you write

[hostname]


and munin automatically groups by domain name. If you write

[nginx;hostname]

instead you get a group named nginx.

Nicolai

Sendt fra en Samsung Mobil



-------- Opprinnelig melding --------
Fra: Vikash Dhiman <notifications@github.com>
Dato:
Til: munin-monitoring/munin <munin@noreply.github.com>
Emne: [munin] Change nodes arrangment in munin GUI (#506)



Hello,

Is it possible that nodes are arrange as services not as automatically by hostname? Like I want to arrange all nodes on Munin server via monitoring plugins.

Eg : I want that all nodes which have Nginx should arrange in single group and so on.
