### ISSUE TITLE
Holes in Munin graphs across all nodes 

### ISSUE THREAD

**Issue by fibigerg** [munin-monitoring/munin#512]
Hello, I have a problem with missing values in Munin graphs. There are holes in ALL graphs across all monitored nodes. Munin cron is running every 5 minutes and everything seems OK in the munin-update.log, even at the time when hole is being generated in the graphs. I would appreciate any help.

```
2015/07/06 16:50:01 Opened log file
2015/07/06 16:50:02 [INFO]: Starting munin-update
2015/07/06 16:50:02 TLS set to "disabled".
2015/07/06 16:50:02 TLS set to "disabled".
2015/07/06 16:50:08 [INFO] Reaping Munin::Master::UpdateWorker<localdomain;localhost.localdomain>.  Exit value/signal: 0/0
2015/07/06 16:50:08 [INFO] Reaping Munin::Master::UpdateWorker<vpsfree;01.vpsfree>.  Exit value/signal: 0/0
2015/07/06 16:50:08 [INFO]: Munin-update finished (6.18 sec)
2015/07/06 16:55:02 Opened log file
2015/07/06 16:55:02 [INFO]: Starting munin-update
2015/07/06 16:55:02 TLS set to "disabled".
2015/07/06 16:55:02 TLS set to "disabled".
2015/07/06 16:55:09 [INFO] Reaping Munin::Master::UpdateWorker<localdomain;localhost.localdomain>.  Exit value/signal: 0/0
2015/07/06 16:55:09 [INFO] Reaping Munin::Master::UpdateWorker<vpsfree;01.vpsfree>.  Exit value/signal: 0/0
2015/07/06 16:55:09 [INFO]: Munin-update finished (7.42 sec)
2015/07/06 17:00:02 Opened log file
2015/07/06 17:00:03 [INFO]: Starting munin-update
2015/07/06 17:00:03 TLS set to "disabled".
2015/07/06 17:00:03 TLS set to "disabled".
2015/07/06 17:00:10 [INFO] Reaping Munin::Master::UpdateWorker<localdomain;localhost.localdomain>.  Exit value/signal: 0/0
2015/07/06 17:00:10 [INFO] Reaping Munin::Master::UpdateWorker<vpsfree;01.vpsfree>.  Exit value/signal: 0/0
2015/07/06 17:00:10 [INFO]: Munin-update finished (7.82 sec)
```

Node 1
![image](https://cloud.githubusercontent.com/assets/5537140/8525437/24cca7d8-2401-11e5-8c0b-c01c23a62abf.png)
![image](https://cloud.githubusercontent.com/assets/5537140/8525439/2a7f3b6e-2401-11e5-8584-51e6e26ff08b.png)

Munin Node
![image](https://cloud.githubusercontent.com/assets/5537140/8525447/399fe454-2401-11e5-8afd-d7e122ad6921.png)
![image](https://cloud.githubusercontent.com/assets/5537140/8525456/4202ccec-2401-11e5-863c-fd10bf2f4775.png)
![image](https://cloud.githubusercontent.com/assets/5537140/8525457/49eaeaa2-2401-11e5-91dc-a68ec292d4e6.png)

**Comment by shevett** [comment]
It's not uncommon for processing to run longer than 5 minutes.  If that's
the case, you'll see holes happening in the charts.  Check to see if your
munin graphing server is going idle before starting hte next round.

One thing that helped me was removing 'dead' nodes from the munin config.
Dead nodes slow things down enormously.

On Mon, Jul 6, 2015 at 11:12 AM, Gary <notifications@github.com> wrote:

> Hello, I have a problem with missing values in Munin graphs. There are
> holes in ALL graphs across all monitored nodes. Munin cron is running every
> 5 minutes and everything seems OK in the munin-update.log, even at the time
> when hole is being generated in the graphs. I would appreciate any help.
>
> 2015/07/06 16:50:01 Opened log file
> 2015/07/06 16:50:02 [INFO]: Starting munin-update
> 2015/07/06 16:50:02 TLS set to "disabled".
> 2015/07/06 16:50:02 TLS set to "disabled".
> 2015/07/06 16:50:08 [INFO] Reaping
> Munin::Master::UpdateWorker<localdomain;localhost.localdomain>. Exit
> value/signal: 0/0
> 2015/07/06 16:50:08 [INFO] Reaping
> Munin::Master::UpdateWorker<vpsfree;01.vpsfree>. Exit value/signal: 0/0
> 2015/07/06 16:50:08 [INFO]: Munin-update finished (6.18 sec)
> 2015/07/06 16:55:02 Opened log file
> 2015/07/06 16:55:02 [INFO]: Starting munin-update
> 2015/07/06 16:55:02 TLS set to "disabled".
> 2015/07/06 16:55:02 TLS set to "disabled".
> 2015/07/06 16:55:09 [INFO] Reaping
> Munin::Master::UpdateWorker<localdomain;localhost.localdomain>. Exit
> value/signal: 0/0
> 2015/07/06 16:55:09 [INFO] Reaping
> Munin::Master::UpdateWorker<vpsfree;01.vpsfree>. Exit value/signal: 0/0
> 2015/07/06 16:55:09 [INFO]: Munin-update finished (7.42 sec)
> 2015/07/06 17:00:02 Opened log file
> 2015/07/06 17:00:03 [INFO]: Starting munin-update
> 2015/07/06 17:00:03 TLS set to "disabled".
> 2015/07/06 17:00:03 TLS set to "disabled".
> 2015/07/06 17:00:10 [INFO] Reaping
> Munin::Master::UpdateWorker<localdomain;localhost.localdomain>. Exit
> value/signal: 0/0
> 2015/07/06 17:00:10 [INFO] Reaping
> Munin::Master::UpdateWorker<vpsfree;01.vpsfree>. Exit value/signal: 0/0
> 2015/07/06 17:00:10 [INFO]: Munin-update finished (7.82 sec)
>
> Node 1
> [image: image]
> <https://cloud.githubusercontent.com/assets/5537140/8525437/24cca7d8-2401-11e5-8c0b-c01c23a62abf.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5537140/8525439/2a7f3b6e-2401-11e5-8584-51e6e26ff08b.png>
>
> Munin Node
> [image: image]
> <https://cloud.githubusercontent.com/assets/5537140/8525447/399fe454-2401-11e5-8afd-d7e122ad6921.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5537140/8525456/4202ccec-2401-11e5-863c-fd10bf2f4775.png>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5537140/8525457/49eaeaa2-2401-11e5-91dc-a68ec292d4e6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/munin-monitoring/munin/issues/512>.
>



-- 
Dave Shevett
shevett@pobox.com

**Comment by fibigerg** [comment]
Thank you for the answer. My Munin is set up with only two nodes (one local and one remote). I will add more in the future. The local node is almost unused VPS (4 core, 4GB ram). Proccesses munin-update/graph run only few seconds.

I looked into uptime-uptime-g.rrd, and there are missing (NaN) values in it (corresponding to the graphs). Node-update is running every 5 minutes and there are no errors ing the munin-update.log.

![image](https://cloud.githubusercontent.com/assets/5537140/8526954/29db8484-240a-11e5-9879-2b5a6bfcbfef.png)

**Comment by ssm** [comment]
Missing values happen when munin-update is not able to read all the data from all the nodes. and store those in RRD. 

 A dump of the RRD files will show NaN (Not a Number) for time periods where data was not stored.

In general, this is often due to:

* munin-nodes not answering before timeout.
* munin-update running for more than 5 minutes master, blocking the next munin-update run.
* Someone broke the internet.

If it is the munin nodes' fault, increase "timeout" on the nodes, or add more munin-update workers.

If it is the munin master's fault, start using rrdcached.
