### ISSUE TITLE
Munin-Gallery shows truncated plugin name

### ISSUE THREAD

**Issue by dipohl** [munin-monitoring/munin#517]
e.g. here the plugin "amavis" shows up as "ama"
http://gallery.munin-monitoring.org/antivirus-index.html

Likely this error is a regression from some changes made after my contribution of the script set, as the error is not present in my version of the gallery (daily generated and so based on the same current data from munin github repository)
http://munin-gallery.dipohl-kunden.de/antivirus-index.html

**Comment by kenyon** [comment]
Last three characters are chopped off of the core plugin names. Third-part plugins are unaffected.

**Comment by chteuchteu** [comment]
I found the source of this issue (I'm currently working on redesigning the gallery): in [/contrib/plugin-gallery/print-gallery.awk](https://github.com/munin-monitoring/munin/blob/devel/contrib/plugin-gallery/print-gallery.awk#L36), we're trying to cut off an extension that doesn't exist:

    # cut off extension ".in" 
    plugin = substr(plugin,1,length(plugin)-3)

Commenting this line fixes the bug.
We have to check though if this removal doesn't introduced side effects

**Comment by steveschnepp** [comment]
Oh, the extension was removed in f043699a82d1fb1766443237fc392e8d316319ef
