### ISSUE TITLE
Shall we recommend usage of these plugin attributes?

### ISSUE THREAD

**Issue by dipohl** [munin-monitoring/munin#518]
I moved the content from wiki page http://munin-monitoring.org/wiki/protocol-config to the Munin-Guide. I left out documentation of the following attributes since I doubt that we should recommend their usage. What's your opinion?

graph_printf :  Wouldn't it be better to use graph_args for that?

{fieldname}.oldname : I fear there is more potential for trouble than help..

**Comment by ssm** [comment]
I'm not sure what either of these are good for.

**Comment by ssm** [comment]
I've documented graph_printf for #309, but think we could quietly forget about .oldname

**Comment by dipohl** [comment]
Thanks!
