### ISSUE TITLE
Bug in HTMLOld.pm on ArchLinux

### ISSUE THREAD

**Issue by IlikePepsi** [munin-monitoring/munin#519]
I'm encountering a bug when the munin-cgi-html script is executed by apache, when a user requests data. I'm on an ArchLinux machine and therefore made related post in the ArchLinux forum. Please help.

https://bbs.archlinux.org/viewtopic.php?id=200127

**Comment by sumpfralle** [comment]
Is this still an issue?

**Comment by sumpfralle** [comment]
Maybe the problem is based on the Arch packaging?
Closing for now due to lack information ...
