### ISSUE TITLE
cdef processing skips second occurrence of graphname

### ISSUE THREAD

**Issue by Mrten** [munin-monitoring/munin#521]
I'd like to attract attention to my bug 1017 in the original bugtracker:
http://munin-monitoring.org/ticket/1017

> I think I may have found a bug in the cdef processing:
> `qcache_eff.cdef Qcache_hits,Qcache_hits,Com_select,+,/,100,*`
> gives an RRD error in munin-graph.log:
> 
> `2011/01/14 09:26:07 [RRD ERROR] Unable to graph [...] invalid rpn expression in: aQcache_hits,Qcache_hits,aCom_select,+,/,100,*`
> 
> Looks suspiciously like a regular expression search/replace that misses
> the 'global' qualifier.
> 
> ```
> graph_args --base 1000 --no-gridfit --slope-mode
> graph_title Cache efficiency
> graph_vlabel %
> graph_category mysql
> Qcache_hits.type DERIVE
> Qcache_hits.graph no
> Com_select.type DERIVE
> Com_select.graph no
> qcache_eff.cdef Qcache_hits,Qcache_hits,Com_select,+,/,100,*
> qcache_eff.draw LINE1
> qcache_eff.label Momentary query cache efficiency
> qcache_eff.type GAUGE
> qcache_eff.update no
> ```
> 
> Which does not work.
> btw, you can work around this by putting aliases in the order of the graph:
> `graph_order qh=Qcache_hits cs=Com_select`
>  then use the alias (once!).

...because I'm hitting it again with a new plugin.

**Comment by Erreu** [comment]
Here's an alternate workaround that works for me, just add 0 to separate any identical field names:
aQcache_hits,0,+,Qcache_hits,aCom_select,+,/,100,*

I think this bug dates back to at least 2014: https://github.com/munin-monitoring/munin/pull/312

**Comment by sumpfralle** [comment]
Fixed in f0462854633cc6930f50bd700206b7a7887e9c4a (Munin v2.0.41).
