### ISSUE TITLE
Incorrect images path in comparison day,week,month,year

### ISSUE THREAD

**Issue by prijswij** [munin-monitoring/munin#524]
The path of the images are not alway correct and vary depending on the category depth.
<TMPL_VAR NAME="CIMGDAY">
<TMPL_VAR NAME="CIMGWEEK">
<TMPL_VAR NAME="CIMGMONTH">
<TMPL_VAR NAME="CIMGYEAR">

Since the link around the image is always correct would it not be a sulution to use the same buildup?
link in template ==> <TMPL_VAR NAME="R_PATH">/<TMPL_VAR NAME="URL">
image in template ==> <TMPL_VAR NAME="R_PATH">/<TMPL_VAR NAME="CIMG[DAY|WEEK|MONTH|YEAR]">

it does not work now because the <TMPL_VAR NAME="CIMG[DAY|WEEK|MONTH|YEAR]"> allready has a wrong "../../" count

**Comment by ssm** [comment]
Which version of munin are you running?

**Comment by prijswij** [comment]
I'm running 2.0.25

**Comment by prijswij** [comment]
I cant really pinpoint the exact problem, but is has something to do with the depth of the category.
I created categories in the order of:
testing
testing - streetx
testing - streetx - elasticsearch
testing - streetx - webservers
... etc.
staging
... etc.
production
production - elasticsearch
production - elasticsearch - clustername1
production - elasticsearch - clustername2
production - webservers
production - couchbase - clustername1
... etc.

**Comment by tylux** [comment]
I also ran into this issue, none of the image paths on my comparison pages were working...my "fix" was to add ../ right before <TMPL_VAR NAME

So:

<img src="<TMPL_VAR NAME="CIMGDAY">

Became

<img src="../<TMPL_VAR NAME="CIMGDAY">

I made this change to munin-comparison-day.tmpl and added and extra ../ to week, month, year templates.

**Comment by prijswij** [comment]
Thanks for you suggestion.
I tried this too, but depending on the "depth" it did or did not work.

**Comment by MKabe** [comment]
Got the same problem, if I remember correctly I fixed it by changing the image "src" as :
"<TMPL_VAR NAME="NODENAME">/<TMPL_VAR NAME="NODE">-day.png"
And month/week/year for others templates

**Comment by sumpfralle** [comment]
I am quite confident, that this is solved in 633de82386f67c8108362a5bd2fc6331b402f1b1 (released in 2.0.49).

Please re-open, if you still see this issue.
