### ISSUE TITLE
if_ plugin spikes in graphs but not in the data

### ISSUE THREAD

**Issue by nusenu** [munin-monitoring/munin#531]
Hi,

I'm observing extreme spikes in if_<interface> graphs (>>1Gbps) that can not be reproduced in the data (I'm logging plugin output). The system can not do more than ~200Mbps.

The node runs munin-node-2.0.25_4 on FreeBSD 10.1, the master runs munin 2.0.25 on Debian 8.

Ref:
http://sourceforge.net/p/munin/mailman/munin-users/?viewmonth=201507&viewday=28

**Comment by ssm** [comment]
When the data source rolls over, either because the counter reaches max, or because of a boot, RRD may create spikes.

Please see http://munin-monitoring.org/wiki/SpikeRemoval, or google for "rrd spike".
