### ISSUE TITLE
ntp_ plugin in a private network (offline)

### ISSUE THREAD

**Issue by Ahlqvist91** [munin-monitoring/munin#542]
I'm experience if i use the plugin ntp_ offline it does not generate graphs (html and png) in /var/www/munin/xX/Xx.
I'm able to generate graphs if I connect to the public internet and use "sudo apt-get update", which is pretty wierd.

The plugin file exists in /etc/munin/plugins and the peer exists in ntp.conf.

**Comment by kenyon** [comment]
I'd guess this is because DNS lookups are failing, but would have to know more about your setup to be sure. Please use the mailing list or IRC for further support. Thanks.
