### ISSUE TITLE
Munin for unbound dns server

### ISSUE THREAD

**Issue by SergeyMuha** [munin-monitoring/munin#553]
I install munin-node to CentOS Linux release 7.1.1503
create file unbound_munin_ and linked it to /etc/munin/plugins/  to list 
unbound_munin_by_class
unbound_munin_by_flags
unbound_munin_by_opcode
unbound_munin_by_rcode
unbound_munin_by_type
unbound_munin_histogram
unbound_munin_hits
unbound_munin_memory
unbound_munin_queue
but when I am start munin-node in log i see next
2015/08/27-12:02:13 [2766] Service 'unbound_munin_hits' timed out.
2015/08/27-12:03:15 [2766] Service 'unbound_munin_by_rcode' timed out.
2015/08/27-12:04:17 [2766] Service 'unbound_munin_queue' timed out.
2015/08/27-12:05:20 [2766] Service 'unbound_munin_histogram' timed out.
2015/08/27-12:06:22 [2766] Service 'unbound_munin_by_type' timed out.
2015/08/27-12:07:24 [2766] Service 'unbound_munin_by_opcode' timed out.
2015/08/27-12:08:26 [2766] Service 'unbound_munin_by_class' timed out.
2015/08/27-12:09:28 [2766] Service 'unbound_munin_by_flags' timed out.
and in munin server web created only  cpu processes and etc. but without dns

When I do [root@test plugin-state]#  telnet 127.0.0.1 4949
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
list
cpu df df_inode entropy forks fw_conntrack fw_forwarded_local fw_packets if_eno16780032 if_err_eno16780032 interrupts irqstats load memory netstat open_files open_inodes postfix_mailqueue postfix_mailvolume proc_pri processes swap threads unbound_munin_by_class unbound_munin_by_flags unbound_munin_by_opcode unbound_munin_by_rcode unbound_munin_by_type unbound_munin_histogram unbound_munin_hits unbound_munin_memory unbound_munin_queue uptime users vmstat

list
cpu df df_inode entropy forks fw_conntrack fw_forwarded_local fw_packets if_eno16780032 if_err_eno16780032 interrupts irqstats load memory netstat open_files open_inodes postfix_mailqueue postfix_mailvolume proc_pri processes swap threads unbound_munin_by_class unbound_munin_by_flags unbound_munin_by_opcode unbound_munin_by_rcode unbound_munin_by_type unbound_munin_histogram unbound_munin_hits unbound_munin_memory unbound_munin_queue uptime users vmstat
fetch cpu
user.value 21431
nice.value 0
system.value 34474
idle.value 8161123
iowait.value 308879
irq.value 3
softirq.value 497
steal.value 0
guest.value 0
.
^[[A^H
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
fetch df
_dev_mapper_centos_root.value 6.9134157553977
_dev_sda1.value 24.0092176771768
.
list
cpu df df_inode entropy forks fw_conntrack fw_forwarded_local fw_packets if_eno16780032 if_err_eno16780032 interrupts irqstats load memory netstat open_files open_inodes postfix_mailqueue postfix_mailvolume proc_pri processes swap threads unbound_munin_by_class unbound_munin_by_flags unbound_munin_by_opcode unbound_munin_by_rcode unbound_munin_by_type unbound_munin_histogram unbound_munin_hits unbound_munin_memory unbound_munin_queue uptime users vmstat
ft^He
# Unknown command. Try cap, list, nodes, config, fetch, version or quit
fetch threads
threads.value 185
.
fetch unbound_munin_by_class
# Timed out

as i understood correct it mean plugins added to munin but  timed out. steel present
Can any one help me please ??

**Comment by SergeyMuha** [comment]
setenforce 0

**Comment by ssm** [comment]
selinux may bring surprises sometimes, indeed.
