### ISSUE TITLE
hddtemp_smartctl fails to parse temperature from output

### ISSUE THREAD

**Issue by jonathanwminer** [munin-monitoring/munin#576]
(Red Hat Bugzilla 1269230, munin 2.0.25)

The hddtemp_smartctl plug-in fails to parse temperature from the output of smartctl.

Upon investigation, discovered that the drive reports "190 Airflow_Temperature_Cel" but that token does not match the strings used in the parsing algorithm.

**Comment by dipohl** [comment]
Can you provide a complete smartctl report with "smartctl -q noserial -a <DEVICE>" ?

**Comment by jonathanwminer** [comment]
Unfortunately no.  The system is air gapped, and looking at the output, it's too much to retype.  The line that needs to be parsed is:

190 Airflow_Temperature_Cel 0x0022 070 062 040 Old_age Always  - 30 (Min/Max 21/30)

If there is some other entry that you're specifically looking for, let me know and I can track that down.

**Comment by dipohl** [comment]
From this shorter output: smartctl -i -q noserial DEVICE
Device Model:
Firmware Version:
Device is: 
ATA Version is:

**Comment by jonathanwminer** [comment]
Device Model: WDC WD5000HHTZ-60N21V0
Firmware Version: 04.06A01
Device is: Not in smartctl database [ for details use: -P showall ]
ATA Version is: 8

**Comment by dipohl** [comment]
It's already done, please test.

https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d/hddtemp_smartctl

```diff
git show f2179a63
commit f2179a63e40b575c61750f4d7825a3f59eea3044
Author: leeclemens 
Date:   Thu Jan 30 22:12:30 2014 -0500

    Add Airflow_Temperature_Cel as temperature reading
    
    Samsung SSD 830 Pro (at least) only provides Airflow_Temperature_Cel from smartctl

diff --git a/plugins/node.d/hddtemp_smartctl.in b/plugins/node.d/hddtemp_smartctl.in
index e1c2781..f81e46c 100644
--- a/plugins/node.d/hddtemp_smartctl.in
+++ b/plugins/node.d/hddtemp_smartctl.in
@@ -238,6 +238,9 @@ foreach my $drive (@drives) {
   } elsif ($output =~ /^(231 Temperature_Celsius.*)/m) {
     my @F = split ' ', $1;
     print "$drive.value $F[9]\n";
+  } elsif ($output =~ /^(190 Airflow_Temperature_Cel.*)/m) {
+    my @F = split ' ', $1;
+    print "$drive.value $F[9]\n";
   } else {
       print "$drive.value U\n";
       print "$drive.extinfo Temperature not detected in smartctl output\n";
```

**Comment by jonathanwminer** [comment]
Thanks. Just waiting for this upstream fix to be propagated down to the EPEL repository.

**Comment by dipohl** [comment]
It's already in branch master, so should go out with the next release.

https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/hddtemp_smartctl
