### ISSUE TITLE
plugin fw_conntrack returns non-integer warning,critical values

### ISSUE THREAD

**Issue by azrdev** [munin-monitoring/munin#578]
According to [1] and [2] and [3], the config values for `{fieldname}.warning` and `{fieldname}.critical` have to be integers. Looking at https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d.linux/fw_conntrack#L122  the fw_conntrack plugin may return float values, though.

[1] https://munin.readthedocs.org/en/latest/reference/plugin.html#data-source-attributes
[2] http://munin-monitoring.org/wiki/fieldname.warning
[3] http://munin-monitoring.org/wiki/fieldname.critical

**Comment by dipohl** [comment]
Thanks for the hint! That was a documentation bug. Now fixed in https://github.com/munin-monitoring/munin/commit/fd9efadb8e9725fdb39e8eb395a480bb41bd0f18

warning and critical can also be decimal numbers.
