### ISSUE TITLE
Insecure $ENV{PATH} in Open3.

### ISSUE THREAD

**Issue by colinmollenhour** [munin-monitoring/munin#582]
On my system (Ubuntu 14.04) when trying to generate graphs the Open3.pm generates an error "Insecure $ENV{PATH} ...". I fixed it by adding the following line before all of the Open3 includes:

    $ENV{PATH} = "/bin:/usr/bin"; # Minimal PATH.

**Comment by jleroy** [comment]
Ame error here on Debian Jessie.

**Comment by steveschnepp** [comment]
Any luck with using 52d2d2998fee95d6405974a1830d8a77d25ff836 ?

**Comment by colinmollenhour** [comment]
Thanks for pointing out a fix commit, @steveschnepp but I won't be able to test this any time soon; I just wanted to report the bug in case it hadn't already been reported.

**Comment by steveschnepp** [comment]
@ssm how come it can affect Debian Jessie as @jleroy commented ? 
... i guess that commit doesn't fixit.

**Comment by jleroy** [comment]
I've just upgraded my server to 2.999.2, and everything works now. So this patch seems to fix this error.
