### ISSUE TITLE
Notification(contact) Plugin not initiating alerts

### ISSUE THREAD

**Issue by Slind14** [munin-monitoring/munin#587]
I have a custom notification script which I want to supply with data from munin whenever a critical event occurs. Unfortunately I was not able on getting it to work, while following the official docs. The notification script it self is tested and works fine when called from the shell with fake data. It's permissions are on 755 so execution shouldn't be an issue either. Hence the contact hook probably not being called. What I did is this:

# /etc/munin/munin-conf.d/my.cnf
    [...]
    contact.slack.command MUNIN_SERVICESTATE="${var:worst}" MUNIN_HOST="${var:host}" MUNIN_SERVICE="${var:graph_title}" MUNIN_GROUP=${var:group} /usr/local/bin/notify_slack_munin
    contact.slack.always_send warning critical
    contact.slack.text ${if:cfields \u000A* CRITICALs:${loop<,>:cfields  ${var:label} is ${var:value} (outside range [${var:crange}])${if:extinfo : ${var:extinfo}}}.}${if:wfields \u000A* WARNINGs:${loop<,>:wfields  ${var:label} is ${var:value} (outside range [${var:wrange}])${if:extinfo : ${var:extinfo}}}.}${if:ufields \u000A* UNKNOWNs:${loop<,>:ufields  ${var:label} is ${var:value}${if:extinfo : ${var:extinfo}}}.}${if:fofields \u000A* OKs:${loop<,>:fofields  ${var:label} is ${var:value}${if:extinfo : ${var:extinfo}}}.}

Above those lines the nodes and dir's are defined which works fine. But the notification isn't going out. Do you have any idea on what it could be?

I checked all the logs in /var/log/munin but couldn't find anything particular related to the contact module. Is there a specific log I should be looking for?

**Comment by chteuchteu** [comment]
You should seek for clues in /var/log/munin/munin-limits.log. You have to check if `munin` user is able to execute your script. You could try this:

    chown munin:munin /usr/local/bin/notify_slack_munin
    chmod u+x /usr/local/bin/notify_slack_munin

If this doesn't work either, it means that it isn't a permissions issue.

**Comment by Slind14** [comment]
```
:/usr/local/bin# ls -al
total 32
drwxr-xr-x  2 root  root   4096 Oct  4 02:41 .
drwxr-xr-x 10 root  root   4096 Jun 27  2014 ..
-rwxr-xr-x  1 munin munin  1629 Oct  4 03:03 notify_slack_munin
-rwxr-xr-x  1 root  root   1022 Apr 19  2015 rdiff-backup
-rwxr-xr-x  1 root  root  14518 Apr 19  2015 rdiff-backup-statistics
```

munin-limits.log
https://gist.github.com/Slind14/4dda557f1f35cc196ec1

https://i.imgur.com/NoqJ9dR.png

The warning happened at around 18 o'clock. The limits log doesn't show anything going bad or good.
The script it self works fine when run with `su munin`.

Atm, the `contact` is defined in `/etc/munin/munin-conf.d/my.cnf`, as are the nodes, html and tmpl path. Is `contact` required to be in the main config? `/etc/munin/munin.conf`?

**Comment by SirWilli** [comment]
@chteuchteu any news to this issue?

**Comment by chteuchteu** [comment]
I won't be able to help further unfortunately, we should call @steveschnepp or @ssm for help

**Comment by dipohl** [comment]
Slind14: You said in your initial posting, that your node definitions are placed above the contact definition lines, if I understand it right:

> Above those lines the nodes and dir's are defined 

But the "Munin-Tree" has to be the last section of munin.conf. You have to place the contacts option above the first node declaration.

http://guide.munin-monitoring.org/en/latest/reference/munin.conf.html

**Comment by Slind14** [comment]
argh, I didn't know that. Changing now, thanks.

Where does it say this about the order? In my opinion it should be a huge red box on docs :D

**Comment by Slind14** [comment]
Just to make sure, this should work, right?

```
htmldir /var/www/monitoring/htdocs/munin
tmpldir	/etc/munin/templates

contact.slack.command MUNIN_SERVICESTATE="${var:worst}" MUNIN_HOST="${var:host}" MUNIN_SERVICE="${var:graph_title}" MUNIN_GROUP=${var:group} /usr/local/bin/notify_slack_munin
contact.slack.always_send warning critical
contact.slack.text ${if:cfields \u000A* CRITICALs:${loop<,>:cfields  ${var:label} is ${var:value} (outside range [${var:crange}])${if:extinfo : ${var:extinfo}}}.}${if:wfields \u000A* WARNINGs:${loop<,>:wfields  ${var:label} is ${var:value} (outside range [${var:wrange}])${if:extinfo : ${var:extinfo}}}.}${if:ufields \u000A* UNKNOWNs:${loop<,>:ufields  ${var:label} is ${var:value}${if:extinfo : ${var:extinfo}}}.}${if:fofields \u000A* OKs:${loop<,>:fofields  ${var:label} is ${var:value}${if:extinfo : ${var:extinfo}}}.}

[GroupA;Charlie]
    address ssh://charlie.example.com -W localhost:4949
    use_node_name yes
```

**Comment by dipohl** [comment]
Concerning the huge red box advice.. I will add a warning about the importance of the ordering.
But we had not many issues in this field as most of the people use the delivered template.
The current version (before Build) is available here and shows, that the definition of contacts is placed before the munin tree: https://github.com/munin-monitoring/munin/blob/master/etc/munin.conf.PL

Concerning your snippet: I am not very experienced with defining ones own contact procedures, so I am not sure, if your declaration is correct.

I suggest to setup a working munin.conf with standard contacts (mail) first and then in a second step add your extensions.

My munin.conf:

------------
  htmldir /var/www/html/munin
  includedir /etc/munin/conf.d
  graph_strategy cgi
  html_strategy cgi
  contact.gap.command mail -s "Munin notification ${var:host}" gap@mydomain
  contact.gap.always_send warning critical
  
  # a simple host tree
  
  [MyGroup;]
  contacts gap
  
  [MyGroup;node1.example.com]
    address <IP-Address of the Node>
    port 4949
    use_node_name yes

------------

**Comment by Slind14** [comment]
ok thanks. I never ran into any issues concerning the order of configuration, first (life) time, so this totally didn't cross my mind.

The snippet is working fine, two minutes after I moved it up, I got the first alerts.
One quick question, is it possible to define a reporting limit. With the snippet above it sends out an alert every 5 minutes (cron interval), one for each issue until resolved would be sufficient for me.
I found the `max_messages` in the docs and are quite certain that it would do just this. But as I couldn't find any explanation about `always_send` I'm wondering of how they cooperate. 
Would setting `always_send` overwrite the `max_messages` limit for the level?

**Comment by dipohl** [comment]
I hope you are ok with me closing this issue now. 

If you need advice about the further configuration options for contacts, please use Munin-Mailinglist or ask on IRC.

If you find bugs you are welcome to open another report here.

Concerning the Munin-Guide. Moving the wikis content to the Guide is work in progress.. As the wiki docs are very old, some infos given there are outdated.. and in case I will be happy about your contributions to the Munin-Guide :-)

I set moving contents from the wiki page about munin.conf as next task, when I have spare time..

**Comment by Slind14** [comment]
sure, thanks for the help.
