### ISSUE TITLE
integrity check

### ISSUE THREAD

**Issue by PF4Public** [munin-monitoring/munin#588]
Not certain on where to post: here or at rrdtool, correct me if I'm wrong.
After some minor filesystem corruption I notice that munin-graph taker forever to complete. Running it as munin-user with --debug flag shows, that it hangs after (or in the middle of) calling rrdtool on certain files. Deleting those files allows munin-graph to proceed further until another corrupted (I suppose) file is encountered.
Comparing healthy (that is the file, which does not hang munin-graph) and corrupted one gives some clues.
Healthy file mostly contains `<!-- 2015-10-31 02:50:00 MSK / 1446249000 --> <row><v>0.0000000000e+00</v></row>`, `<!-- 2015-10-31 00:15:00 MSK / 1446239700 --> <row><v>NaN</v></row>` and various `<!-- 2015-09-30 19:00:00 MSK / 1443628800 --> <row><v>3.8571428571e-04</v></row>`. Corrupted one however has amount of really weird numbers like `<!-- 2015-10-29 14:25:00 MSK / 1446117900 --> <row><v>3.0774343304e-308</v></row>`, which I believe provokes hung condition.

This is more like a feature request for rrd integrity test rather then bug report, since filesystem corruption is beyond the scope of munin.
Again, if I'm wrong, advice me on wording for filling this for rrdtool, as I'm not certain on how munin-rrdtool interface implemented.

**Comment by dipohl** [comment]
Munin uses the "The Perl RRDtool bindings". Your enhancement request should go to RRD-Tools Developer.
