### ISSUE TITLE
munin-asyncd returning no values, creating lot of warning emails

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#597]
Sometimes munin-asyncd can't fetch values, creating a lot of OK-UNKNOWN-OK-... emails. Munin-users mailing list has a nice explanation about the problem:

http://sourceforge.net/p/munin/mailman/message/34631236/

My old patch for this:

http://sourceforge.net/p/munin/mailman/message/34631328/

My patch is not the real solution but only works-for-me kludge. I think this bug is still valid in 2.999.x too but I can't test it.

**Comment by steveschnepp** [comment]
Good catch. That said, I added some spool file locking in 2.999.x, so i'm curious if one could reproduce it there.

**Comment by sumpfralle** [comment]
This was probably fixed by a48026ab615ff9938e521230e2bb27bd7c2b2224 (since 2.0.43).
