### ISSUE TITLE
Don't show detailed graph

### ISSUE THREAD

**Issue by stefanocog** [munin-monitoring/munin#601]
Hi, i have an architecture master / slave, it work but don't show detailed/cgi graph, when open the image i have:
```
Software error:
Can't open /var/log/munin/munin-cgi-graph.log (Permission denied) at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender/File.pm line 103.
```
The file `/var/log/munin/munin-cgi-graph.log` not exists, how can set munin to create this log files?

**Comment by dipohl** [comment]
Check the ownership and directory attributes for /var/log/munin and give owner munin create permission to that directory.

**Comment by stefanocog** [comment]
The directory has a right permission:

-rw-r-----   1 munin munin      0  5 dic 03.28 munin-graph.log
-rw-r-----   1 munin munin  38080 29 nov 03.31 munin-graph.log-20151129.gz
-rw-r-----   1 munin munin  38156 30 nov 03.45 munin-graph.log-20151130.gz
-rw-r-----   1 munin munin  37239  1 dic 03.26 munin-graph.log-20151201.gz
-rw-r-----   1 munin munin  37180  2 dic 03.05 munin-graph.log-20151202.gz
-rw-r-----   1 munin munin  37739  3 dic 03.05 munin-graph.log-20151203.gz
-rw-r-----   1 munin munin  37814  4 dic 03.05 munin-graph.log-20151204.gz
-rw-r-----   1 munin munin  23292  4 dic 17.35 munin-graph.log-20151205.gz
-rw-r-----   1 munin munin      0  5 dic 03.28 munin-html.log
-rw-r-----   1 munin munin   6664 29 nov 03.30 munin-html.log-20151129.gz
-rw-r-----   1 munin munin   6605 30 nov 03.45 munin-html.log-20151130.gz
-rw-r-----   1 munin munin   6547  1 dic 03.25 munin-html.log-20151201.gz
-rw-r-----   1 munin munin   6544  2 dic 03.05 munin-html.log-20151202.gz
-rw-r-----   1 munin munin   6756  3 dic 03.05 munin-html.log-20151203.gz
-rw-r-----   1 munin munin   6713  4 dic 03.10 munin-html.log-20151204.gz
-rw-r-----   1 munin munin   4149  4 dic 17.35 munin-html.log-20151205.gz
-rw-r-----   1 munin munin      0  5 dic 03.28 munin-limits.log
-rw-r-----   1 munin munin   2372 29 nov 03.30 munin-limits.log-20151129.gz
-rw-r-----   1 munin munin   2386 30 nov 03.45 munin-limits.log-20151130.gz
-rw-r-----   1 munin munin   2345  1 dic 03.25 munin-limits.log-20151201.gz
-rw-r-----   1 munin munin   2309  2 dic 03.05 munin-limits.log-20151202.gz
-rw-r-----   1 munin munin   2373  3 dic 03.05 munin-limits.log-20151203.gz
-rw-r-----   1 munin munin   2398  4 dic 03.10 munin-limits.log-20151204.gz
-rw-r-----   1 munin munin   1639  4 dic 17.35 munin-limits.log-20151205.gz
-rw-r-----   1 munin munin      0  5 dic 03.28 munin-update.log
-rw-r-----   1 munin munin 356774 29 nov 03.35 munin-update.log-20151129.gz
-rw-r-----   1 munin munin 352470 30 nov 03.45 munin-update.log-20151130.gz
-rw-r-----   1 munin munin 346603  1 dic 03.30 munin-update.log-20151201.gz
-rw-r-----   1 munin munin 345905  2 dic 03.05 munin-update.log-20151202.gz
-rw-r-----   1 munin munin 351089  3 dic 03.05 munin-update.log-20151203.gz
-rw-r-----   1 munin munin 353713  4 dic 03.10 munin-update.log-20151204.gz
-rw-r-----   1 munin munin 212347  4 dic 17.35 munin-update.log-20151205.gz

I need create the file manually?

Il 05/12/2015 19:34, dipohl ha scritto:

**Comment by dipohl** [comment]
Sorry, my first answer was not fully correct. Log Directory has to allow creation of files by cgi-process owner.

I looked it up on my Munin-Master now. 
  drwxrwxr-x. 2 apache munin 4096 Dec  5 19:55 /var/log/munin

and both logfiles have owner apache (cgi is processed from there..)

  -rw-r--r--. 1 apache apache   50796 Dec  4 11:39 munin-cgi-html.log
  -rw-r--r--. 1 apache apache 7289854 Jul 29 15:58 munin-cgi-graph.log

Although the last one seems not to be used any longer.. (?)

Instead I find a current:

  -rw-r-----  1 munin  munin    10670 Dec  5 19:50 munin-graph.log

with only dummy report entries of this sort:

  2015/12/05 20:05:24 [INFO] graphing is cgi, do nothing

I use munin-2.0.25-2.el6.noarch with cgi-graphing enabled.

**Comment by stefanocog** [comment]
Ok thanks, i resolved with righ permission to /var/log/munin directory

chwon apache.munin /var/log/munin

Il 05/12/2015 20:09, dipohl ha scritto:
