### ISSUE TITLE
`users` plugin not working on Debian 4 w/ munin-node 1.2.5

### ISSUE THREAD

**Issue by MrMitch** [munin-monitoring/munin#613]
Hi,

I'm trying to enable the users plugin on a Debian 4.0. I copied the [`users` file from this repo](https://github.com/munin-monitoring/munin/blob/devel/plugins/node.d/users) to `/usr/share/munin/plugins/users` and created a symlink pointing to this file in `/etc/munin/plugins/users`.

The plugins doesn't work and I get the following logs in `/var/log/munin/munin-node.log`: 

```
Can't locate Munin/Plugin.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.8.8 /usr/local/share/perl/5.8.8 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.8 /usr/share/perl/5.8 /usr/local/lib/site_perl .
) at /etc/munin/plugins/users line 46.
BEGIN failed--compilation aborted at /etc/munin/plugins/users line 46.
2016/01/05-16:20:16 Plugin "users" exited with status 512. ----
```

Here are some information about the system : 

### perl version

```
tomcat:~# perl --version
This is perl, v5.8.8 built for i486-linux-gnu-thread-multi
```

### munin-node version

```
tomcat:~# munin-node --version
munin-node (munin-node) version 1.2.5.
```

### kernel version
```
tomcat:~# uname -srvo
Linux 2.6.18-5-686 #1 SMP Tue Dec 18 21:24:20 UTC 2007 GNU/Linux
```

**Comment by chteuchteu** [comment]
Since `users` plugin wasn't shipped with munin-node v1.2.5, it may not be compatible. (ping @steveschnepp or @ssm just to be sure)

The best way to achieve this would be to recreate this plugin by mimicking its behavior (starting from a similar one).

**Comment by ssm** [comment]
You could add the Munin/Plugin.pm to your perl load path from a later munin release, if you want to use plugins which need it. It may work, it may not. :)

To see your load path:

    perl -e 'print join "\n", @INC ;' 

(Choose a /usr/local/ directory to avoid stepping on the toes of dpkg)

Try using Plugin.pm from https://github.com/munin-monitoring/munin/tree/devel/lib/Munin

**Comment by MrMitch** [comment]
Thanks, I'll try that and keep you posted.

**Comment by MrMitch** [comment]
I've added the `lib/Munin/Plugin.pm` and `lib/Munin/Common/Defaults.pm.PL` files, but now the compilation fails because of the `use Module::Build;` line in [lib/Munin/Common/Defaults.pm.PL](https://github.com/munin-monitoring/munin/blob/devel/lib/Munin/Common/Defaults.pm.PL#L9) and I can't find that file in the repo.
