### ISSUE TITLE
2.999.2: libfile-readbackwards-perl is not installed

### ISSUE THREAD

**Issue by chteuchteu** [munin-monitoring/munin#625]
The `libfile-readbackwards-perl` package is required for munin-node to be started but does not seem to be installed with munin-node:

    # service munin-node status
    Can't locate File/ReadBackwards.pm in @INC

**Comment by ssm** [comment]
Build.PL lists File::ReadBackwards as a dependency.

I see File::ReadBackwards used is in plugins/node.d/munin_stats, and munin-node should be able to run without that, and even if that plugin fails to run.

If you run from source and install with perl Build.PL [...], the output should list any missing dependencies at the very top.

If this is from packages, I would like the package version to reproduce.

**Comment by chteuchteu** [comment]
I installed `munin` & `munin-node` from your repository (v. 2.999.2) and it yelled this issue.
It seems that the package wasn't installed during the install

What exactly do you need to fix this?

**Comment by steveschnepp** [comment]
Recent version of the deb package are ok. Closing it.
