### ISSUE TITLE
2.999.2: The navigation panel on the left should be hideable

### ISSUE THREAD

**Issue by shapirus** [munin-monitoring/munin#636]
Feature request: the vertical navigation panel on the left should be able to be toggled on and off. It is not always needed, but it always occupies a significant portion of the precious display space which can be well used by the graphs instead (with SVG or hi-res PNG graphs enabled and the infinitely stretchable graphs patch applied).

**Comment by chteuchteu** [comment]
+1, we should auto-hide the navigation panel when there isn't enough space to display two graphs side by side
It should be togglable with a button on the left of the toolbar: we would then remove the current behavior (displaying a full-width toggle under the toolbar on mobiles)
