### ISSUE TITLE
example Apache subdirectory configuration

### ISSUE THREAD

**Issue by azrdev** [munin-monitoring/munin#645]
The current documentation includes an example for [apache using VirtualHost](http://guide.munin-monitoring.org/en/stable/example/webserver/apache-virtualhost.html) - however, hosting munin in a subdirectory on the server (e.g. because VirtualHosts are not available) is not trivial. Please add an example config for that.

**Comment by chteuchteu** [comment]
It depends on what's available on your server. Are you trying to run munin on a mutualized hosting?
Symlinking `/var/cache/munin/www/` => `/var/www/munin` should be enough actually

Don't hesitate to contribute to the documentation if you find a suitable solution.

**Comment by azrdev** [comment]
@chteuchteu I've a standalone "root" server in a private LAN: Full access for me, but no domain name(s), only local hostnames. The config should work with pure IPs, too.

---

I've got it to work now. Before adding it to the examples, though, someone more expert with munin and apache configs should look through it.

OS: Fedora 22
Munin packets (from system repos): `munin-2.0.25-2`, `munin-cgi-2.0.25-2` (munin-httpd is not packaged)

`/etc/munin/munin.conf`:
~~~
graph_strategy cgi
cgiurl_graph /munin-cgi/munin-cgi-graph # packet default
html_strategy cgi
~~~

`/etc/httpd/conf.d/munin-cgi.conf`:
~~~
<Location /munin>
    RewriteEngine On
    RewriteRule /munin/static/(.*) /var/www/html/munin/static/$1 [L]
    RewriteRule /munin/(.*) /cgi-bin/munin-cgi-html/$1
    RewriteRule /cgi-bin/munin-cgi-html$ /cgi-bin/munin-cgi-html/
</Location>

# the following lines are again package defaults

    # Ensure we can run (fast)cgi scripts
    <Directory "/var/www/cgi-bin">
        Options +ExecCGI
        <IfModule mod_fcgid.c>
            SetHandler fcgid-script
        </IfModule>
        <IfModule !mod_fcgid.c>
            SetHandler cgi-script
        </IfModule>
    </Directory>
~~~

`/var/www/html/munin` contains nothing but the `static/` directory from the package. All other content (html pages and graphs) are generated by CGI.

**Comment by chteuchteu** [comment]
This configuration looks correct indeed, but If @ssm or @steveschnepp could confirm, that would be great!

**Comment by sumpfralle** [comment]
The Munin Guide now contains some more examples: http://guide.munin-monitoring.org/en/latest/installation/webserver.html. Usually `/munin/` is used as a base path in these examples.

Most of the apache examples are framed within a `VirtualHost` section, but they could be placed anywhere, as well.
