### ISSUE TITLE
Add graph name to context passed to contact function

### ISSUE THREAD

**Issue by hugochinchilla** [munin-monitoring/munin#660]
It would be nice to be able to generate links to graph images when sending notifications from munin, so the important data could be seen at a glance witohut the need of entering munin dashboard.

Quoting @chteuchteu in #659:

> Unfortunately, we don't have access to the plugin name. All we have about it is the ${var:graph_title} - "Interface 1sec stats for eth0" instead of "if1sec_eth0" (or at least it is not documented)

If we had a variable like ${var:graph_name} we could generate urls by concatenating some data:

~~~
http://[munin base URL] / ${var:group}  /  ${var:host}  / ${var:graph_name}-day.png
~~~

**Comment by chteuchteu** [comment]
By browsing [/lib/Munin/Master/LimitsOld.pm](https://github.com/munin-monitoring/munin/blob/devel/lib/Munin/Master/LimitsOld.pm), I just found the `plugin` field. Could you check if it contains the right value please?

According to the code, here are the following available variables: `fields, plugin, graph_title, host, group, worst, worstid, recovered`.

**Comment by hugochinchilla** [comment]
@chteuchteu it works! thank you very much!

**Comment by chteuchteu** [comment]
I updated the documentation to include this information: [Let Munin croak alarm](http://guide.munin-monitoring.org/en/latest/tutorial/alert.html#group-or-host-or-plugin-related-variables)

**Comment by hugochinchilla** [comment]
:+1: @chteuchteu thanks for all your help :smile:
