### ISSUE TITLE
df, df_inode: device used as fieldname is not unique

### ISSUE THREAD

**Issue by ssm** [munin-monitoring/munin#671]
The device used as field name in these plugins are not unique. This leads to output like:

```
# munin-run df_inode 
_dev_vda1.value 22
udev.value 1
tmpfs.value 1
tmpfs.value 1
tmpfs.value 1
tmpfs.value 1
tmpfs.value 1
tmpfs.value 1
```

**Comment by sumpfralle** [comment]
Now the mountpoint is used for ambiguous (virtual) device names.
(the linux-oriented `df` plugin already had this feature)
