### ISSUE TITLE
2.999.2: munin-asyncd doesn't use cap dirtyconfig

### ISSUE THREAD

**Issue by shapirus** [munin-monitoring/munin#676]
$subj.

Here's a snapshot of environment variables saved by a plugin that gets queried by munin-asyncd:

```
MUNIN_PLUGSTATE=/var/lib/munin-node/plugin-state/root
MUNIN_PERL=/usr/bin/perl
MUNIN_STATEDIR=/var/run/munin
TERM=xterm
MUNIN_PLUGINUSER=root
MUNIN_LOGDIR=/var/log/munin
LC_ALL=C
MUNIN_HASSETR=yes
MUNIN_LIBDIR=/usr/share/munin
MUNIN_HTMLDIR=/var/www/munin
MUNIN_DEBUG=0
MUNIN_CAP_MULTIGRAPH=1
PATH=/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
LANG=C
FQDN=munin.hjdev
MUNIN_VERSION=2.999.2
SHLVL=2
MUNIN_MASTER_IP=127.0.0.1
MUNIN_SPOOLDIR=/var/spool/munin
MUNIN_DBDIR=/var/lib/munin
MUNIN_CGITMPDIR=/var/cache/munin
MUNIN_CONFDIR=/etc/munin
MUNIN_STATEFILE=/var/lib/munin-node/plugin-state/root/test-127.0.0.1
MUNIN_USER=root
MUNIN_GROUP=root
_=/usr/bin/env
```

No MUNIN_CAP_DIRTYCONFIG, as we can see.

**Comment by shapirus** [comment]
There's possibly a fix at https://github.com/steveschnepp/munin/commit/7b3588f38be506abcd7bf513315e80bb656e6090

**Comment by bjoe2k4** [comment]
Can this finally be merged (and backported)? This is such a trivial fix, yet adds so much pain...

**Comment by steveschnepp** [comment]
For merged, it's done. For backporting, I'm quite reluctant to add it right away.

**Comment by bjoe2k4** [comment]
Thanks! I see no obvious reason not to backport it right away. There is no harm other than additional (configured) plugins adding to the spoolfetched data. In order for this feature to be tested well, v3.0 stable needs to be out.
If it helps, I was manually patching my v2 installation with this patch and it is working for months now without complications.
