### ISSUE TITLE
graph_width generated by config in diskstats plugin -- issue if graph_width is changed remotely on the graphing server

### ISSUE THREAD

**Issue by alankila** [munin-monitoring/munin#682]
I was patching munin locally to accommodate high-DPI screens. On a retina screen, each pixel is duplicated and images rendered at 50 % size will use the full native resolution of the screen. This basically means that I patched the style-new.css to perform "img { zoom: 0.5; }", and then duplicated the defaults in graph_width and graph_height to 800 and 350, respectively.

Unfortunately the diskstats plugin assumes that the graph_width parameters has the value 400px unless otherwise specified. This alone wouldn't be so bad, but the real issue is that it generates this graph_width into the config output, causing that particular plugin's graphs to render at half of the width of the others.

To close this bug, I'd suggest removing the graph_width output from the plugin's config so that users don't have to write config line like [diskstats] env.graph_width 800 on every machine that they are monitoring. In my case, this is over 10 machines, and I can imagine there are people with many more machines. I'd also argue it is an error to attempt to determine or make use of the graph width in any way through the plugin configuration. The graph_width is chosen and made use of by the machine rendering the graph -- the munin node reporting simply doesn't have this information.

Edit: unfinished sentence fixed.

**Comment by sumpfralle** [comment]
I agree, that it is not preferable to let the plugin organize and calculate the dimensions of its visual output.

The diskstats plugin is the only plugin in the "munin" repository, that uses the `graph_width` setting.
In the "munin-contrib" repository there are only six plugins with this approach.

Going forward to a wider variety of devices, I guess, this is today even worse, than it was some years ago.

Thus I changed the the diskstats plugin as follows:
* "trim_labels" was removed
* "graph_width" can have three states:
    * (default) undefined/empty: use default graph width (this may look ugly with long device names)
    * zero: automatically use a suitable graph width depending on the length of the device names
    * non-zero: use this specific graph width and trim labels, if necessary

I hope, this is a suitable fix for your situation.

**Comment by martok** [comment]
@steveschnepp Apologies for the "issue necromancy" and for being extremely unaware how the experimental/stable dev process here works, but it seems like this change never made it on the 2.x branch? Debian packages come without it including `munin-plugins-core (2.0.74-2)` from current sid. This is a bit confusing as the plugin gallery is generated from master, so the documentation and functionality don't match...
