### ISSUE TITLE
I want to draw only certain graph.

### ISSUE THREAD

**Issue by seosuhyun** [munin-monitoring/munin#689]
Hello, 

I'm use to munin and I want to draw only certain graph.
using "munin-graph", I can not draw a particular graph.

I use the command are as follows.

> sudo -u munin ./munin-graph --config /etc/munin/munin-test.conf --list-images --noday --noweek --month --noyear --nosumyear

I just want to month graph for one of the host graph.
but, configure file is not used, All of the data(/etc/munin/munin.conf) is the using. 

So, I need your help to find what I draw the part of the graph.

Thank you.

**Comment by kenyon** [comment]
I'm not sure exactly what you're trying to do. Drawing only the month graph for a certain plugin is not a supported feature, I think. If you haven't figured it out yet, try asking for help in our IRC channel #munin on irc.oftc.net. Thanks.
