### ISSUE TITLE
hddtemp_smartctl fails on a drive in standby

### ISSUE THREAD

**Issue by covex** [munin-monitoring/munin#690]
This what the plugin resports:

UNKNOWNs: sdb is unknown: Command /usr/sbin/smartctl -A --nocheck=standby /dev/sdb on drive
sdb failed: 512.  The plugin needs to have read permission on all monitored devices., sdd is
unknown: Command /usr/sbin/smartctl -A --nocheck=standby /dev/sdd on drive sdd failed: 512.  The
plugin needs to have read permission on all monitored devices..
        OKs: sda is 32.00, sdc is 33.00.

Both sbb and sdd are in standby. The plugin correctly uses "--nocheck=standby" however smartctl returns non zero exit code upon this on drive that is in standby.The plugin threats this as error:

 my $output = `$cmd`;
  if ($? ne 0) {
...
and prints this "incorrect" message.

**Comment by dipohl** [comment]
> Both sbb and sdd are in standby. The plugin correctly uses "--nocheck=standby" however smartctl returns non zero exit code upon this on drive that is in standby.The plugin threats this as error

I could reproduce it:
```
[root@niva smartmontools]# munin-run hddtemp_smartctl
sda.value 31
sdf.value U
sdf.extinfo Command /usr/sbin/smartctl -A --nocheck=standby /dev/sdf on drive sdf failed: 512.  The plugin needs to have read permission on all monitored devices.
[ERROR] Command /usr/sbin/smartctl -A --nocheck=standby /dev/sdf on drive sdf failed: 512.  The plugin needs to have read permission on all monitored devices.

```
I see two issues to fix here.

1. smartctl status is a bitmask. We should add a section like that from plugin smart_

```
Python Code
        if exit_status!=None :
            # smartctl exit code is a bitmask, check man page.
            num_exit_status=int(exit_status/256) # Python convention
            if int(log(num_exit_status,2))<=2 :  # bit code
                verboselog('smartctl cannot access S.M.A.R.T values on drive '+hard_drive+'. Command exited with code '+str(num_exit_status)+' (bit '+str(int(log(num_exit_status,2)))+')')
                verboselog(lastline[:-1])
            else :
                verboselog('smartctl exited with code '+str(num_exit_status)+' (bit '+str(int(log(num_exit_status,2)))+'). '+hard_drive+' may be FAILING RIGHT NOW!')
        else :
            num_exit_status=0

```
That plugin says in the same sitution (SLEEP Mode) with "verbose=True" 

```
[root@niva smartmontools]# munin-run smart_sdf
smart_sdf: plugins' UID: 0 / plugins' GID: 99
smart_sdf: Reading S.M.A.R.T values
smart_sdf: smartctl cannot access S.M.A.R.T values on drive sdf. Command exited with code 2 (bit 1)
smart_sdf: Device is in SLEEP mode, exit(2)
smart_sdf: Can't find any S.M.A.R.T values in smartctl output!
smart_sdf: Failed to get S.M.A.R.T values from drive. Try to recall previous S.M.A.R.T attributes for sdf
smart_sdf: Printing unknown values for all attributes in state file
smartctl_exit_status.value U

```
which gives a much better info on the case

smartctl man page on bit 1 in status code:

```
Bit 1: Device open failed, device did not return an IDENTIFY DEVICE struc‐
         ture, or device is in a low-power mode (see ´-n´ option above).

```
2nd issue to fix: Suppress output of error message in case bit 1 is set and $use_nocheck is not 0

**Comment by dipohl** [comment]
I opened a ticket in smartmontools Trac to address the issue _false alarm_ also on their side.
https://www.smartmontools.org/ticket/697#ticket

**Comment by dipohl** [comment]
I contributed a patch that improves the usability for users of this plugin by telling them smartctl exit code and warning message: https://github.com/munin-monitoring/munin/commit/5f6f39c52003464869fb114c3f58bf64a3370433 

Thanks to Lupe for review and help with Perl.

**Comment by dipohl** [comment]
Output in similar case as reported above is now:

`
# munin-run hddtemp_smartctl
sda.value 35
sdf.value U
sdf.extinfo Command '/usr/sbin/smartctl -A --nocheck=standby /dev/sdf' on drive sdf failed with exit(2)
`
