### ISSUE TITLE
Change Update Rate to One Minute

### ISSUE THREAD

**Issue by fenichelar** [munin-monitoring/munin#698]
OS: Ubuntu 14.04
Munin: 2.0.19 (I believe, installed through apt-get)
I am running Munin to monitor one server only, master and node is the same.

I am having some trouble changing the update rate to 60 seconds. I changed both the `munin` and `munin-node` cron tasks to run every minute. I put `update_rate 60` in `my munin.conf`. The graphs are saying that were updated every minute but I am only getting one value for every 5 minute period. Did I miss something? Thanks.

**Comment by ssm** [comment]
This is not trivial, but it is possible.

http://software.danielwatrous.com/increase-munin-resolution-to-one-minute/ has an answer to the configuration question.

Munin does not change already existing RRD files, but   http://dieter.plaetinck.be/post/rrdtool_updating_rra_settings_and_keeping_your_collected_data/ looks promising.

**Comment by fenichelar** [comment]
I followed those exact steps, it did not work. My existing data is still displayed.

**Comment by fenichelar** [comment]
What I am saying is the cron change seems to have worked but the `update_rate 60` and `graph_data_size custom 1d, 1m for 1w, 5m for 1t, 15m for 1y` did not do anything. I tried placing them in both `munin.conf` and `munin-node.conf`.

**Comment by kitatek** [comment]
My understanding is the update_rate is to be set SELECTIVELY by plugin and node. Have you changed it on the master server config ?

**Comment by mailinglists35** [comment]
> 
> 
> My understanding of [the doc](http://guide.munin-monitoring.org/en/latest/plugin/supersampling.html#overview) is the update_rate is to be set SELECTIVELY by plugin and node. Have you changed it on the master server config ?

I have update_rate 60 in /etc/munin/conf.d/local.conf
I run a [custom plugin](https://github.com/mooondark/munin-iperf) from cron once per minute
I run munin-update once per minute from cron
but
what does it mean and how do you "change it on the node"?
**it still does not update once per minute...!**

oracle linux 7.5 and munin from epel
munin-node-2.0.63-1.el7.noarch
munin-2.0.63-1.el7.noarch
munin-common-2.0.63-1.el7.noarch
munin-cgi-2.0.63-1.el7.noarch
munin-apache-2.0.63-1.el7.noarch


rrdtool info /var/lib/munin/localhost/localhost-iperf-up-g.rrd

filename = "/var/lib/munin/localhost/localhost-iperf-up-g.rrd"
rrd_version = "0003"
**step = 300**

**Comment by sumpfralle** [comment]
I think, you need to change the [RRD resolution](http://guide.munin-monitoring.org/en/latest/advanced/custom-rrd-sizing.html) of the relevant (all?) graphs. This option is only applied, if the RRD file does not exist, yet.

**Comment by mailinglists35** [comment]
http://guide.munin-monitoring.org/en/latest/advanced/custom-rrd-sizing.html is total cryptic to my understanding.

is there anywhere on earth a basic full working example of munin cgi with 1 minute graphs?

**Comment by mailinglists35** [comment]
I no longer understand what I am doing. but it seems now it produces step 60 rrd files after deleting the rrd

I've put this into  /etc/munin/munin-node.conf and /etc/munin/conf.d/local.conf, 

graph_data_size custom 1d, 1m for 1w, 5m for 1t, 15m for 1y
update_rate 60

````
# cat /etc/munin/conf.d/local.conf
# Example host tree with localhost node. Configure your nodes here.

graph_strategy cgi
cgiurl_graph /munin/graph
html_strategy cgi
graph_data_size custom 1d, 1m for 1w, 5m for 1t, 15m for 1y
update_rate 60
[localhost]
    address 127.0.0.1
    use_node_name yes
    iperf.update_rate 60
````

````
tail -2 /etc/munin/munin-node.conf
graph_data_size custom 1d, 1m for 1w, 5m for 1t, 15m for 1y
update_rate 60
````

**Comment by sumpfralle** [comment]
> is there anywhere on earth a basic full working example of munin cgi with 1 minute graphs?

I am not aware of such a description. You are more than welcome to [contribute](https://github.com/munin-monitoring/munin/tree/master/doc) it!

> I no longer understand what I am doing. but it seems now it produces step 60 rrd files after deleting the rrd

Your approach looks reasonable to me. Which part of it is specifically confusing for you? Do you have any hints for improvements?
