### ISSUE TITLE
Varnish Memory Usage

### ISSUE THREAD

**Issue by bulewold** [munin-monitoring/munin#700]
Hello, So I've been using Munin service monitor for a while and recently after installing Varnish to my dedicated server, i noticed that Memory usage is blank.  It has many charts under Varnish such as 'backend traffic', 'hit rates' and etc... and it all works great, displaying data.  But Memory is not.  Tried uninstall & reinstall munin to newest version but this did not change.

any idea what we can do to fix this?
Thank you.

**Comment by kenyon** [comment]
Did you figure this out? If not, ask for help in our IRC channel #munin on irc.oftc.net. We will certainly need more information. Thanks.
