### ISSUE TITLE
error on httpd monitoring

### ISSUE THREAD

**Issue by sutiyonodoang** [munin-monitoring/munin#701]
Dear All,

i'v a problem when activate apache plugin.
Status-server is activated
when run command munin-node-configure --suggest, on apache show liek this :  

apache_accesses            | yes  | no [Port 80: Authorization Required]
apache_processes           | yes  | no [Port 80: Authorization Required]
apache_volume              | yes  | no [Port 80: Authorization Required]

munin version 2.0, centos 6.5, httpd 2.2

what configuration is wrong?

**Comment by chteuchteu** [comment]
Hello, 

The http://127.0.0.1/server-status URL must be accessible (without any authentication) locally from the node. You should set an exception to your authentication configuration for this specific URI (/server-status)

You can test if it will work from your node using lynx (the command line browser). 

Let us know if that works for you!

**Comment by sutiyonodoang** [comment]
Hello,

Thanks for your feedback.

i've try that solution, its work, but the page need to add username and
password, with same auth like to access url http://mydomain.com/munin

but when access from remote http://mydomain.com/server-status, that auth
didn't need. so, where is configuration setting that local auth, even i set
the configuration like default on other server it is work normaly.

**Comment by sutiyonodoang** [comment]
fyi to, i've add this script to every file apache_* under [apache_volume]
like:

env.url http://user:password@localhost/server-status?auto

there is still not work ...

**Comment by kenyon** [comment]
Did you get this working? If not, ask for help in our IRC channel #munin on irc.oftc.net. Thanks.

**Comment by sutiyonodoang** [comment]
body {
width: 100% !important;
}
.ReadMsgBody {
width: 100%;
}
.ExternalClass {
width: 100%;
}
body {
-webkit-text-size-adjust: none;
}
body {
margin: 0; padding: 0;
}
img {
border: 0 none; height: auto; line-height: 100%; outline: none; text-decoration: none;
}
body {
background-color: #f8f8f8;
}



















































Halo reply@reply.github.com, Sutiyono doang Memberikanmu Credits Sebesar Rp0!










Sutiyono doang

mengundangmu untuk bergabung ke Bukalapak. Dapatkan Credits Rp0 milikmu dengan bergabung dan berbelanja di Bukalapak sekarang. Caranya mudah:



Bergabung & Dapatkan Credits





Klik tombol "Bergabung & Dapatkan Credits" di atas dan daftarkan akunmu


Atau kamu bisa mendaftar dengan membuka website
Bukalapak,
kemudian klik tombol "Daftar" di bagian kanan atas halaman beranda Bukalapak


Pada saat mendaftar tersebut, masukkan kode

sutiyonodoang2tdb

pada kolom "Kode Referral"


Setelah itu kamu tinggal lakukan transaksi minimum Rp200.000 paling lambat 0 hari setelah mendaftar


Selamat! Kamu mendapatkan Credits Rp0




Yuk, daftar dan berbelanja sekarang!



bukalapak.com/rf/sutiyonodoang2tdb































Segala bentuk informasi seperti

nomor kontak, alamat e-mail, atau password kamu bersifat rahasia.

Jangan menginformasikan data-data tersebut kepada siapa pun, termasuk kepada pihak yang mengatasnamakan Bukalapak.



























Copyright © 2019 PT Bukalapak.com. All Rights Reserved


Plaza City View Lt. 1 Jl. Kemang Timur No. 22


Jakarta Selatan Indonesia 12510















































































Anda memperoleh e-mail ini karena keanggotaan Anda pada Bukalapak.com. Anda bisa mengubah
pengaturan notifikasi
kapan pun.









Harap jangan membalas e-mail ini, karena e-mail ini dikirimkan secara otomatis oleh sistem.
