### ISSUE TITLE
Munin doesn't generate html files

### ISSUE THREAD

**Issue by michaelvoorjans** [munin-monitoring/munin#704]
hi

i'm trying to install munin master in a docker container with the Ubuntu 14.04 image. But munin doesn't generate the html files for the webinterface in /var/cache/munin/www.The owner & rights are good from the map & i have also changed the munin.conf & apache.conf

**Comment by chteuchteu** [comment]
Hi,

Could you check munin logs in /var/log/munin/? You should find an error in one of them depending on where the issue occurs.

**Comment by michaelvoorjans** [comment]
munin-node.log:
Process Backgrounded
2016/04/18-22:36:39 Munin::Node::Server (type Net::Server::Fork) starting! pid(2251)
Resolved [*]:4949 to [::]:4949, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 4949 on host :: with IPv6
Setting gid to "0 0"

munin-node-configure.log:
 Starting munin-node-configure --shell
ln -s '/usr/share/munin/plugins/cpu' '/etc/munin/plugins/cpu'
ln -s '/usr/share/munin/plugins/df' '/etc/munin/plugins/df'
ln -s '/usr/share/munin/plugins/df_inode' '/etc/munin/plugins/df_inode'
ln -s '/usr/share/munin/plugins/diskstats' '/etc/munin/plugins/diskstats'
ln -s '/usr/share/munin/plugins/entropy' '/etc/munin/plugins/entropy'
ln -s '/usr/share/munin/plugins/forks' '/etc/munin/plugins/forks'
ln -s '/usr/share/munin/plugins/fw_packets' '/etc/munin/plugins/fw_packets'
ln -s '/usr/share/munin/plugins/if_' '/etc/munin/plugins/if_eth0'
ln -s '/usr/share/munin/plugins/if_err_' '/etc/munin/plugins/if_err_eth0'
ln -s '/usr/share/munin/plugins/interrupts' '/etc/munin/plugins/interrupts'
ln -s '/usr/share/munin/plugins/irqstats' '/etc/munin/plugins/irqstats'
ln -s '/usr/share/munin/plugins/load' '/etc/munin/plugins/load'
ln -s '/usr/share/munin/plugins/memory' '/etc/munin/plugins/memory'
ln -s '/usr/share/munin/plugins/munin_stats' '/etc/munin/plugins/munin_stats'
ln -s '/usr/share/munin/plugins/netstat' '/etc/munin/plugins/netstat'
ln -s '/usr/share/munin/plugins/open_files' '/etc/munin/plugins/open_files'
ln -s '/usr/share/munin/plugins/open_inodes' '/etc/munin/plugins/open_inodes'
ln -s '/usr/share/munin/plugins/proc_pri' '/etc/munin/plugins/proc_pri'
ln -s '/usr/share/munin/plugins/processes' '/etc/munin/plugins/processes'
ln -s '/usr/share/munin/plugins/swap' '/etc/munin/plugins/swap'
ln -s '/usr/share/munin/plugins/threads' '/etc/munin/plugins/threads'
ln -s '/usr/share/munin/plugins/uptime' '/etc/munin/plugins/uptime'
ln -s '/usr/share/munin/plugins/users' '/etc/munin/plugins/users'
ln -s '/usr/share/munin/plugins/vmstat' '/etc/munin/plugins/vmstat'
The following errors were reported by munin-node-configure --shell
# The following plugins caused errors:
# hddtemp_smartctl:
#       Junk printed to stderr
# mysql_:
#       Non-zero exit during autoconf (2)
# ntp_:
#       Non-zero exit during autoconf (2)
# ntp_states:
#       Non-zero exit during autoconf (2)
# postfix_mailqueue:
#       Non-zero exit during autoconf (255)
# postgres_autovacuum:
#       Non-zero exit during autoconf (255)
# postgres_bgwriter:
#       Non-zero exit during autoconf (255)
# postgres_cache_:
#       Non-zero exit during autoconf (255)
# postgres_checkpoints:
#       Non-zero exit during autoconf (255)
# postgres_connections_:
#       Non-zero exit during autoconf (255)
# postgres_connections_db:
#       Non-zero exit during autoconf (255)
# postgres_locks_:
#       Non-zero exit during autoconf (255)
# postgres_oldest_prepared_xact_:
#       Non-zero exit during autoconf (255)
# postgres_prepared_xacts_:
#       Non-zero exit during autoconf (255)
# postgres_querylength_:
#       Non-zero exit during autoconf (255)
# postgres_scans_:
#       Non-zero exit during autoconf (255)
# postgres_size_:
#       Non-zero exit during autoconf (255)
# postgres_transactions_:
#       Non-zero exit during autoconf (255)
# postgres_tuples_:
#       Non-zero exit during autoconf (255)
# postgres_users:
#       Non-zero exit during autoconf (255)
# postgres_xlog:
#       Non-zero exit during autoconf (255)
# proc:
#       In family 'auto' but doesn't have 'autoconf' capability
# sendmail_mailqueue:
#       Non-zero exit during autoconf (255)
# sendmail_mailstats:
#       Non-zero exit during autoconf (255)
# sendmail_mailtraffic:
#       Non-zero exit during autoconf (255)
# smart_:
#       Non-zero exit during autoconf (127)
# tomcat_:
#       Non-zero exit during autoconf (127)
# varnish_:
#       Non-zero exit during autoconf (2)

**Comment by chteuchteu** [comment]
Everything seems to be OK here.
Could you check munin-html.log?

**Comment by michaelvoorjans** [comment]
the munin-html.log is empty

**Comment by chteuchteu** [comment]
This seems to be a configuration problem. Could you [join us on IRC](http://munin-monitoring.org/wiki/HowToGetHelp) and explain your issue? It will be easier to diagnose.

I'm closing this issue, don't hesitate to reopen it if necessary.

**Comment by michaelvoorjans** [comment]
solution:
run this command in the docker container: cron run munin-cron
