### ISSUE TITLE
MySQL 5.7 error

### ISSUE THREAD

**Issue by Angristan** [munin-monitoring/munin#707]
Hello, 

I updated my MySQL server to 5.7 and MySQL graphs aren't generated anymore. In the logs I have this multiple times : 

```
2016/05/08-15:50:02 [1647] Error output from mysql_queries:
2016/05/08-15:50:02 [1647]      mysqladmin: unable to show status; error: 'Table 'performance_schema.global_status' doesn't exist'
```

What can I do ? 

I found this https://dev.mysql.com/doc/refman/5.7/en/performance-schema-variable-table-migration.html

**Comment by maxbarry** [comment]
This may be caused by a failed MySQL upgrade, in which case it has nothing to do with Munin.

See: http://stackoverflow.com/questions/31967527/table-performance-schema-session-variables-doesnt-exist

**Comment by Angristan** [comment]
I had the same problem on a fresh install.

**Comment by sumpfralle** [comment]
Is this still an issue?
Which munin version do you use?

**Comment by Angristan** [comment]
I use mariadb now, no more issues
