### ISSUE TITLE
support associative array for plugins

### ISSUE THREAD

**Issue by drzraf** [munin-monitoring/munin#712]
`key => value` is very useful way to pass configuration to plugin.
Currently if a graph can draw lines according to configuration and that each line depends on two parameters then it's painful to implement and configure it correctly.

Some example:

```
filetype=>title
regexp=>human-name
ratio=>thredshold
```

Currently you need to do this:

```
env.filetypes jpg css js
env.filenames jpeg stylesheet javascript
```

even worse:

```
# define the environment variables defined
env.known_curves games work vacations
env.title_games Games
env.setting_games x+3
env.title_work Working ours
env.setting_work /^work/
...
```

That's just one example of this common pattern.
Is there plan of improving the way configuration can pass data-structure a bit more elaborate while simplifying the configuration of the most powerful plugins?

thanks

**Comment by darac** [comment]
I don't think this needs to be part of munin itself. As far as I know, there's nothing stopping you doing, say:

    env.mappings jpg=jpeg css=stylesheet js=javascript

and then, in your plugin, something like:

    my %mappings;
    if (exists $ENV{mappings}){
        foreach (split ' ', $ENV{mappings}) {
            my ($key, $value) = split /=/;
            $mappings{$key} = $value;
        }
    }

_Perhaps_ there might be a niche for it in Munin::Plugin.

**Comment by kenyon** [comment]
Not sure exactly what you're trying to do here. If you can develop the feature and submit a pull request, that would be ideal. Otherwise, I don't really see the problem which you're trying to solve. Thanks.
