### ISSUE TITLE
MySQL 5.7 plugin for munin-node gives: "Wrong amount of autoconf"

### ISSUE THREAD

**Issue by mvl22** [munin-monitoring/munin#713]
On Ubuntu 16.04 LTS, MySQL generates an error:

```
root@machine:~# munin-node-configure --suggest --shell
# The following plugins caused errors:
[...]
# mysql_:
#   Wrong amount of autoconf
[...]
```

The relevant software was installed as follows:
1. Create a VM and do a bare installation of Ubuntu Server 16.04 LTS.
2. `apt-get install -y mysql-server-5.7 mysql-client-5.7`
3. Install Munin node with dependencies:

```
apt-get install -y libcache-perl libcache-cache-perl
# Add libdbi-perl as otherwise /usr/share/munin/plugins/mysql_ suggest will show missing DBI.pm; see: http://stackoverflow.com/questions/20568836/cant-locate-dbi-pm
apt-get install -y libdbi-perl
apt-get install -y munin-node
apt-get install -y munin-plugins-extra
# See: http://munin-monitoring.org/wiki/munin-node-configure
munin-node-configure --suggest --shell | sh
/etc/init.d/munin-node restart
```

**Comment by mvl22** [comment]
Is anyone able to clarify what "Wrong amount of autoconf" actually means, so I can see if I can at least try to debug things a bit?

**Comment by chteuchteu** [comment]
This comes from `parse_autoconf_response` in [`Plugin.pm#L222`](https://github.com/munin-monitoring/munin/blob/3552273136d8273db7d51574103d31af8b3a07a5/lib/Munin/Node/Configure/Plugin.pm#L222). It seems to be returned when autoconf returns a response != 1

[`# FIXME: not a good message`](https://github.com/munin-monitoring/munin/blob/3552273136d8273db7d51574103d31af8b3a07a5/lib/Munin/Node/Configure/Plugin.pm#L221): oh the irony ;)

You'll have to dig into mysql's plugin to see when its autoconf returns a value != 1

**Comment by mvl22** [comment]
Thanks for that, @chteuchteu.

By adding a few lines of debugging just afterwards, using
```
        my $line = shift @response;
        $self->log_error($line);
```

I was able to get `munin-node-configure --suggest --shell | sh` to show me the problem:

```
Wrong amount of autoconf
no (install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at (eval 12) line 3.
Perhaps the DBD::mysql perl module hasn't been fully installed,
or perhaps the capitalisation of 'mysql' isn't right.
Available drivers: DBM, ExampleP, File, Gofer, Proxy, Sponge.
)
```

**Comment by chteuchteu** [comment]
Glad it helped!
I'm quite disappointed that munin doesn't output/log this anywhere actually. @ssm / @steveschnepp ?

**Comment by sumpfralle** [comment]
The mysql-plugin related problem was solved (by installing its dependencies).

Thus I moved the missing error output to a separate issue #1043.
