### ISSUE TITLE
Could not open plugin configuration directory: Permission denied at /usr/share/perl5/Munin/Node/Service.pm line 110

### ISSUE THREAD

**Issue by FAWTS** [munin-monitoring/munin#717]
Hello,

I'm writting a plugin to read CPU speed on Intel pstate CPU. I'm running on Ubuntu 16.04.

The plugin is : 

`#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

cpuspeed - Plugin to monitor CPU speed

=head1 APPLICABLE SYSTEMS

Linux systems with a working CPU speed governor/stats kernel module
that can be accessed through the /sys filesystem.

=head1 CONFIGURATION

None needed by default.

You can set one environment variable to modify the plugins behaviour:

  [cpuspeed]
     env.scaleto100 1

Show the frequency as a percentage instead of absolute frequency.  If
set the plugin sets up a CDEF to change the speed in Hz to percent.

If you set or unset this the whole time series will be shown in the
same way, either as Hz or percent (as the graphs are updated).

=head1 INTERPRETATION

The plugin shows the average CPU speed in the measurement period as
represented by /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq.

This is a counter plugin and represents the average.  Many cpuspeed
plugins reports the "instant" CPU speed at the time the plugin runs.
This is not representative for this metric.

=head1 BUGS

Nah.

=head1 AUTHOR

Nicolai Langfeldt

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. /usr/share/munin/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
    if [ -r /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq ] ; then
        echo yes
        exit 0
    else
        echo "no (missing /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq)"
        exit 0
    fi
fi

if [ "$1" = "config" ]; then
    echo graph_title CPU frequency scaling
    echo graph_args --base 1000
    echo graph_info This graph shows the average speeds at which the CPUs are running
    echo graph_category system

    if [ "$scaleto100" = "yes" ]; then
        echo "graph_vlabel %"
        echo "graph_scale no"
    else
        echo "graph_vlabel Hz"
    fi

    for c in /sys/devices/system/cpu/cpu[0-9]*; do
        N=${c##*/cpu}

        echo "cpu$N.label CPU $N"
        echo "cpu$N.type DERIVE"

        if [ -r $c/cpufreq/cpuinfo_max_freq ]; then

            MAXHZ=$(cat $c/cpufreq/cpuinfo_max_freq)
            # Adding 10% to $MAXHZ, to cope with polling jitters
            # See bug D#615957
            MAXHZ=$(( $MAXHZ + $MAXHZ / 10 ))
            echo "cpu$N.max $MAXHZ"

            if [ "$scaleto100" = "yes" ]; then
                echo "cpu$N.cdef cpu$N,1000,*,$MAXHZ,/"
            else
                echo "cpu$N.cdef cpu$N,1000,*"
            fi
        fi

        if [ -r $c/cpufreq/cpuinfo_min_freq ]; then
            MINHZ=$(cat $c/cpufreq/cpuinfo_min_freq)
            echo "cpu$N.min $MINHZ"
        fi

        print_warning "cpu$N"
        print_critical "cpu$N"

    done
    exit 0;
fi

for c in /sys/devices/system/cpu/cpu[0-9]*; do
printf "cpu%d.value $(cat $c/cpufreq/cpuinfo_cur_freq)\n" ;

done`

I can manualy run it as root : 

`thomas@octopus2630:/usr/share/munin/plugins$ sudo munin-run cpuspeed
[sudo] Mot de passe de thomasÂ :
cpu0.value 1280898
cpu0.value 1230023
cpu0.value 1262421
cpu0.value 1382648
cpu0.value 1367523
cpu0.value 1310460
cpu0.value 1400093
cpu0.value 1268007
cpu0.value 1597750
cpu0.value 1209312
cpu0.value 1284937
cpu0.value 1218421
cpu0.value 1244718
cpu0.value 1264656
cpu0.value 1532093
cpu0.value 1200203
cpu0.value 1369242
cpu0.value 1200375
cpu0.value 1200117
cpu0.value 1200031
thomas@octopus2630:/usr/share/munin/plugins$ sudo munin-run cpuspeed --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /135/0/
# Setting /egid/euid/ to /135 135 0/0/
# Setting up environment
# About to run '/etc/munin/plugins/cpuspeed'
cpu0.value 1200031
cpu0.value 1277203
cpu0.value 1200546
cpu0.value 1250906
cpu0.value 1238531
cpu0.value 1369242
cpu0.value 1253828
cpu0.value 1255375
cpu0.value 1200460
cpu0.value 1389695
cpu0.value 1200546
cpu0.value 1665554
cpu0.value 1199945
cpu0.value 1277203
cpu0.value 1321890
cpu0.value 1314414
cpu0.value 1242054
cpu0.value 1253742
cpu0.value 1203125
cpu0.value 1199945
thomas@octopus2630:/usr/share/munin/plugins$ sudo munin-run cpuspeed config
graph_title CPU frequency scaling
graph_args --base 1000
graph_info This graph shows the average speeds at which the CPUs are running
graph_category system
graph_vlabel Hz
cpu0.label CPU 0
cpu0.type DERIVE
cpu0.max 3410000
cpu0.cdef cpu0,1000,*
cpu0.min 1200000
cpu1.label CPU 1
cpu1.type DERIVE
cpu1.max 3410000
cpu1.cdef cpu1,1000,*
cpu1.min 1200000
cpu10.label CPU 10
cpu10.type DERIVE
cpu10.max 3410000
cpu10.cdef cpu10,1000,*
cpu10.min 1200000
cpu11.label CPU 11
cpu11.type DERIVE
cpu11.max 3410000
cpu11.cdef cpu11,1000,*
cpu11.min 1200000
cpu12.label CPU 12
cpu12.type DERIVE
cpu12.max 3410000
cpu12.cdef cpu12,1000,*
cpu12.min 1200000
cpu13.label CPU 13
cpu13.type DERIVE
cpu13.max 3410000
cpu13.cdef cpu13,1000,*
cpu13.min 1200000
cpu14.label CPU 14
cpu14.type DERIVE
cpu14.max 3410000
cpu14.cdef cpu14,1000,*
cpu14.min 1200000
cpu15.label CPU 15
cpu15.type DERIVE
cpu15.max 3410000
cpu15.cdef cpu15,1000,*
cpu15.min 1200000
cpu16.label CPU 16
cpu16.type DERIVE
cpu16.max 3410000
cpu16.cdef cpu16,1000,*
cpu16.min 1200000
cpu17.label CPU 17
cpu17.type DERIVE
cpu17.max 3410000
cpu17.cdef cpu17,1000,*
cpu17.min 1200000
cpu18.label CPU 18
cpu18.type DERIVE
cpu18.max 3410000
cpu18.cdef cpu18,1000,*
cpu18.min 1200000
cpu19.label CPU 19
cpu19.type DERIVE
cpu19.max 3410000
cpu19.cdef cpu19,1000,*
cpu19.min 1200000
cpu2.label CPU 2
cpu2.type DERIVE
cpu2.max 3410000
cpu2.cdef cpu2,1000,*
cpu2.min 1200000
cpu3.label CPU 3
cpu3.type DERIVE
cpu3.max 3410000
cpu3.cdef cpu3,1000,*
cpu3.min 1200000
cpu4.label CPU 4
cpu4.type DERIVE
cpu4.max 3410000
cpu4.cdef cpu4,1000,*
cpu4.min 1200000
cpu5.label CPU 5
cpu5.type DERIVE
cpu5.max 3410000
cpu5.cdef cpu5,1000,*
cpu5.min 1200000
cpu6.label CPU 6
cpu6.type DERIVE
cpu6.max 3410000
cpu6.cdef cpu6,1000,*
cpu6.min 1200000
cpu7.label CPU 7
cpu7.type DERIVE
cpu7.max 3410000
cpu7.cdef cpu7,1000,*
cpu7.min 1200000
cpu8.label CPU 8
cpu8.type DERIVE
cpu8.max 3410000
cpu8.cdef cpu8,1000,*
cpu8.min 1200000
cpu9.label CPU 9
cpu9.type DERIVE
cpu9.max 3410000
cpu9.cdef cpu9,1000,*
cpu9.min 1200000`

But it fail as normal user : 

`thomas@octopus2630:/usr/share/munin/plugins$ munin-run cpuspeed --debug
Could not open plugin configuration directory: Permission denied at /usr/share/perl5/Munin/Node/Service.pm line 110.
`
line 110 looks like this : 

`
    # PATH should be *very* sane by default. Can be overrided via
    # config file if needed (Closes #863 and #1128).
    $ENV{PATH} = '/usr/sbin:/usr/bin:/sbin:/bin';

    if ($config->{sconffile}) {
        # only used by munin-run
        $config->parse_plugin_config_file($config->{sconffile});
    }
    else {
        $config->process_plugin_configuration_files();
    }
    $config->apply_wildcards(@plugins);

    return;
}`

I set the plugnin to run as root in /etc/munin/plugin-conf.d/munin-node : 

`[cpuspeed_pstate]
user root
group root`

Does anyone have an idea how to fix it ? Other plugins works fine.

Thank you very much.

**Comment by FAWTS** [comment]
What it is strange, it that I have the same error with ntp plugin, but it works fine : 

`thomas@octopus2630:/usr/share/munin/plugins$ munin-run uptime --debug
Could not open plugin configuration directory: Permission denied at /usr/share/perl5/Munin/Node/Service.pm line 110.`

`thomas@octopus2630:/usr/share/munin/plugins$ sudo munin-run uptime --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /135/65534/
# Setting /egid/euid/ to /135 135/65534/
# Setting up environment
# About to run '/etc/munin/plugins/uptime'
uptime.value 0.24`

And the graph is OK

**Comment by FAWTS** [comment]
Eventualy my plugin works!!!!!!!!!!!

I fixed right issues with 
`sudo munin-check cpuspeed_pstate`

I won't detail this as I'm not sure it was the root cause and it will depend of your linux distribution.

And the laste version of the plugin is : 

`#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

cpuspeed - Plugin to monitor CPU speed

=head1 APPLICABLE SYSTEMS

Linux systems with a working CPU speed governor/stats kernel module
that can be accessed through the /sys filesystem.

=head1 CONFIGURATION

None needed by default.

You can set one environment variable to modify the plugins behaviour:

  [cpuspeed]
     env.scaleto100 1

Show the frequency as a percentage instead of absolute frequency.  If
set the plugin sets up a CDEF to change the speed in Hz to percent.

If you set or unset this the whole time series will be shown in the
same way, either as Hz or percent (as the graphs are updated).

=head1 INTERPRETATION

The plugin shows the average CPU speed in the measurement period as
represented by /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq.

This is a counter plugin and represents the average.  Many cpuspeed
plugins reports the "instant" CPU speed at the time the plugin runs.
This is not representative for this metric.

=head1 BUGS

Nah.

=head1 AUTHOR

Nicolai Langfeldt

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

. /usr/share/munin/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
    if [ -r /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state ] ; then
        echo yes
        exit 0
    else
        echo "no (missing /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state)"
        exit 0
    fi
fi


if [ "$1" = "config" ]; then
    echo graph_title CPU frequency scaling
    echo graph_args --base 1000
    echo graph_info This graph shows the average speeds at which the CPUs are running
    echo graph_category system

    if [ "$scaleto100" = "yes" ]; then
        echo "graph_vlabel %"
        echo "graph_scale no"
    else
        echo "graph_vlabel Hz"

fi

    for c in /sys/devices/system/cpu/cpu[0-9]*; do
        N=${c##*/cpu}

        echo "cpu$N.label CPU $N"
        echo "cpu$N.type GAUGE"

        if [ -r $c/cpufreq/cpuinfo_max_freq ]; then

            MAXHZ=$(cat $c/cpufreq/cpuinfo_max_freq)
            # Adding 10% to $MAXHZ, to cope with polling jitters
            # See bug D#615957
            MAXHZ=$(( $MAXHZ + $MAXHZ / 10 ))
            echo "cpu$N.max $MAXHZ"

            if [ "$scaleto100" = "yes" ]; then
                echo "cpu$N.cdef cpu$N,1000,*,$MAXHZ,/"
            else
                echo "cpu$N.cdef cpu$N,1000,*"
            fi
        fi

        if [ -r $c/cpufreq/cpuinfo_min_freq ]; then
            MINHZ=$(cat $c/cpufreq/cpuinfo_min_freq)
            echo "cpu$N.min $MINHZ"
        fi

        print_warning "cpu$N"
        print_critical "cpu$N"

    done
    exit 0;
fi

for c in /sys/devices/system/cpu/cpu[0-9]*; do

        N=${c##*/cpu}

printf "cpu$N.value $(cat $c/cpufreq/cpuinfo_cur_freq)\n" ;

done`

I called the file `cpuspeed_pstate`

My first Munin plugin \o/

**Comment by FAWTS** [comment]
[cpuspeed_pstate.txt](https://github.com/munin-monitoring/munin/files/368075/cpuspeed_pstate.txt)

**Comment by yunal** [comment]
This is not an improvement. It shows a snapshot of the cpu frequency every time munin runs.  Since munin tends to put load on the host the current cpu frequency will tend to jump up if the machine is otherwise relatively low load. Therefore this plugin shows the cpu-frequency when munin runs rather than something that reflects the machines cpu speeds the previous 5 minutes. Or as the docs say

```
This is a counter plugin and represents the average.  Many cpuspeed
plugins reports the "instant" CPU speed at the time the plugin runs.
```
Which these changes undo.

The cumulative stats in the current plugin are more representative than a snapshot.

**Comment by sumpfralle** [comment]
Yes, indeed.

I read a bit more into https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717287 and https://bugzilla.kernel.org/show_bug.cgi?id=57941.

It seems that the CPU frequency handling for Intel-based CPUs switched with Linux 3.9 from the "acpi-cpufreq" module to the "intel_pstate" driver. This was probably an improvement in may areas, but it was also a regression with regards to the available frequency usage data.

Thus for all users of the "intel_pstate" driver there is only the option of tracking the current snapshot, since no averaging is available at all.

Thus I applied (based of @FAWTS contribution) optional handling of the "intel_pstate" data in ace9a23aa14a314828b4b8a34b8db3bbea3168ee.

**Comment by yunal** [comment]
I just discovered that the time in state feature was gone on my laptop yes. I had not arrived at the explanation yet.
