### ISSUE TITLE
Installing on CentOS 7

### ISSUE THREAD

**Issue by xtpclark** [munin-monitoring/munin#719]
Hello,

Not sure if this is the right place to ask, but I'm looking for instructions on installing the latest master 2.999.2 or better on CentOS 7 like it would be in a production environment.  I intend to pilot/test this outside of a sandbox environment.  Not necessarily looking for an RPM, but if one is available somewhere, that would be great.

Thank you,

Perry Clark

**Comment by ssm** [comment]
There should be packages for Centos 7 in the EPEL repository.

**Comment by ssm** [comment]
Ah, nevermind. For munin not-quite-version-3, I'm not sure where there are packages.  Sorry.
