### ISSUE TITLE
apache graph

### ISSUE THREAD

**Issue by alexandr2k** [munin-monitoring/munin#727]
Hello.

I don't see apache section in munin categories on page http://myhost.domain/munin.

The modules work:
# munin-node-configure --suggest|grep apac

apache_accesses            | yes  | yes
apache_processes           | yes  | yes
apache_volume              | yes  | yes

Apache log:
127.0.0.1 - - [16/Aug/2016:03:12:02 +0300] "GET /server-status?auto HTTP/1.1" 200 503 "-" "munin/2.0.19-3 (libwww-perl/6.05)"
127.0.0.1 - - [16/Aug/2016:03:12:04 +0300] "GET /server-status?auto HTTP/1.1" 200 504 "-" "munin/2.0.19-3 (libwww-perl/6.05)"
127.0.0.1 - - [16/Aug/2016:03:12:05 +0300] "GET /server-status?auto HTTP/1.1" 200 504 "-" "munin/2.0.19-3 (libwww-perl/6.05)"

Could you help me?

**Comment by kenyon** [comment]
Did you get this working? If not, ask for help in our IRC channel #munin on irc.oftc.net. Thanks.
