### ISSUE TITLE
Installation de Munin sur Redhat 7

### ISSUE THREAD

**Issue by aureller** [munin-monitoring/munin#729]
Bonjour,

J'essaie d'installer Munin sur un serveur Red Hat Enterprise Linux Server release 7.2
Mais je n'arrive pas à le faire l'installation.
Les erreurs sont multiples et diverses:
1) Problème de dépendance, même si j'en installe 1 à la main( via le lien de depôt rpm), il y en a d'autres.
2) Certains packages qui doivent être utilsés pour munin ne sont plus compatible avec red hat 7.2.
3) La configuration pour redhat: je n'ai pas trouvé d'installation qui se rapproche de redhat 7.2
4) L'arrêt/relance de munin se fait comment.

Merci beaucoup pour votre aide et pour votre diponibilité.

**Comment by lwandrebeck** [comment]
Bonjour Aureller,

Merci d’utiliser l’anglais si possible :)

Le dépôt epel http://fedoraproject.org/wiki/EPEL permet d’installer munin sans difficultés sur RHEL/CentOS/SL 7.

Pour l’arrêt et la relance de munin, c’est lié à apache (ou nginx fonction du serveur web que tu utilises).

**Comment by kenyon** [comment]
Did you get this working? If not, ask for help in our IRC channel #munin on irc.oftc.net. Thanks.
