### ISSUE TITLE
View graphs of hourly munin version 2.0.25

### ISSUE THREAD

**Issue by danitorres05** [munin-monitoring/munin#731]
hello, it would be possible to see the graphics of munin per hour?
I have installed version is 2.0.25.
Thank for the help.

**Comment by kenyon** [comment]
No, there is no way to make a separate hourly graph. You can use the zooming feature to look more closely at certain hours. Also, this may help: http://serverfault.com/questions/394878/can-munin-be-configured-to-display-hourly-graphs
