### ISSUE TITLE
Centos 7 - CPU Graph Update Problem

### ISSUE THREAD

**Issue by vincenzot1987** [munin-monitoring/munin#732]
Hello,

I have installed Munin from entos7 repository, but I have an strange issue.

The CPU graph is update for 3 or 4 days after that, the CPU graph sto to working and is impossible to see again the CPU stats.

For view again the CPU stats, I need to uninstall munin, remove all data files of old graph, and the CPU graph is generated again, but after 3 or 4 days, stop to works again.

I use munin from more of 5 years, with centos6, is the first time that I use munin on centos7, there is anything that I need to setup for CPU-Graph and Centos7?

Regards

**Comment by chteuchteu** [comment]
Hello,

Please provide last 25 lines of `munin-update.log` so we can investigate (it is located in `/var/log/munin/` directory)

**Comment by vincenzot1987** [comment]
Hello,

munin-update.log
2016/08/24 21:30:01 [INFO] starting work in 547221 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 21:30:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 21:30:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (2.38 sec)
2016/08/24 21:30:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 21:30:03 [INFO]: Munin-update finished (2.41 sec)
2016/08/24 21:35:01 [INFO]: Starting munin-update
2016/08/24 21:35:01 [INFO] starting work in 572663 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 21:35:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 21:35:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (1.94 sec)
2016/08/24 21:35:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 21:35:03 [INFO]: Munin-update finished (1.97 sec)
2016/08/24 21:40:01 [INFO]: Starting munin-update
2016/08/24 21:40:01 [INFO] starting work in 600553 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 21:40:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 21:40:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (1.96 sec)
2016/08/24 21:40:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 21:40:03 [INFO]: Munin-update finished (1.98 sec)
2016/08/24 21:45:01 [INFO]: Starting munin-update
2016/08/24 21:45:01 [INFO] starting work in 627946 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 21:45:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 21:45:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (1.92 sec)
2016/08/24 21:45:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 21:45:03 [INFO]: Munin-update finished (1.95 sec)
2016/08/24 21:50:01 [INFO]: Starting munin-update
2016/08/24 21:50:01 [INFO] starting work in 658268 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 21:50:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 21:50:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (1.92 sec)
2016/08/24 21:50:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 21:50:03 [INFO]: Munin-update finished (1.93 sec)
2016/08/24 21:55:01 [INFO]: Starting munin-update
2016/08/24 21:55:01 [INFO] starting work in 684131 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 21:55:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 21:55:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (1.90 sec)
2016/08/24 21:55:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 21:55:03 [INFO]: Munin-update finished (1.91 sec)
2016/08/24 22:00:01 [INFO]: Starting munin-update
2016/08/24 22:00:01 [INFO] starting work in 709611 for SERVER_NAME/127.0.0.1:4949.
2016/08/24 22:00:01 [INFO] node SERVER_NAME advertised itself as localhost.localdomain instead.
2016/08/24 22:00:03 [INFO]: Munin-update finished for node iltuohosting.it;SERVER_NAME (2.21 sec)
2016/08/24 22:00:03 [INFO] Reaping Munin::Master::UpdateWorker<iltuohosting.it;SERVER_NAME>.  Exit value/signal: 0/0
2016/08/24 22:00:03 [INFO]: Munin-update finished (2.25 sec)

munin-node.log
2016/08/24-22:00:02 [709612] Error output from uptime:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/uptime: line 4: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'uptime' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from uptime:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/uptime: line 4: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'uptime' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from swap:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/swap: line 4: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'swap' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from swap:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/swap: line 4: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'swap' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from load:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/load: line 4: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'load' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from load:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/load: line 4: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'load' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from cpu:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/cpu: line 3: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'cpu' exited with status 1/0.
2016/08/24-22:00:02 [709612] Error output from cpu:
2016/08/24-22:00:02 [709612]    /etc/munin/plugins/cpu: line 3: cannot create temp file for here-document: No such file or directory
2016/08/24-22:00:02 [709612] Service 'cpu' exited with status 1/0.
2016/08/24-22:02:23 Server closing!

If I restart the munin-node with "systemctl restart munin-node" the CPU graph start to works again.

I think that the problem is 

2016/08/24-22:00:02 [709612]    /etc/munin/plugins/cpu: line 3: cannot create temp file for here-document: No such file or directory

But the space on my server is free

df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       291G   32G  245G  12% /
devtmpfs         63G     0   63G   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G  4.1G   59G   7% /run
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/sda2       488M  184M  279M  40% /boot
/dev/sdb1       1.6T  762G  699G  53% /data
/dev/sdc1       2.0T 1013G  901G  53% /disk1
tmpfs            13G     0   13G   0% /run/user/0
tmpfs            13G     0   13G   0% /run/user/10538
tmpfs            13G     0   13G   0% /run/user/10460
tmpfs            13G     0   13G   0% /run/user/10497

**Comment by chteuchteu** [comment]
This log row seems to yell the issue:

    2016/08/24-22:00:02 [709612] /etc/munin/plugins/cpu: line 3: cannot create temp file for here-document: No such file or directory

Could you paste the content of `/etc/munin/plugins/cpu`?

**Comment by vincenzot1987** [comment]
Hello

this is the first line of the CPU plugins

=============================================
#!/usr/bin/sh
#
: <<=cut

=head1 NAME

cpu - Plugin to monitor CPU usage.

=head1 APPLICABLE SYSTEMS

All Linux systems

=head1 CONFIGURATION

The following is default configuration

  [cpu]
        env.HZ  100

See "BUGS" for a explanation of this setting.

=head2 EXAMPLE WARNING AND CRITICAL SETTINGS

You can also set warning and critical levels for each of the data
series the plugin reports.  The following environment variables are
used as default for all fields:

  env.warning
  env.critical

But each field can be controlled separately:

  env.system_warning
  env.system_critical

  env.user_warning
  env.user_critical

  env.nice_warning
  env.nice_critical

  env.idle_warning
  env.idle_critical

For some kernels there is also the following settings:
=============================================

**Comment by chteuchteu** [comment]
I'm not able to find this plugin in the munin's repository. Could you paste the whole script here? What you pasted previously is just the documentation header.

Once done, we'll be able to see where your error comes from.

**Comment by vincenzot1987** [comment]
#!/usr/bin/sh
#
: <<=cut

=head1 NAME

cpu - Plugin to monitor CPU usage.

=head1 APPLICABLE SYSTEMS

All Linux systems

=head1 CONFIGURATION

The following is default configuration

  [cpu]
	env.HZ	100

See "BUGS" for a explanation of this setting.

=head2 EXAMPLE WARNING AND CRITICAL SETTINGS

You can also set warning and critical levels for each of the data
series the plugin reports.  The following environment variables are
used as default for all fields:

  env.warning
  env.critical

But each field can be controlled separately:

  env.system_warning
  env.system_critical

  env.user_warning
  env.user_critical

  env.nice_warning
  env.nice_critical

  env.idle_warning
  env.idle_critical

For some kernels there is also the following settings:

  env.iowait_warning
  env.iowait_critical
  env.irq_warning
  env.irq_critical
  env.softirq_warning
  env.softirq_critical
  env.steal_warning
  env.steal_critical
  env.guest_warning
  env.guest_critical

=head1 INTERPRETATION

The plugin shows cpu usage in percent. In case of more than one core
it displays 100% for each core.

If a core is 100% busy there will be no "iowait" showing, that only
shows if the CPU has nothing else to do while it waits on IO.
Therefore a 100% busy core can hide a lot of iowait.  Please refer to
the IO latency and other disk related graphs for further information
about IO performance.

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf


=head1 VERSION

  $Id$

=head1 BUGS

Some combinations of hardware and Linux (probably only 2.4 kernels)
use 1000 units/second in /proc/stat corresponding to the systems
HZ. (see /usr/src/linux/include/asm/param.h). But Almost all systems
use 100 units/second and this is our default. Even if
Documentation/proc.txt in the kernel source says otherwise. - Finding
and fix by dz@426.ch

Otherwise none known

=head1 AUTHOR

Unknown

=head1 LICENSE

GPLv2

=cut


. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi

HZ=${HZ:-100}

extinfo=""

if egrep -q '^cpu +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+' /proc/stat; then
	extinfo="iowait irq softirq"
	if egrep -q '^cpu +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+' /proc/stat; then
		extextinfo="steal"
	fi
	if egrep -q '^cpu +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+' /proc/stat; then
		extextextinfo="guest"
	fi

fi

if [ "$1" = "config" ]; then

	NCPU=$(egrep '^cpu[0-9]+ ' /proc/stat | wc -l)
	if [ "$scaleto100" = "yes" ]; then
		graphlimit=100
	else
		graphlimit=$(($NCPU * 100))
	fi
	echo 'graph_title CPU usage'
	echo "graph_order system user nice idle" $extinfo
	echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit $graphlimit"
	echo 'graph_vlabel %'
	echo 'graph_scale no'
	echo 'graph_info This graph shows how CPU time is spent.'
	echo 'graph_category system'
	echo 'graph_period second'
	echo 'system.label system'
	echo 'system.draw AREA'
	echo 'system.min 0'
	echo 'system.type DERIVE'
	echo "system.info CPU time spent by the kernel in system activities" 
	echo 'user.label user'
	echo 'user.draw STACK'
	echo 'user.min 0'
	echo 'user.type DERIVE'
	echo 'user.info CPU time spent by normal programs and daemons'
	echo 'nice.label nice'
	echo 'nice.draw STACK'
	echo 'nice.min 0'
	echo 'nice.type DERIVE'
	echo 'nice.info CPU time spent by nice(1)d programs'
	echo 'idle.label idle'
	echo 'idle.draw STACK'
	echo 'idle.min 0'
	echo 'idle.type DERIVE'
	echo 'idle.info Idle CPU time'

	for field in system user nice idle; do
		print_adjusted_thresholds "$field" "$graphlimit"
	done

	if [ "$scaleto100" = "yes" ]; then
		echo "system.cdef system,$NCPU,/"
		echo "user.cdef user,$NCPU,/"
		echo "nice.cdef nice,$NCPU,/"
		echo "idle.cdef idle,$NCPU,/"
	fi
	if [ ! -z "$extinfo" ]
	then
		echo 'iowait.label iowait'
		echo 'iowait.draw STACK'
		echo 'iowait.min 0'
		echo 'iowait.type DERIVE'
		echo 'iowait.info CPU time spent waiting for I/O operations to finish when there is nothing else to do.'
		echo 'irq.label irq'
		echo 'irq.draw STACK'
		echo 'irq.min 0'
		echo 'irq.type DERIVE'
		echo 'irq.info CPU time spent handling interrupts'
		echo 'softirq.label softirq'
		echo 'softirq.draw STACK'
		echo 'softirq.min 0'
		echo 'softirq.type DERIVE'
		echo 'softirq.info CPU time spent handling "batched" interrupts'
		if [ "$scaleto100" = "yes" ]; then
			echo "iowait.cdef iowait,$NCPU,/"
			echo "irq.cdef irq,$NCPU,/"
			echo "softirq.cdef softirq,$NCPU,/"
		fi
		for field in iowait irq softirq; do
			print_adjusted_thresholds "$field" "$graphlimit"
		done
	fi

	if [ ! -z "$extextinfo" ]
	then
		echo 'steal.label steal'
		echo 'steal.draw STACK'
		echo 'steal.min 0'
		echo 'steal.type DERIVE'
		echo 'steal.info The time that a virtual CPU had runnable tasks, but the virtual CPU itself was not running'
		if [ "$scaleto100" = "yes" ]; then
			echo "steal.cdef steal,$NCPU,/"
		fi
		for field in steal; do
			print_adjusted_thresholds "$field" "$graphlimit"
		done
	fi

	if [ ! -z "$extextextinfo" ]
	then
		echo 'guest.label guest'
		echo 'guest.draw STACK'
		echo 'guest.min 0'
		echo 'guest.type DERIVE'
		echo 'guest.info The time spent running a virtual CPU for guest operating systems under the control of the Linux kernel.'
		if [ "$scaleto100" = "yes" ]; then
			echo "guest.cdef guest,$NCPU,/"
		fi
		for field in guest; do
			print_adjusted_thresholds "$field" "$graphlimit"
		done
	fi

	exit 0
fi

# Note: Counters/derive need to report integer values.  Also we need
# to avoid 10e+09 and the like %.0f should do this.

if [ ! -z "$extextextinfo" ]; then
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\niowait.value %.0f\nirq.value %.0f\nsoftirq.value %.0f\nsteal.value %.0f\nguest.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz, $6*100/hz, $7*100/hz, $8*100/hz, $9*100/hz, $10*100/hz }' < /proc/stat
elif [ ! -z "$extextinfo" ]; then
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\niowait.value %.0f\nirq.value %.0f\nsoftirq.value %.0f\nsteal.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz, $6*100/hz, $7*100/hz, $8*100/hz, $9*100/hz }' < /proc/stat
elif [ ! -z "$extinfo" ]; then
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\niowait.value %.0f\nirq.value %.0f\nsoftirq.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz, $6*100/hz, $7*100/hz, $8*100/hz }' < /proc/stat
else
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz }' < /proc/stat
fi

**Comment by vincenzot1987** [comment]
`#!/usr/bin/sh
#
: <<=cut

=head1 NAME

cpu - Plugin to monitor CPU usage.

=head1 APPLICABLE SYSTEMS

All Linux systems

=head1 CONFIGURATION

The following is default configuration

  [cpu]
	env.HZ	100

See "BUGS" for a explanation of this setting.

=head2 EXAMPLE WARNING AND CRITICAL SETTINGS

You can also set warning and critical levels for each of the data
series the plugin reports.  The following environment variables are
used as default for all fields:

  env.warning
  env.critical

But each field can be controlled separately:

  env.system_warning
  env.system_critical

  env.user_warning
  env.user_critical

  env.nice_warning
  env.nice_critical

  env.idle_warning
  env.idle_critical

For some kernels there is also the following settings:

  env.iowait_warning
  env.iowait_critical
  env.irq_warning
  env.irq_critical
  env.softirq_warning
  env.softirq_critical
  env.steal_warning
  env.steal_critical
  env.guest_warning
  env.guest_critical

=head1 INTERPRETATION

The plugin shows cpu usage in percent. In case of more than one core
it displays 100% for each core.

If a core is 100% busy there will be no "iowait" showing, that only
shows if the CPU has nothing else to do while it waits on IO.
Therefore a 100% busy core can hide a lot of iowait.  Please refer to
the IO latency and other disk related graphs for further information
about IO performance.

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf


=head1 VERSION

  $Id$

=head1 BUGS

Some combinations of hardware and Linux (probably only 2.4 kernels)
use 1000 units/second in /proc/stat corresponding to the systems
HZ. (see /usr/src/linux/include/asm/param.h). But Almost all systems
use 100 units/second and this is our default. Even if
Documentation/proc.txt in the kernel source says otherwise. - Finding
and fix by dz@426.ch

Otherwise none known

=head1 AUTHOR

Unknown

=head1 LICENSE

GPLv2

=cut


. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi

HZ=${HZ:-100}

extinfo=""

if egrep -q '^cpu +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+' /proc/stat; then
	extinfo="iowait irq softirq"
	if egrep -q '^cpu +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+' /proc/stat; then
		extextinfo="steal"
	fi
	if egrep -q '^cpu +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+ +[0-9]+' /proc/stat; then
		extextextinfo="guest"
	fi

fi

if [ "$1" = "config" ]; then

	NCPU=$(egrep '^cpu[0-9]+ ' /proc/stat | wc -l)
	if [ "$scaleto100" = "yes" ]; then
		graphlimit=100
	else
		graphlimit=$(($NCPU * 100))
	fi
	echo 'graph_title CPU usage'
	echo "graph_order system user nice idle" $extinfo
	echo "graph_args --base 1000 -r --lower-limit 0 --upper-limit $graphlimit"
	echo 'graph_vlabel %'
	echo 'graph_scale no'
	echo 'graph_info This graph shows how CPU time is spent.'
	echo 'graph_category system'
	echo 'graph_period second'
	echo 'system.label system'
	echo 'system.draw AREA'
	echo 'system.min 0'
	echo 'system.type DERIVE'
	echo "system.info CPU time spent by the kernel in system activities" 
	echo 'user.label user'
	echo 'user.draw STACK'
	echo 'user.min 0'
	echo 'user.type DERIVE'
	echo 'user.info CPU time spent by normal programs and daemons'
	echo 'nice.label nice'
	echo 'nice.draw STACK'
	echo 'nice.min 0'
	echo 'nice.type DERIVE'
	echo 'nice.info CPU time spent by nice(1)d programs'
	echo 'idle.label idle'
	echo 'idle.draw STACK'
	echo 'idle.min 0'
	echo 'idle.type DERIVE'
	echo 'idle.info Idle CPU time'

	for field in system user nice idle; do
		print_adjusted_thresholds "$field" "$graphlimit"
	done

	if [ "$scaleto100" = "yes" ]; then
		echo "system.cdef system,$NCPU,/"
		echo "user.cdef user,$NCPU,/"
		echo "nice.cdef nice,$NCPU,/"
		echo "idle.cdef idle,$NCPU,/"
	fi
	if [ ! -z "$extinfo" ]
	then
		echo 'iowait.label iowait'
		echo 'iowait.draw STACK'
		echo 'iowait.min 0'
		echo 'iowait.type DERIVE'
		echo 'iowait.info CPU time spent waiting for I/O operations to finish when there is nothing else to do.'
		echo 'irq.label irq'
		echo 'irq.draw STACK'
		echo 'irq.min 0'
		echo 'irq.type DERIVE'
		echo 'irq.info CPU time spent handling interrupts'
		echo 'softirq.label softirq'
		echo 'softirq.draw STACK'
		echo 'softirq.min 0'
		echo 'softirq.type DERIVE'
		echo 'softirq.info CPU time spent handling "batched" interrupts'
		if [ "$scaleto100" = "yes" ]; then
			echo "iowait.cdef iowait,$NCPU,/"
			echo "irq.cdef irq,$NCPU,/"
			echo "softirq.cdef softirq,$NCPU,/"
		fi
		for field in iowait irq softirq; do
			print_adjusted_thresholds "$field" "$graphlimit"
		done
	fi

	if [ ! -z "$extextinfo" ]
	then
		echo 'steal.label steal'
		echo 'steal.draw STACK'
		echo 'steal.min 0'
		echo 'steal.type DERIVE'
		echo 'steal.info The time that a virtual CPU had runnable tasks, but the virtual CPU itself was not running'
		if [ "$scaleto100" = "yes" ]; then
			echo "steal.cdef steal,$NCPU,/"
		fi
		for field in steal; do
			print_adjusted_thresholds "$field" "$graphlimit"
		done
	fi

	if [ ! -z "$extextextinfo" ]
	then
		echo 'guest.label guest'
		echo 'guest.draw STACK'
		echo 'guest.min 0'
		echo 'guest.type DERIVE'
		echo 'guest.info The time spent running a virtual CPU for guest operating systems under the control of the Linux kernel.'
		if [ "$scaleto100" = "yes" ]; then
			echo "guest.cdef guest,$NCPU,/"
		fi
		for field in guest; do
			print_adjusted_thresholds "$field" "$graphlimit"
		done
	fi

	exit 0
fi

# Note: Counters/derive need to report integer values.  Also we need
# to avoid 10e+09 and the like %.0f should do this.

if [ ! -z "$extextextinfo" ]; then
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\niowait.value %.0f\nirq.value %.0f\nsoftirq.value %.0f\nsteal.value %.0f\nguest.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz, $6*100/hz, $7*100/hz, $8*100/hz, $9*100/hz, $10*100/hz }' < /proc/stat
elif [ ! -z "$extextinfo" ]; then
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\niowait.value %.0f\nirq.value %.0f\nsoftirq.value %.0f\nsteal.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz, $6*100/hz, $7*100/hz, $8*100/hz, $9*100/hz }' < /proc/stat
elif [ ! -z "$extinfo" ]; then
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\niowait.value %.0f\nirq.value %.0f\nsoftirq.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz, $6*100/hz, $7*100/hz, $8*100/hz }' < /proc/stat
else
	awk -v hz=$HZ '/^cpu / { printf "user.value %.0f\nnice.value %.0f\nsystem.value %.0f\nidle.value %.0f\n", $2*100/hz, $3*100/hz, $4*100/hz, $5*100/hz }' < /proc/stat
fi

`

**Comment by vincenzot1987** [comment]
[cpu.txt](https://github.com/munin-monitoring/munin/files/437833/cpu.txt)
``

**Comment by vincenzot1987** [comment]
Hello

I have attached into precedent post the cpu.txt files with the content of munin plugin.

The munin was be installed directly from centos repository so with yum command.

Thanks

Regards

**Comment by chteuchteu** [comment]
Thanks for the complete cpu plugin.
It does not seem to directly come from the plugin. Could you check if the TEMP (TMP or TMPDIR) variable is defined in your batch, and if its directory exists?

**Comment by vincenzot1987** [comment]
Hello

where I need to find this variable? Into munin-config?

This is the munin version installed on my OS

[root@plesk1 ~]# rpm -qa | grep munin
munin-common-2.0.25-11.el7.noarch
munin-2.0.25-11.el7.noarch
munin-node-2.0.25-11.el7.noarch

Thanks

Regards

**Comment by chteuchteu** [comment]
No, that's actually an environment variable. You can call `env` or `printenv` commands to list environment variables.

**Comment by vincenzot1987** [comment]
Hello,

there is not any TMP variable on env enviroment, but I checked also with centos6 and is the same thing

Regards

**Comment by chteuchteu** [comment]
What about TEMP or TMPDIR? 

Is there a /tmp or /temp directory on your system?

**Comment by vincenzot1987** [comment]
Hello

my tmp dir is /tmp and have chmod 777 

Regards

**Comment by chteuchteu** [comment]
Could you try to:

    export TMPDIR=/tmp
    export TEMP=/tmp
    munin-run cpu

**Comment by vincenzot1987** [comment]
Hello

I will do this command, when the CPU graph stop to works again, because actually works again after uninstall and install munin again.

See you in the next days

Thanks

**Comment by vincenzot1987** [comment]
Hello

I have insert an cron for restart each 24 hours the munin, and now works fine

Regards

**Comment by kenyon** [comment]
You have some serious problems with your system that are unrelated to munin.
