### ISSUE TITLE
Install plugin pgbouncer for Munin

### ISSUE THREAD

**Issue by danitorres05** [munin-monitoring/munin#733]
hello, we want to install the plugin for Munin pgbouncer. The version of munin is 2.0.25
Thanks.

**Comment by chteuchteu** [comment]
[This article](http://tapoueh.org/blog/2011/11/16-pgbouncer-munin) explains how to enable pgboucner's munin plugin (the symlink's name will be used by the plugin to determine what to graph, `pgbouncer_dbname_stats_requests` or `pgbouncer_dbname_pools`).

To enable a munin plugin on a node, just run `ln -s /path/to/plugin /etc/munin/plugins/plugin_name` and `service munin-node restart`.

Please reopen this issue if you experience any issue.

**Comment by danitorres05** [comment]
Hello, thanks for answering. We perform steps according link provided. the plugins was created after the symbolic link as follows was created

pgbouncer_atlas1_pools -> / usr / share / munin / plugins / pgbouncer_

where atlas1 is the name of the database, according to the log shows the following:

2016/08 / 25-17: 37: 40 [14773] Error output from pgbouncer_atlas1_pools:
2016/08 / 25-17: 37: 40 [14773] Traceback (most recent call last):
2016/08 / 25-17: 37: 40 [14773] File "/ etc / munin / plugins / pgbouncer_atlas1_pools", line 11, in <module>
2016/08 / 25-17: 37: 40 [14773] import os, psycopg
2016/08 / 25-17: 37: 40 [14773] ImportError: No module named psycopg
2016/08 / 25-17: 37: 40 [14773] Service 'pgbouncer_atlas1_pools' exited with status 1/0.

the library was installed psycopg

[Munin plugins @ atldes-db1] $ rpm -qa | grep psycopg
python-psycopg2-2.6.2-1.rhel7.x86_64

What you could be missing?

**Comment by chteuchteu** [comment]
This plugin is written in python, right? How did you install the library? If your environment runs both python2 and python3, you have to install the library using the right pip.

**Comment by danitorres05** [comment]
hello, if it is written in pyton
the plugin copy it from here
http://tapoueh.org/resources/pgbouncer_
The library was installed with pip

**Comment by chteuchteu** [comment]
Do you have pip3* installed on your system? Type `pip3` then use <Tab> to check.
If you do, please run (for example) `pip-3.2 install psycopg`

**Comment by danitorres05** [comment]
this we have installed for python
[Munin plugins @ atldes-db1] $ rpm -qa | grep python
python-sssdconfig-1.12.2-58.el7_1.17.noarch
dbus-python-1.1.1-9.el7.x86_64
python-kitchen-1.1.1-5.el7.noarch
newt-python-0.52.15-4.el7.x86_64
python-pyudev-0.15-6.el7.noarch
python-lxml-3.2.1-4.el7.x86_64
python-urllib3-1.10.2-2.el7_1.noarch
python-2.7.5-38.el7_2.x86_64
python-suds-0.4.1-5.el7.noarch
libsemanage-python-2.1.10-16.el7.x86_64
python-decorator-3.4.0-3.el7.noarch
libselinux-python-2.2.2-6.el7.x86_64
python-chardet-2.2.1-1.el7_1.noarch
python-slip-dbus-0.4.0-2.el7.noarch
python-iniparse-0.4-9.el7.noarch
python-backports-1.0-8.el7.x86_64
python-setuptools-0.9.8-3.el7.noarch
python-urlgrabber-3.10-6.el7.noarch
python-clufter-0.9.137-13.el7_1.4.x86_64
rpm-python-4.11.1-25.el7.x86_64
python-psutil-1.2.1-1.el7.x86_64
python-pep8-1.4.6-3.el7.noarch
python-flake8-2.0-5.el7.noarch
python-six-1.3.0-4.el7.noarch
python-requests-2.6.0-1.el7_1.noarch
python-libs-2.7.5-38.el7_2.x86_64
python-devel-2.7.5-38.el7_2.x86_64
audit-libs-python-2.4.1-5.el7.x86_64
policycoreutils-python-2.2.5-15.el7.x86_64
python-mccabe-0.2.1-4.el7.noarch
python-slip-0.4.0-2.el7.noarch
python-configobj-4.7.2-7.el7.noarch
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-pycurl-7.19.0-17.el7.x86_64
python-pip-7.1.0-1.el7.noarch
python-IPY-0.75-6.el7.noarch

For the pip

[Munin plugins @ atldes-db1] $ rpm -qa | grep pip
libpipeline-1.2.3-3.el7.x86_64
python-pip-7.1.0-1.el7.noarch

**Comment by chteuchteu** [comment]
I just re-read your message:

    [Munin plugins @ atldes-db1] $ rpm -qa | grep psycopg
    python-psycopg2-2.6.2-1.rhel7.x86_64

The package you installed is `psycopg2`, when the munin plugin is looking for `psycopg`. Could you try to run `pip install psycopg`?

**Comment by danitorres05** [comment]
hello, we seek psycopg and does not exist in the repositories, only exists psycopg version would have any link where I could download?
Thank.

**Comment by chteuchteu** [comment]
Try installing the pip package, then `pip install psycopg`

**Comment by danitorres05** [comment]
when it comes to install with pip install psycopg the result is as follows:
Could not find a version That satisfies the requirement psycopg (from versions:)
No matching distribution found for psycopg

**Comment by chteuchteu** [comment]
Then I'm afraid that this plugin isn't compatible with your system (since its dependencies aren't).
You could try [this version](https://github.com/samuel/python-munin/blob/master/munin/pgbouncer.py) as last resort.

I'm closing this issue since it doesn't concern munin directly.

**Comment by danitorres05** [comment]
hello, we put the plugin and have recommended the following error:

Error output from postgres_pgbouncer_atlas1:
2016/08/29-18:04:59 [29177]     Traceback (most recent call last):
2016/08/29-18:04:59 [29177]       File "/etc/munin/plugins/postgres_pgbouncer_atlas1", line 13, in <module>
2016/08/29-18:04:59 [29177]         from munin.postgres import MuninPostgresPlugin
2016/08/29-18:04:59 [29177]     ImportError: No module named munin.postgres
2016/08/29-18:04:59 [29177] Service 'postgres_pgbouncer_atlas1' exited with status 1/0.
2016/08/29-18:04:59 [29177] Error output from postgres_pgbouncer_atlas1:
2016/08/29-18:04:59 [29177]     Traceback (most recent call last):
2016/08/29-18:04:59 [29177]       File "/etc/munin/plugins/postgres_pgbouncer_atlas1", line 13, in <module>
2016/08/29-18:04:59 [29177]         from munin.postgres import MuninPostgresPlugin
2016/08/29-18:04:59 [29177]     ImportError: No module named munin.postgres

This is the plugin in question:

#! /usr/bin/python
# -*- coding: utf-8 -*-
import sys
from munin.postgres import MuninPostgresPlugin

class MuninPgBouncerPlugin(MuninPostgresPlugin):
    dbname_in_args = False
    default_table = "pgbouncer"
    category = "PgBouncer"

    def __init__(self, *args, **kwargs):
        super(MuninPgBouncerPlugin, self).__init__(*args, **kwargs)
        self.dbwatched = sys.argv[0].rsplit('_', 1)[-1]

    def connection(self):
        if not hasattr(self, '_connection'):
            import psycopg2
            self._connection = psycopg2.connect(self.dsn)
            self._connection.set_isolation_level(0)
        return self._connection

    def execute(self):
        cursor = self.cursor()
        cursor.execute(self.command)
        columns = [column[0] for column in cursor.description]

        totals = dict.fromkeys((field[0] for field in self.fields), 0)
        for row in cursor:
            row_dict = dict(zip(columns, row))
            if row_dict['database'] in (self.dbwatched, self.dbwatched + '\x00'):
                for field in self.fields:
                    totals[field[0]] += row_dict[field[0]]

        return dict((field[0], totals[field[0]]) for field in self.fields)
