### ISSUE TITLE
Ubuntu 16.04 munin-node 2.0.25-2

### ISSUE THREAD

**Issue by maaguilar** [munin-monitoring/munin#734]
Hi,

I can do in localhost or remote "telnet localhost 4949" but when I type "list" munin hangs.

OS version: Ubuntu 16.04 64 bits
munin-node version 2.0.25-2

Regards.

**Comment by kenyon** [comment]
Did you get this working? If not, ask for help in our IRC channel #munin on irc.oftc.net. We're going to need more information to help. Thanks.
