### ISSUE TITLE
Can't locate object method "check_perms" via package "Munin::Node::OS"

### ISSUE THREAD

**Issue by sloanebernstein** [munin-monitoring/munin#741]
While investigating a permissions issue on a Munin installation, I attempted to enable paranoia mode for munin-node temporarily to ensure that I had not opened something up too much. However, doing so caused the following sort of log message to be emitted in munin-node.log:

`2016/10/26-03:37:18 [1458]      Can't locate object method "check_perms" via package "Munin::Node::OS" at /usr/share/perl5/Munin/Node/OS.pm line 74.`

At first, I thought it might be a problem with the way your libraries were being included, but then I looked at the code: Munin::Node::Service functions try to run Munin::Node::OS->check_perms_if_paranoid() on some paths; if the argument is a file, this then ultimately calls check_perms() on the containing directory. The problem is that check_perms() does not exist anymore, as best as I can tell. I presume that check_perms_if_paranoid() should be calling itself here, and that this was missed when the code renamed/refactored a while ago.

I replicated this on two entirely different setups, one a CentOS 7 server with cPanel running Munin 2.0.25 out of its private instance of Perl, and the other as prepared on Slackware 14.1 using the slackbuilds.org SlackBuild (also Munin 2.0.25) against the system instance of Perl.

This appears to have been a problem going back many versions of 2.0.x, and it is still a problem in the master branch.

**Comment by sumpfralle** [comment]
This was fixed in master by #809 - now it is applied to `stable-2.0`, too.
