### ISSUE TITLE
munin-httpd "Error generating image"

### ISSUE THREAD

**Issue by bauerj** [munin-monitoring/munin#749]
I'm trying to use munin 2.999.3. I installed it from source and it seems to be running fine. `rrd`-files are created but the webinterface doesn't show any graphs.

`munin-httpd` creates this output while requesting an image:

	2016-11-12 13:25:25 [debug][000029]: RRDs_graph(chld_out=)
	2016-11-12 13:25:25 [debug][000029]: RRDs_graph(chld_err=)
	2016-11-12 13:25:25 [info][000029]: '/tmp/rm02bma9AC' \
	'--base' \
	'1000' \
	'--title' \
	'NGINX status - by week' \
	'--watermark' \
	'Munin master' \
	'--imgformat' \
	'PNG' \
	'--start' \
	'end-12000m' \
	'--slope-mode' \
	'--font' \
	'TITLE:12:Sans' \
	'--font' \
	'DEFAULT:7' \
	'--font' \
	'LEGEND:7' \
	'--color' \
	'BACK#F0F0F0' \
	'--color' \
	'FRAME#F0F0F0' \
	'--color' \
	'CANVAS#FFFFFF' \
	'--color' \
	'FONT#666666' \
	'--color' \
	'AXIS#CFD6F8' \
	'--color' \
	'ARROW#CFD6F8' \
	'--width' \
	'400' \
	'--height' \
	'175' \
	'--border' \
	'0' \
	'--end' \
	'1478957125' \
	'--vertical-label' \
	'Connections' \
	'DEF:avg_total=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-total-g.rrd:42:AVERAGE' \
	'DEF:min_total=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-total-g.rrd:42:MIN' \
	'DEF:max_total=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-total-g.rrd:42:MAX' \
	'DEF:avg_reading=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-reading-g.rrd:42:AVERAGE' \
	'DEF:min_reading=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-reading-g.rrd:42:MIN' \
	'DEF:max_reading=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-reading-g.rrd:42:MAX' \
	'DEF:avg_writing=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-writing-g.rrd:42:AVERAGE' \
	'DEF:min_writing=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-writing-g.rrd:42:MIN' \
	'DEF:max_writing=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-writing-g.rrd:42:MAX' \
	'DEF:avg_waiting=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-waiting-g.rrd:42:AVERAGE' \
	'DEF:min_waiting=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-waiting-g.rrd:42:MIN' \
	'DEF:max_waiting=/var/lib/munin/abc.xyz/abc.xyz-nginx_status-waiting-g.rrd:42:MAX' \
	'VDEF:vavg_total=avg_total,AVERAGE' \
	'VDEF:vmin_total=min_total,MINIMUM' \
	'VDEF:vmax_total=max_total,MAXIMUM' \
	'VDEF:vlst_total=avg_total,LAST' \
	'VDEF:vavg_reading=avg_reading,AVERAGE' \
	'VDEF:vmin_reading=min_reading,MINIMUM' \
	'VDEF:vmax_reading=max_reading,MAXIMUM' \
	'VDEF:vlst_reading=avg_reading,LAST' \
	'VDEF:vavg_writing=avg_writing,AVERAGE' \
	'VDEF:vmin_writing=min_writing,MINIMUM' \
	'VDEF:vmax_writing=max_writing,MAXIMUM' \
	'VDEF:vlst_writing=avg_writing,LAST' \
	'VDEF:vavg_waiting=avg_waiting,AVERAGE' \
	'VDEF:vmin_waiting=min_waiting,MINIMUM' \
	'VDEF:vmax_waiting=max_waiting,MAXIMUM' \
	'VDEF:vlst_waiting=avg_waiting,LAST' \
	'COMMENT:\t' \
	'COMMENT:Cur\t' \
	'COMMENT:Min\t' \
	'COMMENT:Avg\t' \
	'COMMENT:Max\t\r' \
	'LINE2:avg_total#00CC00:Active connections\l' \
	'COMMENT:\u' \
	'COMMENT:\t' \
	'GPRINT:vlst_total:%6.2lf%s\t' \
	'GPRINT:vmin_total:%6.2lf%s\t' \
	'GPRINT:vavg_total:%6.2lf%s\t' \
	'GPRINT:vmax_total:%6.2lf%s\t' \
	'COMMENT:\r' \
	'LINE2:avg_reading#0066B3:Reading\l' \
	'COMMENT:\u' \
	'COMMENT:\t' \
	'GPRINT:vlst_reading:%6.2lf%s\t' \
	'GPRINT:vmin_reading:%6.2lf%s\t' \
	'GPRINT:vavg_reading:%6.2lf%s\t' \
	'GPRINT:vmax_reading:%6.2lf%s\t' \
	'COMMENT:\r' \
	'LINE2:avg_writing#FF8000:Writing\l' \
	'COMMENT:\u' \
	'COMMENT:\t' \
	'GPRINT:vlst_writing:%6.2lf%s\t' \
	'GPRINT:vmin_writing:%6.2lf%s\t' \
	'GPRINT:vavg_writing:%6.2lf%s\t' \
	'GPRINT:vmax_writing:%6.2lf%s\t' \
	'COMMENT:\r' \
	'LINE2:avg_waiting#FFCC00:Waiting\l' \
	'COMMENT:\u' \
	'COMMENT:\t' \
	'GPRINT:vlst_waiting:%6.2lf%s\t' \
	'GPRINT:vmin_waiting:%6.2lf%s\t' \
	'GPRINT:vavg_waiting:%6.2lf%s\t' \
	'GPRINT:vmax_waiting:%6.2lf%s\t' \
	'COMMENT:\r' \
	'VRULE:1478956862#999999:Last update:dashes=2,5\l' \
	'COMMENT:\u' \
	'COMMENT:Sat Nov 12 13\:21\:02 2016\r'
	2016-11-12 13:25:25 [error][000029]: Error generating image: 72057594037927935
	2016-11-12 13:25:25 [debug][000029]: sending '/tmp/rm02bma9AC'
	2016-11-12 13:25:25 [debug][000029]: total:0.074s (db:0.034s rrd:0.040s)

The http request returns an empty body:

	root@36354c8f12f0:/var/lib/munin/abc.xyz# curl localhost:4948/abc.xyz/abc.xyz/load-week.png -vvv
	*   Trying ::1...
	* connect to ::1 port 4948 failed: Connection refused
	*   Trying 127.0.0.1...
	* Connected to localhost (127.0.0.1) port 4948 (#0)
	> GET /abc.xyz/abc.xyz/load-week.png HTTP/1.1
	> Host: localhost:4948
	> User-Agent: curl/7.47.0
	> Accept: */*
	>
	* HTTP 1.0, assume close after body
	< HTTP/1.0 200 OK
	< Content-Type: image/png; charset=ISO-8859-1
	<
	* Closing connection 0

If I run rrdtool manually with the generated parameters I get this output:

    expected a ',' at : l

**Comment by bauerj** [comment]
This seems to be the `l` the error message is talking about:

```diff
- 'VRULE:1478956862#999999:Last update:dashes=2,5\l'
+ 'VRULE:1478956862#999999:Last update:dashes=2,5'
```

By removing it, I get an image from rrdtool.

**Comment by mgeisler** [comment]
I can confirm the bug using the packages for Debian Experimental. Removing the `\l` from `Graph.pm` lets me see images in `munin-httpd`. I don't really know Perl, but this is the change I applied:
```
--- /usr/share/perl5/Munin/Master/Graph.pm~	2016-11-02 11:59:09.000000000 +0100
+++ /usr/share/perl5/Munin/Master/Graph.pm	2016-11-19 14:32:41.414245075 +0100
@@ -475,7 +475,7 @@
 	# future begins at this horizontal ruler
 	if ($lastupdated) {
 		# TODO - we have to find the last updated for aliased items
-		push(@rrd_gfx, "VRULE:$lastupdated#999999:Last update:dashes=2,5\\l");
+		push(@rrd_gfx, "VRULE:$lastupdated#999999:Last update:dashes=2,5");
 		my $last_update_str = escape_for_rrd(scalar localtime($lastupdated));
 		push @rrd_gfx, "COMMENT:\\u";
 		push @rrd_gfx, "COMMENT:$last_update_str\\r";
```

**Comment by mgeisler** [comment]
For some reason, I saw images when starting `munin-httpd` by hand -- when I start it with Systemd, there are no images.

**Comment by bauerj** [comment]
I don't quite understand you: Does it generate images for you just by starting `munin-httpd` manually (without applying the patch)?

**Comment by mgeisler** [comment]
Yeah, I suppose that was a bit confusing :-) When I edited the file and took out the `\l` you found, I saw images after starting `munin-httpd` by hand. However, when I stopped it again and restarted it via Systemd, there were no images. I didn't investigate further.

**Comment by bauerj** [comment]
Okay, now I get it 😃 Maybe that's unrelated to this bug though.

**Comment by bauerj** [comment]
I have the same issue with the current 2.999.4 release.
