### ISSUE TITLE
Make "graph no" option configurable for ping_ plugin

### ISSUE THREAD

**Issue by throwable-one** [munin-monitoring/munin#760]
With "graph no" I can't see any error in "Problems" section of web GUI.
I am sure it is up to user to choose whether packetloss should be displayed, or not.

I can have several links to ping_ with different configurations, one of them with packetloss just to see in on web (and not only use it with limits)

**Comment by sumpfralle** [comment]
It is configurable now via the `enable_packetloss_graph` environment variable.
See fbfd9727dcc69f29ed1d3ceba358acff36ed9ae8.
