### ISSUE TITLE
nvidia plugin should use nvidia-smi instead of nvclock

### ISSUE THREAD

**Issue by kalvdans** [munin-monitoring/munin#769]
The nvclock program has not been packaged for Ubuntu:s later than 14.04, it is better to use nvidia-smi which is always installed together with the driver.

There is an alternative plugin, that uses nvidia-smi, over at
https://github.com/tianon/munin-plugins/blob/master/nvidia

**Comment by kenyon** [comment]
Since this this plugin requires certain hardware to test, someone who has that hardware is going to have to make the changes to the plugin and submit a pull request.

**Comment by akosmaroy** [comment]
I'm interested in this as well. tried to add the above plugin to my munin instance, but it didn't show up

please advise on how to proceed

**Comment by sumpfralle** [comment]
Did you already go through the documentation for [using munin plugins](http://guide.munin-monitoring.org/en/latest/plugin/use.html#plugin-use)?

**Comment by akosmaroy** [comment]
yes, at the end I managed to make it work.
if I'd like to extend the nature of data collected, could you give some guidelines / hints? e.g. I'd like to track the power draw of each card, how would I do that?

**Comment by sumpfralle** [comment]
Yes, I am happy to guide you a bit.

Did you take a look at the directory `/sys/class/hwmon`? Is your graphics card available there, as well?

Did you take a look at the content of the virtual hwmon directory? Does it contain all bits of information that you want to track?

If you take a look at the hwmon plugin, you will see that it looks for files ending with `_input` (and their corresponding `_label` files). If your graphics card hwmon directory resembles that structure, then it may well work out of the box?

**Comment by akosmaroy** [comment]
no, the nvidia card details don't seem to be exposed under /sys/class/hwmon
but the data I'm looking to get is exposed via the nvidia-smi utility. the contributed nvidia plugin mentioned by @kalvdans above already uses this tool to get the temperature and fan speed data that is being collected there. this is what I'd like to extend to include power draw

**Comment by sumpfralle** [comment]
OK - I understand.

The plugin referenced above is maintained by someone else. If the author does not maintain it anymore, it may be a good idea to move it into this "contrib" repository. Of course it is also fine to maintain plugins outside of this repository.

Regarding power consumption and nvidia: did you already take a look at the `nvidia_gpu_` plugin in this repository (`plugins/gpu/nvidia_smi_`)? It contains a "power" graph - maybe this is just what you are looking for?

**Comment by akosmaroy** [comment]
I'm not finding the nvidia_smi_ plugin you're referring to. can you please provide a specific link?

otherwise, how difficult would it be to extend the nvidia plugin by @kalvdans  to also inclue power consumption info?

**Comment by sumpfralle** [comment]
Ah - you are right: [the plugin is part of the "contrib" repository](https://github.com/munin-monitoring/contrib/blob/master/plugins/gpu/nvidia_gpu_).

Regarding the munin plugins in the [tianon](https://github.com/tianon/munin-plugins) repository: the latest commit over there is five years old, thus I would no recommend to base your work on this probably outdated code.

The plugins in the "contrib" repository are quite probably better maintained. E.g the `nvidia_gpu_` plugin received "power consumption" retrieval just a few weeks ago.

**Comment by akosmaroy** [comment]
indeed there is an nvidia_smi_ plugin in the contrib directory. but it requires a Perl module that doesn't compile / install for me on ubuntu 17.04. thus it doesn't work. BTW, this wouldn't provide power data either.

(the nvidia_gpu_ plugin uses an outdated nvidia command and doesn't work with recent nvidia drivers.)

thus @kalvdans 's plugin is the only one that works for the time being.

only if it was easy to extend it with power data :)

**Comment by sumpfralle** [comment]
`nvidia_smi_` vs. `nvidia_gpu_`: yes, I mixed up these two plugins in my last but one comment. I wanted to refer to `nvidia_gpu_`.

Regarding the outdated nvidia command used in `nvidia_gpu_`: I am surprised, that someone actually updated that plugin two months ago under these circumstances. But I have no idea about the nvidia eco system - thus I cannot tell.

Regarding the possible actions to be taken (from my point of view):
A) File an issue for @kalvdans' plugin and propose that you migrate the plugin here (or ask, if he would like to include your proposed improvements). Then you could create a pull request here with this new plugin. You will need to be prepared to improve it a bit in the process (e.g. add a proper documentation header, ...).
B) Migrate the `nvidia_gpu_` plugin (which contains all the features) from the old nvidia command to the new interface.

Personally I would strongly prefer B, as the change is probably quite simple and this would reduce the number of outdated plugins for nvidia graphics cards.

**Comment by akosmaroy** [comment]
actually, my mistake. the nvidia_gpu_ plugin in the contrib repository works as expected. also displays power stats.

sorry, my mistake

all works fine :)

**Comment by sumpfralle** [comment]
Hehe - I did not think of option C :)
Perfect!
