### ISSUE TITLE
apt reporting pending packages, but there are none

### ISSUE THREAD

**Issue by mehturt** [munin-monitoring/munin#775]
I'm using Munin 2.0.25 on Debian 8.6. Recently I started to get notifications from apt which report big number of pending packages, about 100. Then, 5 minutes later I get another notification stating there is 0 pending packages.
When I run "aptitude safe-upgrade", or "aptitude full-upgrade" from cmd line, nothing gets upgraded.  I looked at the code and it seems to be running "apt-get -u dist-upgrade --print-uris --yes " but that reports 0 packages when run from command line as well.
I guess it's not really munin related question, but maybe somebody has an idea of what's going on?
Thanks.
m.

**Comment by aquadraht** [comment]
can confirm same behaviour, Debian 8.9 and munin 2.0.25.

**Comment by sumpfralle** [comment]
I tried to take a good look at the implementation of the plugin.
It does the following:
* run `apt-get -u dist-upgrade --print-uris --yes` and parse the output:
    * count all *words* (whitespace separated, multiple lines) starting from specific strings (e.g. `^The following NEW packages will be installed:`)
    * stop on the first line starting with a non-whitespace character

The logic is fragile: any change of output strings would break the parser. But a problem would end up *not* counting - but it could never count too much (as far as I can imagine).

Could it be, that you changed your apt sources during the time of non-zero upgradeable packages being detected?
Or maybe someone hast an idea, what could go wrong here?

**Comment by sumpfralle** [comment]
Indeed the `apt_all` plugin reported outdated information due to the order of execution of "update state file" and "create report".
