### ISSUE TITLE
Service psu_foo returned no data for label processes

### ISSUE THREAD

**Issue by doublehp** [munin-monitoring/munin#776]
munin-update.log :
2017/01/12 19:25:39 [WARNING] Service psu_nobody on server/bar-03:4949 returned no data for label processes

/etc/munin/plugins :
lrwxrwxrwx 1 root root   29 Nov  7 00:37 psu_daemon -> /usr/share/munin/plugins/psu_
lrwxrwxrwx 1 root root   29 Nov  7 00:37 psu_nobody -> /usr/share/munin/plugins/psu_
lrwxrwxrwx 1 root root   29 Nov  7 00:37 psu_root -> /usr/share/munin/plugins/psu_

# ./psu_nobody config
graph_title Number of processes owned by nobody
graph_args --base 1000 --vertical-label processes -l 0
graph_category processes
count.label nobody
processes.draw LINE2

# ./psu_root config
graph_title Number of processes owned by root
graph_args --base 1000 --vertical-label processes -l 0
graph_category processes
count.label root
processes.draw LINE2

**Comment by kenyon** [comment]
OK, you gave us a bunch of output. What are we supposed to do with this?

**Comment by doublehp** [comment]
Fix the code ?

**Comment by kenyon** [comment]
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by chteuchteu** [comment]
Sir, you'll have to give a little more context: since when are you experiencing this issue? Since you installed the plugin? At a special trigger event (like a system update or something)? Which version of munin-node are you running? On which OS & version?

Without all this context, we won't be able to reproduce the issue nor fix it.

**Comment by doublehp** [comment]
Since 7 years; that plugin never worked properly; neither in Munin 1 or 2.
2.0.28-1 for now.
Debian stretch

I have better bugs coming: no graph and no warning or error about it in logs; will be fun.

**Comment by doublehp** [comment]
An older machine:
Gentoo 2011 (probably updated around 2013)
Munin version 2.0.14
tail -n 1000 /var/log/munin/munin-update.log | grep psu_root
2017/01/14 13:05:02 [WARNING] Service psu_root on uranus.doublehp.org/127.0.0.1:4949 returned no data for label processes
2017/01/14 13:10:02 Missing required attribute 'label' for data source 'processes' in service psu_root on uranus.doublehp.org/127.0.0.1:4949

When things are broken on two different distributions, with a completely different configuration, I just don't know what to report.

# tail -n 1000 /var/log/munin/munin-node.log | grep psu_root

give snothing about it.

=> Never worked since install, years ago, never got fixed with updates; broken on old Gentoo, old Debian, fresh Debian

**Comment by doublehp** [comment]
Kenyon, after reading your link ...

"if the program really didn't work at all, they would probably have noticed. Since they haven't noticed, it must be working for them."

... I have one thing to add: I am the first one reporting this issue because I am obviously the first Munin user doing two things:
- I manually checked that every single file in /etc/munin/plugins is producing at least one image in the webpage
- i am doing stats on log files: I use the loggrep plugin to track WARNING and ERROR lines in logfiles; and I can tell that the default configuration produces a HUGE LOT of error messages (most of them shall go to Debian tracker first, since a large part of these errors may be linked to the debian installer of the package; and Debian team must check them first before going upstream here)

But, default installer does not configure a plugin to track errors; and since that plugin is not generating graph at all, the webpage is not showing any kind of issue.  Because the only error message is sent in a file nobody reads. So I believe everyone has this error; but no-one ever noticed it in the past years. Web page does not contain any error. So most people just assume everything is working fine.
