### ISSUE TITLE
Opening and ending tag mismatch: li line 0 and ul

### ISSUE THREAD

**Issue by JvGinkel** [munin-monitoring/munin#779]
Munin version 2.0.29 (Also tested with 2.0.28)
OS: Centos 7 (64bits)
Installed from the EPEL repository

Problem: 
Error in the index.html
```
This page contains the following errors:
error on line 149 at column 9: Opening and ending tag mismatch: li line 0 and ul
Below is a rendering of the page up to the first error.
```

![screenshot 2017-01-15 08 29 40](https://cloud.githubusercontent.com/assets/7691054/21960977/f11602ea-dafc-11e6-9b57-2fe75d589d1e.png)

The error is only here when you use more then 1 layer in the node file:
```
[production;test;muninmaster]
  address 192.168.24.6
  use_node_name yes
```
If I remove the `test;` so you only have `[production;muninmaster]` then the error is gone.

**Comment by niclan** [comment]
On 15. jan. 2017 08:36, Jethro wrote:
...
> |[production;test;muninmaster] address 192.168.24.6 use_node_name yes |
>
> If I remove the |test;| so you only have |[production;muninmaster]| then
> the error is gone.

Yeah, I think that two levels are probably not supported.

Nicolai

**Comment by JvGinkel** [comment]
On a munin 2.0.25 server it is working. So something broke between 2.0.25 en 2.0.29 I think?

**Comment by JvGinkel** [comment]
Problem still exists in version 2.0.33

**Comment by sumpfralle** [comment]
Weird!
I am using 2.0.33, too - here it works with one, two or three levels.

Could you please take a look at the log files? Do you see an error message?
Could you share your configuration file and the (incomplete) html file with us?

**Comment by sumpfralle** [comment]
Closing: no further comments and newer versions seem to work.
