### ISSUE TITLE
munin draws warning lines on graphs

### ISSUE THREAD

**Issue by northway** [munin-monitoring/munin#780]
Hi! I'm using munin 2.0.25-2 on Ubuntu 16.04.1.

I made a plugin to monitor the room temperatures at home. Later I setted up warning and critical ranges to get notifications when the temperatues are exceeding the limits.

I noticed that the warning lines appeard on the graphs and there's no method disable this. Also worth to mention that the critical lines are never showed up on the graps.

I had to turn off the warning ranges and keep only ciricatal ranges, because this way I could prevent the warning lines on the graphs.

    echo "budapest.label Budapest\n";
    echo "budapest.info Budapest\n";
    echo "budapest.colour COLOUR7\n";
    //echo "budapest.warning -15:38\n";
    echo "budapest.critical -18:40\n";

![warn1](https://cloud.githubusercontent.com/assets/3431401/21987660/b9d35d38-dc04-11e6-9336-2193742c47ae.png)
![warn2](https://cloud.githubusercontent.com/assets/3431401/21987661/b9d65a2e-dc04-11e6-969f-46c592b66771.png)

**Comment by JoHartmann** [comment]
I have the problem, the warning lines disturb the overview. But I want to use the limiter warning and critical to be alert by an email. My unprofessional way: patching the file [/usr/share/perl5/Munin/Master/GraphOld.pm](url) !
**My wish for the next version:**
A new configurations / environment variable graph_warn no like graph_scale!

-- 
Greetings from the home of CeBIT
Gruß aus der Stadt der CeBIT
Jochen

**Comment by northway** [comment]
I commented out the lines from 1242 to 1266 in the GraphOld.pm file and now the warning lines have disappeared from the graph!

The commented lines:

```
#        elsif (my $tmpwarn = munin_get($field, "warning")) {
#
#            my ($warn_min, $warn_max) = split(':', $tmpwarn,2);
#
#            if (defined($warn_min) and $warn_min ne '') {
#                unshift(
#                    @rrd,
#                    "HRULE:" 
#                        . $warn_min
#                        . "#" . (
#                        $single_value
#                        ? "ff0000"
#                        : $COLOUR[($field_count - 1) % @COLOUR]));
#            }
#            if (defined($warn_max) and $warn_max ne '') {
#                unshift(
#                    @rrd,
#                    "HRULE:" 
#                        . $warn_max
#                        . "#" . (
#                        $single_value
#                        ? "ff0000"
#                        : $COLOUR[($field_count - 1) % @COLOUR]));
#            }
#        }
```

It's not an elegant solution, but it works. So I can use my warning values again.

**Comment by JoHartmann** [comment]
That was the patch I do, but with the next update of munin I have to do it again!
That is the reason for **my wish** to the programmers of Munin. 
PS:
Yesterday I tried to insert my patch as code as you do. I fault, every time I switched to Preview it looks ugly. Something like this:
`
# Row 1
 #Row 2
`
--
Greetings from the home of CeBIT
Gruß aus der Stadt der CeBIT
Jochen

**Comment by JoHartmann** [comment]
My patches are:
```
                my ($warn_min, $warn_max) = split(':', $tmpwarn,2);

##                if (defined($warn_min) and $warn_min ne '') {
##                    unshift(
##                        @rrd,
##                        "HRULE:" 
##                            . $warn_min
##                            . "#" . (
##                            $single_value
##                            ? "ff0000"
##                            : $COLOUR[($field_count - 1) % @COLOUR]));
##                }
##                if (defined($warn_max) and $warn_max ne '') {
##                    unshift(
##                        @rrd,
##                        "HRULE:" 
##                            . $warn_max
##                            . "#" . (
##                            $single_value
##                            ? "ff0000"
##                            : $COLOUR[($field_count - 1) % @COLOUR]));
##                }
            }

            push(@rrd,
```
```
            my ($warn_min, $warn_max) = split(':', $tmpwarn,2);

##            if (defined($warn_min) and $warn_min ne '') {
##                unshift(
##                    @rrd,
##                    "HRULE:" 
##                        . $warn_min
##                        . "#" . (
##                        $single_value
##                        ? "ff0000"
##                        : $COLOUR[($field_count - 1) % @COLOUR]));
##            }
##            if (defined($warn_max) and $warn_max ne '') {
##                unshift(
##                    @rrd,
##                    "HRULE:" 
##                        . $warn_max
##                        . "#" . (
##                        $single_value
##                        ? "ff0000"
##                        : $COLOUR[($field_count - 1) % @COLOUR]));
##            }
        }
    }

    my $graphtotal = munin_get($service, "graph_total");
```
--
Greetings from the home of CeBIT
Gruß aus der Stadt der CeBIT
Jochen

**Comment by c-schmitz** [comment]
It would be great if this issue could be fixed.  Please give us a way to enable/disable the warning line and to properly format it (color, appearance, etc)

**Comment by sumpfralle** [comment]
I think, we could add such a feature to `stable-2.0`.

The relevant details are probably:
* introduce a new configuration setting (or multiple settings) for the visualization of warning and critical values
    * Which level would be appropriate? Field, plugin, node or master?
* prevent the lines from being drawn, based on the above configuration

A pull request would be very welcome!

**Comment by sumpfralle** [comment]
Commit 66d1eff271fa52f5d94ca64929e41e551d418135 changed the appearance of warning lines: now they are dotted. Thus they can be easily distinguished from the data.
