### ISSUE TITLE
dynazoom.html: enabling munin graph zoom feature on OpenSuse 13.1

### ISSUE THREAD

**Issue by leemgs** [munin-monitoring/munin#800]
I have used munin package on Ubuntu 14.04/16.04. Recently, I tried to install munin package on OpenSUSE 13.1. Unfortunately, I could not generate a graph in the dynazoom.html file. At that time, I had installed _perl-CGI-Fast_ and _apache2-mod_fcgid_ package on OpenSUSE 13.1.  How can we enable the dynazoom functionality on OpenSUSE 13.1 as well as Ubuntu 14.04/16.04 LTS.?  Anyone who has a similar experience on OpenSUSE?

 * install 'munin' rpm package
```
zypper addrepo http://download.opensuse.org/repositories/server:monitoring/openSUSE_13.1/server:monitoring.repo
zypper refresh
zypper install munin
```

 * install 'munin-node' rpm package
```
zypper addrepo http://download.opensuse.org/repositories/server:monitoring/openSUSE_13.1/server:monitoring.repo
zypper refresh
zypper install munin-node
```

 * install FastCGI components
 [FYI] It seems that  Fast CGI script (written by perl) is not compatible with Munin package. 
```
zypper addrepo http://download.opensuse.org/repositories/devel:languages:perl/openSUSE_13.1/devel:languages:perl.repo
zypper refresh
zypper install perl-CGI-Fast


zypper addrepo http://download.opensuse.org/repositories/Apache:Modules/Apache_openSUSE_13.1/Apache:Modules.repo
zypper refresh
zypper install apache2-mod_fcgid
a2enmod fcgid
systemctl restart apache2
apache2ctl  -M | grep cgi
  ... fcgid_module (shared)...
```

 * apache-munin.conf  for apache2 webserver
```
vi /etc/apache2/conf.d/munin.conf
---------------
Alias /munin /srv/www/htdocs/munin
<Directory /srv/www/htdocs/munin>
 # Require local
 Require all granted
 Options FollowSymLinks SymLinksIfOwnerMatch
 Options None
</Directory>

ScriptAlias /munin-cgi/munin-cgi-graph /srv/www/cgi-bin/munin-cgi-graph
<Location /munin-cgi/munin-cgi-graph>
 # Require local
 Require all granted
 Options FollowSymLinks SymLinksIfOwnerMatch
 <IfModule mod_fcgid.c>
 SetHandler fcgid-script
 </IfModule>
 <IfModule !mod_fcgid.c>
 SetHandler cgi-script
 </IfModule>
</Location>
----------------------
systemctl restart apache2
http://localhost/munin/
```

 * Screenshot: 
![dynazoom-graph-zooming-error](https://cloud.githubusercontent.com/assets/82404/23414934/f78b44f4-fe20-11e6-9ee2-e6e2e659bcac.png)

**Comment by leemgs** [comment]
I have found some differences munin 2.0 and munin 2.1 at the official munin webpage. On OpenSUSE 13.1 distribution, Munin graphing (e.g., dynazoom.html) is not correctly run with FastCGI.It seems that we have to use munin 2.1 instead of the existing version to run dynazoom.html normally on OpenSUSE 13.1. 

* Reference:  http://guide.munin-monitoring.org/en/latest/installation/upgrade.html#upgrading-munin-from-2-0-x-to-2-1-x

**Comment by leemgs** [comment]
I have solved the issue by debugging dynzoom.html (e.g. https://localhost/munin/static/dynazoom.html?cgiurl_graph=/srv/munin-cgi/munin-cgi-graph&plugin_name=localhost.domain/cpu).   The issues has generated by 1) incorrect permission in /var/log/munin/ and 2) shortage of connection time for generating the zoom-in graph with FastCGI. 

Here is recipe to solve this issue on OpenSUSE 13.1 
```
$ sudo chmod -R 775 /var/log/munin/ 
$ chown -R munin:www  /var/log/munin/
$ ls -al  /var/log/ | grep munin
drwxrwxr-x  2 munin  munin     4096 Mar 17 15:40 munin
$ sudo vi /etc/apache/conf.d/munin-apache.conf 
------------apache:end-----------------------

Alias /munin /srv/munin
<Directory /srv/munin>
#  SSLRequireSSL
#  Options None
   Require all granted
   Options FollowSymLinks SymLinksIfOwnerMatch
   AllowOverride None
   Order allow,deny
   Allow from all
   AuthName "Nagios Access"
   AuthType Basic
   AuthUserFile /etc/nagios/htpasswd.users
   Require valid-user
    <IfDefine KOHANA2>
      DirectoryIndex index.html index.php
    </IfDefine>
</Directory>

ScriptAlias /srv/munin-cgi/munin-cgi-graph /srv/www/cgi-bin/munin-cgi-graph
<Location /srv/munin-cgi/munin-cgi-graph>
 # Require local
 Require all granted
 Options ExecCGI FollowSymLinks SymLinksIfOwnerMatch
 <IfModule mod_fcgid.c>
 SetHandler fcgid-script
# [url]http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html[/url]
# IPCConnectTimeout 300
# IPCCommTimeout 600
 </IfModule>
 <IfModule !mod_fcgid.c>
 SetHandler cgi-script
 </IfModule>
</Location>
------------apache:end-----------------------
```

**Comment by sumpfralle** [comment]
@leemgs: this sounds like an issue with the packaging for OpenSUSE, or?
Did you file a bug report at their issue tracker?

**Comment by sumpfralle** [comment]
Closing this distribution-specific issue.
