### ISSUE TITLE
Munin Plugin Gallery shows no plugins

### ISSUE THREAD

**Issue by dipohl** [munin-monitoring/munin#803]
http://gallery.munin-monitoring.org/

[The gallery scripts from branch master](https://github.com/munin-monitoring/munin/tree/master/contrib/plugin-gallery) are working. I setup a [fresh gallery instance](http://munin-gallery.dipohl.de/) with them on my server. See INSTALL instructions and I am willing to help also.

So please get in contact.

Gabriele

**Comment by steveschnepp** [comment]
This is fixed by b7507b78f1f869e27d2e6c94d9b988a9a9841978 and 96395192138f5ee8f725d919ba71c0c267f5d3e3.
