### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by mydexterid** [munin-monitoring/munin#811]
Trying to figure out how to configure the email alerts according to this:
http://guide.munin-monitoring.org/en/latest/tutorial/alert.html
and the linked site under "Munin alert email notification":
http://blog.edseek.com/archives/2006/07/13/munin-alert-email-notification/

is not available since 2 years now.

**Comment by Lusitaniae** [comment]
Basically Munin will run whatever command you define in a shell.

You can send email, slack, telegram, email notifications, etc

You should see some examples on the configuration file, in your Munin master.

/etc/munin/munin.conf    

#contact.anotheruser.command mail -s "Munin notification" anotheruser@blibb.comm

in my case I may use, 

contact.**telegram**.command **/usr/bin/send_to_telegram**

1. you can write anything in place of telegram.

2. You can write whatever you want after .command.

**Comment by mydexterid** [comment]
Soo umm.. the guide is still linking the unavailable site. Why is this issue closed then?

**Comment by ssm** [comment]
I did read this issue as a configuration question that got an answer.

I'll remove or update the broken URL you mentioned.  Thanks.
