### ISSUE TITLE
nginx_request plugin needs some updating

### ISSUE THREAD

**Issue by mitchellkrogza** [munin-monitoring/munin#818]
Would love to see somebody modify the rather outdated nginx_request plugin - https://github.com/munin-monitoring/munin/blob/203a4210fddcc393aee4ed0b8480b9c9f02955b7/plugins/node.d/nginx_request

It only supports port 80 and would be great if it could cover both port 80 and port 443 in one graph.

**Comment by Lusitaniae** [comment]
Nginx returns the number of connections for both protocols all together.

Example status page:

> Active connections: 43 
> server accepts handled requests
>  7368 7368 10993 
> Reading: 0 Writing: 5 Waiting: 38

So we cannot distinguish between one and the other.
