### ISSUE TITLE
Munin broken after system hard reboot because of empty storable files

### ISSUE THREAD

**Issue by AMDmi3** [munin-monitoring/munin#821]
A VPS I run munin (2.0.33 on FreeBSD 11.0) on got hard rebooted and I ended up with broken munin.

Though the data was still being polled and RRDs updated successfully, the process which generates html pages constantly failed to run. I don't have much debug left as I've had to fix it ASAP, but the suspected cause is that some files under munin vardir (for instance, ```/var/munin/limits.storable```) ended up being zero size, and perl failed to read storables from them. After removing these files the problem was fixed.

I see at least two possible solutions for this problem. First, I suspect that these files are written in an unsafe way (e.g. file is written into directly, instead of using temporary file which is then renamed over the actual one). Next, since these seem to be non-critical and are regenerated if deleted, munin should not hesitate to recreate them if they are not readable.

**Comment by steveschnepp** [comment]
> First, I suspect that these files are written in an unsafe way (e.g. file is written into directly, instead of using temporary file which is then renamed over the actual one). 

They actually use a temporary file and `rename()` them atomically after the `close()`.

> Next, since these seem to be non-critical and are regenerated if deleted, munin should not hesitate to recreate them if they are not readable.

That's a very valid statement.

**Comment by AMDmi3** [comment]
> They actually use a temporary file and rename() them atomically after the close().

Maybe it lacks f(data)sync? I admit it's possible this is filesystem or virtual machine problem, but I only see it with munin storables, not with log files or databases also running on this vm, and have seen it before.

**Comment by steveschnepp** [comment]
Hmmm... seems that https://github.com/munin-monitoring/munin/blob/stable-2.0/master/lib/Munin/Master/Utils.pm#L850 already takes care of deleting them automatically.

Do you have an error message ?

**Comment by AMDmi3** [comment]
Yes. I can reproduce it by ```echo -n > limits.storable``` and running ```/usr/local/share/munin/munin-limits```:

```
% sudo -u munin /usr/local/share/munin/munin-limits
Magic number checking on storable file failed at /usr/local/lib/perl5/site_perl/mach/5.24/Storable.pm line 399, at /usr/local/lib/perl5/site_perl/Munin/Master/Utils.pm line 279.
```

program exists with 255, file is left untouched. Mentioned line reads Storable directly, not through munin_read_storable you've mentioned.

**Comment by steveschnepp** [comment]
Ack. 

Could you see if #822 fixes your issue ?

**Comment by AMDmi3** [comment]
Yes, thank you! I've corrupted all .storable's in `/var/munin`, and it has recreated them all and is running without problems.
