### ISSUE TITLE
Params::Validate version requirement

### ISSUE THREAD

**Issue by kimheino** [munin-monitoring/munin#823]
Commit 6a6ccfebb09052b89663c61e062a746ba7e71844 (by ssm) add version requirement 1.13 for Params::Validate. Could it be lowered to version 1.08? RHEL7 has only that older version. I tested munin-update and munin-httpd, both seems to work with 1.08, but not really sure where it's required.

**Comment by steveschnepp** [comment]
I do not see any issue to lower most our depencies.

I'm even in favor of letting them to *any* version until there is a referenced issue against them (or that we _know_ it is an issue)

**Comment by ssm** [comment]
If it does not break with 1.08, I'm all for lowering it.  If that requires changes to support RHEL7, I'll gladly fix it.
