### ISSUE TITLE
2.0.x stable : outdated plugins (mysql, ...)

### ISSUE THREAD

**Issue by Daryes** [munin-monitoring/munin#826]
used version :  stable 2.0.x (2.0.25 on debian, 2.0.33 on centos7)
both munin and munin-node

Hello,
Took me a while to figure out how latest packages on both distrib from official repos could have old version of some plugins. 
For example, the mysql_ plugin on latest stable version is currently from around 2013, while other are much older.

mysql_ plugin header, [2.0.33](https://github.com/munin-monitoring/munin/tree/2.0.33/plugins/node.d) tree : 
```
=head1 APPLICABLE SYSTEMS    
 Any MySQL platform, tested by the author on MySQL 5.1.29 and 5.0.51
```

mysql_ plugin header, [master](https://github.com/munin-monitoring/munin/tree/master/plugins/node.d) tree : 
```
=head1 APPLICABLE SYSTEMS

Any MySQL platform, tested by the authors on:
* MySQL 5.6.12
* MySQL 5.5.32, 5.5.37
* MySQL 5.1.29,
* MySQL 5.0.51
* MariaDB 5.5.39
* MariaDB-5.5.39(galera).
* MariaDB 10.0.18
```

This state make munin unable to work out of the box on latest version of MySQL and MariaDB from distrib repos. Even crashing with a cryptic error on `$section_map{$sec}->();` without much explanation aside the presence of unexpected empty data.
Any chance you could push compatible plugins to the 2.0.x stable branch ?

**Comment by steveschnepp** [comment]
I see the point here, but as debian, we try to keep the stable stable.

For the plugins it does make sense to provide something akin to  debian volatile (which is *-update now)

**Comment by Daryes** [comment]
Then, in this manner, would it be acceptable to have a new munin-plugins-bleedingedge package (or similar, you get the idea), providing the latest version of a selection, if not all the updated plugins compatible with the stable version ?  
With a dependency on munin-node and munin-plugins (but not the opposite)
Available on both debian and rhel/centos repos.  

This way, users would be able to use the stable version untouched, and only if they deliberately install the new package, they will have the updated plugins for the stable version.

**Comment by sumpfralle** [comment]
The updates of the `mysql_` plugin in master were recently backported to munin 2.0. Thus you can enjoy them since munin v2.0.35.
