### ISSUE TITLE
[munin-node-configure] Wrong documentation for SNMP

### ISSUE THREAD

**Issue by bortzmeyer** [munin-monitoring/munin#831]
http://munin.readthedocs.io/en/latest/reference/munin-node-configure.html#munin-node-configure says "--snmpauthprotocol " but:

```
Unknown option: snmpauthprotocol
```

The real name of the option is --snmpauthproto. Same thing for --snmpprivprotocol

**Comment by ssm** [comment]
Which version of munin are you using?

**Comment by bortzmeyer** [comment]
@ssm 2.0.33
