### ISSUE TITLE
Where are the apache plugins?

### ISSUE THREAD

**Issue by Lusitaniae** [munin-monitoring/munin#832]
When I install Apache on ubuntu server I have these plugins avaible for installation, can anyone tell me where to find the repositories containing these scripts? The one on this repo seems to produce all 3 graphs from one single script.

```
/usr/share/munin/plugins# ll | grep apache
-rwxr-xr-x 1 root root  4375 Mar  3 13:49 apache_accesses*
-rwxr-xr-x 1 root root  5757 Mar  3 13:49 apache_processes*
-rwxr-xr-x 1 root root  4320 Mar  3 13:49 apache_volume*
```

**Comment by sumpfralle** [comment]
The Debian package (which surely went unmodified into Ubuntu) probably contains plugins from this munin repository and additionally some plugins from the [contrib](https://github.com/munin-monitoring/contrib) repository.

If you want to dive into the technical details, you may want to find the package belonging to a file (`dpkg -S /usr/share/munin/plugins/apache_accesses`) and then take a look at the packaging (`apt-get source PACKAGE`).
