### ISSUE TITLE
Arbitrary precision limit for warning/critical?

### ISSUE THREAD

**Issue by rrzefox** [munin-monitoring/munin#833]
In `lib/Munin/Master/LimitsOld.pm`, function `process_service()`, this can currently be found around line 391:
`$value = sprintf "%.2f", $value;`
This of course rounds the value to 2 decimal places for the following comparisons with the warning/critical values. Therefore, warning/critical with more than 2 decimal places will not work properly.

This rounding breaks warnings for us in a few places, as we have a few plugins that return relatively small values (because the graph is in "A" but the values in the graph are in the "mA" range), and should warn if the value exceeds 0.01. Due to the rounding above, a value of "0.014" will not generate a warning, as it's rounded to 0.01, and 0.01 is not greater than 0.01.

Is there a reason for this seemingly completely arbitrary precision limit? Small values do not seem to be rounded anywhere else in munin, they also do not seem to be problematic, they work just fine. "warning" and "critical" itself do not seem to be rounded either, only the value it's compared with is. And simply replacing the `%.2f` with `%.5f` makes warnings work properly for us, while it doesn't seem to break anything.

**Comment by ssm** [comment]
The format %.2f is present in munin-limits in the import from CVS to SVN in 2004, where git history begins. I would guess the reason to be "this seems like a reasonable format and works for us" at the time of writing.

How would you like to see this handled?

**Comment by rrzefox** [comment]
I'm still at a loss why one would pick that specific precision, and it seems noone else has got any idea why that was chosen either.
I see no point in passing it through a printf at all, maybe that was done to ensure it is really a number - but the same is not done for crit and warn.
_My_ preferred solution would be no artificial rounding at all, just pass it through unchanged - but I'm unsure whether that might have any negative effects in some cornercases. Maybe someone more familiar with that code could comment...
If it really needs to be passed through sprintf for whatever reason, at least the precision limit should be increased. Perhaps just juse "%f" without specifying a precision limit, that should be equal to "%.6f" (but perhaps not on windows).

**Comment by sumpfralle** [comment]
I tend to agree with the proposal of using `%.6f` in order to avoid most (not all) precision problems.
I do not know the surrounding code well - thus I would like to keep the change at a minimum.

Any objections?
