### ISSUE TITLE
postfix_mailstats plugin: support milter-rejects

### ISSUE THREAD

**Issue by mapreri** [munin-monitoring/munin#839]
I configured spamassassin as a milter in my postfix (using spamass-milter), but I noticed the postfix-mailstats (up to master) doesn't show those rejects.

An example log line is the following:
`May 22 11:12:55 savidlin postfix/cleanup[6797]: C81E5A0679: milter-reject: END-OF-MESSAGE from unknown[94.177.175.66]: 5.7.1 Blocked by SpamAssassin; from=<aifygzstw@hmsheridan.co.uk> to=<mattia@mapreri.org> proto=ESMTP helo=<hmsheridan.co.uk>`

I am unsure what do to about it, I've tried adding
```perl
/postfix\/cleanup.* milter-reject: \S+ \S+ \S+ (\S+)/
```
to the reject regexps, so to catch the code `5.7.1` as a rejection reason, but that's not a "valid" munin field name:
```
root@savidlin ~ # munin-run postfix_mailstats
delivered.value 516
r5.7.1.value 4
root@savidlin ~ # 
```
That causes a "No .label provided" message instead of the actual label in the output.

**Comment by sumpfralle** [comment]
How about choosing another keyword as a reason for the rejection?
btw: `5.7.1` is a rather generic code that would conflict with some of the currently counted reject reasons: e.g. `450` and `451`.

What do you think? Could there be a more suitable keyword that is consistently found in these log messages?

The current state of the plugin is rather trivial - thus it is required to pick an identifier, that is acceptable as a munin fieldname.
If you want to change this, you could try to call `clean_fieldname` (available via munin's perl module) whenever a `rejects` key is used as a fieldname.

**Comment by mapreri** [comment]
> How about choosing another keyword as a reason for the rejection?
> What do you think? Could there be a more suitable keyword that is consistently found in these log messages?

I pasted in my first message the full relevant log line, they are all like that (also, the lines around are totally useless for this).

> btw: `5.7.1` is a rather generic code that would conflict with some of the currently counted reject reasons: e.g. `450` and `451`.

I'd personally be fine with 5.x.y as logged reject codes, they might be a tad less precise than postfix-specific 550/554/etc, but still quite useful to know, it's just that 5.x.y can't be used as a munin field name.

**Comment by sumpfralle** [comment]
If you do not see a good alternative keyword to be matched within these lines, then I can only recommend to add `clean_fieldname` handling to that plugin. This would solve the issue (and would be nice progress anyway).

Pull requests are welcome!
