### ISSUE TITLE
/var/run/munin permission denied

### ISSUE THREAD

**Issue by Gollam** [munin-monitoring/munin#855]
Hi,
If I use munin with cron, who should create the rundir and when? Since /var/run is a tmpfs, it gets emptied on every reboot. It is owned by root, and the munin-cron job is running under user munin, so it get's a permission denied.

**Comment by sumpfralle** [comment]
From my point of view, this integration into the system is typically done by distributors.

E.g. the init script of the munin package in Debian contains only one relevant line:
```shell
mkdir -p /var/run/munin && chown munin /var/run/munin
```

**Comment by Gollam** [comment]
Thanks! Then I'll ask my distribution's developers about it.
