### ISSUE TITLE
psu_ plugin provides invalid config

### ISSUE THREAD

**Issue by doublehp** [munin-monitoring/munin#857]
http://gallery.munin-monitoring.org/distro/plugins/node.d/psu_

Issue is trivial:

if [ "$1" = "config" ]; then

	echo graph_title Number of processes owned by $name
	echo 'graph_args --base 1000 --vertical-label processes -l 0'
	echo 'graph_category processes'
	echo "count.label $name"
	echo 'processes.draw LINE2'
	exit 0

=>
"Missing required attribute 'label' for data source 'processes' in service psu_"

I guess we want
	echo 'count.draw LINE2'

This report is dup of https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860487
I was not sure who's fault it was (Debian has many patches), now found the issue is upstream.

**Comment by sumpfralle** [comment]
Thank you for reporting this!

I prepared a pull request that follows your suggestion.
