### ISSUE TITLE
cat: /var/run/munin/munin-node.pid: No such file or directory

### ISSUE THREAD

**Issue by deva420patra** [munin-monitoring/munin#865]
Hi Everyone,
My munin-node version is - v2.0.33
Linux OS - RHEL 6.9 Santiago
Whenever i restart munin-node service I am getting below error:
Stopping Munin Node agents: cat: /var/run/munin/munin-node.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
                                                                        [FAILED]
Starting Munin Node:                                       [  OK  ]
The status of the service is showing:
"munin-node dead but subsys locked"
Log file screenshot has been attached.
(Even if I create a munin-node.pid file in /var/run/munin/ it automatically get missing after restarting the service.)
![munin-node-log](https://user-images.githubusercontent.com/30835317/29113802-c6dee180-7d0f-11e7-8030-83086b654ce4.PNG)

Any suggestions how to solve this issue.

**Comment by sumpfralle** [comment]
Hello deva420patra,

the above is the output of the init script, that is provided by your distribution (RHEL). Thus they will know how this error message appears.

The messages in your screenshot seem to indicate (but I am just guessing), that munin wants to provide its services via IPv4 and IPv6, but the system lacks the latter? Thus it stops?
Or (second interpretation): there is already a running munin process, that you need to kill manually (`netstat -lpn | grep :4949`).
Another though: maybe the init script is very picky about `start` vs. `restart` - probably it will not show the above error message, if you use `start` while there is no running process.

Anyway: all just wild guessing, since this is the domain of your distribution (and not munin).

Hope this helps,
cheers,
Lars

**Comment by deva420patra** [comment]
Hello sumpfralle,
Thanks for the response, Appreciated.
Can you please give your comments on below error for the same case.

/usr/bin/perl -wT /usr/sbin/munin-node
Use of uninitialized value $current_pid in pattern match (m//) at /usr/share/perl5/vendor_perl/Net/Server/Daemonize.pm line 48.
Couldn't find pid in existing pid_file at /usr/share/perl5/vendor_perl/Net/Server/Daemonize.pm line 48. 

Cheers
Deva

**Comment by deva420patra** [comment]
Hello sumpfralle,
Thanks for the response, Appreciated.
I'll go with your suggestions and update if the issue resolves.

Cheers
Deva

**Comment by sumpfralle** [comment]
I am not sure, what I could comment on this error message.
Where do you see it? What exactly fails to work?

**Comment by deva420patra** [comment]
Actually this above error comes when we try to restart munin-node. 
See Attached.
![munin-node_restarterror](https://user-images.githubusercontent.com/30835317/29261213-08f3f29c-80ec-11e7-9795-40685d2f2e4e.PNG)

**Comment by deva420patra** [comment]
I am not sure that even this issue or bug will solve, I am planning to upgrade the munin-node version from 2.0.33 to a higher stable version like 2.1.8 or any suggestion. Do any one one have proper document for the munin upgrade process for rhel 6.9
Thanks in advance

**Comment by sumpfralle** [comment]
If the above error message is the only thing that worries you (and everything is working fine), then I would recommend to keep it as it is. The error message is probably just the result of a sloppily written init script.

Personally I would try to stick to the version provided by my distribution.

If you want to upgrade manually, then you may want to take a look at the [upgrade notes](http://guide.munin-monitoring.org/en/latest/installation/upgrade.html).

**Comment by deva420patra** [comment]
I don't know but my graphs are not updating since july 18(posted in another issue) may be all this errors are a bug or might be solved with latest version of munin

**Comment by sumpfralle** [comment]
I would recommend the following debugging procedure an the host that is collecting and visualizing the data:
* check the munin-update log (probably /var/log/munin/munin-update.log) - here you should see details regarding the collection of data from the hosts
* check the munin-graph.log (or munin-cgi-graph.log - probably also in /var/log/munin/) - here you find details regarding the generation of graphs based on the data files
* check munin-html.log

Afterwards you should have a better feeling, where the problem starts.

**Comment by sumpfralle** [comment]
Probably a packaging issue or due to the old version being used?
Closing due to the lack of information.

**Comment by leaf-node** [comment]
I ran into this issue on an older system. The solution was to shut down the vm, mount it offline, then make sure that `/var/run` is symlinked to `/run` or `../run`.
