### ISSUE TITLE
Munin graphs are not Updating from Jul 18

### ISSUE THREAD

**Issue by deva420patra** [munin-monitoring/munin#866]
Hi Everyone,
My Munin version is (munin-node) v2.0.33.
OS - Linux RHEL 6.9(satiago)
Graphs are not updating for any of the servers, and for some its not at all showing.
I checked this http://munin-monitoring.org/wiki/faq#Q.Thegraphsarenotupdatinganymore  and find everything normal.
The .png files in /var/lib/munin/cgi-tmp/munin-cgi-graph are updating after Jul18
munin-cgi-graph.log has been attached(hostname removed)
It shows cannot create graph..
Please don't hesitate to ask any further question or queries to solve this issue, I might have done less investigation.
![munin-cgi-graph-log](https://user-images.githubusercontent.com/30835317/29170382-fad7eff4-7df5-11e7-939d-d5e26ea287f5.PNG)

All help will be appreciated.
Cheers

**Comment by sumpfralle** [comment]
The two most common problems are probably:
* no space left
* permission problem (directory ownership, permission bits)

Did you check these?

**Comment by deva420patra** [comment]
Hi Sumpfralle,

First of all thanks a lot for your response. Please find my observations.

1) No space issue in disk :
  26G   13G   12G  54% /var/lib/munin

2) I don't think there is any permission or ownership issues for /var/lib/munin file : 
 ls -lrth /var/lib/ | grep munin
drwxr-xr-x  13 munin   munin   132K Aug 14 07:30 munin

I read some where to restart http service may solve this graph issue So, I restarted httpd service it gave me below error:
Starting httpd: [Fri Aug 11 08:14:33 2017] [warn] The ScriptAlias directive in /etc/httpd/conf.d/munin.conf at line 33 will probably never match because it overlaps an earlier ScriptAlias.

We'vw below files under /etc/httpd/conf.d
-rw-r--r-- 1 root root 1510 Jun  8  2012 fastcgi.conf
-rw-r--r-- 1 root root  455 Oct  8  2013 fcgid.conf
-rw-r--r-- 1 root root 1549 Feb 27  2015 munin-cgi.conf
-rw-r--r-- 1 root root 1549 May  5 07:57 munin-cgi.conf.bak
-rw-r--r-- 1 root root  976 May  5 12:42 munin.conf
-rw-r--r-- 1 root root  976 May  5 07:57 munin.conf.bak
-rw-r--r-- 1 root root  932 Jul 21  2015 munin.conf.old
-rw-r--r-- 1 root root 1176 May  5 12:42 munin.conf.orig
-rw-r--r-- 1 root root  976 Jul 21  2015 munin.conf.rpmsave
-rw-r--r-- 1 root root  392 Jul  7 11:41 README
-rw-r--r-- 1 root root  322 Nov  7  2016 squid.conf
-rw-r--r-- 1 root root 1010 Feb 26  2015 TipsnTricks.conf
-rw-r--r-- 1 root root  299 Jul  7 11:34 welcome.conf

Cheers

**Comment by sumpfralle** [comment]
Did you maybe already solve this issue?

Regarding the graph update: did you check if the directory given in the munin-cgi log is write-accessible for the owner of the cgi process (probably www-data or something similar)?

Regarding the shadowed `ScriptAlias` directive: maybe there is a mixture of local configuration and distribution's config files? `grep -R`-ing through the /etc/apache2 directory with the duplicate location could help exposing the cause of the problem.
