### ISSUE TITLE
munin-asyncd accumulating spool files at midnight UTC

### ISSUE THREAD

**Issue by zorun** [munin-monitoring/munin#870]
Hi,

I use a setup with munin-async running on a number of machines (Ubuntu, Debian, CentOS), all collected centrally through SSH by a Debian jessie machine.

The problem I have is that on most machines, `munin-async` does not remove its spool data at midnight:

```
# ls -lh /var/lib/munin-async/
total 27M
-rw-r--r-- 1 munin-async munin-async  12K Aug 28 01:56 munin-daemon.df.1503792000.86400
-rw-r--r-- 1 munin-async munin-async 200K Aug 29 01:56 munin-daemon.df.1503878400.86400
-rw-r--r-- 1 munin-async munin-async 200K Aug 30 01:56 munin-daemon.df.1503964800.86400
-rw-r--r-- 1 munin-async munin-async 201K Aug 31 01:57 munin-daemon.df.1504051200.86400
-rw-r--r-- 1 munin-async munin-async 200K Sep  1 01:57 munin-daemon.df.1504137600.86400
-rw-r--r-- 1 munin-async munin-async 200K Sep  2 01:57 munin-daemon.df.1504224000.86400
...
```
This machine is running on UTC+2, so this actually happens at midnight UTC.  This can be verified using the timestamp in the file names:

```
$ LANG=C date -u -d '@1504224000'
Fri Sep  1 00:00:00 UTC 2017
```

I have the same issue with another machine in UTC-7, still happens at midnight UTC:

```
-rw-r--r-- 1 munin-async munin-async 461K Aug 26 16:55 munin-daemon.cpu.1503705600.86400
-rw-r--r-- 1 munin-async munin-async 461K Aug 27 16:55 munin-daemon.cpu.1503792000.86400
-rw-r--r-- 1 munin-async munin-async 461K Aug 28 16:55 munin-daemon.cpu.1503878400.86400
-rw-r--r-- 1 munin-async munin-async 461K Aug 29 16:55 munin-daemon.cpu.1503964800.86400
-rw-r--r-- 1 munin-async munin-async 461K Aug 30 16:55 munin-daemon.cpu.1504051200.86400
-rw-r--r-- 1 munin-async munin-async 466K Aug 31 16:56 munin-daemon.cpu.1504137600.86400
-rw-r--r-- 1 munin-async munin-async 461K Sep  1 16:56 munin-daemon.cpu.1504224000.86400
-rw-r--r-- 1 munin-async munin-async 151K Sep  2 00:46 munin-daemon.cpu.1504310400.86400
```

So far I can reproduce this on:

- Debian squeeze (using 2.0.6-4+deb7u2~bpo60+1 from squeeze-backports)
- Debian wheezy (using 2.0.25-1+deb8u3~bpo70+1 from wheezy-backports)
- Debian jessie (using 2.0.25-1+deb8u3)
- Debian stretch (using 2.0.33-1)
- Ubuntu 14.04 (using 2.0.19-3ubuntu0.3)

However, I can *not* reproduce it on CentOS 7 (using 2.0.33 from EL7)

So it's either a very long-standing issue on Debian, or an issue with my munin master...  The munin master is running jessie with munin 2.0.25-1+deb8u3.

**Comment by zorun** [comment]
I have a different deployment, this time with a Debian stretch machine as a munin master, and it shows the same issue.

I tried to find logs from `munin-async` or `munin-asyncd` but couldn't find any, how to go about debugging this?

**Comment by zorun** [comment]
Has anyone else been able to reproduce this issue?

Just using munin-async for 24 hours on Debian is normally enough to encounter this bug.

**Comment by drzraf** [comment]
AFAICT these file will normally be removed when munin master accesses the node and run `munin-async` (with the `--spoolfetch` flag)
NB: `/usr/share/munin/munin-asyncd` takes the `--retain` and `--verbose` parameters (run by `/etc/init.d/munin-async`)

**Comment by zorun** [comment]
@drzraf agreed in general, but for some reason they are not removed at midnight UTC.

I looked at the options and there is indeed an option to retain files:
```
-r --retain <count>        Specify number of interval files to retain [7]
```
And indeed, I have at most 7 leftover files for each service:

```
-rw-r--r-- 1 munin-async munin-async 460K Dec  6 00:58 munin-daemon.cpu.1512432000.86400
-rw-r--r-- 1 munin-async munin-async 460K Dec  7 00:58 munin-daemon.cpu.1512518400.86400
-rw-r--r-- 1 munin-async munin-async 460K Dec  8 00:58 munin-daemon.cpu.1512604800.86400
-rw-r--r-- 1 munin-async munin-async 460K Dec  9 00:58 munin-daemon.cpu.1512691200.86400
-rw-r--r-- 1 munin-async munin-async 460K Dec 10 00:58 munin-daemon.cpu.1512777600.86400
-rw-r--r-- 1 munin-async munin-async 460K Dec 11 00:58 munin-daemon.cpu.1512864000.86400
-rw-r--r-- 1 munin-async munin-async 459K Dec 12 00:55 munin-daemon.cpu.1512950400.86400
-rw-r--r-- 1 munin-async munin-async 167K Dec 12 09:40 munin-daemon.cpu.1513036800.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec  6 00:58 munin-daemon.df.1512432000.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec  7 00:58 munin-daemon.df.1512518400.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec  8 00:58 munin-daemon.df.1512604800.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec  9 00:58 munin-daemon.df.1512691200.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec 10 00:58 munin-daemon.df.1512777600.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec 11 00:58 munin-daemon.df.1512864000.86400
-rw-r--r-- 1 munin-async munin-async 171K Dec 12 00:55 munin-daemon.df.1512950400.86400
-rw-r--r-- 1 munin-async munin-async  63K Dec 12 09:40 munin-daemon.df.1513036800.86400
```

So, this would seem to be a feature rather than a bug?  What is the purpose of retaining one file per day?

**Comment by zorun** [comment]
For the record, on Debian it is possible to change this option by creating `/etc/default/munin-asyncd` with something like:

```
DAEMON_ARGS="--retain 0"
```

But I'm still interested in the "why" of this retaining policy :)

**Comment by steveschnepp** [comment]
> But I'm still interested in the "why" of this retaining policy :)

Because "disk is cheap". 

More seriously, it is done because munin-async and munin-asyncd cannot know when the data isn't needed anymore, as they might be serving multiple munin-update.

**Comment by sumpfralle** [comment]
I assume, that this ticket can be closed?
Or is there an issue with the behavior or the documentation?

**Comment by sumpfralle** [comment]
Closing, as it seems to work-as-it-should.
If you disagree: please state your proposal!
