### ISSUE TITLE
2.999.6-3 deb install error

### ISSUE THREAD

**Issue by debiansid** [munin-monitoring/munin#871]
I downloaded the debian release from here, and made .deb , but when I tried to install it.
the error like this 
OS is  Ubuntu 16.04.3 LTS

```
dpkg -i munin_2.999.6-3_all.deb
(Reading database ... 156307 files and directories currently installed.)
Preparing to unpack munin_2.999.6-3_all.deb ...
Unpacking munin (2.999.6-3) ...
dpkg: error processing archive munin_2.999.6-3_all.deb (--install):
 trying to overwrite '/usr/share/man/man5/munin.conf.5.gz', which is also in package munin-doc 2.0.25-2ubuntu0.16.04.3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Reinstalling /etc/logrotate.d/munin that was moved away
Reinstalling /etc/munin/apache.conf that was moved away
Reinstalling /etc/munin/apache24.conf that was moved away
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
```

**Comment by sumpfralle** [comment]
Maybe you are confusing a technical "*.deb" package with a package distributed by Debian (or Ubuntu).

The former simply follows the technical rules of a specific archive format.

The latter are crafted by the package maintainers of your distribution following specific standards.

In your case you found a conflict between the separation of packages distributed by Ubuntu and the package prepared by the munin developers.

This line is the crucial one:
```
trying to overwrite '/usr/share/man/man5/munin.conf.5.gz', which is also in package munin-doc 2.0.25-2ubuntu0.16.04.3
```
Thus you should do one of the following:
* Option A) remove all munin packages distributed by Ubuntu from your system and install the deb packages from the munin developers afterwards
* Option B) stick to the packages provided by your distribution (maybe picking packages from a more recent release, if possible)

If you want to follow Option B, I would recommend to use the munin packages from [Debian's "experimental" distribution](https://packages.debian.org/search?keywords=munin). The Ubuntu package maintainers probably just repackage the original Debian packaging - thus there should be no conflict with your current packages.

**Comment by debiansid** [comment]
Option B show me same error. So I am going to test it on a brand new ubuntu vm.

**Comment by sumpfralle** [comment]
Indeed the packaging is currently missing a proper transition: [Debian Issue #769158](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=769158)

You could also just remove the "munin-doc" package before installing the new one.

**Comment by debiansid** [comment]
This experimental package miss a lot of plugins, so I roll back to 2.0.33

**Comment by sumpfralle** [comment]
You probably missed the separate packages:
 https://packages.debian.org/search?suite=experimental&keywords=munin
(look for "munin-plugins-...")

**Comment by debiansid** [comment]
I installed all of them, and Munin-httpd can not read/write sqldb

**Comment by sumpfralle** [comment]
> I installed all of them, [..]

Please file a bug report against the Debian package, if a plugin got lost in the process of packaging.


> and Munin-httpd can not read/write sqldb

I am not sure, what this means. Do you miss a feature that existed before?

**Comment by debiansid** [comment]
#847 same issue as in here

**Comment by sumpfralle** [comment]
I could imagine that the database does not belong to the user that is running the munin-httpd process.

Please file a bug report against the Debian package (there does not seem to be one for this issue, yet). The package maintainer is probably not aware of this problem.

**Comment by dirzhov** [comment]
i fixed issue with database permission by setting chown munin-http:munin /var/lib/munin -R
By default owner for this folder with files inside is munin instead of munin-http
