### ISSUE TITLE
Default port seems to be 20203

### ISSUE THREAD

**Issue by jheidbrink** [munin-monitoring/munin#873]
The documentation for munin-node.config states that the default value for the port directive is 4949. However, when I remove the directive from my config-file and restart the munin-node.service, munin-node reproducibly binds to port 20203. Tested with munin-node packages on Archlinux and Fedora 22.

**Comment by sumpfralle** [comment]
Which version of munin-node did you install?

Did you check with your distribution (Archlinux and Fedora), if they use a rather uncommon deployment style?
Here on Debian (up to Stretch) munin-node is accessible via inetd (port 4949).

**Comment by jheidbrink** [comment]
Archlinux: v2.0.26
Fedora: v2.0.33

I just took a quick look at Archlinux's PKGBUILD source for munin and couldn't see anything I would call uncommon. Also, git-grep for the port 20203 found nothing in the munin as well as in the PKGBUILD repo.

I can recreate the behaviour like this:

`systemctl stop munin-node && sed -i -e "s/^port 4949/# port 4949/" /etc/munin/munin-node.conf && systemctl start munin-node`

Which gives me the following lines in `/var/log/munin/munin-node.log`:
`2017/09/13-09:52:28 Server closing!`
`Process Backgrounded`
`2017/09/13-09:52:40 Munin::Node::Server (type Net::Server::Fork) starting! pid(32521)`
`Binding to TCP port 20203 on host X.X.X.X with IPv4`

**Comment by sumpfralle** [comment]
I have found a reference to this number (20203) in the perl module [Net::Server](http://search.cpan.org/~janl/Net-Server-0.99.6.1/lib/Net/Server.pod).
I guess, that the systemd integration of munin-node caused this change (previously the "inetd" approach was common).
Did you already ask the Archlinux or Fedora maintainers?

**Comment by jheidbrink** [comment]
No, but shouldn't munin-node bind to the specified default port regardless of whether it's run via inetd or standalone?

**Comment by sumpfralle** [comment]
Programs that are accessible via inetd do not need to handle ports, address binding and other details of network connection. These things are defined within inetd.

It seems like your distributions decided to not use inetd for running munin-node. This is certainly fine. And maybe everything works as expected, but it just *looks* like it is wrong. You will need to discuss this with the package maintainers of munin-node in Fedora or Archlinux, if you think there is a problem.

**Comment by niclan** [comment]
Hi,

There is a _significant_ startup penalty in munin-node because it runs 
"config" on _all_ plugins to figure out which node they are associated 
with.  Therefore munin-node _should_ be run standalone.

If there is a wish to run munin-node in inetd somehone should look into 
persistent caching of the node information.

Nicolai

**Comment by sumpfralle** [comment]
Shame on me - I mixed up the openwrt/lede packaging (muninlite, which uses inetd) with the real munin-node, which runs independently. Stupid me.
Thus most of my comments above should be ignored and forgotten.

@niclan: do you have an idea regarding the port 20203 mentioned by jheidbrink?

**Comment by sumpfralle** [comment]
Indeed the default value was not properly handled, if the `port` line was missing in the config file.

Fixed in #1056.
