### ISSUE TITLE
Issue with displaying data - Windows - Perf counters

### ISSUE THREAD

**Issue by lektor11** [munin-monitoring/munin#876]
Hello!

I have an issue with displaying data into Munin web interface.

I installed Munin-node on Windows Server 2008 R2, and added counters. When i execute munin-node with key "-run" i don't see any errors, all is fine. Also on munin server i see in logs - "munin-update.log" - that it was added new counters. But i don't see them into web interface.

Could you please advise to me anything? What i'm doing wrong?

**Comment by dipohl** [comment]
On Sun, 24 Sep 2017 14:39:24 -0700
lektor11 wrote:
> I installed Munin-node on Windows Server 2008 R2, and added counters. When i execute munin-node with key "-run" i don't see any errors, all is fine. Also on munin server i see in logs - "munin-update.log" - that it was added new counters. But i don't see them into web interface.
> 
> Could you please advise to me anything? What i'm doing wrong?  

I am not familiar with Munin running on MS-Windows 
but the general troubleshooting advice may be helpful:

http://guide.munin-monitoring.org/en/latest/tutorial/troubleshooting.html

**Comment by sumpfralle** [comment]
@lektor11: any news regarding this?

Otherwise I would close the issue (assuming a configuration problem).

**Comment by niclan** [comment]
@lektor11 : This is better to take to the mailing list or irc channel.  I suspect you should look at your server logs - they might be able to reveal what is wrong.  Also see https://munin.readthedocs.io/en/latest/master/network-protocol.html - you can interogate your munin-node on windows to see what it presents.
