### ISSUE TITLE
netstat plugin problem with netstat command change in debian 9

### ISSUE THREAD

**Issue by rmdefi** [munin-monitoring/munin#877]
I recently updated a server to debian 9, and the netstat plugin stopped reporting the active field (but the others still worked).
The net-tools package was updated in debian 9 and the text output of netstat changed slightly, what was previously reported as "active connections openings" is now "active connection openings".
So the line (from the awk script used to parse netstat output, in the linux version of the plugin)
```
/active connections ope/  { print "active.value " $1 }
```
doesn't work with this new version.

Changing that line to
```
/active connections? ope/  { print "active.value " $1 }
```
would make the plugin compatible both with the old and new version of netstat.

Note that this issue was already reported (by someone else) in debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861851

**Comment by rmdefi** [comment]
I see this has been fixed in the master branch (with a slightly more complicated regex), can this be backported to the stable 2.0 branch?

**Comment by sumpfralle** [comment]
FYI: I will backport it (and close this bug, when it is done).

**Comment by sumpfralle** [comment]
backported as f2094f8f8e00d77e3fe3285d5e5c870e2aa4bedd to the stable-2.0 branch
