### ISSUE TITLE
Unable to draw diagram undefined vname

### ISSUE THREAD

**Issue by tudorapo** [munin-monitoring/munin#880]
Hi,

I am drawing per host network usage diagrams via pmacct, and somehow the default android hostname makes munin-graph unable to draw diagrams.

The hostname: android-e755c8eb782c6b1c

The error in munin-graph.log will be attached.

Creating this issue here because while the error is from RRD i think Munin should provide that vname, whatever it is.

Regards,

tg

**Comment by sumpfralle** [comment]
I looked for the name `pmacct` in this repository (munin) and in munin-contrib (for additional plugins), but I failed to find any reference.

Maybe it is a plugin maintained by someone else?

Regarding the problem: usually field name cleanup is missing in such cases (see the [munin-guide](http://guide.munin-monitoring.org/en/latest/develop/plugins/howto-write-plugins.html#validate-fieldnames)).

**Comment by tudorapo** [comment]
It's a plugin I wrote, and indeed, the hostname contained a dash character. Thanks for pointing out.

tg
