### ISSUE TITLE
hddtemp_smartctl fails to parse temperature from output

### ISSUE THREAD

**Issue by Aloki** [munin-monitoring/munin#881]
The hddtemp_smartctl plug-in fails to parse temperature from the output of smartctl after upgrade from CentOS 7.3 to 7.4 (smartctl 6.2 2017-02-27 r4394, Munin 2.0.33).

Upon investigation, discovered that the drive reports "190 Temperature_Case" and "194 Temperature_Internal" but that tokens does not match the strings used in the parsing algorithm.

```190 Temperature_Case        0x0022   077   075   000    Old_age   Always       -       23 (Min/Max 18/25)```
```194 Temperature_Internal    0x0022   100   100   000    Old_age   Always       -       23```

Device Model: INTEL SSDSC2BB120G6
Firmware Version: G2010140
Device is: In smartctl database [for details use: -P show]
ATA Version is: ACS-2 T13/2015-D revision 3

**Comment by sumpfralle** [comment]
Thank you for your report!
