### ISSUE TITLE
Allow to specify number format in legend

### ISSUE THREAD

**Issue by mikehaertl** [munin-monitoring/munin#884]
I'm currently using munin 2.0.25 as packaged with Ubuntu 16.04.

In a graph I want the numbers to be displayed as `0.12` instead of `123m`. I've achieved this for the y-axis with `graph_args --base 1000 -l 0 --units-exponent 0 --left-axis-format %2.2lf`. But there's no way to modify the number format in the legend. There it's still like `123.45m`. 

I've opened related https://github.com/oetiker/rrdtool-1.x/issues/836 as I'm not sure if this is a limitation of rrdtool or a missing feature in munin.

UPDATE: For the record, I've also tried to add `graph_printf %2.2lf` which makes no difference at all for me.

**Comment by sumpfralle** [comment]
Summarizing your discussion in oetiker/rrdtool-1.x#836, the following works for you:
```
graph_args --base 1000 -l 0 --units-exponent 0 --left-axis-format %2.2lf
```

Do you have a recommendation, where you were looking for such a detail in the [munin guide](http://guide.munin-monitoring.org)?
Maybe we should add a note there.

**Comment by mikehaertl** [comment]
As far as I remember I was looking in the [Developing Plugins](http://guide.munin-monitoring.org/en/latest/develop/plugins/index.html) section.

**Comment by sumpfralle** [comment]
I added a link to the rrdgraph documentation near to the definition of "graph_args". I hope, this helps.
