### ISSUE TITLE
wildcard postgresql plugin  and template1

### ISSUE THREAD

**Issue by deogracia** [munin-monitoring/munin#891]
Hi,
here's my environment:
* Debian Jessie (8) amd64
* munin 2.0.25-1+deb8u3
* postgresql 9.4.12-0+deb8u1
* template1 is not freely accessible
* /etc/munin/plugin-conf.d/munin-node
```
[postgres_*]
user postgres
env.PGUSER postgres
env.PGPORT 5432

```
* I created links in /etc/munin/plugins/ like this
```
ln -s /usr/share/munin/plugins/postgres_scans_ /etc/munin/plugins/postgres_scans_DATABASE-NAME
```
* I enabled, for each of my 6 PG databases:
  * postgres_cache_
  * postgres_connections_
  * postgres_locks_
  * postgres_oldest_prepared_xact_
  * postgres_prepared_xacts_
  * postgres_querylength_
  * postgres_scans_
  * postgres_size_
  * postgres_transactions_
  * postgres_tuples_

Only postgres_tuples_ and postgres_scans_ work as I expected : It connect to "DATABASE-NAME", instead of template1
```
munin-run postgres_transactions_DATABASE-NAME
DBI connect('dbname=template1','',...) failed: FATAL:  database "template1" is not currently accepting connections at /usr/share/perl5/Munin/Plugin/Pgsql.pm line 430.
Failed to connect to database: FATAL:  database "template1" is not currently accepting connections


munin-run postgres_scans_DATABASE-NAME
sequential.value 37874621
index.value 195773588
```

It seems that working plugins set "paramdatabase => 1,", when they call Munin::Plugin::Pgsql->new

When I add this parameter, it works.
```
munin-run postgres_transactions_cleverage
commit.value 11588374
rollback.value 545737
```

Is this a bug in these plugins? Am I missing something else?

Thanks

**Comment by sumpfralle** [comment]
Yes, indeed it was just a missing parameter in these plugins.

Thank you for your detailed analysis.
