### ISSUE TITLE
Apache plugins don't work with ssl

### ISSUE THREAD

**Issue by juegas** [munin-monitoring/munin#892]
I've tried a hand full of techniques for getting apache plugins to work with https with no luck.

Can anyone point me to an updated plugin that works with https?

A little bit about the system
- [x] ubunut16.04
- [x] status on
- [x] fastperl and fcglid installed and on 
- [x] plugin/conf.d/munin-node
- [x] tried master branch apache plugins with no better results. (output of 'U' in terminal nan in graphs)

Aside from normal install and symlinking the apache plugins here is my plugin/conf.d/munin-node
```[apache_*]
env.ssl yes
env.ports 443
env.url https://localhost:443/server-status?auto
```

Thanks in advance.

**Comment by MatthiasLohr** [comment]
Have you made any progress here? I have exactly the same problem...

**Comment by sumpfralle** [comment]
Please try the following:
```
env.PERL_LWP_SSL_VERIFY_HOSTNAME 0
```

This disables certificate name checks for SSL. Here the certifcate still needs to be valid (signed by a known CA) - but a subject name mismatch is tolerated.

Alternatively you may also try `PERL_LWP_SSL_CA_FILE`, `PERL_LWP_SSL_CA_PATH` and `HTTPS_CA_DIR` (see [LWP::UserAgent](http://search.cpan.org/~ether/libwww-perl-6.31/lib/LWP/UserAgent.pm)).

What kind of certificates do you use? Self-signed? Do the above environment variables help here?

I could imagine that you will need to provide the status output on a properly configured site (e.g. localhost via http or  a valid hostname with a valid certificate via https).

**Comment by sumpfralle** [comment]
I assume that the problem is caused by a local misconfiguration (e.g. self-signed certificate).
Please reopen, if you think otherwise.

**Comment by sumpfralle** [comment]
Sorry - I did not make it clear before.
You could put the following block into a file below `/etc/munin/plugin-conf.d/`:
```
[apache_*]
env.PERL_LWP_SSL_VERIFY_HOSTNAME 0
```
After restarting `munin-node`, the above environment setting will be active for the apache plugins.

Or (for a one-shot test) you could run the following:
```shell
PERL_LWP_SSL_VERIFY_HOSTNAME=0 munin-run apache_FOO
```
(replacing `FOO` with the apache plugin of your interest)

**Comment by mlissner** [comment]
Thank you for this. It's wildly helpful! Is this documented somewhere? I don't see where, if so.

**Comment by sumpfralle** [comment]
I added a bit of documentation to the apache plugins for situations with an invalid certificate.

But please note, that you should be able to get them running with a valid (public) certificate under most circumstances. Please note that even `Require local` should usually work for public IP addresses, as long as the client is local (i.e. client and server use the same IP address).

**Comment by mlissner** [comment]
That's great, thank you! I didn't know this documentation existed, so I filed #1083 to talk about how to fix that problem.

**Comment by sumpfralle** [comment]
great - thanks!
