### ISSUE TITLE
munin fcgi process monitoring broken after deb upgrade

### ISSUE THREAD

**Issue by Whichcraft** [munin-monitoring/munin#894]
Hi folks

I've updated this packages and rebooted the server.

Start-Date: 2017-11-11  17:17:50
Commandline: apt-get upgrade -y
Upgrade: libtomcat7-java:amd64 (7.0.28-4+deb7u15, 7.0.28-4+deb7u17), tomcat7-common:amd64 (7.0.28-4+deb7u15, 7.0.28-4+deb7u17), libgraphicsmagick3:amd64 (1.3.16-1.1+deb7u12, 1.3.16-1.1+deb7u14), tomcat7:amd64 (7.0.28-4+deb7u15, 7.0.28-4+deb7u17), libapr1:amd64 (1.4.6-3+deb7u1, 1.4.6-3+deb7u2), libaprutil1-ldap:amd64 (1.4.1-3, 1.4.1-3+deb7u1), libservlet3.0-java:amd64 (7.0.28-4+deb7u15, 7.0.28-4+deb7u17), libaprutil1-dbd-sqlite3:amd64 (1.4.1-3, 1.4.1-3+deb7u1), libgraphics-magick-perl:amd64 (1.3.16-1.1+deb7u12, 1.3.16-1.1+deb7u14), openssl:amd64 (1.0.1t-1+deb7u2, 1.0.1t-1+deb7u3), libaprutil1:amd64 (1.4.1-3, 1.4.1-3+deb7u1), graphicsmagick:amd64 (1.3.16-1.1+deb7u12, 1.3.16-1.1+deb7u14), libssl1.0.0:amd64 (1.0.1t-1+deb7u2, 1.0.1t-1+deb7u3)
End-Date: 2017-11-11  17:18:16

since then I encounter this munin problem:

telnet hostname 4949
fetch fcgiProcesses
fcgi.value -2

which results in -nan graphs.

Any ideas whats wrong here? I know wheezy isn't the newest version but i cannot upgrade this system atm.

versions information:

Linux hostname 3.2.0-4-amd64 #1 SMP Debian 3.2.93-1 x86_64 GNU/Linux

ii  munin-common                          2.0.6-4+deb7u4                     all          network-wide graphing framework (common)
ii  munin-node                            2.0.6-4+deb7u4                     all          network-wide graphing framework (node)
ii  munin-plugins-core                    2.0.6-4+deb7u4                     all          network-wide graphing framework (plugins for node)
ii  munin-plugins-extra                   2.0.6-4+deb7u4                     all          network-wide graphing framework (user contributed plugins for node)

cat /etc/debian_version
7.11

Many thanks in advance

**Comment by Whichcraft** [comment]
I've had to set 

[fcgi*]
user root

in /etc/munin/plugin-conf.d/munin-node

its working again :-)

**Comment by sumpfralle** [comment]
> its working again :-)

Great!

I just took a look at the munin repository and the munin-contrib repository, but I could not find an fcgi plugin.

If it was an external plugin, then please ask the author to improve the documentation of the plugin.

If it was a plugin that is maintained by the munin people, then please tell me where I can find it.

**Comment by sumpfralle** [comment]
probably outside the scope of this repository
