### ISSUE TITLE
loading file into program

### ISSUE THREAD

**Issue by adambranicki** [munin-monitoring/munin#895]
I have a file (data.txt) generated from the PCL driver
17/11/21	09:38:01	16.00
17/11/21	09:38:06	16.00
17/11/21	09:38:11	15.75
17/11/21	09:38:16	15.25
17/11/21	09:38:21	15.75
17/11/21	09:38:26	16.00
17/11/21	09:38:31	16.00
17/11/21	09:38:36	16.00
17/11/21	09:38:41	16.00
17/11/21	09:38:46	14.50
17/11/21	09:38:51	14.50
17/11/21	09:38:56	15.00
17/11/21	09:39:01	15.00
Is it possible to load a file (data.txt) into the program so that the munin will display the graph

**Comment by sumpfralle** [comment]
Did you already take a look at the [munin guide](http://guide.munin-monitoring.org/)? Especially the [Architecture Overview](http://guide.munin-monitoring.org/en/latest/tutorial/getting-started.html#architectural-fundamentals) could be helpful for a start, I guess.

I am not sure, what exactly you want to do - but probably the following steps can help you getting started:
* decide which information you want to visualize (printed pages, consumption, ...?)
* find a way to retrieve related data
* write a simple plugin that outputs this data
    * maybe the [munin plugin gallery](http://gallery.munin-monitoring.org/) contains something useful for you

**Comment by niclan** [comment]
@adambranicki : I think you want to look at gnuplot or a spreadsheet. Munin does not work like that.
