### ISSUE TITLE
responsive graph instead of images

### ISSUE THREAD

**Issue by staabm** [munin-monitoring/munin#899]
would be great if it could somehow be managed to replace the current image based metric graphs with a html/css alternative which would be responsive and way sharper then what we have today.

https://github.com/mozilla/metrics-graphics

see examples https://www.metricsgraphicsjs.org/examples.htm

**Comment by niclan** [comment]
Need to switch graphing system first.

**Comment by steveschnepp** [comment]
That is not on the roadmap for now. 
That said, we already offer the _sharper_ SVG output and a JSON one that can be leveraged for building and assembling things.

SVG: http://demo.munin-monitoring.org/munin-monitoring.org/www.munin-monitoring.org/load.svg
JSON: http://demo.munin-monitoring.org/munin-monitoring.org/www.munin-monitoring.org/load.json
