### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by Extarys** [munin-monitoring/munin#903]
I just found out this project and it look amazing! But is it still considered by the dev?

**Comment by dipohl** [comment]
On Sun, 21 Jan 2018 09:28:44 +0000 (UTC)
Jeremy wrote:

> I just found out this project and it look amazing!

yes it is. I am using Munin for 14 years now and 
it is a great help for my work as sysadmin.


> But is it still considered by the dev?

Here my similar inquiry on Munin mailing list

https://sourceforge.net/p/munin/mailman/message/36182378/

Unfortunately it brought bad news, the project seems 
to be orphaned, even the stable version :(

**Comment by Extarys** [comment]
Thanks for your reply @dipohl.

Which version should I choose, the 2.999.6 or the 2.0.34? It's my belief that the 2.999.6, since it's closer to 3.0.0 should have more features?

I read through the mailing list thread, thanks for that!

**Comment by sumpfralle** [comment]
> It's my belief that the 2.999.6, since it's closer to 3.0.0 should have more features?

Yes - and it is much closer to unknown territory :)

If you feel a bit adventurous, then go with 2.999.6 and report any problems, that you may encounter. Otherwise: stick with the 2.0.34 release.

**Comment by Extarys** [comment]
Thanks for your input - since maintaining servers in a wild jungle is already adventurous, I'll go right in with the latest ;)
