### ISSUE TITLE
Combining graphs

### ISSUE THREAD

**Issue by dcockerton** [munin-monitoring/munin#904]
Hi there,

I've had a look through documentation but still not sure if what I'm wanting to do is possible any help will be greatly appreciated!

I'm wanting to overlay one graph on top of the other, e.g. the number of active java threads and the java heap usage.

I also have the issue that when I move a server it may have a different host name (due to running a later version of software) and will have a different IP address, however i still want the same graphs and want to keep the information from one system but append to the graph the information from the new system. The issue I have is that I can't seem to figure out how to have a contiguous data set, e.g. I upgrade a system so I can test it and then move it live but Ideally I want to keep the old munin data but with the data from this new system going forward from the live date, is this possible?

<img width="897" alt="screen shot 2018-01-23 at 14 34 26" src="https://user-images.githubusercontent.com/19533101/35281423-c2f71e8e-004a-11e8-8002-b24bd3efc21c.png">
<img width="898" alt="screen shot 2018-01-23 at 14 34 19" src="https://user-images.githubusercontent.com/19533101/35281424-c30cbf8c-004a-11e8-97d3-ce5e927ec553.png">

I attached a couple screenshots of the graphs that I want to join.

Thanks.

**Comment by niclan** [comment]
Hi.
Sorry but you can't overlay graphs like that in munin. It is something that has been requested now and again and is on our wishlist, but it's not supported now or in the near future.

With regards to the how-to-keep-data-when-node-name-and-IP-changes this is better to address to the mailinglist. This is a issue tracker, not a support forum ;-)

**Comment by dcockerton** [comment]
Hi Niclan,

Thanks very much for your quick response, sorry I will post my other question there.

Thanks.
