### ISSUE TITLE
Keeping historical data when moving node to different server/ address

### ISSUE THREAD

**Issue by dcockerton** [munin-monitoring/munin#905]
Hi there,

I'm not sure this is the best place to ask but I can't find anywhere else to ask the question so I'm hoping someone would be kind enough to help me out or point me in the right direction?

I'm looking to keep the historic data collected by munin when I update my servers, the hostname usually changes to help keep a track of what software version it is running e.g. hostname-release2 becomes hostname-release3.

Every time the hostname or the address changes on the node all historic data is lost, is there any way to stop this happening? I notice that in /var/lib/munin/ the .rrd files for the system (same system, but different name) is still there so do I need to merge the files or something and how would I go about doing that?

Thanks.

**Comment by sumpfralle** [comment]
The IRC channel (`#munin` at freenode) and the [mailinglist](https://lists.sourceforge.net/lists/listinfo/munin-users) are good places for discussing questions or thoughts.

> Every time the hostname or the address changes on the node all historic data is lost, [..]

Do you generate your node lists automatically? In this case I would recommend to keep the `name` unchanged and just update the `address` field of each node. Maybe you also need `use_node_name = yes` (just guessing).

**Comment by DaveB93** [comment]
is there a way to migrate it? i'm in the case where I've included the ip as part of the name, but it sounds like I should move away from that.   I guess I'd want to move away from the IP in the name to just the machines purpose.  but what also about blue/green deployments, where for a short period of time I've got 2 nodes running for the same purpose?

**Comment by chanwilson** [comment]
@DaveB93 Migrate?  Probably... its been years since I attempted this. As I recall if you carefully rename the directories and files to the new hostname in your munin-server `dbdir` the old data will happily come across.  Regardless, make sure you have a full backup of your `dbdir` with all the `*.rrd` files before start tinkering like this.
I'd also consider a different host maintenance scheme, one that doesn't change the hostname on release... :-o

**Comment by sumpfralle** [comment]
I would like to clean up the open issues of this repository.
Are there any objections against closing this one, since the question was answered/discussed?

**Comment by DaveB93** [comment]
none here

**Comment by niclan** [comment]
This is for the user list. But in general: all the files are there, they have names corresponding to the host, plguin and data series.  If a host changes name from "a" to "b" then rename the files.
