### ISSUE TITLE
apt cronjob

### ISSUE THREAD

**Issue by felixkretschmer** [munin-monitoring/munin#922]
Hi,
apt and apt_all usage says: 

> This plugin needs a cronjob that runs apt-get update every hour or so

A default munin-node installation (e.g. via repos for ubuntu) includes a cronjob:

> If the APT plugin is enabled, update packages databases approx. once
> an hour (12 invokations an hour, 1 in 12 chance that the update will
> happen), but ensure that there will never be more than two hour (7200
> seconds) interval between updates..

In my opinion it also triggers an apt-get update process. So what do I need to include an additional cronjob for? Might this be removed from the usage section?

-Felix

**Comment by niclan** [comment]
You can then probably not run a cron job on your ubuntu systems.

It should not be removed from the usage section because not all the world that uses apt is ubuntu.
