### ISSUE TITLE
munin_stats: File rotated, starting at start

### ISSUE THREAD

**Issue by doublehp** [munin-monitoring/munin#923]
munin-node.log

```
2018/03/06-06:25:32 [20795] Error output from munin_stats:
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
```

sounds related to logrotate ... minor error, still an error.

I had a dream that one day, munin would work for 48h without producing a single error.

The plugin should handle this a better way, catch the error, and eventually return "U".

**Comment by sumpfralle** [comment]
The documentation of the `tail_open` function in `Munin::Plugin` contains the following:

> Also, if the file was rotated a warning is printed (this can be found in the munin-node log or seen in the terminal when using munin-run).

Here the code uses `warn` for printing a message (`File rotated, starting at start`) to stderr.

Any opinions regarding the usefulness of this message? I am tempted to remove the warning.

**Comment by doublehp** [comment]
The message must be checked to be sure it's logrotate related (I usually use grep, but there are probably better perl methods), and then, yes I would remove it.

I will keep reporting *all* warnings, as long as loggrep reports any. A good working plugin should not report a single warning when things are working as expected. Logrotate is expected, logrotate should not produce warning.

But we must be 100% certain the message is due to logrotate, and not to reboot, or disk full, or read only disk, or something else. For this kind of things, I usually create cache files to accept up to two events of this kind per 24; and report from the 3rd ... (touch cachefile$(date) ; find cachefile* -ctime +1 -delete ; [ $(find cachefile* -ctime -1 | wc -l) -gt 2 ] && .... )

**Comment by niclan** [comment]
I think I put the ```File rotated, starting at start``` message in there to make sure the rotation detection worked.  It is meant to be informational, not a error.

2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start
2018/03/06-06:25:32 [20795]     munin_stats: File rotated, starting at start

The message is repeated four times because there are four logs to read.

As far as I can see from the code it does recover and eventually print a U if there are no new log lines to take time info from.

https://github.com/munin-monitoring/munin/blob/master/plugins/node.d/munin_stats#L98

**Comment by doublehp** [comment]
it matches "loggrep -i error"; if you think it's hamrless because it would not match "\[ERROR\]", just close.

But when things are broken, or not working as expected, the first reflex to have is to
grep -nri -e error /var/log
... and this will come out.

**Comment by niclan** [comment]
Yes...  munin-run handles all STDERR output as errors as well it should and must.

@sumpfralle : I move to make the message conditonal on $MUNIN_DEBUG (see http://guide.munin-monitoring.org/en/latest/reference/munin-run.html#cmdoption-munin-run-pidebug)

	warn "$me: File rotated, starting at start\n" if $ENV{MUNIN_DEBUG};

**Comment by sumpfralle** [comment]
> make the message conditonal on $MUNIN_DEBUG

Interesting - I was not aware of that setting.
This sounds good to me!

**Comment by sumpfralle** [comment]
@niclan: I committed your proposal.
