### ISSUE TITLE
value regex mismatch in SpoolReader can lead to NO_SPOOLFETCH_DATA error

### ISSUE THREAD

**Issue by zmousm** [munin-monitoring/munin#933]
Debian 2.0.25-1+deb8u3 - also affects munin master ee5b5f8730070f7c65d7c1816c4ac3404e418831

The value regex in `Munin::Node::SpoolReader` does not match scientific notation. So if any plugins return such values, `spoolfetch` will return them without an `$epoch:` prefix. This leads `Munin::Master::Node::parse_service_config` into assuming that `$when = $now`, which may in turn bump the recorded spoolfetch timestamp to a value above anything returned by `munin-async`. Depending on timing, the next spoolfetch may happen before `munin-asyncd` has accumulated any data with a timestamp greater or equal than the stored timestamp, which will lead to the master logging a `NO_SPOOLFETCH_DATA` error in that run. Any data accumulated with a timestamp less than that is effectively lost.

The problem is mitigated by fixing the regex in SpoolReader. However I feel the server should be more robust in handling this scenario. Namely it should not consider `$now` timestamps for deriving `$spoolfetch_last_timestamp`, at the very least. I gave it a try, adding another boolean field `when_is_now` in `parse_service_config`, so as to later exclude the corresponding `when` from deriving the spoolfetch timestamp. I also wanted to try using the max of other data source timestamps, rather than `$now`. But then the question arises whether the timestamp to be used in RRD update should also change in such a case, and I did not want to affect that process.

**Comment by sumpfralle** [comment]
Thank you for taking the time to analyze this!

What do you think about the following?
* we merge your pull request (#934) with the extended regular expression into `stable-2.0`
* you prepare a pull request for your approach of improved timestamp handling

**Comment by zmousm** [comment]
Sure, I think you can change the merge base — or do you want me to do that?

As for the second question, I'm not sure how to handle this. Let's say we split timestamp for data storage from spoolfetch.
* If we use `$now` for the former and `max($when)` for the latter, it is possible that in the next run we will fetch data points with an earlier timestamp and AFAIK this will be a problem for RRD storage.
* If we also use `max($when)` for the former, this may work but of course the data point timestamp would be inaccurate.

Let me know how you think this should work and I will try to come up with a patch.

**Comment by zmousm** [comment]
I changed the merge base to `stable-2.0`. Of course this change is still applicable for `master` as well.

**Comment by sumpfralle** [comment]
Thank you!

I took another look at you proposal.
The new regex would not work with numbers starting with a leading dot (`.78` instead of `0.78`), or?
Thus I think, your proposal in the comment in the PR regarding an alternative overly simple regex would be preferable.

Regarding the timestamp: would you please for clarity open another ticket for this and describe which current situation would fail and what could be accomplished by a different logic for `$now`?
I am not trying to complicate - I am just not too familiar with this part of the code ...
Thank you!

**Comment by zmousm** [comment]
> I took another look at you proposal.
> The new regex would not work with numbers starting with a leading dot (.78 instead of 0.78), or?

Right.

> Thus I think, your proposal in the comment in the PR regarding an alternative overly simple regex would be preferable.

Alright then, I updated #934.

> Regarding the timestamp: would you please for clarity open another ticket for this and describe which current situation would fail and what could be accomplished by a different logic for $now?

I wrote #940 for the server part.
