### ISSUE TITLE
Munin Master should not assume $now for non-timestamped dirtyconfig values

### ISSUE THREAD

**Issue by zmousm** [munin-monitoring/munin#940]
The server may receive non-timestamped values in dirtyconfig output. This may happen for example due to a regex mismatch in SpoolReader, as explained in #933.

The current timestamp is used in all such cases. While it makes sense to assume `$now` if a timestamp is missing, this will also bump `$last_timestamp` and `$spoolfetch_last_timestamp`, which can lead to `NO_SPOOLFETCH_DATA` in subsequent spoolfetch runs.

The server should try to avoid running into such problems, in any case. A more conservative approach is not to assume `$now` as a timestamp in such cases, but rather use the max of all timestamps returned. If that still doesn't cut it, then fall back to `$now`.

This is what I implemented in #938.

**Comment by matt-matt2** [comment]
Aha, good call.
I believe i've run into something like this in earlier releases a few years back and hacked a way around it at the time by forcing spoolfetch timestamps to run five minutes out ..

I found that with long-running plugins (I mean 4.5 minutes or so) munin-asyncd records them in the spool with the time stamp from when the plugin _started_ running, not when it finished. So when the spoolfetch ran requesting records "newer than 5 minutes ago", there were none.

You may ask why the heck I had plugins running so long but .. well .. I did .. :)

**Comment by sumpfralle** [comment]
Your proposals for 2.0 and 2.999 were merged as #938 and #982. Thank you!
