### ISSUE TITLE
Export JSON/XML RRD data

### ISSUE THREAD

**Issue by MarcoGrasselli** [munin-monitoring/munin#954]
Hi everyone! 

I would like to export Munin graphs data in JSON/XML format, How could I do that? 

I don't find any reference to JSON API / Munin plugin that allow me to easily export my data... Can you help me?

**Comment by yunal** [comment]
This is a question not a issue.

Munin has no interface for that.  But you can dump the database files using "rrdtool dump" (see https://oss.oetiker.ch/rrdtool/doc/rrddump.en.html).
