### ISSUE TITLE
Update to Munin 2.1 [type] question

### ISSUE THREAD

**Issue by MarcoGrasselli** [munin-monitoring/munin#955]
According to [this question](https://github.com/munin-monitoring/munin/issues/505) I need munin **2.1** for generate json from munin. 

Launching "_apt-get install munin_" on **Ubuntu 14.04.5** 64bit server OS I have **Munin 2.0.19-3ubuntu0.3** installed. 

How could I update munin to 2.1?

**Comment by niclan** [comment]
Munin 2.1 was a test release series as far as I recall.  2.1 is no longer tagged in git. You probably need to take your chances with the github master or the 2.999.6 alpha release from january 2017.

There is now progress in the master branch towards 3.0, but the maintainer lost his motivation somewhere and things stopped.
