### ISSUE TITLE
Munin master: daemon / crontab handling

### ISSUE THREAD

**Issue by ntjn** [munin-monitoring/munin#956]
After an hour of hacking around on a mostly unknown Ubunutu 16.04 and reading docs, I've found out that munin master does not have a daemon, just a cron entry for running munin-cron.
Ubuntu has a systemd service, which is a symlink to `/dev/null`.

It's even missing in the Ubuntu documentation, how the munin-cron is really running, or that it is installed just as a cron entry. (I know it's not your duty to maintain that documentation.)

On Arch Linux, there isn't any service installed, just a cron entry in `/etc/munin` (which is installed to the dest dir when `make install-master-prime` is run), however the Arch Wiki shows a way creating one.

I believe munin is mostly used in containers nowadays, but an initd script / systemd service could be pretty useful. (At least for showing the location of the cron entry.)

I would gladly help writing these if there is a need for that, and I will certainly update the docs, whether a daemon is needed or not.

So what do you think, is there a daemon needed?

**Comment by niclan** [comment]
There are two parts
1. The scheduled batch - which runs perfectly well under cron
2. The web interface which is a web-app running under apache

So i think no.  But maybe documentation?
