### ISSUE TITLE
very slow running

### ISSUE THREAD

**Issue by yarnik1** [munin-monitoring/munin#959]
I have a large list of blocked Ip, and very long processing:
```
# date
Wed May 16 12:37:34 EEST 2018

# munin-run fail2ban --debug
# Processing plugin configuration from /etc/munin/plugin-conf.d/amavis
# Processing plugin configuration from /etc/munin/plugin-conf.d/df
# Processing plugin configuration from /etc/munin/plugin-conf.d/fw_
# Processing plugin configuration from /etc/munin/plugin-conf.d/hddtemp_smartctl
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/postfix
# Processing plugin configuration from /etc/munin/plugin-conf.d/postgres
# Processing plugin configuration from /etc/munin/plugin-conf.d/sendmail
# Setting /rgid/ruid/ to /99/0/
# Setting /egid/euid/ to /99 99/0/
# Setting up environment
# About to run '/etc/munin/plugins/fail2ban'
apache_auth.value 0
apache_badbots.value 0
apache_botsearch.value 3
apache_fakegooglebot.value 0
apache_modsecurity.value 0
apache_nohome.value 1
apache_noscript.value 3
apache_overflows.value 0
apache_shellshock.value 0
dovecot.value 74
exim.value 2435
exim_spam.value 0
pam_generic.value 125
php_url_fopen.value 0
proftpd.value 645
recidive.value 0
sendmail_auth.value 0
sendmail_reject.value 0
sshd.value 21504
sshd_ddos.value 162
uwimap_auth.value 0
xinetd_fail.value 0

# date
Wed May 16 12:48:12 EEST 2018
```

**Comment by yunal** [comment]
That's long indeed.  Plugin needs rewrite or something. Looks like ssm@fnord.no wrote it.  He used to be part of the project but changed jobs.  It would probably be best if you contacted him to ask for advice.

**Comment by sumpfralle** [comment]
Just for my curiosity: could you show us the output of `munin-run fail2ban | ts`?
(`ts` is part of `moreutils`)

And how about `time fail2ban-client status sshd`?

**Comment by sumpfralle** [comment]
> I have not moreutils

Something like `apt get install moreutils` would probably solve this issue :)

Regarding the time required by `fail2ban-client status sshd`: here we have the culprit.
Unless there is a more efficient way for retrieving information from `fail2ban`, I doubt that the corresponding munin plugin can do anything about that.

Maybe you want ask the fail2ban people if there is a faster interface to their status data?
Otherwise this issue cannot be solved by munin or its plugins.

**Comment by ssm** [comment]
Nicolai Langfeldt <notifications@github.com> writes:

> That's long indeed. Plugin needs rewrite or something. Looks like
> ssm@fnord.no wrote it.

Yes, the plugin needs a rewrite for speed. It is likely I wrote it, or
re-wrote it at some point.  Using shell+awk, perl or python would likely
speed it up a lot for larger block lists.

-- 
Stig Sandbeck Mathisen

**Comment by sumpfralle** [comment]
> Using shell+awk, perl or python would likely speed it up a lot for larger block lists.

In general: yes.
Specifically in the case above almost all of the wall clock time is consumed by the `fail2ban-client` call (12 minutes out of ~11 minutes (runtime seems to vary)).
There is nothing, we can do about this, or?

**Comment by niclan** [comment]
Munin runs in 5 minute cycles, setting the plugin timeout to 900 seconds still would fail.

**Comment by ssm** [comment]
sumpfralle <notifications@github.com> writes:

>> Using shell+awk, perl or python would likely speed it up a lot for
>> larger block lists.
>
> In general: yes.
>
> Specifically in the case above almost all of the wall clock time is
> consumed by the fail2ban-client call (12 minutes out of ~11 minutes
> (runtime seems to vary)).

Good point.

> There is nothing, we can do about this, or?

Three options that come to mind are:

* Check if we're using fail2ban-client incorrectly.

  Looks like we do, at first glance.  I may be wrong, though...

  I've set up fail2ban again on a few hosts to get some useful data for
  later.  Also, I should have set up fail2ban a long time ago on those
  hosts, judging from the content of my logs.  Ewwww. :/

* Shortcut fail2ban-client and access its data directly (ick!)

  "fail2ban-client get dbfile" gives the path to a sqlite3 file.  We
  could query it directly, at the cost of introducing a dependency on
  the sqlite3 commandline client.

* See if fail2ban-client can be sped up

  Outside scope of fixing the plugin.

-- 
Stig Sandbeck Mathisen

**Comment by ssm** [comment]
Just to sum up, you could speed up counting addresses in jails by making
a plugin running the sqlite3 command.

    # fail2ban-client get dbfile
    Current database file is:
    `- /var/lib/fail2ban/fail2ban.sqlite3

    # echo 'SELECT printf("%s.value: %d", jail, COUNT(ip)) FROM bans GROUP BY jail' | sqlite3 /var/lib/fail2ban/fail2ban.sqlite3 
    gitlab.value: 4
    sshd.value: 2
    
See
http://guide.munin-monitoring.org/en/latest/develop/plugins/plugin-concise.html
for how to put this in a new plugin.

-- 
Stig Sandbeck Mathisen

**Comment by yarnik1** [comment]
Good job,
What should be the block `# Print the munin values` for successful work?
