### ISSUE TITLE
Munin 2.0.19 Template engine

### ISSUE THREAD

**Issue by MarcoGrasselli** [munin-monitoring/munin#969]
Hi everyone, 

I can't understand what kind of template engine  Munin 2.0.19 uses.

Could you link me its documentation?

**Comment by niclan** [comment]
This is a better suited for the mailing list. A bug-tracker like this is not a forum.

This generates the HTML: https://github.com/munin-monitoring/munin/blob/master/lib/Munin/Master/HTML.pm
