### ISSUE TITLE
Missing laundry counter in FreeBSD 11.1 memory plugin

### ISSUE THREAD

**Issue by WanpengQian** [munin-monitoring/munin#970]
In FreeBSD 11.1, memory plugin missing the laundry counter.

ref:
https://lists.freebsd.org/pipermail/svn-src-user/2015-November/008494.html

**Comment by sumpfralle** [comment]
Thanks for the pointer!

Please test, if #971 works for you.

**Comment by sumpfralle** [comment]
Thank you for reporting and testing!
