### ISSUE TITLE
samba plugin returns 0 values when invoked from munin-run

### ISSUE THREAD

**Issue by jason-azze** [munin-monitoring/munin#972]
**Describe the bug**
The samba plugin returns 0 values for proc, lock, and share when invoked from `munin-run` (as it is during normal Munin operation). But when the plugin script is run by itself from the command line, the correct values are returned.

**To Reproduce**
1. get root-
2. 
```
[root@devsrv03 plugins]# pwd
/etc/munin/plugins
[root@devsrv03 plugins]# munin-run samba
proc.value 0
lock.value 0
share.value 0
[root@devsrv03 plugins]# ./samba
proc.value 12
lock.value 17
share.value 12
```
**Expected behavior**
The samba plugin should return valid data when invoked from `munin-run`.

**Screenshots & Logs**
Here's a run with `--debug`
```
[root@devsrv03 plugins]# munin-run --debug samba
# Processing plugin configuration from /etc/munin/plugin-conf.d/amavis
# Processing plugin configuration from /etc/munin/plugin-conf.d/df
# Processing plugin configuration from /etc/munin/plugin-conf.d/fw_
# Processing plugin configuration from /etc/munin/plugin-conf.d/hddtemp_smartctl
# Processing plugin configuration from /etc/munin/plugin-conf.d/munin-node
# Processing plugin configuration from /etc/munin/plugin-conf.d/postfix
# Processing plugin configuration from /etc/munin/plugin-conf.d/postgres
# Processing plugin configuration from /etc/munin/plugin-conf.d/samba
# Processing plugin configuration from /etc/munin/plugin-conf.d/sendmail
# Setting /rgid/ruid/ to /99/99/
# Setting /egid/euid/ to /99 99/99/
# Setting up environment
# Environment ignoreipcshare = true
# Environment smbstatus = /usr/bin/smbstatus
# About to run '/etc/munin/plugins/samba'
proc.value 0
lock.value 0
share.value 0
```

**Desktop (please complete the following information):**
 - CentOS 6.6
 - munin-node v2.0.33 (as packaged for CentOS 6)

**Comment by sumpfralle** [comment]
Thank you for pointing out this issue!

Indeed the plugin needs to run as root - but this was not mentioned before in its documentation header.

You will need to add something like the following below `/etc/munin/plugins-conf.d/`:
```
[samba]
user root
```

Probably you should report this to your distribution in order get this setting included in their packaging?
(the Debian package is correct in this regard)

**Comment by jason-azze** [comment]
I can confirm that adding the `user root` line suggested above works.
